TOP = ../../..
include $(TOP)/config.mak

CXXPROGRAM = nits_default_linkage_sample

SOURCES = linkageSample.c

DEFINES = UNICODE 

INCLUDES = . $(TOP) $(TOP)/common

LIBRARIES = pal pal

include $(TOP)/mak/rules.mak
