TOP = ../../..
include $(TOP)/config.mak

CXXSHLIBRARY = nits_test_build_sample

SOURCES = linkageSample.cpp

DEFINES = UNICODE TEST_BUILD

INCLUDES = . $(TOP) $(TOP)/common

LIBRARIES = pal nits

include $(TOP)/mak/rules.mak