// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Network::ConsoleProtocols" ), 
    Description ( 
       "A representation of the settings of a Telnet server "
       "connection. The relationship between the SettingData and the "
       "TelnetProtocolEndpoint is described by instantiating the "
       "ElementSettingData association." )]
class CIM_TelnetSettingData : CIM_SettingData {

      [Write, Description ( 
          "An array of integers indicating the terminal modes that "
          "will be enabled." ), 
       ValueMap { "1", "2", "3", "..", "32768..65535" }, 
       Values { "Other", "VT100", "ANSI", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_TelnetSettingData.OtherEnabledTerminalMode" }]
   uint16 EnabledTerminalModes[];

      [Write, Description ( 
          "When the EnabledTerminalModes property contains a value "
          "of 1, \"Other\" then free form string providing more "
          "information about the enabled terminal mode. If it does "
          "not contain 1, this string has no meaning." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_TelnetSettingData.EnabledTerminalModes" }]
   string OtherEnabledTerminalMode[];

      [Write, Description ( 
          "The terminal mode that will be in use if this "
          "SettingData is applied." ), 
       ValueMap { "1", "2", "3", "..", "32768..65535" }, 
       Values { "Other", "VT100", "ANSI", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_TelnetSettingData.OtherTerminalMode", 
          "CIM_TelnetSettingData.EnabledTerminalModes" }]
   uint16 TerminalMode;

      [Write, Description ( 
          "If the TerminalMode property is set to 1, \"Other\" then "
          "this is a free form string providing more information "
          "about the current terminal mode. If not set to 1, this "
          "string has no meaning." ), 
       ModelCorrespondence { "CIM_TelnetSettingData.TerminalMode" }]
   string OtherTerminalMode;

      [Write, Description ( 
          "An array of integers indicating the Character display "
          "modes enabled for the endpoint." ), 
       ValueMap { "1", "2", "3", "..", "32768..65535" }, 
       Values { "Other", "Console", "Stream", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_TelnetSettingData.OtherEnabledCharacterDisplayMode" }]
   uint16 EnabledCharacterDisplayModes[];

      [Write, Description ( 
          "When the EnabledCharacterDisplayModes property contains "
          "a value of 1, \"Other\" then this is a free form string "
          "providing more information about the enabled modes. If "
          "it does not contain 1, this string has no meaning." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_TelnetProtocolEndpoint.EnabledCharacterDisplayModes" }]
   string OtherEnabledCharacterDisplayMode[];

      [Write, Description ( 
          "The character display mode that will be active if this "
          "SettingData is applied." ), 
       ValueMap { "1", "2", "3", "..", "32768..65535" }, 
       Values { "Other", "Console", "Stream", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_TelnetSettingData.OtherCharacterDisplayMode", 
          "CIM_TelnetProtocolEndpoint.EnabledCharacterDisplayModes" }]
   uint16 CharacterDisplayMode;

      [Write, Description ( 
          "When the CharacterDisplayMode property is set to 1, "
          "\"Other\" then this is a free form string providing more "
          "information about the character display mode. If not set "
          "to 1, this string has no meaning." ), 
       ModelCorrespondence { 
          "CIM_TelnetProtocolEndpoint.CharacterDisplayMode", 
          "CIM_TelnetSettingData.OtherEnabledCharacterDisplayMode" }]
   string OtherCharacterDisplayMode;

      [Write, Description ( 
          "String indicating the Escape Character that will be in "
          "effect if this SettingData is applied." ), 
       ModelCorrespondence { 
          "CIM_TelnetProtocolEndpoint.EscapeCharacter" }]
   string EscapeCharacter;

      [Write, Description ( 
          "IdleTimeout specifies how long the connection can be "
          "idle before it is closed. The default value, 0, "
          "indicates that there is no idle timeout period." ), 
       Units ( "Seconds" ), 
       PUnit ( "second" )]
   uint32 IdleTimeout = 0;


};
