// Copyright (c) 2012 DMTF.  All rights reserved.
   [Version ( "2.32.0" ), 
    UMLPackagePath ( "CIM::Network::IP" ), 
    Description ( 
       "CIM_IPNetworkConnection represents the IP network connection "
       "in the system, Eg. \"Local Area Connection\",\"eth0\"" )]
class CIM_IPNetworkConnection : CIM_ServiceAccessPoint {

      [Description ( 
          "This shall contain a free form string, that identifies "
          "the IP network connection." )]
   string ID;


};
