// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SwitchPortPair 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::SwitchingBridging" ), 
    Description ( 
       "This association represents information regarding port "
       "pairings that is used by the SourceRoutingService of a switch." )]
class CIM_SwitchPortPair : CIM_SAPSAPDependency {

      [Override ( "Antecedent" ), 
       Description ( "The lower numbered port." )]
   CIM_SwitchPort REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The higher numbered port." )]
   CIM_SwitchPort REF Dependent;

      [Description ( 
          "A bridge number that uniquely identifies the path "
          "provided by this source routing bridge between the "
          "segments connected to high and low ports. The purpose of "
          "bridge number is to disambiguate between multiple paths "
          "connecting the same two LANs." ), 
       MappingStrings { 
          "MIB.IETF|SOURCE-ROUTING-MIB.dot1dPortPairBridgeNum" }]
   uint16 BridgeNum;

      [Description ( 
          "The state of the pairing. Writing \'invalid(3)\' to this "
          "property removes the association instance." ), 
       ValueMap { "1", "2", "3" }, 
       Values { "Enabled", "Disabled", "Invalid" }, 
       MappingStrings { 
          "MIB.IETF|SOURCE-ROUTING-MIB.dot1dPortPairBridgeState" }]
   uint16 BridgeState;


};
