// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_InboundVLAN 
// ==================================================================
   [Association, Deprecated { "No value" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::VLAN" ), 
    Description ( 
       "This class is deprecated in lieu or not being necessary to "
       "indicate whether the VLAN is inbound/outbound This association "
       "makes explicit the operational dependencies of a SwitchPort "
       "when operating in a VLAN. If there is an association between a "
       "particular SwitchPort and a particular VLAN, then there is the "
       "possibility that a packet received by the port will be "
       "assigned to the VLAN (or if the packet already has a VLAN tag, "
       "that the packet will not be dropped). If there is no such "
       "association, then there is NO possibility that a packet "
       "received by the port will progress through the switch having "
       "been assigned to the referenced VLAN." )]
class CIM_InboundVLAN : CIM_SAPSAPDependency {

      [Deprecated { "No value" }, 
       Override ( "Antecedent" ), 
       Description ( "The VLAN to which the SwitchPort is assigned." )]
   CIM_VLAN REF Antecedent;

      [Deprecated { "No value" }, 
       Override ( "Dependent" ), 
       Description ( "The SwitchPort on the VLAN." )]
   CIM_SwitchPort REF Dependent;

      [Deprecated { "No value" }, 
       Description ( 
          "If TRUE, packets already tagged with this VLAN number "
          "will be accepted when arriving at this port. For "
          "example, if there is an InboundVLAN association between "
          "port 12 and VLAN 7 for which Tagged is true, then when a "
          "packet tagged with VLAN 7 arrives at port 12, the packet "
          "will be accepted into the switch for further processing. "
          "If there is no such association, then the packet will be "
          "dropped. \n"
          "\n"
          "If FALSE, it means that any untagged packets arriving at "
          "this port MIGHT be classified into the associated VLAN. "
          "If, for a particular SwitchPort, there is only one "
          "instance of the association for which Tagged is FALSE, "
          "then all incoming untagged packets will be classified "
          "into that VLAN. This is the typical configuration of a "
          "non-trunk port in a switch implementing port-based "
          "VLANs. If there is more than one such association "
          "instance, then the packet MIGHT be classified into any "
          "one of them, based on some criterion other than the "
          "identity of the switch port. For example, in a MAC-based "
          "VLAN switch, the decision would be based on the source "
          "MAC address. In a protocol-based VLAN switch, the "
          "decision would be based on the values of some set of "
          "bits in the packet. \n"
          "\n"
          "Note that the MAC address is formatted as twelve "
          "hexadecimal digits (e.g., \"010203040506\"), with each "
          "pair representing one of the six octets of the MAC "
          "address in \"canonical\" bit order according to RFC "
          "2469." )]
   boolean Tagged;

      [Deprecated { "No value" }, 
       Description ( 
          "Default should be TRUE if untagged packets received by "
          "the SwitchPort are assigned to the VLAN. For "
          "802.1Q-compliant ports, the Default property should be "
          "TRUE on the association instance connecting a SwitchPort "
          "to the VLAN corresponding to the port\'s PVID. Default "
          "MUST never be TRUE if Tagged is true -- it applies only "
          "to untagged packets." )]
   boolean Default;


};
