// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ASBGPEndpoints 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::ProtocolEndpoints" ), 
    Description ( 
       "This aggregation defines the different router interfaces that "
       "are running BGP in the AutonomousSystem." )]
class CIM_ASBGPEndpoints : CIM_SystemComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( 
          "The AutonomousSystem that aggregates the router "
          "interfaces that are running BGP." )]
   CIM_AutonomousSystem REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The router interfaces that are contained in the AS." )]
   CIM_BGPProtocolEndpoint REF PartComponent;


};
