// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ClassifierElementUsesFilterList 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "This association relates one or more ClassifierElements with a "
       "FilterList that defines the criteria to select packets for the "
       "classifier to process. Note that a classifier is always "
       "modeled as a ClassifierService that aggregates a set of "
       "ClassifierElements. Each of these ClassifierElements is EITHER "
       "associated with a single FilterList OR associated to another "
       "ClassifierService (via NextServiceAfterClassifier Element to "
       "describe hierarchical classification)." )]
class CIM_ClassifierElementUsesFilterList : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The FilterList that specifies the traffic criteria for a "
          "ClassifierElement." )]
   CIM_FilterList REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The ClassifierElement that depends on the FilterList for "
          "its traffic criteria." )]
   CIM_ClassifierElement REF Dependent;


};
