// Copyright (c) 2008 DMTF.  All rights reserved.
   [Association, Version ( "2.19.0" ), 
    UMLPackagePath ( "CIM::Network::Misc" ), 
    Description ( 
       "Describes an element\'s knowledge regarding accessing other "
       "(i.e., remote) Servers and Systems." )]
class CIM_RemoteAccessAvailableToElement : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The remote server or system." )]
   CIM_RemoteServiceAccessPoint REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The EnabledLogicalElement which has knowledge of the "
          "remote server or system." )]
   CIM_EnabledLogicalElement REF Dependent;

      [Description ( 
          "Indicates that this access information is defined as a "
          "default configuration for the system." )]
   boolean IsDefault;

      [Description ( 
          "When an element is accessing remote services and "
          "systems, it MAY be necessary to order those accesses. "
          "This property defines that ordering - where lower "
          "numbers indicate a higher priority for access. A value "
          "of 0 (default) indicates that ordering does not apply. "
          "If multiple RemoteAccessPoint instances have the same "
          "value for OrderOfAccess, then these AccessPoints MAY be "
          "used in any sequence defined by the implementation." )]
   uint16 OrderOfAccess = 0;


};
