// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NextService 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "NextService establishes a predecessor-successor relationship "
       "between two ConditioningService objects. This association is "
       "used to indicate the sequence of ConditioningServices required "
       "to process a particular type of traffic. \n"
       "\n"
       "Instances describe the various relationships between different "
       "ConditioningServices (such as classifiers, meters, droppers, "
       "etc.) that are used collectively to condition traffic. Both "
       "one-to-one and more complicated fan-in and/or fan-out "
       "relationships can be described. The Conditioning Services may "
       "feed one another directly, or they may be mapped to multiple "
       "\'next\' Services based on the characteristics of the packet." )]
class CIM_NextService {

      [Key, Description ( 
          "The preceding ConditioningService, \'earlier\' in the "
          "processing sequence for a packet." )]
   CIM_ConditioningService REF PrecedingService;

      [Key, Description ( 
          "The \'next\' or following ConditioningService." )]
   CIM_ConditioningService REF FollowingService;


};
