// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_Phase1SAUsedForPhase2 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::IPsec" ), 
    Description ( 
       "Phase1SAUsedForPhase2 associates a phase 1 endpoint (such as "
       "an IKESAEndpoint) with an IPsecSAEndpoint that was negotiated "
       "using that phase 1 Security Association." )]
class CIM_Phase1SAUsedForPhase2 : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "Phase 1 SAEndpoint that protected the negotiation of the "
          "phase 2 Security Association. An example of a phase 1 "
          "endpoint is an IKESAEndpoint." )]
   CIM_SecurityAssociationEndpoint REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The phase 2 SAEndpoint." )]
   CIM_IPsecSAEndpoint REF Dependent;


};
