// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_TransformOfSecurityAssociation 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::IPsec" ), 
    Description ( 
       "TransformOfSecurityAssociation maps a SecurityAssociation "
       "Endpoint with the transform that it uses. For security, no "
       "keying material of the SA is exposed." )]
class CIM_TransformOfSecurityAssociation : CIM_ElementSettingData {

      [Override ( "SettingData" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "Transform of the IPsecSAEndpoint." )]
   CIM_SATransform REF SettingData;

      [Override ( "ManagedElement" ), 
       Description ( "The IPsecSAEndpoint that uses the transform." )]
   CIM_IPsecSAEndpoint REF ManagedElement;


};
