// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ReflectorNonClientService 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::BGP" ), 
    Description ( 
       "This association will serve as the base class for handling BGP "
       "routing information for the non-clients of the reflector of "
       "this Cluster." )]
class CIM_ReflectorNonClientService : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The Cluster for which this Service is being defined." )]
   CIM_BGPCluster REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The BGPService which handles routing information as a "
          "non-client of the Cluster." )]
   CIM_BGPService REF Dependent;


};
