// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Network::ConsoleProtocols" ), 
    Description ( 
       "A subclass of ProtocolServiceCapabilities that defines the "
       "capabilities of an SSH Service. An instance of "
       "CIM_SSHCapabilities is associated with an instance of "
       "CIM_ProtocolService via the CIM_ElementCapabilities "
       "association." )]
class CIM_SSHCapabilities : CIM_ProtocolServiceCapabilities {

      [Description ( 
          "An array of integers indicating the version or versions "
          "of SSH protocol that the SSH service supports." ), 
       ValueMap { "0", "1", "2", "3", "4..32767", "32768..65535" }, 
       Values { "Unknown", "Other", "SSHv1", "SSHv2", 
          "DMTF Reserved", "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_SSHCapabilities.OtherSupportedSSHVersion" }]
   uint16 SupportedSSHVersions[];

      [Description ( 
          "If the SupportedSSHVersions property is set to 1, "
          "\"Other\" then free form string providing more "
          "information about supported SSH protocols. If not set to "
          "1, this string has no meaning." ), 
       ModelCorrespondence { 
          "CIM_SSHCapabilities.SupportedSSHVersions" }]
   string OtherSupportedSSHVersion;

      [Description ( 
          "An array of integers indicating the encryption "
          "algorithms that the SSH service supports." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7..32767", 
          "32768..65535" }, 
       Values { "Unknown", "Other", "DES", "DES3", "RC4", "IDEA", 
          "SKIPJACK", "DMTF Reserved", "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_SSHCapabilities.OtherSupportedEncryptionAlgorithm" }]
   uint16 SupportedEncryptionAlgorithms[];

      [Description ( 
          "If the SupportedEncryptionAlgorithms property is set to "
          "1, \"Other\" then free form string providing more "
          "information about supported algorithms. If not set to 1, "
          "this string has no meaning." ), 
       ModelCorrespondence { 
          "CIM_SSHCapabilities.SupportedEncryptionAlgorithms" }]
   string OtherSupportedEncryptionAlgorithm;


};
