// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostedRoutingPolicy 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::RoutingForwarding" ), 
    Description ( 
       "A RoutingPolicy is weak to the network device (i.e., the "
       "ComputerSystem) that contains it. This association formalizes "
       "that relationship." )]
class CIM_HostedRoutingPolicy : CIM_HostedDependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The network device/computer system that scopes the RoutingPolicy."
           )]
   CIM_ComputerSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Weak, Description ( 
          "The routing policy defined in the context of the network device."
           )]
   CIM_RoutingPolicy REF Dependent;


};
