// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SwitchesAmong 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::SwitchingBridging" ), 
    Description ( 
       "A SwitchService switches frames between SwitchPorts. This "
       "association makes that relationship explicit." )]
class CIM_SwitchesAmong : CIM_ForwardsAmong {

      [Override ( "Antecedent" ), 
       Description ( "The switch port." )]
   CIM_SwitchPort REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( "The switching service." )]
   CIM_SwitchService REF Dependent;


};
