// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_IngressConditioningServiceOnEndpoint 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "This association represents the binding, in the ingress "
       "direction, between a ProtocolEndpoint and the first "
       "ConditioningService that processes packets received via that "
       "Endpoint. Since there can only be one \'first\' "
       "ConditioningService for a ProtocolEndpoint, the cardinality "
       "for the Dependent object reference is narrowed from 0..n to "
       "0..1. On the other hand, a single ConditioningService can be "
       "the first to process packets received via multiple "
       "ProtocolEndpoints. So, the cardinality of the Antecedent "
       "object reference remains 0..n." )]
class CIM_IngressConditioningServiceOnEndpoint : CIM_ServiceSAPDependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The ProtocolEndpoint through which traffic arrives at a "
          "network device." )]
   CIM_ProtocolEndpoint REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( 
          "The ConditioningService which begins the traffic "
          "conditioning processing within a network device." )]
   CIM_ConditioningService REF Dependent;


};
