// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_EndpointOfNetworkPipe 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::Pipes" ), 
    Description ( 
       "EndpointOfNetworkPipe describes the endpoints between which a "
       "pipe transfers information. Whether an endpoint is a source or "
       "sink is indicated by a property of the association, "
       "SourceOrSink." ), 
    MappingStrings { "Recommendation.ITU|M3100.Pipe.a-TPInstance", 
       "Recommendation.ITU|M3100.Pipe.z-TPInstance" }]
class CIM_EndpointOfNetworkPipe : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 2 ), 
       Max ( 2 ), 
       Description ( "One of the endpoints of the pipe." )]
   CIM_ProtocolEndpoint REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The pipe which is dependent on the endpoints as the "
          "source or sink of the transferred information." )]
   CIM_NetworkPipe REF Dependent;

      [Description ( 
          "Indicates whether the endpoint is a source (value = 2), "
          "or sink (value = 3) for the pipe. If this information is "
          "not applicable, the property is set to 4. If the "
          "information is not known, the property is set to 0." ), 
       ValueMap { "0", "2", "3", "4" }, 
       Values { "Unknown", "Source", "Sink", "Not Applicable" }]
   uint16 SourceOrSink;


};
