// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ConnectivityMembershipSettingData 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::Collections" ), 
    Description ( 
       "ConnectivityMembershipSettingData provides the identification "
       "criteria for possible members of a ConnectivityCollection." )]
class CIM_ConnectivityMembershipSettingData : CIM_SettingData {

      [Required, Description ( 
          "ConnectivityMemberType specifies the type of "
          "identification used in the ConnectivityMemberID field." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "..", "0x8000.." }, 
       Values { "Unknown", "Other", "Permanent Address", 
          "Network Address", "Switch Port ID", "Logical Port Group", 
          "Connectivity Collection", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_ConnectivityMembershipSettingData.ConnectivityMemberID", 
          "CIM_ConnectivityMembershipSettingData.OtherConnectivityMemberType" }]
   uint16 ConnectivityMemberType;

      [Description ( 
          "This property specifies the type of identification used "
          "in the ConnectivityMemberID field, when "
          "ConnectivityMemberType is 1, \"Other\"." ), 
       ModelCorrespondence { 
          "CIM_ConnectivityMembershipSettingData.ConnectivityMemberType" }]
   string OtherConnectivityMemberType;

      [Required, Description ( 
          "The identification of the member, based on the type "
          "specified by ConnectivityMemberType." ), 
       ModelCorrespondence { 
          "CIM_ConnectivityMembershipSettingData.ConnectivityMemberType" }]
   string ConnectivityMemberID;


};
