// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RoutingProtocolDomain 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::RoutingForwarding" ), 
    Description ( 
       "A Routing Protocol Domain is a collection of routers which "
       "coordinate their routing knowledge using a single [instance of "
       "a] routing protocol. This class represents the "
       "area/layer/level/zone like property of a routing protocol, "
       "such as an OSPF (area), IS-IS (layer) or PNNI (level). It does "
       "not represent the entire routing domain in every case. For "
       "example for OSPF, it represents an Area, but in the case of "
       "RIP, it represents the whole RIP domain. Any common attributes "
       "of these routing domains can be placed in this class in future "
       "versions of CIM." )]
class CIM_RoutingProtocolDomain : CIM_AdminDomain {


};
