// Copyright (c) 2012 DMTF.  All rights reserved.
   [Version ( "2.32.0" ), 
    UMLPackagePath ( "CIM::Network::IP" ), 
    Description ( 
       "This SettingData instance is the aggregation point identifying "
       "an IP configuration. Multiple IP configurations could exist "
       "for a target. Each configuration is represented with an "
       "instance of IPAssignmentSettingData. The details of the IP "
       "configuration are defined by instances of sub-classes of this "
       "class (i.e. StaticIPAssignmentSettingData, DHCPSettingData, "
       "DNSSettingData). These instances are associated with the "
       "IPAssignmentSettingData instance using the OrderedComponent or "
       "ConcreteComponent associations. For example, a static IP "
       "configuration would be represented by an instance of "
       "IPAssignmentSettingData and an instance of "
       "StaticIPAssignmentSettingData associated via an instance of "
       "ConcreteComponent. A static IP configuration including DNS "
       "would be modeled using an instance of IPAssignmentSettingData, "
       "DNSSettingData, and StaticIPAssignmentSettingData. The "
       "DNSSettingData and StaticIPAssignmentSettingData instance "
       "would be associated with the IPAssignmentSettingData using "
       "instances of ConcreteComponent." )]
class CIM_IPAssignmentSettingData : CIM_SettingData {

      [Description ( 
          "AddressOrigin identifies the method by which the IP "
          "Address, Subnet Mask for IPv4 or Prefix Length for IPv6, "
          "and Gateway shall be assigned to the IPProtocolEndpoint. \n"
          "A value of 3 \"Static\" shall indicate the values will "
          "be assigned manually. \n"
          "A value of 4 \"DHCP\" shall indicate the values will be "
          "assigned utilizing the Dynamic Host Configuration "
          "Protocol. See RFC 2131 and related. \n"
          "A value of 5 \"BOOTP\" shall indicate the values will be "
          "assigned utilizing BOOTP. See RFC 951 and related. \n"
          "A value of 6 \"IPv4 Link Local\" shall indicate the "
          "values will be assigned using the IPv4 Link Local "
          "protocol. See RFC 3927.\n"
          "A value of 7 \"DHCPv6\" shall indicate the values will "
          "be assigned using DHCPv6. See RFC 3315. \n"
          "A value of 8 \"IPv6 AutoConfig \" shall indicate the "
          "values will be assigned using the IPv6 AutoConfig. See "
          "RFC 4862. \n"
          "A value of 9 \"Stateless\" shall indicate Stateless will "
          "be assigned. \n"
          "A value of 10 \"Link Local\" shall indicate Link Local "
          "values will be assigned." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "..", "32768.." }, 
       Values { "Unknown", "Other", "Not Applicable", "Static", 
          "DHCP", "BOOTP", "IPv4 Link Local", "DHCPv6", 
          "IPv6AutoConfig", "Stateless", "Link Local", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint16 AddressOrigin = 0;

      [Description ( "An enumeration that describes the IP version." ), 
       ValueMap { "0", "..", "4096", "4097", "32768.." }, 
       Values { "Unknown", "DMTF Reserved", "IPv4", "IPv6", 
          "Vendor Reserved" }, 
       ModelCorrespondence { "CIM_ProtocolEndpoint.ProtocolIFType" }]
   uint16 ProtocolIFType;


};
