// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "No value" }, 
    Aggregation, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::VLAN" ), 
    Description ( 
       "This class is deprecated as a fall out of the previous "
       "deprecations within the existing model An association linking "
       "SwitchService to a component VLANService." )]
class CIM_SwitchServiceVLAN : CIM_ServiceComponent {

      [Deprecated { "No value" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The SwitchService containing the VLANService." )]
   CIM_SwitchService REF GroupComponent;

      [Deprecated { "No value" }, 
       Override ( "PartComponent" ), 
       Description ( 
          "The VLANService that is a component of the SwitchService." )]
   CIM_VLANService REF PartComponent;


};
