// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_EGPRouteCalcDependency 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::BGP" ), 
    Description ( 
       "This is a specialization of ServiceServiceDependency, and "
       "captures the dependency that external gateway protocols (such "
       "as BGP) have on interior gateway protocols (such as OSPF)." )]
class CIM_EGPRouteCalcDependency : CIM_ServiceServiceDependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The independent RouteCalculationService that provides "
          "routing information from the AS, for the EGP to use." )]
   CIM_RouteCalculationService REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The dependent RouteCalculationService (e.g., the Route "
          "CalculationService) that is functioning as an EGP." )]
   CIM_RouteCalculationService REF Dependent;

      [Description ( 
          "Sometimes it is necessary to inject EGP information, "
          "such as that from BGP, into IGPs. This attribute defines "
          "whether this should be done for the two routing "
          "protocols that are defined by this association. The "
          "values below mean that no, partial, and full EGP "
          "information is injected into the IGP, respectively." ), 
       ValueMap { "1", "2", "3" }, 
       Values { "None", "Partial", "Full" }]
   uint16 IGPInjection;


};
