// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_BGPClustersInAS 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::BGP" ), 
    Description ( 
       "This aggregation establishes \'whole-part\' relationships "
       "between an AutonomousSystem and the BGPClusters that it "
       "contains." )]
class CIM_BGPClustersInAS {

      [Key, Aggregate, Max ( 1 ), 
       Description ( 
          "The AutonomousSystem that aggregates the Clusters "
          "belonging to it and administers them." )]
   CIM_AutonomousSystem REF GroupAS;

      [Key, Description ( 
          "The Clusters that are contained in the AS." )]
   CIM_BGPCluster REF PartAS;


};
