// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_OSPFServiceCapabilities 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::OSPF" ), 
    Description ( 
       "The OSPFServiceCapabilities class represents the capabilities "
       "of an OSPF service." )]
class CIM_OSPFServiceCapabilities : CIM_Capabilities {

      [Description ( 
          "This attribute indicates whether this router supports "
          "NSSA (\"not-so-stubby\") areas or not, see RFC 1587." )]
   boolean SupportNSSA;

      [Description ( 
          "This attribute indicates whether this router supports "
          "on-demand circuits or not, see RFC 1793." ), 
       MappingStrings { "MIB.IETF|OSPF-MIB.ospfDemandExtensions" }]
   boolean SupportOnDemand;

      [Description ( 
          "This attribute indicates whether this router supports "
          "MOSPF (multicast enhancements to OSPF) or not, see B.1 "
          "in RFC 1584." ), 
       MappingStrings { "MIB.IETF|OSPF-MIB.ospfMulticastExtensions" }]
   boolean SupportMOSPF;


};
