// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "A class describing a company\'s and/or administrator\'s "
       "credential requirements that should be authenticated in order "
       "to establish/trust a CIM_Identity. This class defines the "
       "specific public/private key pair that should be authenticated." )]
class CIM_PublicPrivateKeyAuthentication : CIM_AuthenticationCondition {

      [Description ( 
          "Boolean indicating whether the key pair is self-issued "
          "(TRUE) or issued by a Certificate Authority (FALSE)." )]
   boolean SelfIssuedKey;

      [Description ( 
          "String holding the user\'s (distinguished) name." )]
   string DistinguishedName;

      [Description ( "String holding the public key data." )]
   string PublicKey;


};
