// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_PolicySetComponent" }, 
    Aggregation, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "PolicySetComponent provides a more general mechanism for "
       "aggregating both PolicyGroups and PolicyRules and doing so "
       "with the priority value applying only to the aggregated set "
       "rather than policy wide. \n"
       "\n"
       "A relationship that aggregates one or more PolicyRules into a "
       "PolicyGroup. A PolicyGroup may aggregate PolicyRules and/or "
       "other PolicyGroups." )]
class CIM_PolicyRuleInPolicyGroup : CIM_PolicyComponent {

      [Deprecated { "CIM_PolicySetComponent.GroupComponent" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "A PolicyGroup that aggregates one or more PolicyRules." )]
   CIM_PolicyGroup REF GroupComponent;

      [Deprecated { "CIM_PolicySetComponent.PartComponent" }, 
       Override ( "PartComponent" ), 
       Description ( "A PolicyRule aggregated by a PolicyGroup." )]
   CIM_PolicyRule REF PartComponent;


};
