// Copyright (c) 2005 DMTF.  All rights reserved.
   [Abstract, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "An abstract class whose subclasses describe one of a company\'s "
       "and/or administrator\'s credential requirements, and/or other "
       "information that should be authenticated in order to "
       "establish/trust a CIM_Identity. The PolicyConditions collected "
       "by an instance of AuthenticationRule describe the various "
       "requirements under which a CIM_Identity\'s "
       "CurrentlyAuthenticated Boolean is set to TRUE. Note that the "
       "CIM_Identities which are authenticated are specified through "
       "the AuthenticationRule, using the PolicySet AppliesToElement "
       "association." )]
class CIM_AuthenticationCondition : CIM_PolicyCondition {


};
