// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "A class describing a company\'s and/or administrator\'s "
       "credential requirements that should be authenticated in order "
       "to establish/trust a CIM_Identity. This class defines a "
       "specific identity whose account credentials should be "
       "authenticated." )]
class CIM_AccountAuthentication : CIM_AuthenticationCondition {

      [Description ( 
          "String defining the account\'s ID which is authenticated." )]
   string AccountID;

      [Description ( 
          "String defining a hostname, URI or other information "
          "identifying the system where the Account resides." )]
   string AccountContext;


};
