// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "A class describing a company\'s and/or administrator\'s "
       "credential requirements that should be authenticated in order "
       "to establish/trust a CIM_Identity. This class defines a user "
       "whose Kerberos ticket should be authenticated." )]
class CIM_KerberosAuthentication : CIM_AuthenticationCondition {

      [Description ( 
          "String holding the user name for which the ticket is issued."
           )]
   string UserName;


};
