// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ServiceComponent 
// ==================================================================
   [Association, Aggregation, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "The ServiceComponent aggregation models a set of subordinate "
       "Services that are aggregated together to form a higher-level "
       "service." )]
class CIM_ServiceComponent : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( "The parent Service." )]
   CIM_Service REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "The component Service." )]
   CIM_Service REF PartComponent;


};
