// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SupportAccess 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Core::ProductFRU" ), 
    Description ( 
       "The CIM_SupportAccess association defines how to obtain "
       "assistance for a Product." )]
class CIM_SupportAccess : CIM_ManagedElement {

      [Key, Description ( 
          "SupportAccessID is an arbitrary, free form string "
          "defined by the Product Vendor or by the organization "
          "that deploys the Product. This property, since it is a "
          "key, should be unique throughout the enterprise." ), 
       MaxLen ( 256 )]
   string SupportAccessId;

      [Override ( "Description" ), 
       Description ( 
          "A textual description of the type of Support provided." ), 
       MappingStrings { "MIF.DMTF|Support|001.3" }]
   string Description;

      [Description ( 
          "CommunicationInfo provides the details of the "
          "Communication Mode. For example, if the "
          "CommunicationMode is \'Phone\', CommunicationInfo "
          "specifies the phone number to be called." ), 
       MappingStrings { "MIF.DMTF|FRU|002.11", "MIF.DMTF|FRU|002.12" }]
   string CommunicationInfo;

      [Description ( 
          "CommunicationMode defines the form of communication in "
          "order to obtain support. For example, phone "
          "communication (value =2), fax (3) or email (8) can be "
          "specified." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8" }, 
       Values { "Other", "Phone", "Fax", "BBS", "Online Service", 
          "Web Page", "FTP", "E-mail" }, 
       MappingStrings { "MIF.DMTF|Support|001.5" }]
   uint16 CommunicationMode;

      [Description ( 
          "Locale defines the geographic region and/or language "
          "dialect to which this Support resource pertains." ), 
       MaxLen ( 64 ), 
       MappingStrings { "MIF.DMTF|Support|001.2" }]
   string Locale;


};
