// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Redundancy" ), 
    Description ( 
       "The Spared association indicates an element that is acting as "
       "a replacement for another element. If the Dependent references "
       "a Collection, this indicates that \'spared\' element is a "
       "member of that collection and the actual mapping between the "
       "spare and the spared is un-important." )]
class CIM_Spared : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "A ManagedElement that has replaced/spared another the "
          "reference Dependent element." )]
   CIM_ManagedElement REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The Element or Elements (in the case of a collection) "
          "that have been replaced/spared." )]
   CIM_ManagedElement REF Dependent;


};
