// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_FRUPhysicalElements 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Core::ProductFRU" ), 
    Description ( "Indicates the PhysicalElements that make up a FRU." )]
class CIM_FRUPhysicalElements {

      [Key, Aggregate, Max ( 1 ), 
       Description ( "The FRU." )]
   CIM_FRU REF FRU;

      [Key, Description ( 
          "The PhysicalElement which is a part of the FRU." )]
   CIM_PhysicalElement REF Component;


};
