// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ServiceStatistics 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Core::Statistics" ), 
    Description ( 
       "ServiceStatistics relates the ServiceStatisticalInformation "
       "class to the Service to which it applies." )]
class CIM_ServiceStatistics : CIM_Statistics {

      [Override ( "Stats" ), 
       Weak, Description ( "The statistical object." )]
   CIM_ServiceStatisticalInformation REF Stats;

      [Override ( "Element" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The Service to which the statistics apply." )]
   CIM_Service REF Element;


};
