// Copyright (c) 2010 DMTF.  All rights reserved.
   [Version ( "2.27.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "RemoteServiceAccessPoint describes access or addressing "
       "information or a combination of this information for a remote "
       "connection that is known to a local network element. This "
       "information is scoped or contained by the local network "
       "element, because this is the context in which the connection "
       "is remote. \n"
       "The relevance of the remote access point and information on "
       "its use are described by subclassing RemoteServiceAccessPoint "
       "or by associating to it." )]
class CIM_RemoteServiceAccessPoint : CIM_ServiceAccessPoint {

      [Description ( 
          "Access or addressing information or a combination of "
          "this information for a remote connection. This "
          "information can be a host name, network address, or "
          "similar information." ), 
       ModelCorrespondence { 
          "CIM_RemoteServiceAccessPoint.InfoFormat" }]
   string AccessInfo;

      [Description ( 
          "An enumerated integer that describes the format and "
          "interpretation of the AccessInfo property.\n"
          "206\'Parameterized URL\'- a URL containing "
          "${parameterName} strings. Those strings are intended to "
          "be replaced in their entirety by the value of the named "
          "parameter. The interpretation of such parameters is not "
          "defined by this subclass. \n"
          "As an example use: If a parameter named \'CompanyURL\' "
          "has a value of \'www.DMTF.org\' and the value of "
          "AccessInfo was \'http:\\${CompanyURL}\', then the "
          "resultant URL is intended to be \'http:\\www.dmtf.org\'." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "11", "12", "13", "100", "101", "102", "103", "104", 
          "200", "201", "202", "203", "204", "205", "206", "..", 
          "32768..65535" }, 
       Values { "Other", "Host Name", "IPv4 Address", 
          "IPv6 Address", "IPX Address", "DECnet Address", 
          "SNA Address", "Autonomous System Number", "MPLS Label", 
          "IPv4 Subnet Address", "IPv6 Subnet Address", 
          "IPv4 Address Range", "IPv6 Address Range", "Dial String", 
          "Ethernet Address", "Token Ring Address", "ATM Address", 
          "Frame Relay Address", "URL", "FQDN", "User FQDN", 
          "DER ASN1 DN", "DER ASN1 GN", "Key ID", 
          "Parameterized URL", "DMTF Reserved", "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_RemoteServiceAccessPoint.OtherInfoFormatDescription" }]
   uint16 InfoFormat;

      [Description ( 
          "Describes the format when the property InfoFormat is set "
          "to 1 (Other)." ), 
       ModelCorrespondence { 
          "CIM_RemoteServiceAccessPoint.InfoFormat" }]
   string OtherInfoFormatDescription;

      [Description ( 
          "The AccessContext property identifies the role this "
          "RemoteServiceAccessPoint is playing in the hosting "
          "system." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11", "..", "32768..65535" }, 
       Values { "Unknown", "Other", "Default Gateway", "DNS Server", 
          "SNMP Trap Destination", "MPLS Tunnel Destination", 
          "DHCP Server", "SMTP Server", "LDAP Server", 
          "Network Time Protocol (NTP) Server", 
          "Management Service", 
          "internet Storage Name Service (iSNS)", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_RemoteServiceAccessPoint.OtherAccessContext" }]
   uint16 AccessContext = 0;

      [Description ( 
          "When the AccessContext property contains a value of 1, "
          "\"Other\" then this is a free form string providing more "
          "information about the role of RemoteServiceAccessPoint "
          "in the hosting system." ), 
       ModelCorrespondence { 
          "CIM_RemoteServiceAccessPoint.AccessContext" }]
   string OtherAccessContext;


};
