// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00714.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_Location
// ==================================================================
   [Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Physical" ), 
    Description ( 
       "The Location class specifies the position and address of a "
       "PhysicalElement." )]
class CIM_Location : CIM_ManagedElement {

      [Key, Description ( 
          "Name is a free-form string defining a label for the "
          "Location. It is a part of the key for the object." ), 
       MaxLen ( 256 )]
   string Name;

      [Key, Description ( 
          "Position is a free-form string that indicates the "
          "placement of a PhysicalElement. It can specify slot "
          "information on a HostingBoard, mounting site in a "
          "Cabinet, or latitude and longitude information, for "
          "example, from a GPS. It is part of the key of the "
          "Location object." ), 
       MaxLen ( 256 )]
   string PhysicalPosition;

      [Description ( 
          "Address is a free-form string indicating a street, "
          "building, or other type of address for the location of "
          "the PhysicalElement." ), 
       MaxLen ( 1024 )]
   string Address;


};
