// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.23.0" ), 
    UMLPackagePath ( "CIM::Device::CoolingAndPower" ), 
    Description ( 
       "CIM_PowerUtilizationManagementCapabilities describes the "
       "capabilities of the associated "
       "CIM_PowerUtilizationManagementService." )]
class CIM_PowerUtilizationManagementCapabilities : CIM_EnabledLogicalElementCapabilities {

      [Description ( 
          "PowerUtilizationModesSupported indicates the power "
          "utilization modes supported by associated instances of "
          "CIM_PowerUtilizationManagementService. See "
          "CIM_PowerUtilizationManagementService.PowerSavingMode "
          "for a description of each enumeration value." ), 
       ValueMap { "3", "4", "..", "32768..65535" }, 
       Values { "Dynamic", "Static", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_PowerUtilizationManagementService.PowerUtilizationMode" }]
   uint16 PowerUtilizationModesSupported[];

      [Description ( "Enumeration of supported method identifiers" ), 
       ValueMap { "2", "..", "32768..65535" }, 
       Values { "ApplyPowerAllocationSettings", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 SupportedMethods[];


};
