// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PhysicalStatistics 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Core::Statistics" ), 
    Description ( 
       "PhysicalStatistics relates the PhysicalStatisticalInformation "
       "class to the PhysicalElement to which it applies." )]
class CIM_PhysicalStatistics : CIM_Statistics {

      [Override ( "Stats" ), 
       Weak, Description ( "The statistical object." )]
   CIM_PhysicalStatisticalInformation REF Stats;

      [Override ( "Element" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The PhysicalElement to which the statistics apply." )]
   CIM_PhysicalElement REF Element;


};
