// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00714.001" type ="change">Update of
// descriptions based on Tech Edit review.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ContainedLocation
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Physical" ), 
    Description ( 
       "ContainedLocation defines one location in the context of "
       "another. For example, a campus might \'contain\' a building, "
       "which in turn \'contains\' a floor." )]
class CIM_ContainedLocation : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( "The containing location." )]
   CIM_Location REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "The contained location." )]
   CIM_Location REF PartComponent;


};
