// Copyright (c) 2010 DMTF.  All rights reserved.
   [Version ( "2.25.0" ), 
    UMLPackagePath ( "CIM::System::SystemElements" ), 
    Description ( 
       "CIM_VirtualSystemSettingData defines the virtual aspects of a "
       "virtual system through a set of virtualization specific "
       "properties. CIM_VirtualSystemSettingData is also used as the "
       "top level class of virtual system configurations. Virtual "
       "system configurations model configuration information about "
       "virtual systems and their components. A virtual system "
       "configuration consists of one top-level instance of class "
       "CIM_VirtualSystemSettingData that aggregates a number of "
       "instances of class CIM_ResourceAllocationSettingData, using "
       "association CIM_ConcreteComponent. \n"
       "Virtual system configurations may for example be used to "
       "reflect configurations of \n"
       "- virtual systems that are defined at a virtualization "
       "platform, \n"
       "- virtual systems that are currently active, \n"
       "- input requests to create new virtual systems, \n"
       "- input requests to modify existing virtual systems, or \n"
       "- snapshots of virtual systems." )]
class CIM_VirtualSystemSettingData : CIM_SettingData {

      [Description ( 
          "VirtualSystemIdentifier shall reflect a unique name for "
          "the system as it is used within the virtualization "
          "platform. Note that the VirtualSystemIdentifier is not "
          "the hostname assigned to the operating system instance "
          "running within the virtual system, nor is it an IP "
          "address or MAC address assigned to any of its network "
          "ports. \n"
          "On create requests VirtualSystemIdentifier may contain "
          "implementation specific rules (like simple patterns or "
          "regular expression) that may be interpreted by the "
          "implementation when assigning a VirtualSystemIdentifier." )]
   string VirtualSystemIdentifier;

      [Description ( 
          "VirtualSystemType shall reflect a particular type of "
          "virtual system.\n"
          "The property value shall conform to this format (in "
          "ABNF): vs-type = dmtf-value / other-org-value / "
          "legacy-value; dmtf-value = \"DMTF:\" defining-org \":\" "
          "org-vs-type; other-org-value = defining-org \":\" org-vs-type;\n"
          "Where: dmtf-value:\n"
          "is a property value defined by DMTF and is defined in "
          "the description of this property. other-org-value:\n"
          "is a property value defined by a business entity other "
          "than DMTF and is not defined in the description of this "
          "property. legacy-value:\n"
          "is a property value defined by a business entity other "
          "than DMTF and is not defined in the description of this "
          "property. These values are permitted but recommended to "
          "be deprecated over time. defining-org:\n"
          "is an identifier for the business entity that defines "
          "the virtual system type. It shall include a copyrighted, "
          "trademarked, or otherwise unique name that is owned by "
          "that business entity. It shall not be \"DMTF\" and shall "
          "not contain a colon (:). org-vs-type:\n"
          "is an identifier for the virtual system type within the "
          "defining business entity. It shall be unique within the "
          "defining-org. It may use any character allowed for CIM "
          "strings, except for the following: U0000-U001F (Unicode "
          "C0 controls) U0020 (space), note that the reason is that "
          "OVF allows for multiple space-separated vs-type values "
          "in this property. U007F (Unicode C0 controls) "
          "U0080-U009F (Unicode C1 controls)\n"
          "If there is a need to structure the value into segments, "
          "the segments should be separated with a single colon (:).\n"
          "The values of this property shall be processed case "
          "sensitively. They are intended to be processed "
          "programmatically (instead of being a display name) and "
          "should be short.\n"
          "As stated in the class description, instances of this "
          "class may be used for various purposes. A management "
          "application intending to use an instance of this class "
          "as input parameter to an operation that creates or "
          "modifies a virtual system should first determine the set "
          "of valid virtual system types that are supported by the "
          "virtualization platform hosting the virtual system by "
          "inspecting values of array property "
          "VirtualSystemTypesSupported of the instance of class "
          "CIM_VirtualSystemManagementCapabilities that describes "
          "the capabilities of the virtualization platform.\n"
          "The following DMTF values are defined: DMTF:unknown - "
          "the virtual system type is unknown or cannot be "
          "determined" )]
   string VirtualSystemType;

      [Description ( 
          "End-user supplied notes that are related to the virtual system."
           )]
   string Notes[];

      [Description ( 
          "Time when the virtual system configuration was created." )]
   datetime CreationTime;

      [Description ( 
          "Unique id of the virtual system configuration. Note that "
          "the ConfigurationID is different from the InstanceID as "
          "it is assigned by the implementation to a virtual system "
          "or a virtual system configuration. It is not a key, and "
          "the same value may occur within more than one instance." )]
   string ConfigurationID;

      [Description ( 
          "Filepath of a directory where information about the "
          "virtual system configuration is stored.Format shall be "
          "URI based on RFC 2079." )]
   string ConfigurationDataRoot;

      [Description ( 
          "Filepath of a file where information about the virtual "
          "system configuration is stored. A relative path appends "
          "to the value of the ConfigurationDataRoot "
          "property.Format shall be URI based on RFC 2079." )]
   string ConfigurationFile;

      [Description ( 
          "Filepath of a directory where information about virtual "
          "system snapshots is stored. A relative path appends to "
          "the value of the ConfigurationDataRoot property.Format "
          "shall be URI based on RFC 2079." )]
   string SnapshotDataRoot;

      [Description ( 
          "Filepath of a directory where suspend related "
          "information about the virtual system is stored. A "
          "relative path appends to the value of the "
          "ConfigurationDataRoot property.Format shall be URI based "
          "on RFC 2079." )]
   string SuspendDataRoot;

      [Description ( 
          "Filepath of a directory where swapfiles of the virtual "
          "system are stored. A relative path appends to the value "
          "of the ConfigurationDataRoot property.Format shall be "
          "URI based on RFC 2079." )]
   string SwapFileDataRoot;

      [Description ( 
          "Filepath of a directory where log information about the "
          "virtual system is stored. A relative path appends to the "
          "value of the ConfigurationDataRoot property.Format shall "
          "be URI based on RFC 2079." )]
   string LogDataRoot;

      [Description ( 
          "Action to take for the virtual system when the host is started."
           ), 
       ValueMap { "2", "3", "4", ".." }, 
       Values { "None", "Restart if previously active", 
          "Always startup", "DMTF Reserved" }]
   uint16 AutomaticStartupAction;

      [Description ( 
          "Delay applicable to startup action. The value shall be "
          "in the interval variant of the datetime datatype." )]
   datetime AutomaticStartupActionDelay;

      [Description ( 
          "Number indicating the relative sequence of virtual "
          "system activation when the host system is started. A "
          "lower number indicates earlier activation. If one or "
          "more configurations show the same value, the sequence is "
          "implementation dependent. A value of 0 indicates that "
          "the sequence is implementation dependent." )]
   uint16 AutomaticStartupActionSequenceNumber;

      [Description ( 
          "Action to take for the virtual system when the host is shut down."
           ), 
       ValueMap { "2", "3", "4", ".." }, 
       Values { "Turn Off", "Save state", "Shutdown", "DMTF Reserved" }]
   uint16 AutomaticShutdownAction;

      [Description ( 
          "Action to take for the virtual system when the software "
          "executed by the virtual system fails. Failures in this "
          "case means a failure that is detectable by the host "
          "platform, such as a non-interruptible wait state "
          "condition." ), 
       ValueMap { "2", "3", "4", ".." }, 
       Values { "None", "Restart", "Revert to snapshot", 
          "DMTF Reserved" }]
   uint16 AutomaticRecoveryAction;

      [Description ( 
          "Filepath of a file where recovery relateded information "
          "of the virtual system is stored.Format shall be URI "
          "based on RFC 2079." )]
   string RecoveryFile;


};
