// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00722.000" type ="change">Update of
// descriptions based on Tech Edit review.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ActiveConnection
// ==================================================================
   [Association, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "This association defines a connection that is currently "
       "communicating, or is configured to communicate, between two "
       "ServiceAccessPoints. It is used when the connection is not "
       "treated as a ManagedElement itself (that is, with Status, "
       "statistics, and so on), but its existence is known. The SAPs "
       "that are connected are typically at the same networking or "
       "application layer." )]
class CIM_ActiveConnection : CIM_SAPSAPDependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "A ServiceAccessPoint that is configured to communicate "
          "or is actively communicating with the Dependent SAP. In "
          "a unidirectional connection, this SAP is the one that is "
          "transmitting." )]
   CIM_ServiceAccessPoint REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "A second ServiceAccessPoint that is configured to "
          "communicate or is actively communicating with the "
          "Antecedent SAP. In a unidirectional connection, this SAP "
          "is the one that is receiving the communication." )]
   CIM_ServiceAccessPoint REF Dependent;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this element is deprecated because it "
          "is incorrectly placed on the association. Unicast, "
          "broadcast, or other traffic types are not a function of "
          "the connection between the referenced endpoints, but "
          "rather are a function of the addressing, protocol and "
          "basic functionality of the endpoints. \n"
          "Deprecated description: The type of traffic that is "
          "carried over this connection." ), 
       ValueMap { "0", "1", "2", "3", "4", "5" }, 
       Values { "Unknown", "Other", "Unicast", "Broadcast", 
          "Multicast", "Anycast" }, 
       ModelCorrespondence { 
          "CIM_ActiveConnection.OtherTrafficDescription" }]
   uint16 TrafficType;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this element is deprecated because it "
          "is incorrectly placed on the association. Unicast, "
          "broadcast, or other traffic types are not a function of "
          "the connection between the referenced endpoints, but "
          "rather are a function of the addressing, protocol and "
          "basic functionality of the endpoints. \n"
          "Deprecated description: A string that describes the type "
          "of traffic that is being carried over this instance when "
          "its Type property is set, for example, to 1 (Other)." ), 
       MaxLen ( 64 ), 
       ModelCorrespondence { "CIM_ActiveConnection.TrafficType" }]
   string OtherTrafficDescription;

      [Description ( 
          "TRUE means that this connection is unidirectional; FALSE "
          "means that this connection is bidirectional. When the "
          "connection is unidirectional, the \"speaker\" should be "
          "defined as the Antecedent reference. In a bidirectional "
          "connection, the selection of which AccessPoint is the "
          "Antecedent or Dependent is immaterial." )]
   boolean IsUnidirectional;


};
