// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00717.001" type ="add">Deprecated</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RedundancyComponent
// ==================================================================
   [Association, Deprecated { "CIM_MemberOfCollection" }, 
    Aggregation, Version ( "2.13.0" ), 
    UMLPackagePath ( "CIM::Core::Redundancy" ), 
    Description ( 
       "A RedundancyGroup aggregates Managed System Elements and "
       "indicates that these elements, taken together, provide "
       "redundancy. All elements aggregated in a RedundancyGroup "
       "should be instantiations of the same object class. \n"
       "The use of this class is being depreacted in lieu of using "
       "MemberOfCollection in conjunction with RedundancySet." )]
class CIM_RedundancyComponent : CIM_Component {

      [Deprecated { "CIM_MemberOfCollection.Collection" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "The RedundancyComponent association indicates that \'this "
          "set of fans\' or \'these physical extents\' participate "
          "in a single RedundancyGroup." )]
   CIM_RedundancyGroup REF GroupComponent;

      [Deprecated { "CIM_MemberOfCollection.Member" }, 
       Override ( "PartComponent" ), 
       Description ( "The component of the redundancy group." )]
   CIM_ManagedSystemElement REF PartComponent;


};
