// Copyright (c) 2008 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_ListenerDestinationWSManagement describes the destination "
       "for CIM indications to be delivered via WS-Management." )]
class CIM_ListenerDestinationWSManagement : CIM_ListenerDestination {

      [Required, Override ( "Destination" ), 
       Description ( 
          "The destination URL defined in the WS-Eventing Subscribe "
          "message. This must match the wsa:Address element in the "
          "wse:NotifyTo EPR. The value may be the WS-Addressing "
          "anonymous URI if the subscription uses or employs a Pull "
          "mode." )]
   string Destination;

      [Description ( 
          "Separate To address for notice of abnormal subscription "
          "termination." )]
   string DestinationEndTo;

      [Description ( 
          "If the events contain localized content, the service "
          "should accept a subscription with this Locale block "
          "acting as a hint. The language of the event message is "
          "encoded in an xml:lang attribute using RFC 3066 language "
          "codes. The service should attempt to localize any "
          "descriptive content to the specified language when "
          "delivering such events." )]
   string Locale;

      [Description ( 
          "This block acts as a hint to indicate how the delivered "
          "events should be encoded. The two standard tokens "
          "defined for this purpose are \"UTF-8\" or \"UTF-16\", "
          "although other encoding formats may be specified if "
          "necessary." )]
   string ContentEncoding;

      [Description ( 
          "Method by which the service is to deliver events to the "
          "client. Values are as follows. Push (2): the event is "
          "sent to the destination address; depending on the "
          "protocol, delivery may not be guaranteed. PushWithAck "
          "(3): the service sends the event and waits for a "
          "specific acknowledgment message from the subscriber. "
          "Events (4): the service collects events into batches and "
          "sends the batches to the subscriber. Pull (5): the "
          "service collects the events into batches and the "
          "subscriber pulls each batch from the service using "
          "wxf:Pull." ), 
       ValueMap { "2", "3", "4", "5", "..", "32787.." }, 
       Values { "Push", "PushWithAck", "Events", "Pull", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint16 DeliveryMode;

      [Description ( 
          "Specifies how often heartbeat events are added to the "
          "event stream at the specified interval." ), 
       Units ( "Seconds" )]
   uint64 Heartbeat;

      [Description ( 
          "A property element that instructs the service to send a "
          "bookmark with each event. Bookmarks apply to all "
          "delivery modes. The bookmark is a token which represents "
          "an abstract pointer in the event stream, but whether it "
          "points to the last delivered event or the last event "
          "plus one (the upcoming event) makes no difference since "
          "the token is supplied to the same implementation during "
          "a subsequent wse:Subscribe operation. The service may "
          "thus attach any service-specific meaning and structure "
          "to the bookmark with no change to the client." )]
   boolean SendBookmark;

      [Description ( 
          "This element may contain a duration that indicates the "
          "maximum amount of time the service should allow to "
          "elapse while batching EVENT bodies. That is, this time "
          "may not be exceeded between the encoding of the first "
          "event in the batch and the dispatching of the batch for "
          "delivery." ), 
       Units ( "Seconds" )]
   uint64 MaxTime;

      [Description ( 
          "A URI identifying the WS-Management security profile to "
          "be used by the service (acting as publisher) when "
          "authenticating to the event sink (consumer) at event "
          "delivery time." )]
   string DeliveryAuth;

      [Description ( 
          "Specifies the treatment of Indication subclasses, "
          "whether subclasses are to be included and with what set "
          "of properties. Valid values are: None, "
          "IncludeSubclassProperties, and "
          "ExcludeSubclassProperties. Using None, only instances of "
          "the parent class are included in the output (event "
          "stream). For other modes, subclass instances are "
          "included with the sets of properties stated." ), 
       ValueMap { "1", "2", "3", ".." }, 
       Values { "None", "IncludeSubclassProperties", 
          "ExcludeSubclassProperties", "DMTF Reserved" }]
   uint16 PolyMorphismMode;


};
