// Copyright (c) 2010 DMTF.  All rights reserved.
   [Indication, Version ( "2.27.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_InstModification notifies when an instance is modified." )]
class CIM_InstModification : CIM_InstIndication {

      [Description ( 
          "A copy of the \'previous\' instance whose change "
          "generated the Indication. PreviousInstance contains "
          "\'older\' values of an instance\'s properties (as "
          "compared to SourceInstance), selected by the "
          "IndicationFilter\'s Query." ), 
       EmbeddedObject]
   string PreviousInstance;


};
