// Copyright (c) 2011 DMTF.  All rights reserved.
   [Indication, Abstract, Version ( "2.29.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_InstIndication is an abstract superclass describing "
       "changes to instances. Subclasses represent specific types of "
       "change notifications, such as instance creation, deletion and "
       "modification." )]
class CIM_InstIndication : CIM_Indication {

      [Required, Description ( 
          "A copy of the instance that changed to generate the "
          "Indication. SourceInstance contains the current values "
          "of the properties selected by the Indication Filter\'s "
          "Query. In the case of CIM_InstDeletion, the property "
          "values are copied before the instance is deleted." ), 
       EmbeddedObject]
   string SourceInstance;

      [Description ( 
          "The Model Path of the SourceInstance. The following "
          "format MUST be used to encode the Model Path: \n"
          "<NamespacePath>:<ClassName>.<Prop1>=\"<Value1>\", \n"
          "<Prop2>=\"<Value2>\", ..." ), 
       ModelCorrespondence { "CIM_InstIndication.SourceInstance" }]
   string SourceInstanceModelPath;

      [Description ( 
          "The host name or IP address of the SourceInstance." ), 
       ModelCorrespondence { "CIM_InstIndication.SourceInstance" }]
   string SourceInstanceHost;


};
