// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::IPsecPolicy" ), 
    Description ( 
       "RuleThatGeneratedSA associates a SecurityAssociationEndpoint "
       "with the SARule used to generate (or negotiate) it." )]
class CIM_RuleThatGeneratedSA : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 0 ), 
       Max ( 1 ), 
       Description ( "SARule that led to the Security Association." )]
   CIM_SARule REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "SecurityAssociationEndpoint created using the rule." )]
   CIM_SecurityAssociationEndpoint REF Dependent;


};
