// Copyright (c) 2005 DMTF.  All rights reserved.
   [Abstract, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::IPsecPolicy" ), 
    Description ( 
       "SAAction is the base class for the various types of key "
       "exchange or IPsec actions. It is abstract and used to "
       "categorize the different types of actions of SARules." ), 
    MappingStrings { "IPSP Policy Model.IETF|SAAction" }]
class CIM_SAAction : CIM_PolicyAction {

      [Description ( 
          "DoPacketLogging causes a log message to be generated "
          "when the action is applied to a packet." ), 
       MappingStrings { 
          "IPSP Policy Model.IETF|SAAction.DoPacketLogging" }, 
       ModelCorrespondence { 
          "CIM_SecurityAssociationEndpoint.PacketLoggingActive" }]
   boolean DoPacketLogging;


};
