// Copyright (c) 2007 DMTF.  All rights reserved.
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Metrics::UnitOfWork" ), 
    Description ( 
       "This association links a LogicalElement to the UnitsOfWork "
       "that it can perform. For example, a Printer Device may have "
       "associated UnitOfWorkDefinitions representing PrintJobs. This "
       "is a Dependency relationship since the Definitions are given "
       "context by the LogicalElement." )]
class CIM_LogicalElementUnitOfWorkDef : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The LogicalElement that is providing the UnitOfWork." )]
   CIM_LogicalElement REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The UnitOfWorkDefinition associated with the LogicalElement."
           )]
   CIM_UnitOfWorkDefinition REF Dependent;


};
