TOP = ../../../..
include $(TOP)/config.mak
LIBRARY = moftestutil

SOURCES= \
    util.c 

INCLUDES= \
    $(TOP) \
    $(TOP)/common \
    $(TOP)/common/inc \

DEFINES= TEST_BUILD

include $(TOP)/mak/rules.mak

