s~<wsa:MessageID>uuid:....................................</wsa:MessageID>~<wsa:MessageID>uuid:00000000-0000-0000-0000-000000000000</wsa:MessageID>~g
s~<wsen:EnumerationContext>[0-9][0-9]*</wsen:EnumerationContext>~<wsen:EnumerationContext>NNNN</wsen:EnumerationContext>~g
s~Content-Length: [0-9][0-9]*~Content-Length: NNNN~g
s~<p:SystemName>.*$~~g
s~<p:ConfigLibDir>.*$~~g
s~<p:ConfigBinDir>.*$~~g
s~<p:ConfigIncludeDir>.*$~~g
s~<p:ConfigDataDir>.*$~~g
s~<p:ConfigDataDir>.*$~~g
s~<p:ConfigLocalStateDir>.*$~~g
s~<p:ConfigSysConfDir>.*$~~g
s~<p:ConfigLogFile>.*$~~g
s~<p:ConfigPIDFile>.*$~~g
s~<p:ConfigRegisterDir>.*$~~g
s~<p:ConfigSchemaDir>.*$~~g
s~<p:ConfigProviderDir>.*$~~g
s~<p:ProductVersionRevision>.*$~~g
s~<p:ProductVersionMinor>.*$~~g
s~<p:ProductVersionMajor>.*$~~g
s~<p:ProductVersionString>.*$~~g
