/*
**==============================================================================
**
** Copyright (c) Microsoft Corporation. All rights reserved. See file LICENSE
** for license information.
**
**==============================================================================
*/

#define XML_ERROR_BAD_ENTITY_REFERENCE              5000
#define XML_ERROR_BAD_CHARACTER_REFERENCE           5001
#define XML_ERROR_UNDEFINED_NAMESPACE_PREFIX        5002
#define XML_ERROR_EXPECTED_ATTRIBUTE_NAME           5003
#define XML_ERROR_EXPECTED_ATTRIBUTE_EQUALS         5004
#define XML_ERROR_EXPECTED_ATTRIBUTE_OPENING_QUOTES 5005
#define XML_ERROR_EXPECTED_ATTRIBUTE_CLOSING_QUOTES 5006
#define XML_ERROR_TOO_MANY_NAMESPACES               5007
#define XML_ERROR_TOO_MANY_ATTRIBUTES               5008
#define XML_ERROR_END_OF_XML_INSTRUCTION            5009
#define XML_ERROR_END_OF_INSTRUCTION_MISSING        5010
#define XML_ERROR_ELEMENT_NAME_EXPECTED             5011
#define XML_ERROR_ELEMENT_NAME_PREMATURE_END        5012
#define XML_ERROR_ELEMENT_DEPTH_OVERFLOW            5014
#define XML_ERROR_ELEMENT_NAME_NOT_CLOSED           5015
#define XML_ERROR_ELEMENT_NAME_EXPECTED_ELEM_END    5016
#define XML_ERROR_ELEMENT_NAME_PREMATURE_END_ELEM_END 5017
#define XML_ERROR_ELEMENT_NAME_NOT_CLOSED_ELEM_END  5018
#define XML_ERROR_ELEMENT_TOO_MANY_ENDS             5019
#define XML_ERROR_ELEMENT_END_ELEMENT_TAG_NOT_MATCH_START_TAG 5020
#define XML_ERROR_COMMENT_END_EXPECTED              5021
#define XML_ERROR_COMMENT_PREMATURE_END             5022
#define XML_ERROR_CDATA_PREMATURE_END               5023
#define XML_ERROR_DOCTYPE_PREMATURE_END             5024
#define XML_ERROR_CHARDATA_EXPECTED_ELEMENT_END_TAG 5025
#define XML_ERROR_OPEN_ANGLE_BRACKET_EXPECTED       5026
#define XML_ERROR_COMMENT_CDATA_DOCTYPE_EXPECTED    5027
#define XML_ERROR_ELEMENT_EXPECTED                  5028
#define XML_ERROR_UNEXPECTED_STATE                  5029
#define XML_ERROR_SPECIFIC_ELEMENT_EXPECTED         5030
#define XML_ERROR_SPECIFIC_END_ELEMENT_EXPECTED     5031
#define XML_ERROR_CHARACTER_DATA_EXPECTED           5032

/* WS-MAN ONES! */
#define WSMAN_ERROR_NO_CLASS_NAME_IN_SELECTOR       5050
#define WSMAN_ERROR_NO_RESOURCE_URI                 5051
#define WSMAN_ERROR_OUTOFMEMORY                     5052
#define WSMAN_ERROR_BAD_SELECTOR                    5053
#define WSMAN_ERROR_BAD_EPR_IN_SELECTOR             5054
