// Copyright (c) 2010 DMTF.  All rights reserved.
   [Version ( "2.27.0" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "A RegisteredProfile describes a set of CIM Schema classes with "
       "required properties and/or methods, necessary to manage a "
       "real-world entity or to support a usage scenario, in an "
       "interoperable fashion. RegisteredProfiles can be defined by "
       "the DMTF or other standards organizations. Note that this "
       "class should not be confused with CIM_Profile, which collects "
       "SettingData instances, to be applied as a \'configuration "
       "profile\' for an element. \n"
       "A RegisteredProfile is a named \'standard\' for CIM-based "
       "management of a particular System, subsystem, Service or other "
       "entity, for a specified set of uses. It is a complete, "
       "standalone definition, as opposed to the subclass "
       "RegisteredSubProfile, which requires a scoping profile for "
       "context. \n"
       "The uses for a RegisteredProfile or SubProfile MUST be "
       "specified in the document that defines the profile. Examples "
       "of Profiles are to manage various aspects of an Operating "
       "System, Storage Array, or Database. The name of the profile is "
       "defined and scoped by its authoring organization." )]
class CIM_RegisteredProfile : CIM_ManagedElement {

      [Key, Override ( "InstanceID" ), 
       Description ( 
          "Within the scope of the instantiating Namespace, "
          "InstanceID opaquely and uniquely identifies an instance "
          "of this class. In order to ensure uniqueness within the "
          "NameSpace, the value of InstanceID SHOULD be constructed "
          "using the following \'preferred\' algorithm: \n"
          "<OrgID>:<LocalID> \n"
          "Where <OrgID> and <LocalID> are separated by a colon "
          "\':\', and where <OrgID> MUST include a copyrighted, "
          "trademarked or otherwise unique name that is owned by "
          "the business entity creating/defining the InstanceID, or "
          "is a registered ID that is assigned to the business "
          "entity by a recognized global authority. (This is "
          "similar to the <Schema Name>_<Class Name> structure of "
          "Schema class names.) In addition, to ensure uniqueness, "
          "<OrgID> MUST NOT contain a colon (\':\'). When using "
          "this algorithm, the first colon to appear in InstanceID "
          "MUST appear between <OrgID> and <LocalID>. \n"
          "<LocalID> is chosen by the organizational entity and "
          "SHOULD not be re-used to identify different underlying "
          "(real-world) elements. If the above \'preferred\' "
          "algorithm is not used, the defining entity MUST assure "
          "that the resultant InstanceID is not re-used across any "
          "InstanceIDs produced by this or other providers for this "
          "instance\'s NameSpace. \n"
          "For DMTF defined instances, the \'preferred\' algorithm "
          "MUST be used with the <OrgID> set to \'CIM\'." )]
   string InstanceID;

      [Required, Description ( 
          "The organization that defines this profile." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "11", "12", "13", "14", "15", "16", "17", "18", "19", 
          "20", "21", ".." }, 
       Values { "Other", "DMTF", "CompTIA", 
          "Consortium for Service Innovation", "FAST", "GGF", 
          "INTAP", "itSMF", "NAC", 
          //10
          "Northwest Energy Efficiency Alliance", 
          "SNIA", "TM Forum", "The Open Group", "ANSI", "IEEE", 
          "IETF", "INCITS", "ISO", "W3C", //20
          "OGF", 
          "The Green Grid", "DMTF Reserved" }, 
       ModelCorrespondence { 
          "CIM_RegisteredProfile.OtherRegisteredOrganization" }]
   uint16 RegisteredOrganization;

      [Description ( 
          "A free-form string providing a description of the "
          "organization when 1, \"Other\", is specified for the "
          "RegisteredOrganization." ), 
       MaxLen ( 256 ), 
       ModelCorrespondence { 
          "CIM_RegisteredProfile.RegisteredOrganization" }]
   string OtherRegisteredOrganization;

      [Required, Description ( 
          "The name of this registered profile. Since multiple "
          "versions can exist for the same RegisteredName, the "
          "combination of RegisteredName, RegisteredOrganization, "
          "and RegisteredVersion MUST uniquely identify the "
          "registered profile within the scope of the organization." ), 
       MaxLen ( 256 )]
   string RegisteredName;

      [Required, Description ( 
          "The version of this profile. The string representing the "
          "version MUST be in the form: \n"
          "M + \".\" + N + \".\" + U \n"
          "Where: \n"
          "M - The major version (in numeric form) describing the "
          "profile\'s creation or last modification. \n"
          "N - The minor version (in numeric form) describing the "
          "profile\'s creation or last modification. \n"
          "U - The update (e.g. errata, patch, ..., in numeric "
          "form) describing the profile\'s creation or last "
          "modification." )]
   string RegisteredVersion;

      [Required, Description ( 
          "This property signifies the advertisement for the "
          "profile information. It is used by the advertising "
          "services of the WBEM infrastructure to determine what "
          "should be advertised, via what mechanisms. The property "
          "is an array so that the profile MAY be advertised using "
          "several mechanisms. Note: If this property is "
          "null/uninitialized, this is equivalent to specifying the "
          "value 2, \"Not Advertised\"." ), 
       ValueMap { "1", "2", "3" }, 
       Values { "Other", "Not Advertised", "SLP" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_RegisteredProfile.AdvertiseTypeDescriptions" }]
   uint16 AdvertiseTypes[];

      [Description ( 
          "A free-form string providing additional information "
          "related to the AdvertiseType. A description MUST be "
          "provided when the AdvertiseType is 1, \"Other\". An "
          "entry in this array corresponds to the entry in the "
          "AdvertiseTypes array at the same index. It is not "
          "expected that additional descriptions are needed if the "
          "Type is set to \"Not Advertised\" or \"SLP\". However, "
          "as the SLP template expands, or as other advertisement "
          "mechanisms are defined, support for additional "
          "descriptions may be needed. This array is defined to "
          "support this." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_RegisteredProfile.AdvertiseTypes" }]
   string AdvertiseTypeDescriptions[];

      [Description ( 
          "Profiles may gather a set of provisions together that "
          "are implemented, (or not implemented), as a whole by a "
          "conformant implementation. Such sets are known as "
          "profile features.\n"
          "If a profile does not define features, then this "
          "property shall be null. \n"
          "If not null, an implementation shall put the profile "
          "defined feature name of each implemented feature in a "
          "separate entry of this array." )]
   string ImplementedFeatures[];


      [Description ( 
          "This operation is used to close a session to enumerate "
          "central and scoping class instances." )]
   uint32 CloseConformantInstances(
         [IN, Description ( 
             "The EnumerationContext parameter is the "
             "enumeration context value representing the "
             "enumeration session to be used." )]
      string EnumerationContext);

      [Description ( 
          "This operation is used to establish and open a session "
          "to enumerate central and scoping class instances of this "
          "registered profile instance and optionally to retrieve a "
          "first set of such instances." )]
   uint32 OpenConformantInstances(
         [IN, Description ( 
             "NULL, or a class name that acts as a filter to "
             "select only those central or scoping instances "
             "that a kind of the specified class. This is useful "
             "to select particular subclasses or to select a "
             "particular instances when more than one is defined "
             "for a profile." )]
      string ResultClass, 
         [IN, Description ( 
             "NULL, or unordered set of property names, acting "
             "as a restricting filter on the properties included "
             "in the returned instance. An empty list specifies "
             "to return no properties. The instance path shall "
             "always be returned." )]
      string IncludedPropertyList[], 
         [IN, Description ( 
             "The operation timeout is the minimum time the CIM "
             "Server shall maintain the open enumeration session "
             "after the last OpenConformantInstances or "
             "PullConformantInstances invocation, (unless the "
             "enumeration session was closed during that last "
             "invocation). If the operation timeout is exceeded, "
             "the enumeration session may be closed at any time, "
             "releasing any possibly allocated resources related "
             "to the enumeration session. \n"
             "An OperationTimeout of 0 means that there is no "
             "operation timeout, i.e. the enumeration session is "
             "never closed based on time.\n"
             "If OperationTimeout is NULL, the operation timeout "
             "is implementation dependent. \n"
             "All other values for OperationTimeout specify the "
             "operation timeout in seconds.\n"
             "The implementation may restrict the set of "
             "allowable values for OperationTimeout. This "
             "specifically includes the possibility to not allow "
             "0 (no timeout).\n"
             "If the specified value is not an allowable value, "
             "the method shall return failure with return code "
             "CIM_ERR_INVALID_OPERATION_TIMEOUT." )]
      uint32 OperationTimeout, 
         [IN, Description ( 
             "TRUE requests continuation on error. Continuation "
             "on error is the ability to resume an enumeration "
             "session successfully after an invocation of this "
             "method that returned an error. A conformant "
             "implementation may support continuation on error.\n"
             "If ContinueOnError is true and the method does not "
             "support continuation on error, it shall return "
             "failure with return code "
             "CIM_ERR_CONTINUATION_ON_ERROR_NOT_SUPPORTED \n"
             "If the implementation supports continuation on "
             "error, it shall support it as follows: If "
             "ContinueOnErroris true, the enumeration session "
             "shall remain open when this or a subsequent "
             "PullConformantInstances invocation returns "
             "failure, and any subsequent successful "
             "PullConformantInstances operations process the set "
             "of instances that would have remained if the "
             "failing invocation had been successful, subject to "
             "the consistency rules defined for pulled "
             "enumerations, see DSP0223.\n"
             "If ContinueOnError is false, the enumeration "
             "session shall be closed when this method returns "
             "failure." )]
      boolean ContinueOnError, 
         [IN, Description ( 
             "The MaxObjectCount input parameter defines the "
             "maximum number of elements that may be returned by "
             "this Pull operation. Any uint32 number is valid, "
             "including 0. The implementation may deliver any "
             "number of elements up to MaxObjectCount but shall "
             "not deliver more than MaxObjectCount.elements. The "
             "CIM Client may use a MaxObjectCount value of 0 as "
             "a means of restarting the OperationTimeout for the "
             "enumeration session, while it wishes to not "
             "retrieve any elements." )]
      uint32 MaxObjectCount, 
         [IN ( false ), OUT, Description ( 
             "The EnumerationContext parameter is the "
             "enumeration context value representing the "
             "enumeration session to be used.\n"
             "If the session is closed as a result of this "
             "invocation, the output EnumerationContext shall be "
             "NULL. Otherwise, the output EnumerationContext "
             "shall provide the information necessary for a "
             "subsequent PullConformantInstances call." )]
      string EnumerationContext, 
         [IN ( false ), OUT, Description ( 
             "The EndOfSequence output parameter indicates to "
             "the CIM Client whether the enumeration session is "
             "exhausted. If EndOfSequence is true upon "
             "successful completion of this invocation, no more "
             "elements are available and the implementation "
             "shall close the enumeration session, releasing any "
             "possibly allocated resources related to the "
             "enumeration session. If EndOfSequence is false, "
             "there may be additional elements available and "
             "implementation shall not close the enumeration "
             "session." )]
      boolean EndOfSequence, 
         [IN ( false ), OUT, Description ( 
             "On successful completion, an array corresponding "
             "to the InstanceWithPathList that indicates whether "
             "the entry is a scoping instance, a central "
             "instance, or both." ), 
          ValueMap { "2", "3", "4", ".." }, 
          Values { "Central Instance", "Scoping Instance", 
             "Central and Scoping Instance", "DMTF Reserved" }, 
          ArrayType ( "Indexed" ), 
          ModelCorrespondence { 
             "CIM_ProfileRegistration.OpenConformantInstances(InstanceWithPathList)" }]
      uint16 InstanceType[], 
         [IN ( false ), OUT, Description ( 
             "On successful completion, an correlated, but "
             "unordered set of the enumerated instances and "
             "their addresses, with a number of entries from 0, "
             "up to a maximum defined by MaxObjectCount, that "
             "meet the criteria defined in the Open operation "
             "that established this enumeration session. Note "
             "that returning no entries in the array does not "
             "imply that the enumeration session has been "
             "exhausted. Only the EndOfSequence output parameter "
             "indicates whether the enumeration session has been "
             "exhausted." ), 
          EmbeddedInstance ( "CIM_ManagedElement" ), 
          ArrayType ( "Indexed" ), 
          ModelCorrespondence { 
             "CIM_ProfileRegistration.OpenConformantInstances(InstanceType)" }]
      string InstanceWithPathList[]);

      [Description ( 
          "This operation is used to continue enumeration central "
          "class instances in the context of a session established "
          "by OpenConformantInstances." )]
   uint32 PullConformantInstances(
         [IN, Description ( 
             "The MaxObjectCount input parameter defines the "
             "maximum number of elements that may be returned by "
             "this method. Any uint32 number is valid, including "
             "0. The implementation may deliver any number of "
             "elements up to MaxObjectCount but shall not "
             "deliver more than MaxObjectCount elements. The CIM "
             "Client may use a MaxObjectCount value of 0 as a "
             "means of restarting the OperationTimeout for the "
             "enumeration session, while it wishes to not "
             "retrieve any elements." )]
      uint32 MaxObjectCount, 
         [IN, OUT, Description ( 
             "The EnumerationContext parameter is the "
             "enumeration context value representing the "
             "enumeration session to be used.\n"
             "On input, it shall be the EnumerationContext ouput "
             "value from the previous invocation of "
             "OpenConformantInstances or PullConformantInstances "
             "within an open enumeration session.If the session "
             "is closed as a result of this invocation, the "
             "output EnumerationContext shall be NULL. "
             "Otherwise, the output EnumerationContext shall "
             "provide the information necessary for a subsequent "
             "PullConformantInstances call." )]
      string EnumerationContext, 
         [IN ( false ), OUT, Description ( 
             "The EndOfSequence output parameter indicates to "
             "the CIM Client whether the enumeration session is "
             "exhausted. If EndOfSequence is true upon "
             "successful completion of this method, no more "
             "elements are available and the enumeration session "
             "shall be closed, releasing any possibly allocated "
             "resources related to the enumeration session. If "
             "EndOfSequence is false, there may be additional "
             "elements available and enumeration session shall "
             "be remain open unless there is an error in which "
             "case, ContinueOnError governs whether or not the "
             "session is closed or not." )]
      boolean EndOfSequence, 
         [IN ( false ), OUT, Description ( 
             "On successful completion, an array corresponding "
             "to the InstanceWithPathList that indicates whether "
             "the entry is a scoping instance, a central "
             "instance, or both." ), 
          ValueMap { "2", "3", "4", ".." }, 
          Values { "Central Instance", "Scoping Instance", 
             "Central and Scoping Instance", "DMTF Reserved" }, 
          ArrayType ( "Indexed" ), 
          ModelCorrespondence { 
             "CIM_ProfileRegistration.PullConformantInstances(InstanceWithPathList)" }]
      uint16 InstanceType[], 
         [IN ( false ), OUT, Description ( 
             "On successful completion, a correlated, but "
             "unordered set of the enumerated instances and "
             "their addresses, with a number of entries from 0, "
             "up to a maximum defined by MaxObjectCount, that "
             "meet the criteria defined in the "
             "OpenConformantInstances operation that established "
             "this enumeration session. Note that returning no "
             "entries in the array does not imply that the "
             "enumeration session has been exhausted. Only the "
             "EndOfSequence output parameter indicates whether "
             "the enumeration session has been exhausted." ), 
          EmbeddedInstance ( "CIM_ManagedElement" ), 
          ArrayType ( "Indexed" ), 
          ModelCorrespondence { 
             "CIM_ProfileRegistration.PullConformantInstances(InstanceType)" }]
      string InstanceWithPathList[]);

};
