// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "A ObjectManagerAdapter is a Service of the CIM Object Manager. "
       "An adapter can be any service of the Object Manager that needs "
       "to be managed (e.g. started, stopped, monitored, ...). There "
       "MUST be an instance for each Adapter type." )]
class CIM_ObjectManagerAdapter : CIM_WBEMService {

      [Override ( "Name" ), 
       Description ( 
          "A human-readable name that uniquely identifies the "
          "ObjectManager within a system." )]
   string Name;

      [Override ( "ElementName" ), 
       Description ( 
          "The ElementName property is used as a name of the Object "
          "Manager Adapter for human interfaces. For example, \"ACME "
          "ObjectManager Adapter\"." )]
   string ElementName;

      [Required, Description ( 
          "An implementation specific string that identifies the "
          "handle to the Object Manager Adapter." )]
   string Handle;

      [Required, Description ( 
          "AdapterType enumerates the kind of Object Manager "
          "Adapter. If \'Other\' is specified, the "
          "OtherAdapterTypeDescription property MUST be populated. \n"
          "Other - If the adapter does not fit into one of the "
          "other catagories in the list. If specified, the "
          "OtherAdapterTypeDescription property MUST be populated. \n"
          "Client - A client side adapter that responds to client "
          "operation requests, such as CIM-XML or CIM-SOAP. \n"
          "Provider - A provider adapter, such as DMI, SNMP, JSR48 "
          "or CMPI. \n"
          "Indication Handler - An Indication Handler is a service "
          "that delivers indications to a subscriber. Examples of "
          "possible Indication Handlers are CIM-XML, CIM-SOAP, SMPT "
          "(e-mail) or any other delivery mechanism. \n"
          "Repository - A repository is an adapter that can "
          "store/retrieve persistent data, such as CIM Qualifier "
          "Types, CIM Classes and CIM Instances. An Object Manager "
          "could use multiple repositories at one time, for "
          "example one could be used for CIM Schema information "
          "only, while another is used for instance information. "
          "Repositories MAY be remote or local to the CIM Object "
          "Manager. Examples of repository implementations could be "
          "databases, LDAP or files." ), 
       ValueMap { "1", "2", "3", "4", "5" }, 
       Values { "Other", "Client", "Provider", "Indication Handler", 
          "Repository" }, 
       ModelCorrespondence { 
          "CIM_ObjectManagerAdapter.OtherAdapterTypeDescription" }]
   uint16 AdapterType;

      [Description ( 
          "The type(s) of ObjectManagerAdapter when \"Other\" is "
          "included in ObjectManagerAdapterType property." ), 
       ModelCorrespondence { "CIM_ObjectManagerAdapter.AdapterType" }]
   string OtherAdapterTypeDescription;


};
