// Copyright (c) 2005 - 2007, DMTF.  All rights reserved.
// <change cr="WIPCR00383.004" type="add">New Credential class 
// hierarchy</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ManagedCredential 
// ==================================================================
   [Association, Deprecated { "CIM_ServiceAffectsElement" }, 
    Version ( "2.16.0" ), 
    UMLPackagePath ( "CIM::User::Credential" ), 
    Description ( 
       "This relationship associates a CredentialManagementService "
       "with the Credential it manages." )]
class CIM_ManagedCredential : CIM_Dependency {

      [Deprecated { "CIM_ServiceAffectsElement.AffectingElement" }, 
       Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The credential management service." )]
   CIM_CredentialManagementService REF Antecedent;

      [Deprecated { "CIM_ServiceAffectsElement.AffectedElement" }, 
       Override ( "Dependent" ), 
       Description ( "The managed credential." )]
   CIM_Credential REF Dependent;


};
