// Copyright (c) 2011 DMTF.  All rights reserved.
   [Version ( "2.29.0" ), 
    ClassConstraint { 
       "/* The constraints below aim to efficiently */  /* represent a singular OctetString. Each of the properties*/  /* is a single encoded string, thus only the first element */  /* needs to be populated. */ inv:self.EncodedCRL->size()=1" }, 
    UMLPackagePath ( "CIM::User::PublicKey" ), 
    Description ( 
       "CIM_X509CRL describes Internet X509 Public Key Infrastructure "
       "(PKI) standard based Certificate Revocation List (CRL). CRL is "
       "issued by a Certificate Authority\'s (CA) to update the list "
       "of the certificates used in the authentication. Upon "
       "application of a CRL to a set of certificates, the "
       "certificates matched to those contained in the CRL would be "
       "revoked and invalidated for use in authentication. Refer to "
       "the Internet X.509 PKI standard (RFC 3280) for more "
       "information." )]
class CIM_X509CRL : CIM_X509Infrastructure {

      [Override ( "Issued" ), 
       Description ( 
          "This property corresponds to the thisUpdate field in the "
          "Internet X509 PKI standard. The property represents the "
          "issue date of the CRL. Use a value of all "
          "\'00000101000000.000000+000\', (midnight, January 1, 1 "
          "BCE at coordinated universal time +0 minutes), if this "
          "information is not applicable. On CreateInstance, if "
          "this property is unspecified, or set to NULL, then "
          "current time is assumed." )]
   datetime Issued;

      [Override ( "Expires" ), 
       Description ( 
          "This property is not applicable for CIM_X509CRL class "
          "and shall either have value of \n"
          "\'99991231115959.999999-720\' as defined by DSP0004 to "
          "mean \"infinite future or NULL." )]
   datetime Expires;

      [Description ( 
          "The property represents the date by which the next CRL "
          "will be issued. The next CRL could be issued before the "
          "indicated date, but it will not be issued any later than "
          "the indicated date. If this information is not "
          "applicable, use a value of \n"
          "\'99991231115959.999999-720\' as defined by DSP0004 to "
          "mean \"infinite future." )]
   datetime NextUpdate;

      [Description ( 
          "The full content of the CRL in binary form.Only the "
          "first element of the array property shall be populated." ), 
       OctetString]
   string EncodedCRL[];

      [Description ( 
          "An array of serial numbers of X.509 certificates that "
          "are part of CRL." ), 
       OctetString]
   string SerialNumbers[];


};
