// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SecurityService 
// ==================================================================
   [Abstract, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( "A service providing security functionality." )]
class CIM_SecurityService : CIM_Service {


};
