// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_OtherPersonInformation 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::User::Org" ), 
    Description ( 
       "The OtherPersonInformation class is used to provide additional "
       "information about an associated Person instance. This class is "
       "defined so as to incorporate commonly-used LDAP attributes to "
       "permit implementations to easily derive this information from "
       "LDAP-accessible directories." )]
class CIM_OtherPersonInformation : CIM_ManagedElement {

      [Key, Description ( 
          "CreationClassName indicates the name of the class or the "
          "subclass used in the creation of an instance. When used "
          "with the other key properties of this class, this "
          "property allows all instances of this class and its "
          "subclasses to be uniquely identified." ), 
       MaxLen ( 256 )]
   string CreationClassName;

      [Key, Description ( 
          "The Name property defines the label by which the object "
          "is known. In the case of an LDAP-derived instance, the "
          "Name property value may be set to the distinguished name "
          "of the LDAP-accessed object instance." ), 
       MaxLen ( 1024 )]
   string Name;

      [Description ( 
          "In the case of an LDAP-derived instance, the ObjectClass "
          "property value(s) may be set to the objectClass "
          "attribute values." )]
   string ObjectClass[];

      [Description ( 
          "The Audio property may be used to store an audio clip of "
          "the person." ), 
       OctetString]
   string Audio[];

      [Description ( 
          "This property describes the kind of business performed "
          "by an organization." ), 
       MaxLen ( 128 )]
   string BusinessCategory[];

      [Description ( 
          "The CarLicense property is used to record the values of "
          "the vehicle license or registration plate associated "
          "with an individual." ), 
       MaxLen ( 128 )]
   string CarLicense[];

      [Description ( 
          "A CommonName is a (possibly ambiguous) name by which the "
          "role is commonly known in some limited scope (such as an "
          "organization) and conforms to the naming conventions of "
          "the country or culture with which it is associated." )]
   string CommonName[];

      [Description ( 
          "The CountryName property specifies a country as defined "
          "in ISO 3166." )]
   string CountryName[];

      [Description ( 
          "Based on inetOrgPerson, the DepartmentNumber is a code "
          "for department to which a person belongs. This can be "
          "strictly numeric (e.g., 1234) or alphanumeric (e.g., "
          "ABC/123)." )]
   string DepartmentNumber[];

      [Description ( 
          "The Descriptions property values may contain "
          "human-readable descriptions of the object. In the case "
          "of an LDAP-derived instance, the description attribute "
          "may have multiple values that, therefore, cannot be "
          "placed in the inherited Description property." ), 
       MaxLen ( 1024 )]
   string Descriptions[];

      [Description ( 
          "This property is used for the organization\'s telegram service."
           ), 
       MaxLen ( 128 )]
   string DestinationIndicator[];

      [Description ( 
          "Based on inetOrgPerson, the DisplayName property values "
          "are used when displaying an entry." )]
   string DisplayName[];

      [Description ( 
          "Based on inetOrgPerson, the EmployeeNumber property "
          "specifies a numeric or an alphanumeric identifier "
          "assigned to a person." )]
   string EmployeeNumber;

      [Description ( 
          "Based on inetOrgPerson, the EmployeeType property is "
          "used to identify the employer to employee relationship. "
          "Typical values used may include \'Contractor\', "
          "\'Employee\', \'Intern\', \'Temp\', \'External\', and "
          "\'Unknown\' but any value may be used." )]
   string EmployeeType[];

      [Description ( "The person\'s facsimile telephone number." )]
   string FacsimileTelephoneNumber[];

      [Description ( 
          "Based on liPerson, the GenerationQualifier property "
          "specifies a name qualifier that represents the person\'s "
          "generation (e.g., JR., III, etc.)." )]
   string GenerationQualifier[];

      [Description ( 
          "The GivenName property is used for the part of a "
          "person\'s name that is not their surname nor their "
          "middle name." )]
   string GivenName[];

      [Description ( 
          "Based on liPerson, the HomeFax property specifies the "
          "person\'s facsimile telephone number at home." )]
   string HomeFax[];

      [Description ( 
          "Based on RFC1274, the HomePhone property specifies a "
          "home telephone number for the person, e.g. + 44 582 "
          "10101)." ), 
       MaxLen ( 32 )]
   string HomePhone[];

      [Description ( 
          "The HomePostalAddress property values specify the home "
          "address information required for the physical delivery "
          "of postal messages by the postal authority." )]
   string HomePostalAddress[];

      [Description ( 
          "Based on inetOrgPerson, the Initials property specifies "
          "the first letters of the person\'s name, typically the "
          "property values will exclude the first letter of the "
          "surname." )]
   string Initials[];

      [Description ( "The person\'s International ISDN number." ), 
       MaxLen ( 16 )]
   string InternationaliSDNNumber[];

      [Description ( 
          "From inetOrgPerson, the JPEG Photo property values may "
          "be used for one or more images of a person using the "
          "JPEG File Interchange Format." )]
   string JPEGPhoto[];

      [Description ( 
          "Uniform Resource Identifier with optional label as "
          "defined in RFC2079." )]
   string LabeledURI[];

      [Description ( 
          "This property contains the name of a locality, such as a "
          "city, county or other geographic region." )]
   string LocalityName[];

      [Description ( 
          "Based on RFC1274, the mail box addresses for the person "
          "as defined in RFC822." )]
   string Mail[];

      [Description ( 
          "The person\'s manager within the organization. In the "
          "case of an LDAP-derived instance, the Manager property "
          "value may contain the distinguishedName of the Manager." )]
   string Manager[];

      [Description ( 
          "Based on liPerson, the middle name of the person." )]
   string MiddleName[];

      [Description ( 
          "Based on RFC1274, the Mobile phone property specifies a "
          "mobile telephone number for the person, e.g. + 44 582 "
          "10101)." ), 
       MaxLen ( 32 )]
   string Mobile[];

      [Required, Description ( 
          "The name of the person\'s organization." )]
   string OrganizationName[];

      [Description ( 
          "Based on RFC1274, the OrganizationalStatus property "
          "specifies a category by which a person is often referred "
          "to within an organization. Examples of usage in academia "
          "might include undergraduate student, researcher, "
          "lecturer, etc." )]
   string OrganizationalStatus[];

      [Description ( 
          "Based on RFC1274, this property may be used for "
          "electronic mail box addresses other than RFC822 and "
          "X.400." )]
   string OtherMailbox[];

      [Description ( 
          "The name of an organizational unit related to the person." )]
   string OU[];

      [Description ( 
          "Based on RFC1274, the Pager property specifies a pager "
          "telephone number for the person, e.g. + 44 582 10101)." ), 
       MaxLen ( 32 )]
   string Pager[];

      [Description ( 
          "Based on liPerson, the PersonalTitle property may be "
          "used to specify the person\'s personal title such as "
          "Mr., Ms., Dr., Prof. etc." )]
   string PersonalTitle[];

      [Description ( 
          "Based on RFC1274, the Photo property may be used to "
          "specify a photograph for the person encoded in G3 fax as "
          "explained in recommendation T.4, with an ASN.1 wrapper "
          "to make it compatible with an X.400 BodyPart as defined "
          "in X.420." ), 
       OctetString]
   string Photo[];

      [Description ( 
          "The PhysicalDeliveryOfficeName property specifies the "
          "name of the city, village, etc. where a physical "
          "delivery office is situated." ), 
       MaxLen ( 128 )]
   string PhysicalDeliveryOfficeName[];

      [Description ( 
          "The PostalAddress property values specify the address "
          "information required for the physical delivery of postal "
          "messages by the postal authority to the person." )]
   string PostalAddress[];

      [Description ( 
          "The PostalCode property specifies the postal code of the "
          "organization. If this value is present, it will be part "
          "of the object\'s postal address." ), 
       MaxLen ( 40 )]
   string PostalCode[];

      [Description ( 
          "The PostOfficeBox property specifies the PO box by which "
          "the person will receive physical postal delivery. If "
          "present, the property value is part of the object\'s "
          "postal address." ), 
       MaxLen ( 40 )]
   string PostOfficeBox[];

      [Description ( 
          "The PreferredDeliveryMethod property specifies the "
          "preferred method to be used for contacting the person." )]
   string PreferredDeliveryMethod;

      [Description ( 
          "Based on inetOrgPerson, the person\'s preferred written "
          "or spoken language." )]
   string PreferredLanguage;

      [Description ( 
          "This property specifies a postal address suitable for "
          "receipt of telegrams or expedited documents, where it is "
          "necessary to have the recipient accept delivery." )]
   string RegisteredAddress[];

      [Description ( 
          "Based on RFC1274, the RoomNumber property specifies the "
          "room number for the person." )]
   string RoomNumber[];

      [Description ( 
          "Based on RFC1274, the Secretary property may be used to "
          "specify a secretary for the person. In the case of an "
          "LDAP-derived object instance, the value may be a "
          "distinguishedName." )]
   string Secretary[];

      [Description ( 
          "In the case of an LDAP-derived instance, the SeeAlso "
          "property specifies distinguished name of other Directory "
          "objects which may be other aspects (in some sense) of "
          "the same real world object." )]
   string SeeAlso[];

      [Description ( 
          "The State or Province name property specifies a state or province."
           )]
   string StateOrProvince[];

      [Description ( 
          "The Street address property specifies a site for the "
          "local distribution and physical delivery in a postal "
          "address, i.e. the street name, place, avenue, and the "
          "number." ), 
       MaxLen ( 128 )]
   string Street[];

      [Description ( 
          "The Surname property specifies the linguistic construct "
          "that normally is inherited by an individual from the "
          "individual\'s parent or assumed by marriage, and by "
          "which the individual is commonly known." )]
   string Surname[];

      [Description ( 
          "The TelephoneNumber property specifies a telephone "
          "number of the organization, e.g. + 44 582 10101)." ), 
       MaxLen ( 32 )]
   string TelephoneNumber[];

      [Description ( 
          "The TeletexTerminalIdentifier property specifies the "
          "Teletex terminal identifier (and, optionally, "
          "parameters) for a teletex terminal associated with the "
          "organization." )]
   string TeletexTerminalIdentifier[];

      [Description ( 
          "The TelexNumber property specifies the telex number, "
          "country code, and answerback code of a telex terminal "
          "for the organization." )]
   string TelexNumber[];

      [Description ( 
          "A small image of the person\'s organization logo." ), 
       OctetString]
   string ThumbnailLogo[];

      [Description ( "A small image of the person." ), 
       OctetString]
   string ThumbnailPhoto[];

      [Description ( 
          "The Title property may be used to specify the person\'s "
          "designated position or function of the object within an "
          "organization, e.g., Manager, Vice-President, etc." )]
   string Title[];

      [Description ( 
          "Based on RFC1274, the UserID property may be used to "
          "specify a computer system login name." )]
   string UserID[];

      [Description ( 
          "A unique identifier that may be assigned in an "
          "environment to differentiate between uses of a given "
          "named person instance." )]
   string UniqueIdentifier[];

      [Description ( 
          "Based on inetOrgPerson and for directory compatibility, "
          "the UserCertificate property may be used to specify a "
          "public key certificate for the person." ), 
       OctetString]
   string UserCertificate[];

      [Description ( 
          "In the case of an LDAP-derived instance, the "
          "UserPassword property may contain an encrypted password "
          "used to access the person\'s resources in a directory." ), 
       OctetString]
   string UserPassword[];

      [Description ( 
          "Based on inetOrgPerson and for directory compatibility, "
          "the UserPKCS12 property value may be used to provide a "
          "format for exchange of personal identity information. "
          "The property values are PFX PDUs stored as Octetstrings." ), 
       OctetString]
   string UserPKCS12[];

      [Description ( 
          "Based on inetOrgPerson, the User S/MIME Certificate "
          "property may be used to specify the person\'s an S/MIME "
          "(RFC1847) signed message with a zero-length body. It "
          "contains the entire certificate chain and the signed "
          "attribute that describes their algorithm capabilities. "
          "If available, this property is preferred over the "
          "UserCertificate property for S/MIME applications." ), 
       OctetString]
   string UserSMIMECertificate[];

      [Description ( "An X.121 address for the organization." ), 
       MaxLen ( 15 )]
   string X121Address[];

      [Description ( 
          "An X.500 specified unique identifier that may be "
          "assigned in an environment to differentiate between uses "
          "of a given named person object instance." ), 
       OctetString]
   string X500UniqueIdentifier[];


};
