// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SecurityServiceUsesAccount 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::Account" ), 
    Description ( 
       "This relationship associates SecurityService instances to the "
       "Accounts they use in the course of their work." )]
class CIM_SecurityServiceUsesAccount : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "Account used by the SecurityService." )]
   CIM_Account REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Service using the Account." )]
   CIM_SecurityService REF Dependent;


};
