// Copyright (c) 2005 - 2007, DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_ServiceAffectsElement" }, 
    Version ( "2.16.0" ), 
    UMLPackagePath ( "CIM::User::PublicKey" ), 
    Description ( 
       "This relationship associates a CertificateAuthority with the "
       "certificates it signs." )]
class CIM_CASignsPublicKeyCertificate : CIM_ManagedCredential {

      [Deprecated { "CIM_ServiceAffectsElement.AffectingElement" }, 
       Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The CA which signed the certificate." )]
   CIM_CertificateAuthority REF Antecedent;

      [Deprecated { "CIM_ServiceAffectsElement.AffectedElement" }, 
       Override ( "Dependent" ), 
       Weak, Description ( "The certificate issued by the CA." )]
   CIM_PublicKeyCertificate REF Dependent;

      [Deprecated { "No value" }, 
       Description ( "The Serial Number." )]
   string SerialNumber;

      [Deprecated { "No value" }, 
       Description ( "The Signature." ), 
       OctetString]
   uint8 Signature[];

      [Deprecated { "CIM_Credential.Expires" }, 
       Description ( "The time it expires." )]
   datetime Expires;

      [Deprecated { "No value" }, 
       Description ( 
          "The Authority\'s revocation list distribution points." )]
   string CRLDistributionPoint[];


};
