// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_CAHasPublicCertificate 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::PublicKey" ), 
    Description ( 
       "A CertificateAuthority may have certificates issued by other "
       "CAs or self-signed. This association is essentially an "
       "optimization of the CA having an external identity established "
       "by itself or another Authority. This maps closely to "
       "LDAP-based certificate authority implementations." )]
class CIM_CAHasPublicCertificate : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Certificate used by the CA." )]
   CIM_PublicKeyCertificate REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The CA that uses a Certificate." )]
   CIM_CertificateAuthority REF Dependent;


};
