// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ElementAsUser 
// ==================================================================
   [Association, Deprecated { "CIM_AssignedIdentity" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::UsersAccess" ), 
    Description ( 
       "CIM_ElementAsUser is an association used to establish the "
       "\'ownership\' of UsersAccess object instances. That is, the "
       "ManagedElement may have UsersAccess to systems and, therefore, "
       "be \'users\' on those systems. UsersAccess instances must have "
       "an \'owning\' ManagedElement. Typically, the ManagedElements "
       "will be limited to Collection, Person, Service and "
       "ServiceAccessPoint. Other non-human ManagedElements that might "
       "be thought of as having UsersAccess (e.g., a device or system) "
       "have services that have the UsersAccess. \n"
       "\n"
       "Since the UsersAccess class is deprecated in lieu of "
       "CIM_Identity, this association is also deprecated and replaced "
       "by one of similar semantics, AssignedIdentity. It should be "
       "noted that the new class is NOT defined as a Dependency "
       "relationship, since it was felt that the association was not "
       "truly a dependency of the element on its access." )]
class CIM_ElementAsUser : CIM_Dependency {

      [Deprecated { "CIM_AssignedIdentity.ManagedElement" }, 
       Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The ManagedElement that has UsersAccess." )]
   CIM_ManagedElement REF Antecedent;

      [Deprecated { "CIM_AssignedIdentity.IdentityInfo" }, 
       Override ( "Dependent" ), 
       Description ( "The \'owned\' UsersAccess." )]
   CIM_UsersAccess REF Dependent;


};
