// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SystemAdministratorGroup 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::Group" ), 
    Description ( 
       "CIM_SystemAdministratorGroup is an association used to "
       "identify a Group that has system administrator "
       "responsibilities for a CIM_System." )]
class CIM_SystemAdministratorGroup : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The administered system." )]
   CIM_System REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Group of administrators." )]
   CIM_Group REF Dependent;


};
