// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ServiceUsesSecurityService 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "This relationship associates a Service with the Security "
       "Services that it uses." )]
class CIM_ServiceUsesSecurityService : CIM_ServiceServiceDependency {

      [Override ( "Antecedent" )]
   CIM_SecurityService REF Antecedent;

      [Override ( "Dependent" )]
   CIM_Service REF Dependent;


};
