// Copyright (c) 2011 DMTF.  All rights reserved.
   [Version ( "2.29.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "CIM_CertificateManagementCapabilities describes the "
       "capabilities of the associated "
       "CIM_CertificateManagementService instance(s)." )]
class CIM_CertificateManagementCapabilities : CIM_CredentialManagementCapabilities {

      [Override ( "SupportedMethods" ), 
       Description ( 
          "Each enumeration corresponds to support for the "
          "like-named method of the associated "
          "CIM_CertificateManagementService instance(s) for the "
          "exception of \"DeleteCredentialInstance\" that refers to "
          "the capability of executing delete operation on the "
          "instances of the CIM_Credential subclasses." ), 
       ValueMap { "2", "3", "4", "101", "102", "103", "104", "105", 
          "106", "107", "..", "0x8000.." }, 
       Values { "ImportPublicPrivateKeyPair", "CreateKeystore", 
          "DeleteCredentialInstance", 
          "CreatCertificateSigningRequest", 
          "CreateSelfSignedCertificate", 
          "ImportEncodedCertificates", "ImportCertificates", 
          "ExportEncodedCertificate", "ApplyCRL", "ApplyDecodedCRL", 
          "DMTF Reserved", "Vendor Specific" }]
   uint16 SupportedMethods[];

      [Description ( 
          "If the AsymmetricKeyGeneration is TRUE, this property "
          "specifies the possible key algorithms that are supported "
          "by the methods that generate public/private key pairs in "
          "the associated CIM_CertificateManagementService "
          "instance(s)." ), 
       ValueMap { "2", "3", "4", "..", "32768..65535" }, 
       Values { "RSA", "DSA", "ECDSA", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 KeyAlgorithmSupported[];

      [Description ( 
          "The InputFormatsSupported represents the supported input "
          "formats for the certificate(s) and Certificate "
          "Revocation List by the methods in the associated "
          "CIM_CertificateManagementService instance(s)." ), 
       ValueMap { "2", "3", "4", "5", "..", "32768..65535" }, 
       Values { "DER", "PEM", "PKCS7", "PKCS12", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 InputFormatsSupported[];

      [Description ( 
          "The OutputFormatsSupported represents the supported "
          "output formats for the certificate(s) and Certificate "
          "Revocation List by the methods in the associated "
          "CIM_CertificateManagementService instance(s)." ), 
       ValueMap { "2", "3", "4", "5", "..", "32768..65535" }, 
       Values { "DER", "PEM", "PKCS7", "PKCS12", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 OutputFormatsSupported[];

      [Description ( 
          "AsymmetricKeyGeneration property represents the "
          "capability of the instrumentation to generate asymmetric "
          "public/private key pair." )]
   boolean AsymmetricKeyGeneration;

      [Description ( 
          "The SupportedSignatureAlgorithms represents the "
          "supported signature algorithms for the certificate(s) "
          "and Certificate Revocation List by the methods in the "
          "associated CIM_CertificateManagementService instance(s). "
          "This property covers the algorithms specified in the "
          "RFC3279." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "11", "12", "13", "14", "15", "16", "17", "18", "19", 
          "1920..32767", "32768..65535" }, 
       Values { "Other", "SHA1withDSA", "SHA1withECDSA", 
          "SHA224withECDSA", "SHA256withECDSA", "SHA384withECDSA", 
          "SHA512withECDSA", "GOST3411withGOST3410", 
          "GOST3411withECGOST3410", "MD2withRSA", "MD5withRSA", 
          "SHA1withRSA", "SHA224withRSA", "SHA256withRSA", 
          "SHA384withRSA", "SHA512withRSA", "RIPEMD160withRSA", 
          "RIPEMD128withRSA", "RIPEMD256withRSA", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 SupportedSignatureAlgorithms[];


};
