// Copyright (c) 2007, DMTF.  All rights reserved.
   [Deprecated { "CIM_SharedCredential" }, 
    Version ( "2.16.0" ), 
    UMLPackagePath ( "CIM::User::SharedSecret" ), 
    Description ( 
       "CIM_SharedSecret is a secret (such as a password or the "
       "response to a challenge question) that is shared between a "
       "principal and a particular SharedSecret security service. "
       "Secrets may be in the form of a password used for initial "
       "authentication, or as with a session key, used as part of a "
       "message to verify the originator of the message. It is "
       "important to note that SharedSecret is not just a password, "
       "but rather is the password used with a particular security "
       "service." )]
class CIM_SharedSecret : CIM_Credential {

      [Deprecated { "CIM_SharedCredential.InstanceID" }, 
       Key, Description ( "The scoping System\'s CCN." ), 
       MaxLen ( 256 ), 
       Propagated ( 
          "CIM_SharedSecretService.SystemCreationClassName" )]
   string SystemCreationClassName;

      [Deprecated { "CIM_SharedCredential.InstanceID" }, 
       Key, Description ( "The scoping System\'s Name." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_SharedSecretService.SystemName" )]
   string SystemName;

      [Deprecated { "CIM_SharedCredential.InstanceID" }, 
       Key, Description ( "The scoping Service\'s CCN." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_SharedSecretService.CreationClassName" )]
   string ServiceCreationClassName;

      [Deprecated { "CIM_SharedCredential.InstanceID" }, 
       Key, Description ( "The scoping Service\'s Name." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_SharedSecretService.Name" )]
   string ServiceName;

      [Deprecated { "CIM_SharedCredential.RemoteID" }, 
       Key, Description ( 
          "RemoteID is the name by which the principal is known at "
          "the remote secret key authentication service." ), 
       MaxLen ( 256 )]
   string RemoteID;

      [Deprecated { "CIM_SharedCredential.Secret" }, 
       Description ( "The secret known by the principal." ), 
       OctetString]
   string Secret;

      [Deprecated { "CIM_SharedCredential.Algorithm" }, 
       Description ( 
          "The transformation algorithm, if any, used to protect "
          "passwords before use in the protocol. For instance, "
          "Kerberos doesn\'t store passwords as the shared secret, "
          "but rather, a hash of the password." )]
   string Algorithm;

      [Deprecated { "CIM_SharedCredential.Protocol" }, 
       Description ( 
          "The protocol with which the SharedSecret is used." )]
   string Protocol;


};
