// Copyright (c) 2007 DMTF.  All rights reserved.
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Metrics::UnitOfWork" ), 
    Description ( 
       "This association defines the sub-UnitsOfWork (the sub- "
       "transactions) for a particular UnitOfWorkDefinition. For "
       "example, an \'AddOrder\' UnitOfWork could have sub-Units of "
       "\'ValidateCustomer\', \'ValidatePartNumber\', "
       "\'UpdateDatabase\', etc. This is a Dependency relationship "
       "since the sub-UnitsOf Work are put in context relative to the "
       "parent Unit. It is not an aggregation relationship - since "
       "(using another example) a \'DatabaseWrite\' transaction is "
       "likely to be dependent upon a \'DiskWrite\', but the two "
       "transactions are separate concepts and one is not \'contained\' "
       "by the other." )]
class CIM_SubUoWDef : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The parent UnitOfWorkDefinition." )]
   CIM_UnitOfWorkDefinition REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The sub-UnitOfWorkDefinition." )]
   CIM_UnitOfWorkDefinition REF Dependent;


};
