// Copyright (c) 2007 DMTF.  All rights reserved.
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Metrics::UnitOfWork" ), 
    Description ( 
       "An association that describes the Metrics related to a "
       "UnitOfWorkDefinition. This is a Dependency relationship since "
       "the MetricDefinition relies on the UnitOfWorkDefinition for "
       "context. At least one context must be defined for a "
       "MetricDefinition, hence the Min (1) qualifier is placed on the "
       "UnitOfWorkDefinition reference." )]
class CIM_UoWMetricDefinition : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Description ( 
          "The UnitOfWorkDefinition where the Metric applies." )]
   CIM_UnitOfWorkDefinition REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The MetricDefinition for a particular UnitOfWork." )]
   CIM_MetricDefinition REF Dependent;


};
