TOP = ..
include $(TOP)/config.mak

LIBRARY = ut

SOURCES = \
    ut.cpp \
    strutil.cpp \
    utility.cpp

INCLUDES = $(TOP) $(TOP)/common

DEFINES = BUILDING_MICXX MI_CONST= DETECT_FORBIDDEN_FUNCTIONS


LIBRARIES =

include $(TOP)/mak/rules.mak
