// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_StorageClientSettingData 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::StorageHardwareID" ), 
    Description ( 
       "This class models host environment factors that influence the "
       "behavior of Storage Systems. For example, a disk array has "
       "different SCSI responses for clients (initiators) configured "
       "as AIX verses HPUX. Instances of this setting class can be "
       "associated via ElementSettingData to a storage system\'s "
       "LogicalPort, ProtocolController, or Volume instances when "
       "these elements have host awareness. These associations are "
       "created by the management instrumentation provider to reflect "
       "the current configuration. A client deletes/creates these "
       "associations to request changes in element host-awareness. "
       "This settings class can also be associated with "
       "StorageHardwareID instances when that HW ID is configured with "
       "host information. An instance of this setting may include "
       "several ClientType values if the storage system treats them "
       "identically. The storage system exposes all supported setting "
       "instances to a WBEM Enumerate request; the client uses the "
       "returned settings to determine which types are available." )]
class CIM_StorageClientSettingData : CIM_SettingData {

      [Description ( 
          "This enumeration defines operating system, version, "
          "driver, and other host environment factors that "
          "influence the behavior exposed by storage systems. "
          "Values in this array are combined with data from the "
          "OtherClientTypeDescriptions property to provide complete "
          "information on the host environment." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11", "12", "13", "14", "15", "16", "17", "18", 
          "19..32767", "32768..65535" }, 
       Values { "Unknown", "Other", "Standard", "Solaris", "HPUX", 
          "OpenVMS", "Tru64", "Netware", "Sequent", "AIX", "DGUX", 
          "Dynix", "Irix", "Cisco iSCSI Storage Router", "Linux", 
          "Microsoft Windows", "OS400", "TRESPASS", "HI-UX", 
          "DMTF Reserved", "Vendor Specific" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_StorageClientSettingData.OtherClientTypeDescriptions" }]
   uint16 ClientTypes[];

      [Description ( 
          "When the the corresponding array entry in ClientTypes[] "
          "is \"Other\", this entry provides a string describing "
          "the manufacturer and OS/Environment. When the "
          "corresponding ClientTypes[] entry is not \"Other\", this "
          "entry allows variations or qualifications of ClientTypes "
          "- for example, different versions of Solaris." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_StorageClientSettingData.ClientTypes" }]
   string OtherClientTypeDescriptions[];


};
