// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NotaryVerifiesBiometric 
// ==================================================================
   [Association, Deprecated { "CIM_ManagedCredential" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::UsersAccess" ), 
    Description ( 
       "This relationship associates a Notary service with the Users "
       "Access whose biometric information is verified. It is "
       "deprecated since one of its references (UsersAccess) is "
       "deprecated, and because specific biometric credentials are "
       "defined in a new subclass of CIM_Credential (specifically, "
       "BiometricCredential). Given the latter, the relationship of a "
       "Credential to its management service (ManagedCredential) can "
       "be used directly." )]
class CIM_NotaryVerifiesBiometric : CIM_Dependency {

      [Deprecated { "CIM_ManagedCredential.Antecedent" }, 
       Override ( "Antecedent" ), 
       Description ( 
          "The Notary service that verifies biometric information." )]
   CIM_Notary REF Antecedent;

      [Deprecated { "CIM_ManagedCredential.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "The UsersAccess that represents a person using biometric "
          "information for authentication." )]
   CIM_UsersAccess REF Dependent;


};
