// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RequireCredentialsFrom 
// ==================================================================
   [Association, Deprecated { "CIM_AuthenticationCondition", 
       "CIM_AuthenticationRule" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::AuthenticationReqmt" ), 
    Description ( 
       "CIM_RequireCredentialsFrom is an association used to require "
       "that credentials are issued by particular CredentialManagement "
       "Services in order to authenticate a user. This association is "
       "deprecated in lieu of explicit declaration of the "
       "AuthenticationConditions in an AuthenticationRule. Instances "
       "of AuthenticationCondition describe the specific combinations "
       "of credentials (or alternative credentials) that are required "
       "to authenticate an Identity. This allows a more explicit and "
       "flexible description of authentication requirements." )]
class CIM_RequireCredentialsFrom : CIM_Dependency {

      [Deprecated { "CIM_AuthenticationCondition" }, 
       Override ( "Antecedent" ), 
       Description ( 
          "CredentialManagementService from which credentials are "
          "accepted for the associated AuthenticationRequirement." )]
   CIM_CredentialManagementService REF Antecedent;

      [Deprecated { "CIM_AuthenticationRule" }, 
       Override ( "Dependent" ), 
       Description ( 
          "AuthenticationRequirement that limits acceptable credentials."
           )]
   CIM_AuthenticationRequirement REF Dependent;


};
