// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AccountIdentity 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::Account" ), 
    Description ( 
       "CIM_AccountIdentity relates a system Account with the Identity "
       "that is established. Since Account also carries Identity "
       "semantics, the LogicalIdentity association is defined as the "
       "superclass of this association." )]
class CIM_AccountIdentity : CIM_LogicalIdentity {

      [Override ( "SystemElement" ), 
       Description ( "The Account that establishes Identity." )]
   CIM_Account REF SystemElement;

      [Override ( "SameElement" ), 
       Description ( "The Identity established by the Account." )]
   CIM_Identity REF SameElement;


};
