// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AuthenticateForUse 
// ==================================================================
   [Association, Deprecated { "No value" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::AuthenticationReqmt" ), 
    Description ( 
       "CIM_AuthenticateForUse is an association used to provide an "
       "AuthenticationService with the AuthenticationRequirement it "
       "needs to do its job. This association is unnecessary and "
       "therefore deprecated, since it is implied that an Identity "
       "MUST be authenticated (its CurrentlyAuthenticatedBoolean set "
       "to TRUE) in order to have any Privileges." )]
class CIM_AuthenticateForUse : CIM_Dependency {

      [Deprecated { "No value" }, 
       Override ( "Antecedent" ), 
       Description ( "AuthenticationRequirementfor use." )]
   CIM_AuthenticationRequirement REF Antecedent;

      [Deprecated { "No value" }, 
       Override ( "Dependent" ), 
       Description ( 
          "AuthenticationServicethat uses the requirements." )]
   CIM_AuthenticationService REF Dependent;


};
