// Copyright (c) 2005 - 2007, DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="WIPCR00383.004" type="add">New Credential class 
// hierarchy</change>
// ==================================================================
//  CIM_NamedSharedIKESecret 
// ==================================================================
   [Deprecated { "CIM_NamedCredential" }, 
    Version ( "2.16.0" ), 
    UMLPackagePath ( "CIM::User::SharedSecret" ), 
    Description ( 
       "CIM_NamedSharedIKESecret indirectly represents a shared secret "
       "credential. The local identity, IKEIdentity, and the remote "
       "peer identity share the secret that is named by the "
       "SharedSecretName. The SharedSecretName is used by the "
       "SharedSecretService to reference the secret." )]
class CIM_NamedSharedIKESecret : CIM_Credential {

      [Deprecated { "CIM_NamedCredential.InstanceID" }, 
       Key, Description ( "The scoping System\'s CCN." ), 
       MaxLen ( 256 ), 
       Propagated ( 
          "CIM_SharedSecretService.SystemCreationClassName" )]
   string SystemCreationClassName;

      [Deprecated { "CIM_NamedCredential.InstanceID" }, 
       Key, Description ( "The scoping System\'s Name." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_SharedSecretService.SystemName" )]
   string SystemName;

      [Deprecated { "CIM_NamedCredential.InstanceID" }, 
       Key, Description ( "The scoping Service\'s CCN." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_SharedSecretService.CreationClassName" )]
   string ServiceCreationClassName;

      [Deprecated { "CIM_NamedCredential.InstanceID" }, 
       Key, Description ( "The scoping Service\'s Name." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_SharedSecretService.Name" )]
   string ServiceName;

      [Deprecated { "CIM_NamedCredential.LocalIdentity" }, 
       Key, Description ( 
          "The local Identity with whom the direct trust relationship exists."
           ), 
       MaxLen ( 256 ), 
       ModelCorrespondence { 
          "CIM_NamedSharedIKESecret.LocalIdentityType" }]
   string LocalIdentity;

      [Deprecated { "CIM_NamedCredential.LocalIdentityType" }, 
       Key, Description ( 
          "LocalIdentityType is used to describe the type of the "
          "LocalIdentity." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "11" }, 
       Values { "IPV4_ADDR", "FQDN", "USER_FQDN", 
          "IPV4_ADDR_SUBNET", "IPV6_ADDR", "IPV6_ADDR_SUBNET", 
          "IPV4_ADDR_RANGE", "IPV6_ADDR_RANGE", "DER_ASN1_DN", 
          "DER_ASN1_GN", "KEY_ID" }, 
       ModelCorrespondence { "CIM_NamedSharedIKESecret.LocalIdentity" }]
   uint16 LocalIdentityType;

      [Deprecated { "CIM_NamedCredential.PeerIdentity" }, 
       Key, Description ( 
          "The peer identity with whom the direct trust relationship exists."
           ), 
       MaxLen ( 256 ), 
       ModelCorrespondence { 
          "CIM_NamedSharedIKESecret.PeerIdentityType" }]
   string PeerIdentity;

      [Deprecated { "CIM_NamedCredential.PeerIdentityType" }, 
       Key, Description ( 
          "PeerIdentityType is used to describe the type of the PeerIdentity."
           ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "11" }, 
       Values { "IPV4_ADDR", "FQDN", "USER_FQDN", 
          "IPV4_ADDR_SUBNET", "IPV6_ADDR", "IPV6_ADDR_SUBNET", 
          "IPV4_ADDR_RANGE", "IPV6_ADDR_RANGE", "DER_ASN1_DN", 
          "DER_ASN1_GN", "KEY_ID" }, 
       ModelCorrespondence { "CIM_NamedSharedIKESecret.PeerIdentity" }]
   uint16 PeerIdentityType;

      [Deprecated { "CIM_NamedCredential.SharedSecretName" }, 
       Description ( 
          "SharedSecretName is an indirect reference to a shared "
          "secret. The SecretService does not expose the actual "
          "secret but rather provides access to the secret via a "
          "name." )]
   string SharedSecretName;


};
