// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_VerificationService 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "CIM_VerificationService is the authentication service that "
       "verifies a credential for use and may also verify the "
       "appropriateness of a particular credential in conjunction with "
       "a particular target resource." )]
class CIM_VerificationService : CIM_AuthenticationService {


};
