// Copyright (c) 2008 DMTF.  All rights reserved.
   [Association, Version ( "2.20.0" ), 
    UMLPackagePath ( "CIM::User::Role" ), 
    Description ( 
       "The Role object class is used to represent a position or set "
       "of responsibilities within an organization, organizational "
       "unit or other scope. When explicitly restricting the target "
       "elements that may be accessed from this Role, this association "
       "MUST be used." )]
class CIM_RoleLimitedToTarget {

      [Key, Description ( 
          "The Role whose target set is explicitly defined." )]
   CIM_Role REF DefiningRole;

      [Key, Description ( 
          "Reference to the target set that can be accessed from the Role."
           )]
   CIM_ManagedElement REF TargetElement;


};
