// Copyright (c) 2011 DMTF.  All rights reserved.
   [Version ( "2.29.0" ), 
    UMLPackagePath ( "CIM::User::Credential" ), 
    Description ( 
       "CIM_Keystore class represents a keystore, collection of key "
       "based credentials such as certificates. Keystore can be used "
       "to store the certificates that are used for the client role of "
       "the validation of the served up certificates, or for the "
       "server role, serving up the certificates to the client for the "
       "validation. Certificates in the keystore can be "
       "revoked/invalidated by the means of application of Certificate "
       "Revocation List (CRL)." )]
class CIM_Keystore : CIM_CredentialStore {

      [Override ( "Usage" ), 
       Description ( 
          "Usage of the keystore.\n"
          "2 - Owned value means CIM_Keystore instance represents a "
          "collection of key based credentials that belong to "
          "parties local to the manager of the keystore. \n"
          "3 - Trusted value means CIM_Keystore instance represents "
          "a collection of public key based credentials that belong "
          "to parties trusted by the manager of the keystore.\n"
          "4 - Mixed value means CIM_Keystore instance represents a "
          "collection of both Trusted and Owned key based "
          "credentials." ), 
       ValueMap { "2", "3", "4", "..", "32768..65535" }, 
       Values { "Owned", "Trusted", "Mixed", "DMTF Reserved", 
          "Vendor Specified" }]
   uint16 Usage;


};
