// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MoreOrgUnitInfo 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::User::Org" ), 
    Description ( 
       "CIM_MoreOrgUnitInfo is an association used to extend the "
       "information in an CIM_OrgUnit class instance." )]
class CIM_MoreOrgUnitInfo : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The OrgUnit which has more information." )]
   CIM_OrgUnit REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( "Additional data concerning the OrgUnit." )]
   CIM_OtherOrgUnitInformation REF Dependent;


};
