// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AccountMapsToAccount 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::Account" ), 
    Description ( 
       "This relationship may be used to associate an Account used by "
       "an AuthenticationService to an Account used for Authorization. "
       "For instance, this mapping occurs naturally in the UNIX "
       "/etc/passwd file, where the AuthenticationService Account "
       "(\'root\') is mapped to the AuthorizationService Account "
       "(\'0\'). The two are separate accounts, as evidenced by the "
       "ability to have another AuthenticationService Account which "
       "ALSO maps to the AuthorizationService Account (\'0\') without "
       "ambiguity. This association may be used for other account "
       "mappings as well such as for coordinating single signon for "
       "multiple accounts for the same user." )]
class CIM_AccountMapsToAccount : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "An Account." )]
   CIM_Account REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "A related Account." )]
   CIM_Account REF Dependent;


};
