// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Core::Statistics" ), 
    Description ( 
       "A subclass of SystemSpecificCollection which collects together "
       "statistics for a system. This class forms an \'anchor point\' "
       "from which all the statistics kept for the system can be found "
       "(via the MemberOfCollection associations)." )]
class CIM_StatisticsCollection : CIM_SystemSpecificCollection {

      [Description ( 
          "This property provides the minimum sampling interval for "
          "the associated statistics so that client applications "
          "can determine the minimum interval that the "
          "StatisticsCollection should be sampled. If the "
          "statistics are sampled at different cycles, this "
          "property MUST be set to a zero time interval." )]
   datetime SampleInterval = "00000000000000.000000:000";

      [Description ( 
          "The time that the statistics collection was last "
          "sampled. Note that this property MAY be used to trigger "
          "an indication for \'push\' delivery of statistics "
          "samples." )]
   datetime TimeLastSampled;


};
