// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00711.001" type ="change">Update of
// descriptions based on Tech Edit review.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ConcreteIdentity
// ==================================================================
   [Association, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "CIM_ConcreteIdentity associates two elements that represent "
       "different aspects of the same underlying entity. It is defined "
       "as a concrete subclass of the abstract CIM_LogicalIdentity "
       "class, to be used in place of many specific subclasses of "
       "LogicalIdentity that add no semantics, that is, subclasses "
       "that do not clarify the type of identity, update "
       "cardinalities, or add or remove qualifiers. Note that when you "
       "define additional semantics for LogicalIdentity, this class "
       "should not be subclassed. Specific semantics continue to be "
       "defined as subclasses of the abstract CIM_LogicalIdentity. "
       "ConcreteIdentity is limited in its use as a concrete form of a "
       "general identity relationship. \n"
       "\n"
       "It was deemed more prudent to create this concrete subclass "
       "than to change LogicalIdentity from an abstract to a concrete "
       "class. LogicalIdentity already had multiple abstract "
       "subclasses in the CIM Schema, and wider industry usage and "
       "impact could not be anticipated." )]
class CIM_ConcreteIdentity : CIM_LogicalIdentity {

      [Override ( "SystemElement" ), 
       Description ( 
          "One aspect of the ManagedElement. The use of \'System\' "
          "in the name does not limit the scope of the association. "
          "This name is an artifact of the original definition of "
          "the association." )]
   CIM_ManagedElement REF SystemElement;

      [Override ( "SameElement" ), 
       Description ( "Another aspect of the ManagedElement." )]
   CIM_ManagedElement REF SameElement;


};
