// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_InstalledSoftwareIdentity 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Core::Software" ), 
    Description ( 
       "The InstalledSoftwareIdentity association identifies the "
       "System on which a SoftwareIdentity is installed. This class is "
       "a corollary to InstalledSoftwareElement, but deals with the "
       "asset aspects of software (as indicated by SoftwareIdentity), "
       "versus the deployment aspects (as indicated by "
       "SoftwareElement)." )]
class CIM_InstalledSoftwareIdentity {

      [Key, Description ( 
          "The system on which the software is installed." )]
   CIM_System REF System;

      [Key, Description ( "The SoftwareIdentity that is installed." )]
   CIM_SoftwareIdentity REF InstalledSoftware;


};
