// Copyright (c) 2009 DMTF.  All rights reserved.
   [Association, Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "ServiceAffectsElementWithQuota represents an extension of "
       "ServiceAffectsElement to include a quota imposed on the "
       "AffectedElement by the Service. The quota governs the amount "
       "of a resource controlled by the Service that can be allocated "
       "by the AffectedElement in one or more allocations." )]
class CIM_ServiceAffectsElementWithQuota : CIM_ServiceAffectsElement {

      [Description ( 
          "Quota is the maximum number of resource units that may "
          "be allocated to the AffectedElement." )]
   uint64 Quota;

      [Description ( 
          "Quota is the number of resource units currently "
          "allocated to the AffectedElement." )]
   uint64 QuotaUsed;

      [Description ( 
          "QuotaUnits specifies the type of unit used in the Quota "
          "and QuotaUsed properties. The value shall be formatted "
          "according to DSP0004 Appendix C1, where the base-unit is "
          "\"byte\"), and there are no occurrences of "
          "multiplied-base-unit and divided-base-unit." ), 
       IsPUnit]
   string QuotaUnits = "byte";


};
