// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DeviceStatistics 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Core::Statistics" ), 
    Description ( 
       "DeviceStatistics relates the DeviceStatisticalInformation "
       "class to the LogicalDevice to which it applies." )]
class CIM_DeviceStatistics : CIM_Statistics {

      [Override ( "Stats" ), 
       Weak, Description ( "The statistical object." )]
   CIM_DeviceStatisticalInformation REF Stats;

      [Override ( "Element" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The Device to which the statistics apply." )]
   CIM_LogicalDevice REF Element;


};
