// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01378.002" type ="deprecate">Deprecate
// class</change>
// <change cr="SysDevCR00728.000" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SettingContext
// ==================================================================
   [Association, Deprecated { "CIM_ConcreteComponent" }, 
    Aggregation, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "Note: The Configuration class is being deprecated in lieu of "
       "using a ConcreteComponent relationship to indicate a hierarchy "
       "of instances of Setting or SettingData. Therefore, the "
       "aggregation of Settings into Configurations is replaced by the "
       "ConcreteComponent relationship between instances of Settings "
       "and SettingData. \n"
       "Deprecated description: This relationship associates "
       "Configuration objects with Setting objects. For example, "
       "Settings of a NetworkAdapter could change based on the site or "
       "network to which its hosting ComputerSystem is attached. In "
       "this case, the ComputerSystem would have two different "
       "Configuration objects, corresponding to the differences in "
       "network configuration for the two network segments. "
       "Configuration A would aggregate a Setting object for the "
       "NetworkAdapter when operating on segment \"ANet\", whereas "
       "Configuration B would aggregate a different NetworkAdapter "
       "Setting object, specific to segment \"BNet\". Note that many "
       "Settings of the computer are independent of the network "
       "Configuration. For example, both Configurations A and B would "
       "aggregate the same Setting object for the MonitorResolution of "
       "the ComputerSystem." )]
class CIM_SettingContext {

      [Deprecated { "CIM_ConcreteComponent.GroupComponent" }, 
       Key, Aggregate, Description ( 
          "Note: The use of this element is deprecated. Deprecated "
          "description: The Configuration object that aggregates "
          "the Setting." )]
   CIM_Configuration REF Context;

      [Deprecated { "CIM_ConcreteComponent.PartComponent" }, 
       Key, Description ( 
          "Note: The use of this element is deprecated. Deprecated "
          "description: An aggregated Setting." )]
   CIM_Setting REF Setting;


};
