// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ProductFRU 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Core::ProductFRU" ), 
    Description ( 
       "CIM_ProductFRU is an association between Product and FRU that "
       "provides information regarding what Product components have "
       "been or are being replaced. The association is one to many, "
       "conveying that a Product can have many FRUs, and that a "
       "particular instance of a FRU is only applied to one (instance "
       "of a) Product." )]
class CIM_ProductFRU {

      [Key, Max ( 1 ), 
       Description ( "The Product to which the FRU is applied." )]
   CIM_Product REF Product;

      [Key, Description ( "The FRU." )]
   CIM_FRU REF FRU;


};
