// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01378.002" type ="deprecate">Deprecate
// class.</change>
// <change cr="SysDevCR00722.000" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ElementProfile
// ==================================================================
   [Association, Deprecated { "CIM_ElementSettingData", 
       "CIM_ElementSetting" }, 
    Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "Note: The Profile class is being deprecated in lieu of using a "
       "ConcreteComponent relationship to indicate a hierarchy of "
       "Setting or SettingData instances. This relationship allows the "
       "reuse of the element to Setting or SettingData associations "
       "instead of defining a peer association specifically for "
       "Profiles. \n"
       "Deprecated description: ElementProfile represents the "
       "association between ManagedElements and the Profiles "
       "(collection of settings) that are defined for them. This "
       "association indicates that the settings that are collected by "
       "the Profile apply to the associated ManagedElement." )]
class CIM_ElementProfile {

      [Deprecated { "CIM_ElementSettingData.ManagedElement", 
          "CIM_ElementSetting.Element" }, 
       Key, Description ( 
          "Note: The use of this element is deprecated. Deprecated "
          "description: The managed element." )]
   CIM_ManagedElement REF ManagedElement;

      [Deprecated { "CIM_ElementSettingData.SettingData", 
          "CIM_ElementSetting.Setting" }, 
       Key, Description ( 
          "Note: The use of this object is deprecated. Deprecated "
          "description: The Profile object that is associated with "
          "the element." )]
   CIM_Profile REF Profile;


};
