TOP = ..
include $(TOP)/config.mak

CXXSHLIBRARY = httpclientcxx

SOURCES = httpclientcxx.cpp

INCLUDES = $(TOP) $(TOP)/common

LIBRARIES = protocol http sock base io

DEFINES = BUILDING_HTTPCLIENT

include $(TOP)/mak/rules.mak
