TOP = ..
include $(TOP)/config.mak

CXXPROGRAM = omiconfigeditor

SOURCES = configeditor.cpp 

INCLUDES = $(TOP) $(TOP)/common

DEFINES = MI_CONST= HOOK_BUILD

LIBRARIES = $(BASELIBS) $(PALLIBS)

include $(TOP)/mak/rules.mak
