// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AllocatedResource 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::SystemResources" ), 
    Description ( 
       "An association between LogicalDevices and SystemResources, "
       "indicating that the Resource is assigned to the Device." )]
class CIM_AllocatedResource : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Resource." )]
   CIM_SystemResource REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The LogicalDevice to which the Resource is assigned." )]
   CIM_LogicalDevice REF Dependent;


};
