// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Version ( "2.31.0" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "AssociatedJobMethodResult represents an association between a "
       "ConcreteJob and the MethodResult expressing the parameters for "
       "the Job when the job was created by side-effect of the "
       "execution of an extrinsic method." )]
class CIM_AssociatedJobMethodResult {

      [Key, Max ( 1 ), 
       Description ( "The associated ConcreteJob." )]
   CIM_ConcreteJob REF Job;

      [Key, Max ( 1 ), 
       Description ( "The associated MethodResult." )]
   CIM_MethodResult REF JobParameters;


};
