// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PortResource 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::SystemResources" ), 
    Description ( 
       "Since the MemoryMappedIO class applies to memory AND port "
       "resources, there is the potential for key conflict. For "
       "example, both a memory resource and a port resource may be "
       "located at address 0. Since StartingAddress is the "
       "distinguishing key of MemoryMappedIO, two instances would be "
       "created with the same key. This is prevented by defining "
       "memory and port resource subclasses of MemoryMappedIO, and "
       "allowing the CreationClassName key property to distinguish "
       "between them and force uniqueness in their keys." )]
class CIM_PortResource : CIM_MemoryMappedIO {


};
