// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AllocatedDMA 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::SystemResources" ), 
    Description ( 
       "An association between a LogicalDevice and a DMA System "
       "Resource indicating that the DMA Channel is assigned to the "
       "Device." )]
class CIM_AllocatedDMA : CIM_AllocatedResource {

      [Override ( "Antecedent" ), 
       Description ( "The DMA Channel." )]
   CIM_DMA REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The LogicalDevice to which the Resource is assigned." )]
   CIM_LogicalDevice REF Dependent;

      [Description ( 
          "Boolean indicating whether the LogicalDevice can act as "
          "a bus master on the DMA Channel." ), 
       MappingStrings { "MIF.DMTF|System Resource DMA Info|001.6" }]
   boolean BusMaster;


};
