// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::System::BIOS" ), 
    Description ( 
       "The CIM_BIOSString object may be used to instantiate "
       "string-based BIOS attributes." )]
class CIM_BIOSString : CIM_BIOSAttribute {

      [Description ( 
          "The StringType property provides management applications "
          "with information defining implementation\'s capabilities "
          "regarding string values. A value of ASCII indicates a "
          "plain text formatting with no tabs formating or bolds, "
          "plain text. A value of hex indicates a simple encoding "
          "of the numerals 0 to 9 and the letters A to F and is not "
          "case sensitive. A value of unicode indicates fully "
          "multi-lingual text support. A string BIOS Attribute with "
          "value of regex is a regular expression and the "
          "CIM_BIOSString.ValueExpression shall be applied to "
          "values represented and any value that is attempted to be "
          "set by invoking SetBIOSAttribute()." ), 
       ValueMap { "0", "2", "3", "4", "5", "..", "65536..4294967295" }, 
       Values { "Unknown", "ASCII", "hex", "unicode", "regex", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint32 StringType;

      [Description ( 
          "This property specifies the minimum string length "
          "allowed when modifying this BIOS attribute. A value of "
          "NULL SHALL be defined as zero." ), 
       ModelCorrespondence { "CIM_BIOSString.MaxLength" }]
   uint64 MinLength;

      [Description ( 
          "This property specifies the maximum string length "
          "allowed when modifying this BIOS attribute. A value of "
          "NULL defines the maximum length is unknown. A value of 0 "
          "defines the maximum length as 18446744073709551615, the "
          "limitation of the property definition as uint64." ), 
       ModelCorrespondence { "CIM_BIOSString.MinLength" }]
   uint64 MaxLength;

      [Description ( 
          "The property denotes a Perl-compatible regular "
          "expression (PCRE) syntax to use in validating Attribute "
          "values. For a string Attribute where StringType=\"regex\" "
          "this property shall have a value." )]
   string ValueExpression;


};
