// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AvailableDiagnosticService 
// ==================================================================
   [Association, Version ( "2.9.0" ), 
    UMLPackagePath ( "CIM::System::Diagnostics" ), 
    Description ( 
       "This is an association class that relates a DiagnosticService "
       "to a ManagedElement. Consumers wishing to \'diagnose\' a "
       "particular Element could query this association to determine "
       "what services are available." )]
class CIM_AvailableDiagnosticService : CIM_ServiceAvailableToElement {

      [Override ( "ServiceProvided" ), 
       Description ( 
          "The diagnostic service that is available to a ManagedElement."
           )]
   CIM_DiagnosticService REF ServiceProvided;

      [Description ( 
          "Estimated magnitude of time to perform the referenced "
          "DiagnosticService on the referenced ManagedElement. \n"
          "Since the processing speed of a system can vary "
          "immensely due to a variety of factors (e.g., processor "
          "speed), this property takes on values that are a "
          "statement of magnitude, not absolute time. If greater "
          "accuracy can be provided, a quantification may be "
          "specified in the corresponding integer property, "
          "EstimatedDurationQualifier. \n"
          "Since execution times could vary by Element, this "
          "property is located in the association between the two "
          "entities." ), 
       ValueMap { "0", "2", "3", "4", "5", "6" }, 
       Values { "Unknown", "Milliseconds", "Seconds", "Minutes", 
          "Hours", "Days" }, 
       ModelCorrespondence { 
          "CIM_AvailableDiagnosticService.EstimatedDurationQualifier" }]
   uint16 EstimatedDurationOfService;

      [Description ( 
          "EstimatedDurationQualifier can be used to further "
          "quantify the magnitude of time to perform the service." ), 
       ModelCorrespondence { 
          "CIM_AvailableDiagnosticService.EstimatedDurationOfService" }]
   uint32 EstimatedDurationQualifier;


};
