// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_BootOSFromFS 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::OperatingSystem" ), 
    Description ( 
       "A link between the OperatingSystem and the FileSystem(s) from "
       "which this OperatingSystem is loaded. The association is many- "
       "to-many since a Distributed OS could depend on several File "
       "Systems in order to correctly and completely load." )]
class CIM_BootOSFromFS : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The FileSystem from which the OperatingSystem is loaded." )]
   CIM_FileSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The OperatingSystem." )]
   CIM_OperatingSystem REF Dependent;


};
