// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DirectoryContainsFile 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "Specifies the hierarchical arrangement of LogicalFiles in a "
       "Directory." )]
class CIM_DirectoryContainsFile : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( "The Directory." )]
   CIM_Directory REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The LogicalFile \'contained within\' the Directory." )]
   CIM_LogicalFile REF PartComponent;


};
