// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ProcessExecutable 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "A link between a Process and a DataFile indicating that the "
       "File participates in the execution of the Process." )]
class CIM_ProcessExecutable : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The DataFile participating in the execution of the Process."
           )]
   CIM_DataFile REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Process." )]
   CIM_Process REF Dependent;


};
