// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ResidesOnExtent 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "An association between a LogicalElement and the StorageExtent "
       "where it is located. Typically, a FileSystem ResidesOn a "
       "LogicalDisk. However, it is possible for a logical file or "
       "other internal data store to reside directly on a "
       "StorageExtent or appropriate subclass." )]
class CIM_ResidesOnExtent : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The StorageExtent." )]
   CIM_StorageExtent REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The LogicalElement that is located on the StorageExtent." )]
   CIM_LogicalElement REF Dependent;


};
