// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_InstalledOS 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::System::OperatingSystem" ), 
    Description ( 
       "A link between the ComputerSystem and the OperatingSystem(s) "
       "installed or loaded on it. An OperatingSystem is \'installed\' "
       "on a ComputerSystem, when placed on one of its StorageExtents "
       "- for example, copied to a disk drive or downloaded to Memory. "
       "Using this definition, an OperatingSystem is \'installed\' on "
       "a NetPC when downloaded via the network." )]
class CIM_InstalledOS : CIM_SystemComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The ComputerSystem." )]
   CIM_ComputerSystem REF GroupComponent;

      [Override ( "PartComponent" ), 
       Weak, Description ( 
          "The OperatingSystem installed on the ComputerSystem." )]
   CIM_OperatingSystem REF PartComponent;

      [Description ( 
          "Boolean indicating that the OperatingSystem is the "
          "default OS for the ComputerSystem." ), 
       MappingStrings { "MIF.DMTF|Operating System|001.4" }]
   boolean PrimaryOS;


};
