TOP = ../..
include $(TOP)/config.mak

CXXSHLIBRARY = nitssampleproduct

SOURCES = sampleproduct.cpp \

DEFINES = UNICODE HOOK_BUILD 

INCLUDES = . $(TOP) $(TOP)/common

LIBRARIES = pal

include $(TOP)/mak/rules.mak
