TOP = ../../..
include $(TOP)/config.mak

CXXPROGRAM = nits_hook_build_sample

SOURCES = linkageSample.c

DEFINES = UNICODE HOOK_BUILD

INCLUDES = . $(TOP) $(TOP)/common

LIBRARIES = pal

include $(TOP)/mak/rules.mak
