// Copyright (c) 2008 DMTF.  All rights reserved.
   [Association, Version ( "2.18.0" ), 
    UMLPackagePath ( "CIM::Physical::Connector" ), 
    Description ( 
       "Adapter cards, DIMMs and other physical elements are plugged "
       "into System Connectors for power and/or to transfer data. This "
       "relationship is defined by ElementInConnector." )]
class CIM_ElementInConnector : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The Connector into which the Element is inserted." )]
   CIM_PhysicalConnector REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( "The Element in the Connector." )]
   CIM_PhysicalElement REF Dependent;


};
