// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_Chip 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Physical::Component" ), 
    Description ( 
       "The Chip class represents any type of integrated circuit "
       "hardware, including ASICs, processors, memory chips, etc." )]
class CIM_Chip : CIM_PhysicalComponent {

      [Description ( 
          "The implementation form factor for the Chip. For "
          "example, values such as SIMM (7), TSOP (9) or PGA (10) "
          "can be specified." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11", "12", "13", "14", "15", "16", "17", "18", 
          "19", "20", "21", "22", "23" }, 
       Values { "Unknown", "Other", "SIP", "DIP", "ZIP", "SOJ", 
          "Proprietary", "SIMM", "DIMM", "TSOP", 
          // 10               
          "PGA", "RIMM", "SODIMM", 
          "SRIMM", "SMD", "SSMP", "QFP", "TQFP", "SOIC", "LCC", 
          // 20               
          "PLCC", "BGA", "FPBGA", 
          "LGA" }]
   uint16 FormFactor;


};
