// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_Magazine 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Physical::StoragePackage" ), 
    Description ( 
       "StorageMediaLocations are typically slots or spaces where "
       "removable media are located. However, a specific kind of "
       "MediaLocation is a Magazine. This entity represents a single "
       "physical container with multiple StorageMediaLocations in it. "
       "All the MediaLocations within the Magazine are added/removed "
       "together. Often, this container has a Barcode or other label "
       "for identification. This is the unique data captured in the "
       "CIM_Magazine class. Magazine\'s label properties are defined "
       "exactly as are labels for PhysicalMedia." )]
class CIM_Magazine : CIM_StorageMediaLocation {

      [Description ( 
          "One or more strings on \'labels\' on the Magazine. The "
          "format of the labels and their state (readable, "
          "unreadable, upside-down) are indicated in the "
          "corresponding LabelFormats and LabelStates array "
          "properties." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_Magazine.LabelStates", 
          "CIM_Magazine.LabelFormats" }]
   string PhysicalLabels[];

      [Description ( 
          "An array of enumerated integers describing the states of "
          "each of the labels on a Magazine. The Labels themselves "
          "are listed in the PhysicalLabels property. Note, each "
          "entry of this array is related to the entry in "
          "PhysicalLabels that is located at the same index." ), 
       ValueMap { "0", "1", "2" }, 
       Values { "OK/Readable", "Unreadable", "Upside Down" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_Magazine.PhysicalLabels" }]
   uint16 LabelStates[];

      [Description ( 
          "An array of enumerated integers describing the formats "
          "of each of the labels on a Magazine. The Labels "
          "themselves are listed in the PhysicalLabels property. "
          "Note, each entry of this array is related to the entry "
          "in PhysicalLabels that is located at the same index." ), 
       ValueMap { "0", "1", "2", "3", "4", "5" }, 
       Values { "Barcode", "Radio Frequency Identification", 
          "OCR (Optical Character Recognition)", 
          "MICR (Magnetic Ink Character Recognition)", 
          "7 Character Barcode", "9 Character Barcode" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_Magazine.PhysicalLabels" }]
   uint16 LabelFormats[];


};
