// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ElementCapacity 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Physical::Misc" ), 
    Description ( 
       "ElementCapacity associates a PhysicalCapacity object with one "
       "or more PhysicalElements. It serves to associate a description "
       "of min/max hardware requirements or capabilities (stored as a "
       "kind of PhysicalCapacity), with the PhysicalElements being "
       "described." )]
class CIM_ElementCapacity {

      [Key, Description ( 
          "PhysicalCapacity describes the minimum and maximum "
          "requirements, and ability to support different types of "
          "hardware for a PhysicalElement." )]
   CIM_PhysicalCapacity REF Capacity;

      [Key, Min ( 1 ), 
       Description ( "The PhysicalElement being described." )]
   CIM_PhysicalElement REF Element;


};
