// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SlotInSlot 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Physical::Connector" ), 
    Description ( 
       "Slots are special types of Connectors into which adapter Cards "
       "are typically inserted. The SlotInSlot relationship represents "
       "the ability of a special adapter to extend the existing Slot "
       "structure to enable otherwise incompatible Cards to be plugged "
       "into a Frame or Hosting Board. The adapter effectively creates "
       "a new Slot and can be thought of (conceptually) as a Slot in a "
       "Slot. This enables Cards that would otherwise be physically "
       "and/or electrically incompatible with the existing Slots to be "
       "supported, by interfacing to the Slot provided by the adapter. "
       "This has many practical uses. For example, networking boards "
       "are very expensive. As new hardware becomes available, Chassis "
       "and even Card configurations change. To protect the investment "
       "of their customers, networking vendors will manufacture "
       "special adapters that enable old Cards to fit into new Chassis "
       "or Hosting Boards and/or new Cards to fit into old. This is "
       "done using a special adapter that fits over one or more "
       "existing Slots and presents a new Slot into which the Card can "
       "plug." )]
class CIM_SlotInSlot : CIM_ConnectedTo {

      [Override ( "Antecedent" ), 
       Description ( 
          "The Antecedent represents the existing Slot(s) of the "
          "HostingBoard, or Frame that are being adapted to "
          "accommodate a Card that would otherwise not be "
          "physically and/or electrically compatible with it." )]
   CIM_Slot REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( "The new Slot provided by the adapter board." )]
   CIM_Slot REF Dependent;


};
