// Copyright (c) 2008 DMTF.  All rights reserved.
   [Abstract, Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "The description of a CIM Listener destination. A CIM_Listener "
       "is an entity capable of receiving CIM Export Messages (e.g., "
       "Indications or responses to an asynchronous CIM Operation)." )]
class CIM_ListenerDestination : CIM_ManagedElement {

      [Key, Description ( 
          "A System\'s CreationClassName. A CIM Listener "
          "destination is defined in context of a CIM_System (e.g., "
          "the sending system." ), 
       MaxLen ( 256 )]
   string SystemCreationClassName;

      [Key, Description ( 
          "A System\'s Name. A CIM Listener destination is defined "
          "in context of a CIM_System (e.g., the sending system." ), 
       MaxLen ( 256 )]
   string SystemName;

      [Key, Description ( 
          "Indicates the name of the class or the subclass used in "
          "the creation of an instance. When used with the other "
          "key properties of this class, it allows all instances of "
          "this class and its subclasses to be uniquely identified." ), 
       MaxLen ( 256 )]
   string CreationClassName;

      [Key, Description ( 
          "Indicates the name of the CIM Listener destination." ), 
       MaxLen ( 256 )]
   string Name;

      [Description ( 
          "Describes the Persistence Type of the destination "
          "defined by this instance. If the value of "
          "PersistenceType is not specified, the value of "
          "PersistenceType MUST be treated as 2 (\"Permanent\"). A "
          "value of 2 (\"Permanent\") declares that the destination "
          "is always expected to be available (e.g., system log "
          "file). Inability to access this destination MUST be "
          "treated as an error condition. A value of 3 "
          "(\"Transient\") indicates that the destination is "
          "short-lived. Inability to access the destination MAY be "
          "treated as a normal termination condition. Subscriptions "
          "with \"Transient\" destinations MAY be deleted when the "
          "destination terminates or is no longer available." ), 
       ValueMap { "1", "2", "3" }, 
       Values { "Other", "Permanent", "Transient" }, 
       ModelCorrespondence { 
          "CIM_ListenerDestination.OtherPersistenceType" }]
   uint16 PersistenceType;

      [Description ( 
          "A string describing (\"Other\") values for "
          "PersistenceType. This value MUST be set to a non NULL "
          "value when the PersistenceType is 1 (\"Other\"). For all "
          "other values of PersistenceType, the value of "
          "OtherPersistenceType MUST be NULL." ), 
       ModelCorrespondence { 
          "CIM_ListenerDestination.PersistenceType" }]
   string OtherPersistenceType;

      [Description ( 
          "The destination IETF URI to which Export Messages are to "
          "be delivered. The scheme in the URI must be supported by "
          "theprotocol selected in the Protocol property." )]
   string Destination;

      [Description ( 
          "A free-form string providing a description of the "
          "supported protocols when 1, \"Other\", is specified for "
          "the Protocol." ), 
       ModelCorrespondence { "CIM_ListenerDestination.Protocol" }]
   string OtherProtocol;

      [Description ( 
          "Protocol describes an encoding and protocol which will "
          "be used to deliver the indication. If Other is used, the "
          "value for OtherProtocol must not be null.\n"
          "If a protocol is not specified, 2 \"CIM-XML\" must be "
          "assumed." ), 
       ValueMap { "1", "2", "3", "4", "5", ".." }, 
       Values { "Other", "CIM-XML", "SM CLP", "WS-Management", 
          "WSDM", "DMTF Reserved" }, 
       ModelCorrespondence { "CIM_ListenerDestination.OtherProtocol" }]
   uint16 Protocol = 2;


};
