// Copyright (c) 2010 DMTF.  All rights reserved.
   [Indication, Version ( "2.27.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_InstCreation notifies when a new instance is created." )]
class CIM_InstCreation : CIM_InstIndication {


};
