// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_Agreement 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "The agreement or contract referenced for entitlement to service."
        )]
class PRS_Agreement : PRS_ExchangeElement {

      [Description ( 
          "The identifier for the contract between the Request and "
          "the Provider. This property is set by the Requester "
          "prior to submitting a Service Request." )]
   string ContractID;

      [Description ( "A brief description of the contract." )]
   string AgreementType;


};
