// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_ProductAsset 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "PRS_ProductAsset is used to provide specific information about "
       "a PRS_Product. PRS_ProductAsset associates this information to "
       "a PRS_Product using one or more Statements associated to a "
       "PRS_Expression." )]
class PRS_ProductAsset : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The product." )]
   PRS_Product REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The expression." )]
   PRS_Expression REF Dependent;


};
