// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_SolutionElement 
// ==================================================================
   [Abstract, Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "PRS_SolutionElement is an abstract base class for non-Category "
       "objects that are associated with a Solution. This includes: \n"
       "PRS_Reference \n"
       "PRS_Problem \n"
       "PRS_Resolution \n"
       "\n"
       "PRS_SolutionElement provides a common reference for these "
       "objects to be associated with PRS_Expression objects through "
       "the SolutionExpression association. \n"
       "\n"
       "In addition, all of the derived objects may be retrieved with "
       "a single query for the common super-class." )]
class PRS_SolutionElement : PRS_ExchangeElement {


};
