// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_Revision 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( "PRS_Revision records changes to the content." )]
class PRS_Revision : PRS_ExchangeElement {

      [Description ( "The date of this revision." )]
   datetime RevisionDate;

      [Description ( "The name of the specific revision being made." ), 
       ValueMap { "0", "1", "2", "254", "255" }, 
       Values { "Create", "Update", "Delete", "Other", "Unknown" }]
   uint8 ActivityName;

      [Description ( 
          "Type of revision activity. \'Technical\' refers to a "
          "change in content. \'Editorial\' refers to a change in "
          "language or style. \'Administrative\' refers to "
          "information about the object." ), 
       ValueMap { "0", "1", "2", "254", "255" }, 
       Values { "Technical", "Editorial", "Administrative", "Other", 
          "Unknown" }]
   uint8 ActivityType;

      [Description ( 
          "The current state of technical review. \'Open\' means "
          "created but not necessarily completed or resolved. \'Not "
          "Reviewed\' means contents have to be reviewed for "
          "accuracy and consistency with other content. \'Reviewed\' "
          "means review has been completed. \'Approved\' means "
          "formally approval to certify the solution given the "
          "specific status of the contents." ), 
       ValueMap { "0", "1", "2", "3", "254", "255" }, 
       Values { "Open", "Not Reviewed", "Reviewed", "Approved", 
          "Other", "Unknown" }]
   uint8 TechnicalStatus;

      [Description ( 
          "The current state of editorial review. \'In Progress\' "
          "means the content is in the process of being developed. "
          "\'Draft\' means the content is complete but unedited. "
          "\'Reviewed\' means the review has been completed. "
          "\'Published\' means the contents have been released." ), 
       ValueMap { "0", "1", "2", "3", "254", "255" }, 
       Values { "In_Progress", "Draft", "Reviewed", "Published", 
          "Other", "Unknown" }]
   uint8 EditorialStatus;

      [Override ( "Description" ), 
       Description ( 
          "Text description of what was done in this revision." )]
   string Description;


};
