// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_Contact 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "PRS_Contact is used to anchor associations to PRS_Person and "
       "PRS_Orgnaization. PRS_Contact is also used to anchor "
       "associations to PRS_Revision and PRS_Resolution, as well as "
       "PRS_ServiceIncident." )]
class PRS_Contact : PRS_ExchangeElement {


};
