// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_SolutionCategory 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "PRS_SolutionCategory associates PRS_Solution with a "
       "PRS_Category for classification purposes." )]
class PRS_SolutionCategory : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Description ( "The PRS_Solution being classified." )]
   PRS_Solution REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The specific PRS_Category being used to classify the Solution."
           )]
   PRS_Category REF Dependent;


};
