// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_AdminAssociation 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "Associates PRS_Administrative data with any object derived "
       "from PRS_ExchangeElement." )]
class PRS_AdminAssociation : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Description ( "The PRS_ExchangeElement." )]
   PRS_ExchangeElement REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The PRS_Administrative object." )]
   PRS_Administrative REF Dependent;


};
