// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_Feature 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "PRS_Feature is used for structured diagnostic data, including "
       "specific data values like steps or conditions. For example, "
       "consider a PRS_Statement with a Text property value of: \n"
       "Print jobs per day are less than 50 \n"
       "\n"
       "This could be described using a PRS_Feature as follows: \n"
       "Description: \'Print jobs per day\' \n"
       "Prompt: \'How many print jobs per day?\' \n"
       "ValidValues: \'10\' \'50\' \'100\' \n"
       "DataType: \'Integer\' \n"
       "\n"
       "The associated PRS_Statement would contain: \n"
       "Operator: \'<\' \n"
       "FeatureValue: \'50\'" )]
class PRS_Feature : PRS_ExchangeElement {

      [Description ( "Prompt presented through user interface." )]
   string Prompt;

      [Description ( "Valid values for this PRS_Feature." )]
   string ValidValues;

      [Description ( 
          "Data type used for PRS_Statement FeatureValue property." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "254", "255" }, 
       Values { "String", "Integer", "Float", "Date/Time", 
          "Boolean", "Binary", "Other", "Unknown" }]
   uint8 DataType;


};
