// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_Category 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "PRS_Category is used to classify the components of a Solution. "
       "Hierarchical classifications are created by associating "
       "PRS_CategoryParentChild with multiple PRS_Category instances." )]
class PRS_Category : PRS_ExchangeElement {

      [Description ( 
          "The specific value for the category. For example, \'HP "
          "Laserjet\' would be a value for a category containing "
          "printer names." )]
   string CategoryContents;

      [Description ( 
          "The type of category. Used to give additional semantics "
          "to the category. For example, a Category of Type "
          "\'Printers\' would qualify the list of category values "
          "for a list of printers. \n"
          "\n"
          "Note: the relationship of Category Type to Category "
          "Value expresses no intrinsic hierarchy. If a tree of "
          "relationships exists to define categories and "
          "sub-categories, this should be defined using "
          "CategoryParentChild associations." )]
   string CategoryType;


};
