// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_Product 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "PRS_Product is used to describe a single product to associate "
       "with a PRS_Expression." )]
class PRS_Product : PRS_ExpressionElement {

      [Description ( "The vendor of the product." )]
   string Vendor;

      [Description ( "The make and or model of the product." )]
   string ProductName;

      [Description ( "The version of the product." )]
   string Version;

      [Description ( 
          "The order of relevance of this product to an associated "
          "PRS_SolutionElement (which includes PRS_Reference, "
          "PRS_Problem or PRS_Resolution)." )]
   string Order;


};
