// Copyright (c) 2005 DMTF.  All rights reserved.
   [Abstract, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Database::System" ), 
    Description ( 
       "The CIM_DatabaseParameter class extends from "
       "CIM_ScopedSettingData. This abstract class specifies the "
       "database and service configuration parameters that are common "
       "across database models and vendor implementations. \n"
       "The SNMP RDBMS MIB defines database and service parameters as "
       "name and value pair combinations rather than as specific named "
       "properties of the class. In order to maintain a consistent "
       "mapping between SNMP and CIM, a CIM_SNMPDatabaseParameter "
       "class extends from the abstract CIM_DatabaseParameter class, "
       "which defines parameters as a name value pair. \n"
       "In a future release of the database MOF, the working group can "
       "choose to create a new class that extends from "
       "CIM_DatabaseParameter, which specifies properties for common "
       "configuration parameters. \n"
       "The parameter context for a specific database or database "
       "service is established by collecting the SettingData using the "
       "CIM_ElementProfile association. \n"
       "The SNMP RDBMS MIB defines generic tables that contain rows of "
       "named database or service configuration entries. A parameter "
       "entry contains a parameter name, description, and value. See "
       "the description of the rdbmsDbParamTable or the "
       "rdbmsSrvParamTable for more information on the SNMP "
       "definitions." )]
class CIM_DatabaseParameter : CIM_ScopedSettingData {


};
