class X
{
    boolean b;
    uint8 u8;
    sint8 s8;
    uint16 u16;
    sint16 s16;
    uint32 u32;
    sint32 s32;
    uint64 u64;
    sint64 s64;
    real32 r32;
    real64 r64;
    char16 c16;
    string s;
    datetime dt;
    boolean ba[];
    uint8 u8a[];
    sint8 s8a[];
    uint16 u16a[];
    sint16 s16a[];
    uint32 u32a[];
    sint32 s32a[];
    uint64 u64a[];
    sint64 s64a[];
    real32 r32a[];
    real64 r64a[];
    char16 c16a[];
    string sa[];
    datetime dta[];
    string empty[];
};

instance of X
{
    b = true;
    u8 = 8;
    s8 = -8;
    u16 = 16;
    s16 = -16;
    u32 = 32;
    s32 = -32;
    u64 = 64;
    s64 = -64;
    r32 = 32.32;
    r64 = 64.64;
    c16 = 'A';
    s = "String";
    dt = "20101231120000.123456+360";
    ba = { true, false, true };
    u8a = { 8, 9, 10 };
    s8a = { -8, -9, -10 };
    u16a = { 16, 17 };
    s16a = { -16, -17 };
    u32a = { 32, 33 };
    s32a = { -32, -33 };
    u64a = { 64, 65 };
    s64a = { -64, -65 };
    r32a = { 32.32, 33.33 };
    r64a = { 64.64, 65.65 };
    c16a = { 'A', 'B', 'C' };
    sa = { "Red", "Green", "Blue" };
    dta = { "20101231120000.123456+360" };
    empty = NULL;
};
