TOP = ../../../..
include $(TOP)/config.mak

CXXPROGRAM = AsyncEnum

SOURCES = AsyncEnum.cpp

INCLUDES = $(TOP) $(TOP)/common

DEFINES = MI_CONST=

LIBRARIES = omiclient micxx wsman http protocol sock base

include $(TOP)/mak/rules.mak
