TOP = ../../..
include $(TOP)/config.mak

CXXPROGRAM = nits_debug_build_sample

SOURCES = linkageSample.c

DEFINES = UNICODE DEBUG_BUILD

INCLUDES = . $(TOP) $(TOP)/common

LIBRARIES = pal

include $(TOP)/mak/rules.mak
