TOP = ..
include $(TOP)/config.mak

CXXSHLIBRARY = mofcxx

SOURCES = mofcxx.cpp

INCLUDES = $(TOP) $(TOP)/common

DEFINES = MI_CONST=

LIBRARIES = mof base io

DEFINES = BUILDING_MOFCXX

include $(TOP)/mak/rules.mak
