TOP = ../..
include $(TOP)/config.mak

DIRECTORIES = \
    Color \
    Connector \
    ConnectorCXX \
    Fastener \
    Number \
    Demo-i2 \
    PersonProvider \
    PersonProviderCXX \
    President \
    DogPreExec \
    Dog \
    Datetime \
    Tester \
    TestClass_AllDMTFTypes \
    Test_SchemaRetrieval

include $(ROOT)/mak/rules.mak
-include TestProviders.mak
