TOP = ../..
include $(TOP)/config.mak

LIBRARY = indicmn

SOURCES = \
	util.c \

INCLUDES = $(TOP) $(TOP)/common $(TOP)/pal $(TOP)/nits/base 

DEFINES = MI_CONST= HOOK_BUILD

include $(TOP)/mak/rules.mak
