// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ConnectivityCollection 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::Collections" ), 
    Description ( 
       "A ConnectivityCollection groups together a set of "
       "ProtocolEndpoints of the same \'type\' (i.e., class) which are "
       "able to communicate with each other. It may also group related "
       "Systems, users or other ManagedElements. A "
       "ConnectivityCollection represents the ability to send and/or "
       "receive data over a set of ProtocolEndpoints. The collection "
       "is defined in the context of an AdminDomain or scoping "
       "ComputerSystem. This is mandated by the Hosted Collection "
       "association on the SystemSpecificCollection superclass. Note "
       "that the entities aggregated into the Collection are specified "
       "using the association, MemberOfCollection." )]
class CIM_ConnectivityCollection : CIM_SystemSpecificCollection {

      [Description ( 
          "An enumeration describing the current or potential "
          "connectivity between endpoints in this collection. "
          "Connectivity may be provided or not, or may be in a "
          "degraded/partitioned state if one or more endpoints or "
          "links have failed. The latter would prevent full "
          "connectivity between all elements in the Collection, but "
          "would permit connectivity between subsets." ), 
       ValueMap { "0", "2", "3", "4" }, 
       Values { "Unknown", "Connectivity/Up", 
          "No Connectivity/Down", "Partitioned" }]
   uint16 ConnectivityStatus;


};
