#pragma locale ("en_US")
#pragma include("qualifiers.mof")
#pragma include("qualifiers_optional.mof")
#pragma include("CIM_ManagedElement.mof")
#pragma include("CIM_ManagedSystemElement.mof")
#pragma include("CIM_LogicalElement.mof")
#pragma include("CIM_Job.mof")
#pragma include("CIM_ConcreteJob.mof")
#pragma include("CIM_Capabilities.mof")
#pragma include("CIM_EnabledLogicalElement.mof")
#pragma include("CIM_Service.mof")
#pragma include("CIM_SecurityService.mof")
#pragma include("CIM_AuthenticationService.mof")
#pragma include("CIM_EnabledLogicalElementCapabilities.mof")
#pragma include("CIM_IdentityManagementService.mof")
#pragma include("CIM_View.mof")
#pragma include("MSFT_BaseAddressFamily.mof")
#pragma include("MSFT_AddressFamilyIPv4.mof")
#pragma include("CIM_ServiceAccessPoint.mof")
#pragma include("CIM_RemoteServiceAccessPoint.mof")
#pragma include("CIM_ProtocolEndpoint.mof")
#pragma include("CIM_IPProtocolEndpoint.mof")
#pragma include("MSFT_SwitchedVirtualInterface.mof")
#pragma include("MSFT_SubInterface.mof")
#pragma include("MSFT_LoopbackInterface.mof")
#pragma include("MSFT_ASBGPIPEndpoints.mof")
#pragma include("MSFT_AddressFamilyNetwork.mof")
#pragma include("CIM_Account.mof")
#pragma include("CIM_AccountCapabilities.mof")
#pragma include("CIM_AccountManagementCapabilities.mof")
#pragma include("CIM_System.mof")
#pragma include("CIM_ComputerSystem.mof")
#pragma include("CIM_Identity.mof")
#pragma include("CIM_AccountManagementService.mof")
#pragma include("CIM_SettingData.mof")
#pragma include("MSFT_LinkAggregationSettingData.mof")
#pragma include("CIM_AccountSettingData.mof")
#pragma include("CIM_AdminDomain.mof")
#pragma include("CIM_AllocationCapabilities.mof")
#pragma include("CIM_AutonomousSystem.mof")
#pragma include("CIM_Collection.mof")
#pragma include("CIM_Component.mof")
#pragma include("CIM_SystemComponent.mof")
#pragma include("MSFT_AssociatedAddressFamily.mof")
#pragma include("CIM_MemberOfCollection.mof")
#pragma include("MSFT_AssociatedAddressFamilyNetworks.mof")
#pragma include("MSFT_AssociatedAS.mof")
#pragma include("MSFT_AutonomousSystemSettingData.mof")
#pragma include("CIM_Dependency.mof")
#pragma include("CIM_SAPSAPDependency.mof")
#pragma include("CIM_BindsTo.mof")
#pragma include("CIM_LANEndpoint.mof")
#pragma include("CIM_BindsToLANEndpoint.mof")
#pragma include("CIM_ConcreteCollection.mof")
#pragma include("CIM_SystemSpecificCollection.mof")
#pragma include("CIM_ConnectivityCollection.mof")
#pragma include("CIM_LogicalDevice.mof")
#pragma include("CIM_DeviceSAPImplementation.mof")
#pragma include("CIM_ElementCapabilities.mof")
#pragma include("CIM_CollectionOfMSEs.mof")
#pragma include("CIM_Setting.mof")
#pragma include("CIM_ElementSetting.mof")
#pragma include("CIM_Error.mof")
#pragma include("CIM_LogicalPort.mof")
#pragma include("CIM_NetworkPort.mof")
#pragma include("CIM_EthernetPort.mof")
#pragma include("CIM_HostedDependency.mof")
#pragma include("CIM_HostedAccessPoint.mof")
#pragma include("CIM_HostedCollection.mof")
#pragma include("CIM_ResourceAllocationSettingData.mof")
#pragma include("CIM_EthernetPortAllocationSettingData.mof")
#pragma include("CIM_Policy.mof")
#pragma include("CIM_NetworkPolicyAction.mof")
#pragma include("CIM_NetworkPolicyActionSettingData.mof")
#pragma include("CIM_NetworkPolicyCondition.mof")
#pragma include("CIM_PolicySet.mof")
#pragma include("CIM_PolicyRule.mof")
#pragma include("CIM_NetworkPolicyRule.mof")
#pragma include("CIM_NetworkPolicyRuleSettingData.mof")
#pragma include("CIM_NetworkPolicyService.mof")
#pragma include("CIM_NetworkPolicyServiceCapabilities.mof")
#pragma include("CIM_FirewallRuleSettingData.mof")
#pragma include("MSFT_ACL.mof")
#pragma include("CIM_NetworkVLAN.mof")
#pragma include("CIM_PhysicalComputerSystemView.mof")
#pragma include("CIM_PolicyAction.mof")
#pragma include("CIM_PolicyComponent.mof")
#pragma include("CIM_PolicyActionStructure.mof")
#pragma include("CIM_PolicyActionInPolicyRule.mof")
#pragma include("CIM_PolicyCondition.mof")
#pragma include("CIM_PolicyConditionStructure.mof")
#pragma include("CIM_PolicyConditionInPolicyRule.mof")
#pragma include("CIM_PolicySetAppliesToElement.mof")
#pragma include("MSFT_MatchedPolicyComponent.mof")
#pragma include("MSFT_ACLAppliesToElement.mof")
#pragma include("MSFT_VACLAppliesToVLAN.mof")
#pragma include("CIM_PolicySetComponent.mof")
#pragma include("CIM_Privilege.mof")
#pragma include("CIM_ServiceAccessBySAP.mof")
#pragma include("CIM_ProvidesEndpoint.mof")
#pragma include("CIM_RemotePort.mof")
#pragma include("CIM_Role.mof")
#pragma include("CIM_ServiceAccessURI.mof")
#pragma include("CIM_SNMPCommunityString.mof")
#pragma include("CIM_SNMPService.mof")
#pragma include("CIM_SNMPTrapTarget.mof")
#pragma include("CIM_SystemDevice.mof")
#pragma include("CIM_VirtualSystemSettingData.mof")
#pragma include("CIM_VirtualEthernetSwitchSettingData.mof")
#pragma include("CIM_VLAN.mof")
#pragma include("CIM_VLANEndpoint.mof")
#pragma include("CIM_VLANEndpointSettingData.mof")
#pragma include("MSFT_BGPBestpathConfiguration.mof")
#pragma include("MSFT_BGPTemplate.mof")
#pragma include("MSFT_IP4AddressConfiguration.mof")
#pragma include("MSFT_NeighborTemplate.mof")
#pragma include("MSFT_BGPConfiguration.mof")
#pragma include("MSFT_ComPort.mof")
#pragma include("MSFT_LineConsole.mof")
#pragma include("MSFT_AuthenticationAuthorizationAccounting.mof")
#pragma include("MSFT_Banner.mof")
#pragma include("MSFT_Feature.mof")
#pragma include("MSFT_LinkAggregation.mof")
#pragma include("MSFT_LinkAggregationAssociation.mof")
#pragma include("MSFT_Neighbor.mof")
#pragma include("MSFT_NetworkVLAN.mof")
#pragma include("MSFT_SpanningTree.mof")
#pragma include("MSFT_SwitchService.mof")
#pragma include("MSFT_NetworkACLService.mof")
#pragma include("MSFT_VirtualRoutingAndForwarding.mof")
#pragma include("MSFT_VirtualTerminal.mof")
#pragma include("CIM_ElementSettingData.mof")
#pragma include("MSFT_InterfaceCollection.mof")
