// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00722.000" type ="change">Update of
// descriptions based on Tech Edit review.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_BindsTo
// ==================================================================
   [Association, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "This association establishes a ServiceAccessPoint as a "
       "requestor of protocol services from a ProtocolEndpoint. "
       "Typically, this association runs between SAPs and endpoints on "
       "a single system. Because a ProtocolEndpoint is a kind of "
       "ServiceAccessPoint, this binding can be used to establish a "
       "layering of two protocols, with the upper layer represented by "
       "the Dependent and the lower layer represented by the "
       "Antecedent." )]
class CIM_BindsTo : CIM_SAPSAPDependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The lower-level endpoint that is accessed by the SAP." )]
   CIM_ProtocolEndpoint REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The AccessPoint or ProtocolEndpoint that is dependent on "
          "the lower-level endpoint." )]
   CIM_ServiceAccessPoint REF Dependent;


};
