// ===============================================================
//  MSFT_IPACLAppliesToElement
// ===============================================================
	[Association, Description ( "MSFT_IPACLAppliesToElement description." ), 
	Version ( "0.70" )]
class MSFT_ACLAppliesToElement: CIM_PolicySetAppliesToElement
{

	 
       [Description ( 
          "Direction the ACL applies to"), 
       ValueMap { "2", "3"}, 
       Values { "In", "Out"}]
	  uint16 Direction;
};
