// ===============================================================
//  MSFT_SwitchService
// ===============================================================
	[Description ( "MSFT_SwitchService description." ), 
	Version ( "0.7" )]
class MSFT_SwitchService : CIM_Service

{
[Description ( 
          "Defines and assigns a protcol endpoint subclass to a physical or virtual port or interface,"
		 "for example an instance of CIM_EthernetPort or MSFT_Subinterface\n"
          "Input that is not completely specified may be filled out "
          "with default values." ),
       ValueMap { "0",  "4096", "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error", "Job Started", 
	             "Method Reserved", "Vendor Specific" }]
   uint32 AddProtocolEndpoint(
         [Description ( 
             "Reference to the targeted interface. This instance of CIM_ComputerSystem, CIM_EthernetPort, or a NetworkVlan"
              )]
      CIM_ManagedElement REF TargetInterface, 
 
         [Description ( 
             "A string an containing an embedded "
             "instance of class\subclass of "
             "CIM_ProtocolEndpoint that describes "
             "the aspects of a protocol endpoint. For example"
			 "CIM_VLANEndPoint will be associated with an interfaces CIM_LanEndpoint using the association"
			 "CIM_BindsToLANEndpoint\n" ), 
          EmbeddedInstance ( "CIM_ProtocolEndpoint" ) 
         ]
      string ProtocolEndpoint[], 

	         [Description ( 
             "An array of strings each containing an embedded "
             "instance of class\subclass of "
             "CIM_SettingData that describes "
             "are associated with the new protocol endpoint  "
             "Generally these should be associated to the"  "
			  CIM_ProtocolEndpoint with an Instance of CIM_ElementSettingData" 
			  "An example is the association of CIM_VLANEndpointSettingdata with CIM_VLANEndpoint" ), 
          EmbeddedInstance ( "CIM_SettingData" ) 
           ]
      string EndPointSettings[], 
         
         [In ( false ), Out, Description ( 
             "If a the assignment of a protocol endpoint is successfully, "
             "reference to an instance of class "
             "CIM_ProtocolEndpoint that represents the newly "
             "defined Endpoint is returned." )]
      CIM_ProtocolEndpoint REF ResultingEndpoint, 

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	     [Description ( 
          "removes a protcol endpoint subclass from a physical or virtual port or interface,"
		 "for example an instance of CIM_EthernetPort or MSFT_Subinterface\n"
           ), 
       ValueMap { "0",  "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Method Parameters Checked - Job Started", 
          "Method Reserved", "Vendor Specific" }]
   uint32 RemoveProtocolEndpoint(
         [Description ( 
             "Reference to the targeted instance of CIM_ProtocolEndpoint. "
              )]
      CIM_ProtocolEndpoint REF Endpoint,

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);




   [Description ( 
          "Adds one or more VLANs to the targeted switch"), 
        ValueMap { "0",  
		"4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Method Parameters Checked - Job Started", 
          "Method Reserved", "Vendor Specific" }]
   uint32 AddVLAN(
         [Description ( 
             "Reference to the targeted instance of CIM_COmputerSystem. "
              )]
      CIM_ComputerSystem REF TargetedSwitch,

         [Description ( 
             "A string an containing an embedded "
             "instance of class\subclass of "
             "NetWorkVLan Class containing at least the VLANId property set." ), 
          EmbeddedInstance ( "MSFT_NetworkVLAN" ) 
         ]
      string NetworkVLAN[], 

	         [In ( false ), Out, Description ( 
             "Reference to the new NetworkVLAN instances" )]
      MSFT_NetworkVLAN REF VLAN[],

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

[Description ( 
          "removes one or more NetworkVLANs"
           ), 
       ValueMap { "0",  "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Method Parameters Checked - Job Started", 
          "Method Reserved", "Vendor Specific" }]
   uint32 RemoveVLAN(
         [Description ( 
             "Reference to the targeted instance of MSFT_NetworkVLAN. "
              )]
      MSFT_NetworkVLAN REF VLAN[],

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	

	  	  [Description ( 
          "enable one or more NetworkVLANs"
           ), 
       ValueMap { "0",  "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Method Parameters Checked - Job Started", 
          "Method Reserved", "Vendor Specific" }]
   uint32 EnableVLAN(
         [Description ( 
             "Reference to the targeted instance of MSFT_NetworkVLAN to Enable. "
              )]
      MSFT_NetworkVLAN REF VLAN[],

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);


	  	  	  [Description ( 
          "disable one or more NetworkVLANs"
           ), 
       ValueMap { "0",  "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Method Parameters Checked - Job Started", 
          "Method Reserved", "Vendor Specific" }]
   uint32 Disable_VLAN(
         [Description ( 
             "Reference to the targeted instance of MSFT_NetworkVLAN to Enable. "
              )]
      MSFT_NetworkVLAN REF VLAN[],

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);


[Description ( 
          " Create a Link aggregation," ),
       ValueMap { "0",  "4096", "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error", "Job Started", 
	             "Method Reserved", "Vendor Specific" }]
   uint32 CreateLinkAggregation(
          
 
         [Description ( 
             "A string an containing an embedded "
             "instance of class\subclass of "
             "LinkAggregation that describes "
             "the aspects of the Link aggregation. " ), 
          EmbeddedInstance ( "MSFT_LinkAggregation" ) 
         ]
      string LinkAggregation[], 

	     [Description ( 
             "An array of references to instance of CIM_EthernetPort that "
             "will be used to form the aggregation " )     
     ]
      CIM_EthernetPort ref EthernetPort[], 
         
         [In ( false ), Out, Description ( 
             "If a the creation of a Link Aggregation is successfully, "
             "reference to the instance of class "
             "MSFT_LinkAggregation that was created is returned." )]
      MSFT_LinkAggregation REF ResultingLinkAggregation, 

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	     [Description ( 
          "removes a Link Aggregation"
           ), 
       ValueMap { "0",  "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Method Parameters Checked - Job Started", 
          "Method Reserved", "Vendor Specific" }]
   uint32 RemoveLinkAggregation(
         [Description ( 
             "Reference to the targeted instance of MSFT_LinkAggregation. ")]
      MSFT_LINKAggregation REF LinkAggregation,

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);



[Description ( 
          " Add an Ethernet port to a  Link aggregation," ),
       ValueMap { "0",  "4096", "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error", "Job Started", 
	             "Method Reserved", "Vendor Specific" }]
   uint32 AddPortToAggregation(
          
 
         [Description ( 
             "Aggregation to which to add the Ethernet port "
            )
         ]
      MSFT_LinkAggregation ref  LinkAggregation, 

	         [Description ( 
             "An array of references to instance of CIM_EthernetPort that "
             "will be added to the Link Aggregation "
 ) 
         
           ]
      CIm_EthernetPort ref EthernetPort[], 
         
     

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	  	     [Description ( 
          "removes a port from A Link Aggregation"
           ), 
       ValueMap { "0",  "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Method Parameters Checked - Job Started", 
          "Method Reserved", "Vendor Specific" }]
   uint32 RemoveportFromLinkAggregation(
         [Description ( 
             "Reference to the targeted instance of CIM_EthernetPort. "
              )]
      CIM_EthernetPort REF EthernetPort,

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);


};
