// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::Device::FC" ), 
    Description ( 
       "FibreChannel port control and configuration capabilities." )]
class CIM_FCPortCapabilities : CIM_LogicalPortCapabilities {

      [Description ( 
          "List of supported port types that can be configured on "
          "FCPortSettings.RequestedType. \n"
          "RequestedType acts as a filter on the enabled port types "
          "that a port may auto-negotiate during port login. \n"
          "\"G\" = Port may only act as an expansion port (E), or a "
          "fabric port (F). \"GL\" = Port may only act an an "
          "expansion port (E), a fabric port (F), or a fabric port "
          "supporting FC arbitrated loop (FL). \"E\" = Port may "
          "only act as an expansion port (E) connecting fabric "
          "elements. \"F\" = Port may only act as a fabric port "
          "(F). \"FX\" = Port may only act as a fabric port (F), or "
          "a fabric port supporting FC arbitrated loop (FL). \"B\" "
          "= Port may only act as a bridge port (B). \"NX\" = Port "
          "may only act as a node port (N) or a node port "
          "supporting FC arbitrated loop (NL). \"N\" = Port may "
          "only act as a Node port. \"NL\" = Port may only act as a "
          "Node Port supporting FC arbitrated loop. \"NX\" = Port "
          "may only act as a node port (N) or a node port "
          "supporting FC arbitrated loop (NL)." ), 
       ValueMap { "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "..", "16000..65535" }, 
       Values { "G", "GL", "E", "F", "FX", "B", "NX", "N", "NL", 
          "DMTF Reserved", "Vendor Reserved" }, 
       MappingStrings { 
          "FC-SWAPI.INCITS-T11|SWAPI_PORT_CONFIG_CAPS_T.ConfigurablePortTypes" }]
   uint16 RequestedTypesSupported[];


};
