// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_PointingDevice 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Device::UserDevices" ), 
    Description ( 
       "PointingDevice represents those Devices used to \'point\' to "
       "regions of a Display." )]
class CIM_PointingDevice : CIM_UserDevice {

      [Description ( "The type of the pointing device." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9" }, 
       Values { "Other", "Unknown", "Mouse", "Track Ball", 
          "Track Point", "Glide Point", "Touch Pad", "Touch Screen", 
          "Mouse - Optical Sensor" }, 
       MappingStrings { "MIF.DMTF|Pointing Device|003.1" }]
   uint16 PointingType;

      [Description ( 
          "Number of buttons. If the PointingDevice has no buttons, enter 0."
           ), 
       MappingStrings { "MIF.DMTF|Pointing Device|003.4" }]
   uint8 NumberOfButtons;

      [Description ( 
          "Integer indicating whether the PointingDevice is "
          "configured for right (value=2) or left handed operation "
          "(value=3). Also, the values, \"Unknown\" (0) and \"Not "
          "Applicable\" (1), can be defined." ), 
       ValueMap { "0", "1", "2", "3" }, 
       Values { "Unknown", "Not Applicable", 
          "Right Handed Operation", "Left Handed Operation" }]
   uint16 Handedness;

      [Description ( 
          "Tracking resolution of the PointingDevice in Counts per Inch."
           ), 
       Units ( "Counts per Inch" ), 
       PUnit ( "count / inch" )]
   uint32 Resolution;


};
