// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00751.003" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_OOBAlertServiceOnNetworkAdapter
// ==================================================================
   [Association, Deprecated { "CIM_OOBAlertServiceOnNetworkPort" }, 
    Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::NetworkAdapter" ), 
    Description ( 
       "Note: The use of CIM_OOBAlertServiceOnNetworkAdapter has been "
       "deprecated because NetworkAdapter has been deprecated. Instead "
       "use the CIM_OOBAlertServiceOnNetworkPort class. \n"
       "Deprecated description: OOBAlertServiceOnNetworkAdapter "
       "defines where the out-of-band alerting Service is implemented." )]
class CIM_OOBAlertServiceOnNetworkAdapter : CIM_DeviceServiceImplementation {

      [Deprecated { "CIM_OOBAlertServiceOnNetworkPort.Antecedent" }, 
       Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: The NetworkAdapter that "
          "implements the Service." )]
   CIM_NetworkAdapter REF Antecedent;

      [Deprecated { "CIM_OOBAlertServiceOnNetworkPort.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: The alerting Service that is "
          "provided on the NetworkAdapter." )]
   CIM_OOBAlertService REF Dependent;


};
