// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MonitorSetting 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::UserDevices" ), 
    Description ( 
       "MonitorSetting associates the MonitorResolution Setting object "
       "with the DesktopMonitor to which it applies." )]
class CIM_MonitorSetting : CIM_ElementSetting {

      [Override ( "Element" ), 
       Description ( "The DesktopMonitor." )]
   CIM_DesktopMonitor REF Element;

      [Override ( "Setting" ), 
       Description ( 
          "The MonitorResolution associated with the DesktopMonitor." )]
   CIM_MonitorResolution REF Setting;


};
