// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_LabelReader 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::StorageLib" ), 
    Description ( 
       "LabelReaders represent hardware capable of scanning or reading "
       "a physical label or the NonVolatileMemory on a PhysicalMedia. "
       "Examples of labels include barcode and OCR tags." )]
class CIM_LabelReader : CIM_LogicalDevice {

      [Description ( 
          "An array of enumerated integers describing the formats "
          "of the labels that can be read or scanned by the "
          "LabelReader. The values specified for this property "
          "correspond to those defined for "
          "CIM_PhysicalMedia.LabelFormats." ), 
       ValueMap { "0", "1", "2", "3", "4", "5" }, 
       Values { "Barcode", "Radio Frequency Identification", 
          "OCR (Optical Character Recognition)", 
          "MICR (Magnetic Ink Character Recognition)", 
          "7 Character Barcode", "9 Character Barcode" }, 
       ModelCorrespondence { "CIM_PhysicalMedia.LabelFormats" }]
   uint16 SupportedFormats[];

      [Description ( 
          "The technology used by the LabelReader. One entry of the "
          "Values array requires some explanation - \"Memory "
          "Reader\". The latter describes the ability to access "
          "memory in a PhysicalMedia\'s packaging (for example, "
          "memory on an AIT tape). The existence of this Memory is "
          "indicated by the MemoryWithMedia association on the "
          "physical side, or by AssociatedMemory on the logical "
          "side." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6" }, 
       Values { "Unknown", "Other", "Laser", "Infrared", "RF", 
          "Camera", "Memory Reader" }]
   uint16 Technology;


};
