// Copyright (c) 2009 DMTF.  All rights reserved.
   [Association, Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Device::LED" ), 
    Description ( 
       "ManagedSystemElements may have zero or more IndicatorLEDs "
       "associated with them, in order to indicate problem situations. "
       "This relationship is indicated by the AssociatedIndicatorLED "
       "dependency." )]
class CIM_AssociatedIndicatorLED : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Description ( 
          "The ManagedSystemElement that has an associated LED." )]
   CIM_ManagedSystemElement REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The LED." )]
   CIM_IndicatorLED REF Dependent;


};
