// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Device::Controller" ), 
    Description ( "A collection of one or more PCI device ports." )]
class CIM_PCIPortGroup : CIM_LogicalPortGroup {

      [Description ( 
          "The bus number shared by the PCI device ports." )]
   uint8 BusNumber;


};
