// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DeviceServicesLocation 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::StorageLib" ), 
    Description ( 
       "Within an automated StorageLibrary, Media should be accessible "
       "to the various robotics and MediaTransferDevices (Pickers, "
       "Changers, InterLibraryPorts, etc.). The Library may be "
       "serviced by different TransferDevices, each responsible for a "
       "subset of the Library\'s StorageMediaLocations. The Device "
       "ServicesLocation association indicates that the Transfer "
       "Device handles Media stored in the referenced Location. For "
       "example, LibraryPort \'A\' may only service Media from Slots "
       "1-10, while LibraryPort \'B\' covers Slots 11-33. This detail "
       "is conveyed by this association." )]
class CIM_DeviceServicesLocation : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The MediaTransferDevice that handles Media from the "
          "StorageMediaLocation." )]
   CIM_MediaTransferDevice REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The MediaLocation that is serviced." )]
   CIM_StorageMediaLocation REF Dependent;

      [Description ( 
          "Boolean indicating that the referenced "
          "StorageMediaLocation is not currently accessible to the "
          "MediaTransferDevice. For example, the Location could be "
          "the realization of an InterLibraryPort that is currently "
          "servicing another Library. The DeviceServicesLocation "
          "association describes that the TransferDevice COULD "
          "service the MediaLocation. This boolean indicates that "
          "that this is temporarily not possible." )]
   boolean Inaccessible;


};
