// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PackageDependency 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::DeviceElements" ), 
    Description ( 
       "A LogicalDevice is installed in a Package such as a Chassis or "
       "a Rack, not for a specific Device, but to function with the "
       "Package in general. This relationship is described by the "
       "PackageDependency association." )]
class CIM_PackageDependency : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Logical Device for the Package." )]
   CIM_LogicalDevice REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The PhysicalPackage whose environment is affected." )]
   CIM_PhysicalPackage REF Dependent;


};
