// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PickerLabelReader 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::StorageLib" ), 
    Description ( 
       "PickerLabelReader is used to indicate that one or more Label "
       "Readers works in conjunction with PickerElements, to identify "
       "PhysicalMedia as they are being picked/placed." )]
class CIM_PickerLabelReader : CIM_AssociatedLabelReader {

      [Override ( "Antecedent" ), 
       Description ( "The LabelReader." )]
   CIM_LabelReader REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The PickerElement that is dependent on the Reader Device." )]
   CIM_PickerElement REF Dependent;


};
