// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::StorageStatistics" ), 
    Description ( 
       "An instance of this class defines the specific support for the "
       "metered elements and methods for retrieving that statistical "
       "data from a StatisticsService." )]
class CIM_StatisticsCapabilities : CIM_Capabilities {

      [Description ( 
          "The list of element types for which statistical data is "
          "available. This property may not be meaningful if the "
          "StatisticsService these capabilities describe does not "
          "support StatisticalData instances for different types of "
          "elements." )]
   uint16 ElementTypesSupported[];

      [Description ( 
          "The synchronous mechanisms supported for retrieving "
          "statistics and defining and modifying filters for "
          "statistics retrieval." ), 
       ValueMap { "..", "0x8000.." }, 
       Values { "DMTF Reserved", "Vendor Specific" }]
   uint16 SynchronousMethodsSupported[];

      [Description ( 
          "The asychronous mechanisms supported for retrieving statistics."
           ), 
       ValueMap { "..", "0x8000.." }, 
       Values { "DMTF Reserved", "Vendor Specific" }]
   uint16 AsynchronousMethodsSupported[];


};
