// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "CIM_WiFiRadio describes a radio transceiver component of a "
       "WiFiPort. It is modeled because of the possibility of multiple "
       "transceivers being associated with a single port, the "
       "possibility of multiple ports being associated with a single "
       "radio transceiver, and the possibility of enabling/disabling a "
       "radio transceiver independent of its associated WiFiPort." )]
class CIM_WiFiRadio : CIM_LogicalDevice {

      [Description ( "The received signal strength, in -dBm." ), 
       PUnit ( "decibel(m) * -1" )]
   uint32 SignalStrength;

      [Description ( "The received signal noise, in -dBm." ), 
       PUnit ( "decibel(m) * -1" )]
   uint32 SignalNoise;

      [Description ( 
          "Channel shall contain the channel number currently in "
          "use by the WiFiRadio to communicate with the station "
          "with which it is associated. Each channel number is "
          "associated with a particular signal frequency band." )]
   uint16 Channel;

      [Description ( 
          "The frequency, in Megahertz, of the center frequency of "
          "the band (channel) currently in use by the WiFiRado." ), 
       PUnit ( "hertz * 10^6" )]
   uint32 Frequency;


};
