// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_AssociatedSensor" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Device::Sensors" ), 
    Description ( 
       "The use of this association is being deprecated in lieu of "
       "using AssociatedSensor, since the use of the referenced class "
       "CurrentSensor is deprecated. \n"
       "A PowerSupply may have an associated CurrentSensor, monitoring "
       "its input frequency. This is described by this association." )]
class CIM_AssociatedSupplyCurrentSensor : CIM_AssociatedSensor {

      [Deprecated { "CIM_AssociatedSensor.Antecedent" }, 
       Override ( "Antecedent" ), 
       Description ( "The CurrentSensor." )]
   CIM_CurrentSensor REF Antecedent;

      [Deprecated { "CIM_AssociatedSensor.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "The PowerSupply associated with the CurrentSensor." )]
   CIM_PowerSupply REF Dependent;

      [Deprecated { "No value" }, 
       Description ( 
          "Indicates the PowerSupply\'s input frequency range "
          "measured by the associated sensor. Range 1, 2 or both "
          "can be specified using the values 2, 3 or 4, "
          "respectively." ), 
       ValueMap { "0", "1", "2", "3", "4" }, 
       Values { "Unknown", "Other", "Range 1", "Range 2", 
          "Both Range 1 and 2" }]
   uint16 MonitoringRange;


};
