// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DoorAccessToPhysicalElement 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::UserDevices" ), 
    Description ( 
       "Doors provide access to PhysicalElements for hot swap, repair "
       "and similar activities. The entities accessed through a Door "
       "are indicated in this relationship." )]
class CIM_DoorAccessToPhysicalElement : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Door that provides access." )]
   CIM_Door REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The PhysicalElement that is accessed." )]
   CIM_PhysicalElement REF Dependent;


};
