// Copyright (c) 2010 DMTF.  All rights reserved.
   [Version ( "2.27.0" ), 
    UMLPackagePath ( "CIM::Device::CoolingAndPower" ), 
    Description ( 
       "This class is a representation of logical properties of a "
       "generic power source. Any logical device that has an aspect of "
       "producing power and thus effectively being a power source may "
       "be represented by this class or the subclass of this class." )]
class CIM_PowerSource : CIM_LogicalDevice {

      [Description ( 
          "Indicates the maximum amount of power that may be drawn "
          "within the rating of the PowerSource. The units of the "
          "value shall be described by the OutputPowerUnits "
          "property. A value of zero shall indicate \'unknown\'." ), 
       ModelCorrespondence { "CIM_PowerSource.OutputPowerUnits" }]
   uint32 RatedMaxOutputPower;

      [Description ( 
          "Indicates the programatic units for the MaxOutputPower property."
           ), 
       ModelCorrespondence { "CIM_PowerSource.RatedMaxOutputPower" }, 
       ISPunit]
   string OutputPowerUnits;

      [Description ( 
          "A value of true shall indicate the output from the "
          "PowerSource is alternating current (AC). A value of "
          "false shall indicate the output from the PowerSource is "
          "direct current (DC)." )]
   boolean IsACOutput;


};
