// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00752.000" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_NetworkPortStatistics
// ==================================================================
   [Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "The NetworkPortStatistics class describes the statistics for "
       "the NetworkPort." )]
class CIM_NetworkPortStatistics : CIM_StatisticalData {

      [Description ( 
          "The total number of bytes that are transmitted, "
          "including framing characters." ), 
       Units ( "Bytes" ), 
       Counter, MappingStrings { "MIB.IETF|MIB-II.ifOutOctets", 
          "MIF.DMTF|Network Adapter 802 Port|001.7" }, 
       PUnit ( "byte" )]
   uint64 BytesTransmitted;

      [Description ( 
          "The total number of bytes that are received, including "
          "framing characters." ), 
       Units ( "Bytes" ), 
       Counter, MappingStrings { "MIB.IETF|MIB-II.ifInOctets", 
          "MIF.DMTF|Network Adapter 802 Port|001.9" }, 
       PUnit ( "byte" )]
   uint64 BytesReceived;

      [Description ( 
          "The total number of packets that are transmitted." ), 
       Counter]
   uint64 PacketsTransmitted;

      [Description ( 
          "The total number of packets that are received." ), 
       Counter]
   uint64 PacketsReceived;


};
