TOP = ..
include $(TOP)/config.mak

LIBRARY = sock

SOURCES = \
    dummy.c

INCLUDES = $(TOP) $(TOP)/common

DEFINES = MI_CONST= HOOK_BUILD

PKGCONFIGPACKAGES = openssl

LIBRARIES = base

include $(TOP)/mak/rules.mak
