// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PrecedenceService 
// ==================================================================
   [Deprecated { "CIM_QoSService" }, 
    Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "This class represents a specialization of the general concept "
       "of forwarding network traffic by adding specific semantics "
       "that define how traffic is forwarded based on the value of the "
       "ToS byte of a packet. \n"
       "\n"
       "This class is used to enable DiffServ devices and non- "
       "DiffServ devices to exchange traffic. This is done by defining "
       "a sibling class, DiffServService, to represent devices that "
       "forward traffic based on the DiffServ code point. This enables "
       "the administrator to define mappings between devices that do "
       "not support DiffServ (and instead use IP Precedence) and those "
       "that do support DiffServ. \n"
       "\n"
       "PrecedenceService is deprecated since forwarding based on the "
       "value of the ToS byte is specified using a FilterList, which "
       "is associated with a ClassifierElement. If there is a need to "
       "distinguish a higher-level set of coordinated QoS services, "
       "the QoSService class can be instantiated directly." )]
class CIM_PrecedenceService : CIM_QoSService {

      [Deprecated { "CIM_IPHeadersFilter.HdrDSCP" }, 
       Description ( 
          "This property is an 8-bit unsigned integer that defines "
          "the notion of precedence for different types of traffic." )]
   uint8 PrecedenceValue;


};
