// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_QoSConditioningSubService 
// ==================================================================
   [Association, Aggregation, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "A QoSService utilizes underlying ConditioningServices as part "
       "of its overall functionality. This is modeled using the "
       "QoSConditioningSubService association. Note that a "
       "ConditioningService may only be part of a single QoSService - "
       "the cardinality on the QoSService reference is Max (1)." )]
class CIM_QoSConditioningSubService : CIM_ServiceComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "This aggregation identifies the set of "
          "ConditioningServices that together condition traffic for "
          "a particular QoSService." )]
   CIM_QoSService REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "The ConditioningService." )]
   CIM_ConditioningService REF PartComponent;


};
