// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostedBGPAttributes 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::BGP" ), 
    Description ( 
       "The class BGPAttributes is weak to the AutonomousSystem that "
       "contains it. This association formalizes that relationship." )]
class CIM_HostedBGPAttributes : CIM_HostedDependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The AutonomousSystem that scopes the BGP attributes." )]
   CIM_AutonomousSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Weak, Description ( 
          "The BGP attributes defined in the context of the AutonomousSystem."
           )]
   CIM_BGPAttributes REF Dependent;


};
