// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_QoSSubService 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "The associations - QoSSubService and QoSConditioningSub "
       "Service - operate in conjunction. High level QoS definitions, "
       "such as \'John gets Gold Service\', map to lower level, more "
       "concrete QoSServices (the subclasses of QoSService). This is "
       "described by the QoSSubService association. In turn, each of "
       "the SubServices may require their own conditioning. This is "
       "modeled using the QoSConditioningSubService aggregation. \n"
       "\n"
       "Note that a more concrete QoSService may only be aggregated "
       "into one higher level Service, using this association. The "
       "cardinality on the GroupComponent reference is Max (1)." )]
class CIM_QoSSubService : CIM_ServiceComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( 
          "The higher level QoSService that is constructed by "
          "aggregating one or more lower-level QoSServices." )]
   CIM_QoSService REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The more concrete QoSService that is used to provide the "
          "higher level Service." )]
   CIM_QoSService REF PartComponent;


};
