// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_Priority8021QMarkerService 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "Priority8021QMarkerService marks the Priority field in an "
       "802.1Q- compliant frame, with a specified value. Frames are "
       "marked in order to control the conditioning that they will "
       "subsequently receive. Following common practice, the value to "
       "be written into the field is represented as an unsigned 8-bit "
       "integer." )]
class CIM_Priority8021QMarkerService : CIM_MarkerService {

      [Description ( 
          "This property is an unsigned 8-bit integer, representing "
          "a value to be used for marking the Priority field in the "
          "802.1Q header. Since the Priority field consists of 3 "
          "bits, the values for this property are limited to the "
          "range 0..7. When the Priority field is marked, the "
          "remaining two bits in the octet are left unchanged." ), 
       MinValue ( 0 ), 
       MaxValue ( 7 )]
   uint8 PriorityValue;


};
