// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PacketSchedulingService 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "This class represents the scheduling service, which is a "
       "process that determines whether a queued packet should be "
       "removed from a queue and sent to an output interface. Note "
       "that output interfaces can be physical network interfaces or "
       "interfaces to components internal to systems, such as "
       "crossbars or backplanes. In either case, if multiple queues "
       "are involved, schedulers are used to provide access to the "
       "interface. Each instance of a PacketSchedulingService "
       "describes a scheduler from the perspective of the queues that "
       "the scheduler is servicing. One can describe that different "
       "schedulers support different queues, or that a scheduler "
       "supports several queues. \n"
       "\n"
       "PacketSchedulingService is modeled as a ConditioningService so "
       "that it can be aggregated into a QoSService (using the "
       "QoSConditioningSubService association) to indicate that its "
       "functionality underlies that QoS service. It participates in "
       "the NextService association to identify a subsequent "
       "ConditioningService, if any, that acts on traffic after it has "
       "been processed by the scheduler." )]
class CIM_PacketSchedulingService : CIM_ConditioningService {

      [Description ( 
          "This property is an enumerated 16-bit unsigned integer, "
          "and defines the type of scheduler. Values are: \n"
          "1: Other \n"
          "2: FIFO \n"
          "3: Priority \n"
          "4: Allocation \n"
          "5: Bounded Priority \n"
          "6: Weighted Round Robin Packet \n"
          "If no value is specified, 2 (\"FIFO\") should be "
          "assumed." ), 
       ValueMap { "1", "2", "3", "4", "5", "6" }, 
       Values { "Other", "FIFO", "Priority", "Allocation", 
          "Bounded Priority", "Weighted Round Robin Packet" }, 
       ModelCorrespondence { 
          "CIM_PacketSchedulingService.OtherSchedulerType" }]
   uint16 SchedulerType;

      [Description ( 
          "This string property is used in conjunction with the "
          "SchedulerType property. When the value of SchedulerType "
          "is 1 (i.e., \"Other\"), then the type of scheduler to be "
          "used is defined in this attribute." ), 
       ModelCorrespondence { 
          "CIM_PacketSchedulingService.SchedulerType" }]
   string OtherSchedulerType;


};
