// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NetworksInAdminDomain 
// ==================================================================
   [Association, Deprecated { "CIM_HostedCollection" }, 
    Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::Collections" ), 
    Description ( 
       "This association is used to define the set of Logical Networks "
       "contained in an AdminDomain. This has the implied semantics "
       "that this set of LogicalNetworks are all managed by the same "
       "network administrator that manages the domain. \n"
       "\n"
       "Since the LogicalNetwork class is deprecated in lieu of "
       "ConnectivityCollection, this association is no longer "
       "necessary. It is deprecated to the HostedCollection "
       "association, that is inherited by ConnectivityCollection from "
       "its superclass, SystemSpecificCollection." )]
class CIM_NetworksInAdminDomain {

      [Deprecated { "CIM_HostedCollection.Antecedent" }, 
       Key, Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The AdminDomain that hosts the various LogicalNetworks." )]
   CIM_AdminDomain REF Domain;

      [Deprecated { "CIM_HostedCollection.Dependent" }, 
       Key, Weak, Description ( 
          "The LogicalNetworks that are hosted by the AdminDomain." )]
   CIM_LogicalNetwork REF Network;


};
