// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Network::ConsoleProtocols" ), 
    Description ( 
       "A subclass of ProtocolServiceCapabilities that defines the "
       "capabilities of a Telnet Service. An instance of "
       "TelnetCapabilities is associated with the ProtocolService "
       "using ElementCapabilities." )]
class CIM_TelnetCapabilities : CIM_ProtocolServiceCapabilities {

      [Description ( 
          "An array of integers indicating the terminal modes that "
          "the service supports." ), 
       ValueMap { "0", "1", "2", "3", "4..32767", "32768..65535" }, 
       Values { "Unknown", "Other", "VT100", "ANSI", 
          "DMTF Reserved", "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_TelnetCapabilities.OtherSupportedTerminalMode" }]
   uint16 SupportedTerminalModes[];

      [Description ( 
          "If the SupportedTerminalModes property is set to 1, "
          "\"Other\" then free form string providing more "
          "information about supported terminal modes. If not set "
          "to 1, this string has no meaning." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_TelnetCapabilities.SupportedTerminalModes" }]
   string OtherSupportedTerminalMode[];

      [Description ( 
          "An array of integers indicating the Character display "
          "modes supported by the service." ), 
       ValueMap { "0", "1", "2", "3", "4..32767", "32768..65535" }, 
       Values { "Unknown", "Other", "Console", "Stream", 
          "DMTF Reserved", "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_TelnetCapabilities.OtherSupportedCharacterDisplayMode" }]
   uint16 SupportedCharacterDisplayModes[];

      [Description ( 
          "If the SupportedCharacterDisplayModes property is set to "
          "1 \"Other\" then free form string providing more "
          "information about the supported modes. If not set to 1, "
          "this string has no meaning." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_TelnetCapabilities.SupportedCharacterDisplayModes" }]
   string OtherSupportedCharacterDisplayMode[];


};
