// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostedBGPPeerGroup 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::BGP" ), 
    Description ( 
       "A BGPPeerGroup is weak to the AutonomousSystem that contains "
       "it. This association formalizes that relationship." )]
class CIM_HostedBGPPeerGroup : CIM_HostedDependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The AutonomousSystem that scopes the BGP peer group." )]
   CIM_AutonomousSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Weak, Description ( 
          "The BGP peer group defined in the context of the AutonomousSystem."
           )]
   CIM_BGPPeerGroup REF Dependent;


};
