// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_QueueAllocation 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "Describes the reliance of a QueuingService on the availability "
       "of space in a BufferPool." )]
class CIM_QueueAllocation : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The BufferPool supporting packet storage for a QueuingService."
           )]
   CIM_BufferPool REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The QueuingService dependent on the BufferPool for storage space."
           )]
   CIM_QueuingService REF Dependent;

      [Description ( 
          "This property is an 8-bit unsigned integer representing "
          "a percentage from 0 to 100. It defines the percentage of "
          "the BufferPool that should be allocated to the "
          "referenced QueuingService. If absolute sizes are "
          "desired, this is accomplished by defining individual "
          "BufferPools of the specified sizes, with "
          "QueueAllocation.AllocationPercentages set to 100." ), 
       Units ( "Percent" ), 
       MinValue ( 0 ), 
       MaxValue ( 100 )]
   uint8 AllocationPercentage;


};
