// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SchedulingServiceToSchedule 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "This is a top-level association, representing the relationship "
       "between a scheduler (PacketSchedulingService) and a "
       "SchedulingElement, in a configuration involving cascaded "
       "schedulers. The SchedulingElement, in turn, represents the "
       "information in a packet scheduling service that is specific to "
       "this scheduler, such as relative priority or allocated "
       "bandwidth. \n"
       "\n"
       "Although it cannot be expressed formally with the association "
       "cardinalities, there is an additional constraint on "
       "participation in this association. A particular instance of (a "
       "subclass of) SchedulingElement always participates either in "
       "exactly one instance of this association, or in exactly one "
       "instance of the association QueueToSchedule." )]
class CIM_SchedulingServiceToSchedule {

      [Key, Max ( 1 ), 
       Description ( "The scheduler being cascaded." )]
   CIM_PacketSchedulingService REF SchedService;

      [Key, Description ( 
          "A SchedulingElement in the subsequent scheduler." )]
   CIM_SchedulingElement REF SchedElement;


};
