// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_CalculatesAmong 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::RoutingForwarding" ), 
    Description ( 
       "This is a specialization of the ServiceSAPDependency "
       "association, indicating that the referenced ProtocolEndpoint "
       "is utilized by the RouteCalculationService to provide its "
       "functionality." )]
class CIM_CalculatesAmong : CIM_ServiceSAPDependency {

      [Override ( "Antecedent" ), 
       Description ( "The required ProtocolEndpoint." )]
   CIM_ProtocolEndpoint REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The RouteCalculationService, which is dependent on the "
          "underlying ProtocolEndpoint." )]
   CIM_RouteCalculationService REF Dependent;

      [Deprecated { "No value" }, 
       Description ( 
          "TRUE indicates that this ProtocolEndpoint represents a "
          "static route, and FALSE means that it represents a "
          "dynamically-learned route. This property is deprecated "
          "since a Service may use an Endpoint to output several "
          "routes, some static and others dynamic." )]
   boolean IsStatic;


};
