// Copyright (c) 2005 DMTF.  All rights reserved.
   [Deprecated { "No value" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::VLAN" ), 
    Description ( 
       "This class is deprecated following discussion as to the need "
       "of a modeling a 802.1Q as a service. It was determined that a "
       "802.1Q service was not needed. If a switch supports 802.1Q, an "
       "instance of this class should be instantiated in the switch. "
       "If the switch supports GVRP, this class represents the "
       "function that the switch performs with respect to GVRP." )]
class CIM_Specific802dot1QVLANService : CIM_VLANService {


};
