// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AreaOfConfiguration 
// ==================================================================
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::OSPF" ), 
    Description ( 
       "This association connects an area configuration to its area. "
       "The OSPFAreaConfiguration class is defined to act as a focal "
       "point to bring together the router (indicated as a "
       "ComputerSystem with an instance of OSPFService, associated to "
       "the AreaConfiguration using OSPFServiceConfiguration), the "
       "area (indicated as an OSPFArea, associated to the "
       "AreaConfiguration using AreaOfConfiguration) and the address "
       "ranges for advertising (indicated as instances of "
       "RangeOfIPAddresses, associated to the AreaConfiguration using "
       "RangesOfConfiguration). There is an instance of "
       "OSPFAreaConfiguration for each connected area of a "
       "router/OSPFService." )]
class CIM_AreaOfConfiguration : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The OSPF area." )]
   CIM_OSPFArea REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The configuration which is applied to an OSPF area. This "
          "is the Dependent reference in this association, since it "
          "depends on the area for any functional significance." )]
   CIM_OSPFAreaConfiguration REF Dependent;


};
