// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NetworkService 
// ==================================================================
   [Deprecated { "CIM_Service" }, 
    Abstract, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::RoutingForwarding" ), 
    Description ( 
       "This is an abstract base class, derived from the Service "
       "class. It is deprecated in Version 2.7 with the recommendation "
       "that the Service class be subclassed instead. Distinguishing "
       "between services that modify traffic versus supporting basic "
       "communication has not proved useful." )]
class CIM_NetworkService : CIM_Service {

      [Deprecated { "No value" }, 
       Description ( 
          "This is a free-form array of strings that provide "
          "descriptive words and phrases that can be used in "
          "queries. To-date, this property has not been "
          "implemented, since it is not standardized. Also, if this "
          "was a necessary query construct, then it would be "
          "required higher in the inheritance hierarchy. The latter "
          "has not proven necessary. Therefore, the property is "
          "deprecated." )]
   string Keywords[];

      [Deprecated { "CIM_ServiceAccessURI" }, 
       Description ( 
          "This is a URL that provides the protocol, network "
          "location, and other service-specific information "
          "required in order to access the service. It is "
          "deprecated with the recommendation that ServiceAccessURI "
          "be instantiated instead. This new class correctly "
          "positions the semantics of the service access, and "
          "clarifies the format of the information." )]
   string ServiceURL;

      [Deprecated { "No value" }, 
       Description ( 
          "This is a free-form array of strings that specify any "
          "specific pre-conditions that must be met in order for "
          "this service to start correctly. It was expected that "
          "subclasses would refine the inherited StartService() "
          "method to suit their specific needs. To-date, this "
          "refinement has not been necessary. Also, the property is "
          "not very useful, since it is not standardized. If this "
          "was a necessary construct, then it would be required "
          "higher in the inheritance hierarchy (on Service). The "
          "latter has not proven true. Therefore, the property is "
          "deprecated." )]
   string StartupConditions[];

      [Deprecated { "No value" }, 
       Description ( 
          "This is a free-form array of strings that specify any "
          "specific parameters that must be supplied to the "
          "StartService() method in order for this service to start "
          "correctly. It was expected that subclasses would refine "
          "the inherited StartService() methods to suit their "
          "specific needs. To-date, this refinement has not been "
          "necessary. If indeed the method were refined, then its "
          "parameters would more formally convey this information. "
          "Therefore, the property is deprecated." )]
   string StartupParameters[];


};
