// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ClassifierService 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "ClassifierService represents a logical entity associated with "
       "an ingress or egress interface of a device, that takes a "
       "single input stream, and sorts it into one or more output "
       "streams. The sorting is done by a set of filters that select "
       "packets based on the packet contents, or possibly based on "
       "other attributes associated with the packet. Each output "
       "stream is the result of matching a particular filter. \n"
       "\n"
       "Rather than being linked directly to its filters (instantiated "
       "as FilterLists), a classifier is modeled as an aggregation of "
       "ClassifierElements. Each of these ClassifierElements is linked "
       "to a single FilterList, by the association "
       "ClassifierElementUsesFilterList. Note that ClassifierServices "
       "are designed to allow hierarchical classification. When "
       "hierarchical classification is used, a ClassifierElement may "
       "point to another ClassifierService (via the association, "
       "NextServiceAfterClassifierElement). When this is true, the "
       "ClassifierElement MUST NOT use the ClassifierElementUses "
       "FilterList association. \n"
       "\n"
       "A classifier is modeled as a ConditioningService so that it "
       "can be aggregated into a QoSService (using the "
       "QoSConditioningSubService aggregation), and can use the "
       "NextService association to identify the subsequent "
       "ConditioningServices for different traffic streams." )]
class CIM_ClassifierService : CIM_ConditioningService {


};
