// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SwitchPortTransparentBridgingStatistics 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::SwitchingBridging" ), 
    Description ( 
       "Statistical information regarding a SwitchPort, at which "
       "transparent bridging is performed." )]
class CIM_SwitchPortTransparentBridgingStatistics : CIM_SAPStatisticalInformation {

      [Description ( 
          "The number of frames that have been received by the port "
          "from its segment. Note that a frame is only counted if "
          "and only if it is for a protocol being processed by the "
          "local bridging function, including bridge management "
          "frames." ), 
       Counter, MappingStrings { 
          "MIB.IETF|BRIDGE-MIB.dot1dTpPortInFrames" }]
   uint32 InFrames;

      [Description ( 
          "The number of frames that have been transmitted by the "
          "port to its segment. Note that a frame is only counted "
          "if and only if it is for a protocol being processed by "
          "the local bridging function, including bridge management "
          "frames." ), 
       Counter, MappingStrings { 
          "MIB.IETF|BRIDGE-MIB.dot1dTpPortOutFrames" }]
   uint32 OutFrames;

      [Description ( 
          "Count of valid frames received which were discarded "
          "(i.e., filtered) by the forwarding process." ), 
       Counter, MappingStrings { 
          "MIB.IETF|BRIDGE-MIB.dot1dTpPortInDiscards" }]
   uint32 InDiscards;


};
