// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ClassifierFilterSet 
// ==================================================================
   [Association, Deprecated { "CIM_ClassifierElementUsesFilterList", 
       "CIM_ClassifierElementInClassifierService" }, 
    Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "In order for a ClassifierService to correctly identify and "
       "process network traffic, that traffic must be described by "
       "FilterEntries, which are aggregated into FilterLists. This "
       "association defines the Dependency of the ClassifierService on "
       "FilterLists (and therefore, their FilterEntries). The "
       "cardinality of the association requires that the Classifier "
       "Service operate against at least one FilterList. \n"
       "\n"
       "The association is deprecated in lieu of associating Filter "
       "Lists to ClassifierElements, and ClassifierElements into "
       "ClassifierServices. The latter approach is very flexible "
       "regarding the implementations that can be modeled, and removes "
       "the need to track individual traffic streams using an "
       "artificial model property, TrafficClass. Using "
       "ClassifierElements, each stream is processed beginning with a "
       "single FilterList and progressing through various "
       "ConditioningServices, associated via instances of NextService." )]
class CIM_ClassifierFilterSet : CIM_Dependency {

      [Deprecated { "CIM_ClassifierElementUsesFilterList.Antecedent" }, 
       Override ( "Antecedent" ), 
       Description ( 
          "The FilterList aggregating FilterEntries, these in turn "
          "describe how traffic is identified and processed by the "
          "ClassifierService." )]
   CIM_FilterList REF Antecedent;

      [Deprecated { "CIM_ClassifierElementUsesFilterList.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "The ClassifierService which uses the FilterList and its "
          "aggregated FilterEntries." )]
   CIM_ClassifierService REF Dependent;

      [Deprecated { 
          "CIM_ClassifierElementInClassifierService.ClassifierOrder" }, 
       Description ( 
          "The ordering of the FilterLists used in the "
          "classification and forwarding functions of the "
          "ClassifierService." )]
   uint16 FilterListPosition;


};
