// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_InLogicalNetwork 
// ==================================================================
   [Association, Deprecated { "CIM_MemberOfCollection" }, 
    Aggregation, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::Collections" ), 
    Description ( 
       "This association defines a ProtocolEndpoint as a member of a "
       "specific LogicalNetwork. \n"
       "\n"
       "Since the LogicalNetwork class is deprecated in lieu of "
       "ConnectivityCollection, this association is no longer "
       "necessary. It is deprecated to the MemberOfCollection "
       "association, that is inherited by ConnectivityCollection from "
       "its superclass, Collection." )]
class CIM_InLogicalNetwork : CIM_CollectedMSEs {

      [Deprecated { "CIM_MemberOfCollection.Collection" }, 
       Aggregate, Override ( "Collection" ), 
       Description ( 
          "The LogicalNetwork that groups the ProtocolEndpoint instances."
           )]
   CIM_LogicalNetwork REF Collection;

      [Deprecated { "CIM_MemberOfCollection.Member" }, 
       Override ( "Member" ), 
       Description ( 
          "The child ProtocolEndpoints that are components of the "
          "LogicalNetwork." )]
   CIM_ProtocolEndpoint REF Member;


};
