// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01484.000" type ="change"> Correct ValueMaps for ProtocolIfType</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_IPXProtocolEndpoint 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::ProtocolEndpoints" ), 
    Description ( 
       "An IPX communication point from which data may be sent or received."
        )]
class CIM_IPXProtocolEndpoint : CIM_ProtocolEndpoint {

      [Description ( 
          "An IPX address formatted as eight hexadecimal digits "
          "representing the network number, followed by a colon, "
          "followed by twelve hexadecimal digits representing the "
          "host address (e.g. \"00112233:010203040506\")." )]
   string Address;

      [Override ( "ProtocolIFType" ), 
       Description ( 
          "ProtocolIFType\'s enumeration is limited to IPX and "
          "reserved values for this subclass of ProtocolEndpoint." ), 
       ValueMap { "1", "225..4095", "4099", "4301..32767", "32768.." }, 
       Values { "Other", "IANA Reserved", "IPX", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 ProtocolIFType = 4099;


};
