// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_IPConnectivitySubnet 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::Collections" ), 
    Description ( 
       "An IPConnectivitySubnet represents a group of related "
       "IPProtocolEndpoints that can communicate with each other, as "
       "members of a subnet. The class describes the characteristics "
       "of the subnet." )]
class CIM_IPConnectivitySubnet : CIM_ConnectivityCollection {

      [Description ( 
          "The IP address of the entire subnet, formatted according "
          "to the appropriate convention as defined in the "
          "AddressType property of this class." ), 
       ModelCorrespondence { "CIM_IPConnectivitySubnet.AddressType" }]
   string SubnetNumber;

      [Description ( 
          "The mask for the starting IPv4 address of the IP subnet, "
          "if needed (i.e., if the AddressType property is 1, "
          "\"IPv4\")." )]
   string SubnetMask;

      [Description ( 
          "The prefix length for IPv6 addresses in the IP subnet, "
          "if needed (i.e., if the AddressType property is 2, "
          "\"IPv6\")." )]
   uint8 PrefixLength;

      [Description ( 
          "An enumeration that describes the format of the address "
          "properties in IPConnectivitySubnet." ), 
       ValueMap { "0", "1", "2" }, 
       Values { "Unknown", "IPv4", "IPv6" }]
   uint16 AddressType;


};
