// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01484.000" type ="change"> Correct ValueMaps for ProtocolIfType</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_OSPFProtocolEndpointBase 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Network::ProtocolEndpoints" ), 
    Description ( 
       "Base class for OSPF protocol endpoints, defining several "
       "general properties." )]
class CIM_OSPFProtocolEndpointBase : CIM_ProtocolEndpoint {

      [Override ( "EnabledState" ), 
       Description ( 
          "The operational status of the interface, see "
          "ospfIfAdminStat in RFC 1850. This is an integer "
          "enumeration whose complete definition is found in the "
          "EnabledLogicalElement class." ), 
       MappingStrings { "MIB.IETF|OSPF-MIB.ospfIfAdminStat" }]
   uint16 EnabledState;

      [Description ( 
          "Estimated delay, in seconds that it takes to transmit a "
          "Link State Update Packet over this interface, see C.3 in "
          "RFC 2328." ), 
       Units ( "Seconds" ), 
       MappingStrings { "MIB.IETF|OSPF-MIB.ospfIfTransitDelay" }]
   uint16 TransitDelay;

      [Description ( 
          "The number of seconds between LSA (Link State "
          "Advertisement) retransmissions, see C.3 in RFC 2328." ), 
       Units ( "Seconds" ), 
       MappingStrings { "MIB.IETF|OSPF-MIB.ospfIfRetransInterval" }]
   uint16 RetransmitInterval;

      [Required, Description ( 
          "Identifies the authentication procedure to be used on "
          "the attached network, see C.3 in RFC 2328." ), 
       ValueMap { "1", "2", "3", "4" }, 
       Values { "Other", "Null authentication", "Simple password", 
          "Cryptographic authentication" }, 
       MappingStrings { "MIB.IETF|OSPF-MIB.ospfIfAuthType" }]
   uint16 AuthType;

      [Description ( 
          "Specifies the authentication procedure if the value, "
          "\"Other\" (1) is set for AuthType." ), 
       ModelCorrespondence { "CIM_OSPFProtocolEndpoint.AuthType" }]
   string OtherAuthType;

      [Description ( 
          "This key is used during the authentication procedure to "
          "verify OSPF protocol packets, see C.3 RFC 2328. It is "
          "used in the \"Simple password\" and in the "
          "\"Cryptographic authentication\" case too." ), 
       MappingStrings { "MIB.IETF|OSPF-MIB.ospfIfAuthKey" }]
   string AuthKey;

      [Override ( "ProtocolIFType" ), 
       Description ( 
          "ProtocolIFType\'s enumeration is limited to OSPF and "
          "reserved values for this subclass of ProtocolEndpoint." ), 
       ValueMap { "1", "225..4095", "4109", "4301..32767", "32768.." }, 
       Values { "Other", "IANA Reserved", "OSPF", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 ProtocolIFType = 4109;


};
