// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostedRoutingServices 
// ==================================================================
   [Association, Deprecated { "CIM_HostedService" }, 
    Version ( "2.7.1" ), 
    UMLPackagePath ( "CIM::Network::RoutingForwarding" ), 
    Description ( 
       "This is a specialization of CIM_HostedService, which is an "
       "association between a Service and the System on which the "
       "functionality resides. The class, HostedRoutingServices, is "
       "deprecated since it provides no additional semantics over "
       "HostedService, and unnecessarily restricts the Service to a "
       "single ComputerSystem, when the Service could reside in a "
       "Network or other higher level System." )]
class CIM_HostedRoutingServices : CIM_HostedService {

      [Deprecated { "CIM_HostedService.Antecedent" }, 
       Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The hosting router." )]
   CIM_ComputerSystem REF Antecedent;

      [Deprecated { "CIM_HostedService.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( "The Service hosted on the System." )]
   CIM_RouteCalculationService REF Dependent;


};
