// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SchedulerUsed 
// ==================================================================
   [Association, Deprecated { "CIM_QueueToSchedule", 
       "CIM_SchedulingServiceToSchedule" }, 
    Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "In order to remove queued packets, a process or Service "
       "(identified as a PacketSchedulingService) runs. This "
       "association describes the Dependency of the queue and its "
       "QueuingService on a SchedulingService, which empties it. \n"
       "\n"
       "The association is deprecated in lieu of associating Queuing "
       "Services to SchedulingElements, and SchedulingElements into "
       "SchedulingServices. The latter approach is very flexible "
       "regarding the implementations that can be modeled, and removes "
       "the need to track individual traffic streams using an "
       "artificial model property, TrafficClass." )]
class CIM_SchedulerUsed : CIM_ServiceServiceDependency {

      [Deprecated { "CIM_QueueToSchedule.Queue" }, 
       Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The PacketSchedulingService which empties the Queuing "
          "Service\'s queue." )]
   CIM_PacketSchedulingService REF Antecedent;

      [Deprecated { "CIM_QueueToSchedule.SchedElement" }, 
       Override ( "Dependent" ), 
       Description ( 
          "The queue and its QueuingService from which packets are emptied."
           )]
   CIM_QueuingService REF Dependent;


};
