// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_BGPRouteMapsInRoutingPolicy 
// ==================================================================
   [Association, Aggregation, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::BGP" ), 
    Description ( 
       "This aggregation defines the BGPRouteMaps that are used by a "
       "particular RoutingPolicy object. Multiple instances of the "
       "same RouteMap may be used in the same RoutingPolicy instance. "
       "If this is desired, then the Sequence attribute of this "
       "aggregation can be used to disambiguate them." )]
class CIM_BGPRouteMapsInRoutingPolicy : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "The RoutingPolicy that aggregates the RouteMaps." )]
   CIM_RoutingPolicy REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The RouteMaps that are used by the RoutingPolicy." )]
   CIM_BGPRouteMap REF PartComponent;

      [Description ( 
          "This defines the position of this RouteMap instance "
          "relative to all other instances of the same RouteMap." )]
   uint16 MapSequence;


};
