TOP = ../..
include $(TOP)/config.mak

CXXPROGRAM = dos2unix

SOURCES = dos2unix.cpp 

INCLUDES = $(TOP) $(TOP)/common

MAKEDEPSRCDIR=1

SUPPRESS_CCTOOL=1

SUPPRESS_STDERRX=1

include $(TOP)/mak/rules.mak
