// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::IPsecPolicy" ), 
    Description ( 
       "Subclasses of PreconfiguredSAAction are used to create SAs "
       "using preconfigured, hard-wired algorithms and keys. No "
       "negotiation is necessary. Note that this class is defined as "
       "concrete, since its superclass is also concrete. However, it "
       "should not be directly instantiated, but one of its subclasses "
       "used instead. \n"
       "\n"
       "Also note that: \n"
       "- The SPI for a preconfigured SA action is contained in the "
       "association, TransformOfPreconfiguredAction. \n"
       "- The session key (if applicable) is contained in an instance "
       "of SharedSecret. For an instance of the SharedSecret class: "
       "The session key is stored in the Secret property; the property "
       "protocol contains one of the values, \"ESP-encrypt\", "
       "\"ESP-auth\" or \"AH\"; and, the class\' property algorithm "
       "contains the algorithm used to protect the secret. (The latter "
       "can be \"PLAINTEXT\" if the IPsec entity has no secret "
       "storage.) The value of the class\' RemoteID property is the "
       "concatenation of the remote IPsec peer IP address in dotted "
       "decimal, of the character \"/\", of \"IN\" (or respectively "
       "\"OUT\") for inbound/outbound SAs, of the character \"/\" and "
       "of the hexadecimal representation of the SPI." ), 
    MappingStrings { "IPSP Policy Model.IETF|PreconfiguredSAAction" }]
class CIM_PreconfiguredSAAction : CIM_SAStaticAction {

      [Description ( 
          "LifetimeKilobytes defines a traffic limit in kilobytes "
          "that can be consumed before the SA is deleted. A value "
          "of zero (the default) indicates that there is no "
          "lifetime associated with this action (i.e., infinite "
          "lifetime). A non-zero value is used to indicate that "
          "after this number of kilobytes has been consumed the SA "
          "must be deleted. \n"
          "\n"
          "Note that the actual lifetime of the preconfigured SA "
          "will be the lesser of the value of this "
          "LifetimeKilobytes property and the value of the "
          "MaxLifetimeKilobytes property of the associated "
          "SATransform. Also note that some SA negotiation "
          "protocols (such as IKE) can negotiate the lifetime as an "
          "arbitrary length field, it is assumed that a 64-bit "
          "integer will be sufficient." ), 
       Units ( "KiloBytes" ), 
       MappingStrings { 
          "IPSP Policy Model.IETF|PreconfiguredSAAction.LifetimeKilobytes" }, 
       ModelCorrespondence { 
          "CIM_SecurityAssociationEndpoint.LifetimeKilobytes" }, 
       PUnit ( "byte * 10^3" )]
   uint64 LifetimeKilobytes;


};
