// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Aggregation, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::IPsecPolicy" ), 
    Description ( 
       "PacketConditionInSARule aggregates an SARule with at least one "
       "instance of PacketFilterCondition. This is a specialization of "
       "the PolicyConditionInPolicyRule association." ), 
    MappingStrings { "IPSP Policy Model.IETF|SAConditionInRule" }]
class CIM_PacketConditionInSARule : CIM_PolicyConditionInPolicyRule {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( "An SARule subclass of PolicyRule." ), 
       MappingStrings { 
          "IPSP Policy Model.IETF|SAConditionInRule.GroupComponent" }]
   CIM_SARule REF GroupComponent;

      [Override ( "PartComponent" ), 
       Min ( 1 ), 
       Description ( 
          "An SACondition that is required for the SARule." ), 
       MappingStrings { 
          "IPSP Policy Model.IETF|SAConditionInRule.PartComponent" }]
   CIM_PacketFilterCondition REF PartComponent;


};
