TOP = ../..
include $(TOP)/config.mak

CXXPROGRAM = printxml

SOURCES = printxml.cpp

INCLUDES = $(TOP) $(TOP)/common

LIBRARIES = xml base $(PALLIBS)
ARGUMENTS = cimns.xml

include $(TOP)/mak/rules.mak
