TOP = ../..

include $(TOP)/config.mak

CXXSHLIBRARY = wqlcxx

SOURCES = wqlcxx.cpp

INCLUDES = $(TOP) $(TOP)/common

LIBRARIES = wql base pal

DEFINES = BUILDING_WQLCXX

include $(TOP)/mak/rules.mak
