// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00752.000" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ConnectionBasedModem
// ==================================================================
   [Abstract, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Modems" ), 
    Description ( 
       "CIM_ConnectionBasedModem is the superclass for grouping the "
       "numerous types of connection-based Modems. A CableModem is a "
       "type of connection-based Modem." )]
class CIM_ConnectionBasedModem : CIM_Modem {

      [Description ( 
          "VendorID information is reported through Modem-specific "
          "requests. For example, for ADSLModem Devices, the "
          "VendorID is assigned by T1E1.4 according to T1.413, "
          "Appendix D. The correct place in the CIM Schema for this "
          "information is in PhysicalElement (the Manufacturer "
          "property) for hardware and Product (the Vendor property) "
          "if the information is related to Product acquisition. "
          "This data is also reported here because it is part of "
          "the standard output from the Device and is an "
          "optimization." )]
   string VendorID;


};
