// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00735.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ErrorCountersForDevice
// ==================================================================
   [Association, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::DeviceElements" ), 
    Description ( 
       "ErrorCountersForDevice relates the DeviceErrorCounts class to "
       "the LogicalDevice to which it applies." )]
class CIM_ErrorCountersForDevice : CIM_Statistics {

      [Override ( "Stats" ), 
       Weak, Description ( 
          "The statistical object, in this case, the error counter class."
           )]
   CIM_DeviceErrorCounts REF Stats;

      [Override ( "Element" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The Device to which the error counters apply." )]
   CIM_LogicalDevice REF Element;


};
