// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PickerStatData 
// ==================================================================
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Device::StorageLib" ), 
    Description ( 
       "Statistics for a PickerElement, related to pick/put successes, "
       "retries and failures. The element whose statistics are "
       "described is associated using the relationship, "
       "ElementStatisticalData." )]
class CIM_PickerStatData : CIM_StatisticalData {

      [Description ( "The number of successful picks." ), 
       Counter]
   uint64 PickSuccesses;

      [Description ( "The number of failed picks." ), 
       Counter]
   uint64 PickFailures;

      [Description ( "The number of retried picks." ), 
       Counter]
   uint64 PickRetries;

      [Description ( "The number of successful puts." ), 
       Counter]
   uint64 PutSuccesses;

      [Description ( "The number of failed puts." ), 
       Counter]
   uint64 PutFailures;

      [Description ( "The number of retried puts." ), 
       Counter]
   uint64 PutRetries;


};
