// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00735.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ParallelController
// ==================================================================
   [Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Controller" ), 
    Description ( 
       "Capabilities and management of the ParallelController." )]
class CIM_ParallelController : CIM_Controller {

      [Description ( 
          "Set to true if the ParallelController supports DMA." ), 
       MappingStrings { "MIF.DMTF|Parallel Ports|003.7" }]
   boolean DMASupport;

      [Description ( 
          "An integer enumeration that indicates the capabilities "
          "of the ParallelController." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8" }, 
       Values { "Unknown", "Other", "XT/AT Compatible", 
          "PS/2 Compatible", "ECP", "EPP", "PC-98", "PC-98-Hireso", 
          "PC-H98" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { "MIF.DMTF|Parallel Ports|003.8" }, 
       ModelCorrespondence { 
          "CIM_ParallelController.CapabilityDescriptions" }]
   uint16 Capabilities[];

      [Description ( 
          "An array of free-form strings that provides more "
          "detailed explanations for any of the ParallelController "
          "features that are indicated in the Capabilities array. "
          "Note, each entry of this array is related to the entry "
          "in the Capabilities array that is located at the same "
          "index." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_ParallelController.Capabilities" }]
   string CapabilityDescriptions[];

      [Description ( 
          "An enumeration that indicates the operational security "
          "for the Controller. For example, information that the "
          "external interface of the Device is locked out (value=4) "
          "or \"Boot Bypass\" (value=6) can be described using this "
          "property." ), 
       ValueMap { "1", "2", "3", "4", "5", "6" }, 
       Values { "Other", "Unknown", "None", 
          "External Interface Locked Out", 
          "External Interface Enabled", "Boot Bypass" }, 
       MappingStrings { "MIF.DMTF|Parallel Ports|003.10" }]
   uint16 Security;


};
