// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "This association define StorageSettings that reflect the "
       "capabilities of the associated StorageCapabilities. The "
       "associated StorageSetting may not define the operational "
       "characteristics (through settings properties) of any storage "
       "element. Certain StorageSetting instances can be defined as "
       "\"Fixed = Not Changeable\" by using the \"ChangeableType\" "
       "attribute. \"Fixed\" settings have this special association. "
       "This association should be defined between \"Fixed - Not "
       "Changeable\" instances of StorageSetting with the "
       "StorageCapabilities instances that are associated with the "
       "StoragePools which support the storage characteristics "
       "described by the StorageSetting instance. \n"
       "Fixed settings may be associated to many StorageCapabilities." )]
class CIM_StorageSettingsAssociatedToCapabilities : CIM_SettingAssociatedToCapabilities {

      [Override ( "Antecedent" ), 
       Description ( "The StorageCapabilities." )]
   CIM_StorageCapabilities REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The fixed and predefined StorageSetting." )]
   CIM_StorageSetting REF Dependent;


};
