// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_DesktopMonitor 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::UserDevices" ), 
    Description ( 
       "Capabilities and management of the DesktopMonitor (CRT) "
       "LogicalDevice." )]
class CIM_DesktopMonitor : CIM_Display {

      [Description ( 
          "The type of DesktopMonitor or CRT. For example, "
          "multiscan color or monochrome monitors (values 2 or 3, "
          "respectively) can be indicated in this property." ), 
       ValueMap { "0", "1", "2", "3", "4", "5" }, 
       Values { "Unknown", "Other", "Multiscan Color", 
          "Multiscan Monochrome", "Fixed Frequency Color", 
          "Fixed Frequency Monochrome" }]
   uint16 DisplayType;

      [Description ( 
          "Monitor\'s bandwidth in MHertz. If unknown, enter 0." ), 
       Units ( "MegaHertz" ), 
       PUnit ( "hertz * 10^6" )]
   uint32 Bandwidth;

      [Description ( 
          "The logical height of the Display in screen coordinates." )]
   uint32 ScreenHeight;

      [Description ( 
          "The logical width of the Display in screen coordinates." )]
   uint32 ScreenWidth;


};
