// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RealizesAggregatePExtent 
// ==================================================================
   [Association, Deprecated { "CIM_RealizesExtent" }, 
    Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Device::SccExtents" ), 
    Description ( 
       "AggregatePExtents are realized on a PhysicalMedia. This is "
       "described by RealizesAggregatePExtent. However, there is no "
       "need for the specificity of this association. It is deprecated "
       "in lieu of the generic RealizesExtent relationship." )]
class CIM_RealizesAggregatePExtent : CIM_RealizesExtent {

      [Deprecated { "CIM_RealizesExtent.Antecedent" }, 
       Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The PhysicalMedia on which the Extent is realized." )]
   CIM_PhysicalMedia REF Antecedent;

      [Deprecated { "CIM_RealizesExtent.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "The AggregatePExtent that is located on the Media." )]
   CIM_AggregatePExtent REF Dependent;


};
