// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00752.000" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="CIMCoreCR00858" type ="change'>Update the
// the properties MappingStrings.</
// ==================================================================
//  CIM_PrintSAP
// ==================================================================
   [Version ( "2.14.0" ), 
    UMLPackagePath ( "CIM::Device::Printing" ), 
    Description ( "The ServiceAccessPoint for a printing Service." )]
class CIM_PrintSAP : CIM_ServiceAccessPoint {

      [Description ( 
          "Specifies the print procotols that this AccessPoint "
          "uses. Note, each entry of this array is related to the "
          "entry in the PrintProtocolInfo array that is located at "
          "the same index." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7" }, 
       Values { "Unknown", "Other", "SMB", "BSD", "SYSV", "HPNP", 
          "IPP", "Local" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "MIB.IETF|IANA-PRINTER-MIB.PrtChannelInformation", 
          "MIB.IETF|Printer-MIB.prtChannelType" }, 
       ModelCorrespondence { "CIM_PrintSAP.PrintProtocolInfo" }]
   uint16 PrintProtocol[];

      [Description ( 
          "Provides clarifying or additional information about the "
          "protocols that are supported by this AccessPoint. Note, "
          "each entry of this array is related to the entry in the "
          "PrintProtocol array that is located at the same index." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "MIB.IETF|IANA-PRINTER-MIB.PrtChannelInformation", 
          "MIB.IETF|Printer-MIB.prtChannelType" }, 
       ModelCorrespondence { "CIM_PrintSAP.PrintProtocol" }]
   string PrintProtocolInfo[];


};
