// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00735.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="CIMCoreCR00734.006" type ="deprecate">Deprecate class.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_VideoSetting
// ==================================================================
   [Association, Deprecated { "CIM_ElementSetting" }, 
    Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Controller" ), 
    Description ( 
       "Note: The use of the CIM_VideoSetting class has been "
       "deprecated in lieu of CIM_ElementSetting. \n"
       "Deprecated description: \n"
       "VideoSetting associates the VideoControllerResolution Setting "
       "with the Controllers to which it applies." )]
class CIM_VideoSetting : CIM_ElementSetting {

      [Deprecated { "CIM_ElementSetting.Element" }, 
       Override ( "Element" ), 
       Description ( "The VideoController." )]
   CIM_VideoController REF Element;

      [Deprecated { "CIM_ElementSetting.Setting" }, 
       Override ( "Setting" ), 
       Description ( 
          "The resolutions, refresh rates, scan mode, and number of "
          "colors that can be set for the Controller." )]
   CIM_VideoControllerResolution REF Setting;


};
