// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00736.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_FCPortRateStatistics
// ==================================================================
   [Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::FC" ), 
    Description ( 
       "FCPortRateStatistics is the performance rate for the FCPort. "
       "The Frame and Byte rates report the average of a counter "
       "change per second and the maximum counter change per second "
       "over a specified interval, the SampleInterval, which is "
       "defined in the parent class, StatisticalData." )]
class CIM_FCPortRateStatistics : CIM_StatisticalData {

      [Description ( 
          "TxFrameRate is the instantaneous transmit frame rate." ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1.SWAPI_STATS_LBL_TFRR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 TxFrameRate;

      [Description ( 
          "RxFrameRate is the instantaneous receive frame rate." ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1.SWAPI_STATS_LBL_RFRR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 RxFrameRate;

      [Description ( 
          "MaxTxFrameRate is the maximum transmit frame rate achieved."
           ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1.SWAPI_STATS_LBL_TFPR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 MaxTxFrameRate;

      [Description ( 
          "MaxRxFrameRate is the maximum receive frame rate achieved."
           ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1.SWAPI_STATS_LBL_RFPR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 MaxRxFrameRate;

      [Description ( 
          "TxRate is the instantaneous transmit byte rate." ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1. SWAPI_STATS_LBL_TBYR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 TxRate;

      [Description ( 
          "RxRate is the instantaneous receive byte rate." ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1.SWAPI_STATS_LBL_RBYR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 RxRate;

      [Description ( 
          "PeakTxRate is the maximum transmit byte rate achieved." ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1. SWAPI_STATS_LBL_TBPR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 PeakTxRate;

      [Description ( 
          "PeakRxRate is the maximum receive byte rate achieved." ), 
       MappingStrings { 
          "FC-SWAPI.T11|PerformanceRates|1. SWAPI_STATS_LBL_RBPR" }, 
       ModelCorrespondence { "CIM_StatisticalData.SampleInterval" }]
   uint64 PeakRxRate;


};
