// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "A LogicalPort may be configured via the LogicalPortSettings "
       "class. The configuration changes are expected to be stored to "
       "non-volatile memory." )]
class CIM_LogicalPortSettings : CIM_SettingData {

      [Write, Description ( 
          "The requested bandwidth of the Port in Bits per Second. "
          "The actual bandwidth is reported in LogicalPort.Speed." ), 
       Units ( "Bits per Second" ), 
       MappingStrings { 
          "FC-SWAPI.INCITS-T11|UcPortConfigSetLinkSpeed" }, 
       ModelCorrespondence { "CIM_LogicalPort.Speed" }, 
       PUnit ( "bit / second" )]
   uint64 RequestedSpeed;

      [Write, Description ( 
          "A boolean indicating whether the LogicalPort should "
          "automatically negotiate an optimal bandwidth (TRUE), or "
          "attempt to communicate only at the RequestedSpeed "
          "(FALSE). The actual bandwidth is reported in "
          "LogicalPort.Speed. Changing this value to (FALSE) may "
          "cause the OperationalStatus to change to [stopped] if "
          "the RequestedSpeed is not compatible with the attached "
          "device \n"
          "Check LogicalPortCapabilities.AutoSenseSpeedConfigurable "
          "to see if this value may be changed." ), 
       MappingStrings { 
          "FC-SWAPI.INCITS-T11|UcPortConfigSetLinkSpeed" }, 
       ModelCorrespondence { "CIM_LogicalPort.Speed", 
          "CIM_LogicalPortCapabilities.AutoSenseSpeedConfigurable" }]
   boolean AutoSenseSpeed;


};
