// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_USBConnection 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::USB" ), 
    Description ( 
       "USBConnection associates a Device with the USBPort to which it "
       "is connected." )]
class CIM_USBConnection : CIM_DeviceConnection {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The USBPort." )]
   CIM_USBPort REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( "The USBDevice that is connected to the Port." )]
   CIM_USBDevice REF Dependent;


};
