// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "WiFiPort is the logical representation of wireless local area "
       "network communications hardware that conforms to the IEEE "
       "802.11 series of specifications. It embodies properties at the "
       "lowest layers of a network stack, such as the antennas used "
       "for transmission and reception, the address permanently "
       "embedded into the hardware, and the operational bandwidth of "
       "the device." )]
class CIM_WiFiPort : CIM_NetworkPort {

      [Override ( "Speed" ), 
       Description ( 
          "The data rate at which the current PPDU (PLCP (Physical "
          "Layer Convergence Protocol) Protocol Data Unit) was "
          "received. This value is encoded in the first 4 bits of "
          "the PLCP header in each PLCP frame." )]
   uint64 Speed;

      [Override ( "MaxSpeed" ), 
       Description ( 
          "Shall contain the maximum bandwidth relative to the "
          "current operating mode specified in PortType. For "
          "example, shall contain 11000000 if PortType contains 71 "
          "(\"802.11b\")." )]
   uint64 MaxSpeed;

      [Override ( "PortType" ), 
       Description ( 
          "PortType shall contain the specific 802.11 operating "
          "mode that is currently enabled on the Port. All modes "
          "are specified in" ), 
       ValueMap { "0", "1", "70", "71", "72", "73", "..", "16000.." }, 
       Values { "Unknown", "Other", "802.11a", "802.11b", "802.11g", 
          "802.11n", "DMTF Reserved", "Vendor Reserved" }]
   uint16 PortType;

      [Override ( "PermanentAddress" ), 
       Description ( 
          "IEEE 802 EUI-48 MAC address, formatted as twelve "
          "hexadecimal digits (for example, \"010203040506\"), with "
          "each pair representing one of the six octets of the MAC "
          "address in \"canonical\" bit order. (Therefore, the "
          "Group address bit is found in the low order bit of the "
          "first character of the string.)" )]
   string PermanentAddress;

      [Override ( "NetworkAddresses" ), 
       Description ( 
          "IEEE 802 EUI-48 MAC addresses, each formatted as twelve "
          "hexadecimal digits (for example, \"010203040506\"), with "
          "each pair representing one of the six octets of the MAC "
          "address in \"canonical\" bit order. (Therefore, the "
          "Group address bit is found in the low order bit of the "
          "first character of the string.)" )]
   string NetworkAddresses[];


};
