// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AggregatePSExtentBasedOnAggregatePExtent 
// ==================================================================
   [Association, Deprecated { "CIM_ProtectedExtentBasedOn" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Device::SccExtents" ), 
    Description ( 
       "This association is deprecated in lieu of "
       "ProtectedSpaceBasedOn, since AggregatePExtents and "
       "AggregatePSExtents are themselves deprecated. The association "
       "describes that AggregatePSExtents are BasedOn a single "
       "AggregatePExtent." )]
class CIM_AggregatePSExtentBasedOnAggregatePExtent : CIM_BasedOn {

      [Deprecated { "CIM_ProtectedExtentBasedOn.Antecedent" }, 
       Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The AggregatePExtent." )]
   CIM_AggregatePExtent REF Antecedent;

      [Deprecated { "CIM_ProtectedExtentBasedOn.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "The AggregatePSExtent which is built on the Aggregate PExtent."
           )]
   CIM_AggregatePSExtent REF Dependent;


};
