// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "LogicalPortCapabilities describes the configuration "
       "capabilities for properties in LogicalPortSettings." )]
class CIM_LogicalPortCapabilities : CIM_EnabledLogicalElementCapabilities {

      [Description ( 
          "List of supported port speeds that can be configured on "
          "LogicalPortSettings.RequestedSpeed." ), 
       ModelCorrespondence { "CIM_NetworkPort.Speed" }]
   uint64 RequestedSpeedsSupported[];

      [Description ( 
          "A boolean indicating whether the value in "
          "LogicalPortSettings.AutoSenseSpeed may be changed "
          "(TRUE), or may only be viewed (FALSE)." ), 
       ModelCorrespondence { "CIM_NetworkPort.Speed" }]
   boolean AutoSenseSpeedConfigurable;


};
