// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AssociatedAlarm 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::Sensors" ), 
    Description ( 
       "LogicalDevices may have one or more AlarmDevices associated "
       "with them, in order to indicate problem situations. This "
       "relationship is indicated by the AssociatedAlarm dependency." )]
class CIM_AssociatedAlarm : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The AlarmDevice." )]
   CIM_AlarmDevice REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The LogicalDevice that is alarmed." )]
   CIM_LogicalDevice REF Dependent;


};
