// Copyright (c) 2011 DMTF.  All rights reserved.
   [Version ( "2.31.1" ), 
    UMLPackagePath ( "CIM::Device::Controller" ), 
    Description ( 
       "VideoHead represents one head of the CIM_DisplayController." )]
class CIM_VideoHead : CIM_LogicalDevice {

      [Description ( 
          "The number of bits used to display each pixel." ), 
       Units ( "Bits" ), 
       MappingStrings { "MIF.DMTF|Video|004.12" }, 
       PUnit ( "bit" )]
   uint32 CurrentBitsPerPixel;

      [Description ( "Current number of horizontal pixels." ), 
       Units ( "Pixels" ), 
       MappingStrings { "MIF.DMTF|Video|004.11" }, 
       ModelCorrespondence { 
          "CIM_VideoHeadResolution.HorizontalResolution" }, 
       PUnit ( "pixel" )]
   uint32 CurrentHorizontalResolution;

      [Description ( "Current number of vertical pixels." ), 
       Units ( "Pixels" ), 
       MappingStrings { "MIF.DMTF|Video|004.10" }, 
       ModelCorrespondence { 
          "CIM_VideoHeadResolution.VerticalResolution" }, 
       PUnit ( "pixel" )]
   uint32 CurrentVerticalResolution;

      [Description ( 
          "Maximum refresh rate of the DisplayController in Hertz." ), 
       Units ( "Hertz" ), 
       MappingStrings { "MIF.DMTF|Video|004.5" }, 
       ModelCorrespondence { "CIM_VideoHeadResolution.MaxRefreshRate" }, 
       PUnit ( "hertz" )]
   uint32 MaxRefreshRate;

      [Description ( 
          "Minimum refresh rate of the Video Controller in Hertz." ), 
       Units ( "Hertz" ), 
       MappingStrings { "MIF.DMTF|Video|004.4" }, 
       ModelCorrespondence { "CIM_VideoHeadResolution.MinRefreshRate" }, 
       PUnit ( "hertz" )]
   uint32 MinRefreshRate;

      [Description ( "Current refresh rate in Hertz." ), 
       Units ( "Hertz" ), 
       MappingStrings { "MIF.DMTF|Video|004.15" }, 
       ModelCorrespondence { "CIM_VideoHeadResolution.RefreshRate" }, 
       PUnit ( "hertz" )]
   uint32 CurrentRefreshRate;

      [Description ( "Current scan mode." ), 
       ValueMap { "0", "1", "2", "3", "4" }, 
       Values { "Unknown", "Other", "Not Supported", 
          "Non-Interlaced Operation", "Interlaced Operation" }, 
       MappingStrings { "MIF.DMTF|Video|004.8" }, 
       ModelCorrespondence { "CIM_VideoHead.OtherCurrentScanMode", 
          "CIM_VideoHeadResolution.ScanMode" }]
   uint16 CurrentScanMode;

      [Description ( 
          "A string describing the current scan mode when the "
          "instance\'s CurrentScanMode property is 1 (\"Other\")." ), 
       ModelCorrespondence { "CIM_VideoHead.CurrentScanMode", 
          "CIM_VideoHeadResolution.OtherScanMode" }]
   string OtherCurrentScanMode;

      [Description ( 
          "If in character mode, number of rows for this Video "
          "Controller. Otherwise, enter 0." ), 
       MappingStrings { "MIF.DMTF|Video|004.13" }]
   uint32 CurrentNumberOfRows;

      [Description ( 
          "If in character mode, number of columns for this "
          "DisplayController. Otherwise, enter 0." ), 
       MappingStrings { "MIF.DMTF|Video|004.14" }]
   uint32 CurrentNumberOfColumns;

      [Description ( 
          "Number of colors supported at the current resolutions." ), 
       ModelCorrespondence { "CIM_VideoHeadResolution.NumberOfColors" }]
   uint64 CurrentNumberOfColors;


};
