// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_AssociatedProcessorMemory 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::Memory" ), 
    Description ( 
       "Associates the Processor and system Memory, or a Processor\'s Cache."
        )]
class CIM_AssociatedProcessorMemory : CIM_AssociatedMemory {

      [Override ( "Dependent" ), 
       Description ( 
          "The Processor that accesses the Memory or uses the Cache." )]
   CIM_Processor REF Dependent;

      [Description ( 
          "Speed of the bus, in MHertz, between the Processor and Memory."
           ), 
       Units ( "MegaHertz" ), 
       PUnit ( "hertz * 10^6" )]
   uint32 BusSpeed;


};
