// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00751.003" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_FibreChannelAdapter
// ==================================================================
   [Deprecated { "CIM_FCPort" }, 
    Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::NetworkAdapter" ), 
    Description ( 
       "Note: The use of the CIM_FibreChannelAdapter class is "
       "deprecated, consistent with the deprecation of NetworkAdapter. "
       "Instead use CIM_FCPort. \n"
       "Deprecated description: This class describes the capabilities "
       "and management aspects of a Fibre Channel Adapter." )]
class CIM_FibreChannelAdapter : CIM_NetworkAdapter {

      [Deprecated { 
          "CIM_NetworkPort.SupportedMaximumTransmissionUnit" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: The maximum frame size, in "
          "bytes, supported by the Adapter." ), 
       Units ( "Bytes" ), 
       PUnit ( "byte" )]
   uint64 MaxFrameSize;

      [Deprecated { "CIM_FCPort.SupportedCOS" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: The Fibre Channel Classes of "
          "Service that are supported by the Adapter, on its Ports. "
          "The currently negotiated COS for a connection is a "
          "property (NegotiatedCOS) on the FibrePort ActiveLogin "
          "association." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6" }, 
       Values { "Unknown", "1", "2", "3", "4", "6", "F" }]
   uint16 SupportedCOS[];

      [Deprecated { "CIM_FCPort.SupportedFC4Types" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: An array of integers that "
          "indicates the Fibre Channel FC-4 protocols that are "
          "supported by the Adapter. The protocols that are active "
          "and running are indicated in the CurrentFC4Types "
          "property. The values that are used in this array are "
          "taken from the FC-GS2 (bit-mapped) field defined in "
          "Table 11 of the standard. Also, FC-SB-2 codes are "
          "included from the T11 document, 236V0. If the FC4 Type "
          "is \"Vendor Unique\" (value=255), then the specific "
          "vendor values (in the range, 0xE0 to 0xFF) should be "
          "listed in the FC4VendorUniqueTypes property." ), 
       ValueMap { "0", "1", "4", "5", "8", "9", "17", "18", "19", 
          "21", "22", "23", "25", "26", "27", "28", "32", "34", 
          "36", "64", "80", "81", "82", "88", "96", "255" }, 
       Values { "Unknown", "Other", "ISO/IEC 8802 - 2 LLC", 
          "IP over FC", "SCSI - FCP", "SCSI - GPP", 
          "IPI - 3 Master", "IPI - 3 Slave", "IPI - 3 Peer", 
          "CP IPI - 3 Master", "CP IPI - 3 Slave", 
          "CP IPI - 3 Peer", "SBCCS Channel", "SBCCS Control Unit", 
          "FC-SB-2 Channel", "FC-SB-2 Control Unit", 
          "Fibre Channel Services (FC-GS, FC-GS-2, FC-GS-3)", 
          "FC-SW", "FC - SNMP", "HIPPI - FP", "BBL Control", 
          "BBL FDDI Encapsulated LAN PDU", 
          "BBL 802.3 Encapsulated LAN PDU", "FC - VI", "FC - AV", 
          "Vendor Unique" }, 
       ModelCorrespondence { 
          "CIM_FibreChannelAdapter.FC4VendorUniqueTypes" }]
   uint16 FC4TypesSupported[];

      [Deprecated { "CIM_FCPort.SupportedFC4Types" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: When the FC4TypesSupported array "
          "contains the value 255 (\"Vendor Unique\"), then the "
          "property, FC4Vendor UniqueTypes, lists of all the "
          "vendor-specific protocols that are supported by the "
          "Adapter. These values are in the range 0xE0 to 0xFF." ), 
       MinValue ( 240 ), 
       MaxValue ( 255 )]
   uint16 FC4VendorUniqueTypes[];

      [Deprecated { "CIM_FCPort.ActiveFC4Types" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: An array of integers that "
          "indicate the Fibre Channel FC-4 protocols that are "
          "currently running on the Adapter. A list of all "
          "protocols that are supported by the Adapter is indicated "
          "in the FC4TypesSupported property. The values used in "
          "this array are taken from the FC-GS2 (bit-mapped) field "
          "that is defined in Table 11 of the standard. Also, "
          "FC-SB-2 codesare included from the T11 document, 236V0. "
          "If the FC4 Type is \"Vendor Unique\" (value=255), then "
          "the specific vendor values (in the range 0xE0 to 0xFF) "
          "that are currently running should be listed in the "
          "CurrentFC4VendorTypes property." ), 
       ValueMap { "0", "1", "4", "5", "8", "9", "17", "18", "19", 
          "21", "22", "23", "25", "26", "27", "28", "32", "34", 
          "36", "64", "80", "81", "82", "88", "96", "255" }, 
       Values { "Unknown", "Other", "ISO/IEC 8802 - 2 LLC", 
          "IP over FC", "SCSI - FCP", "SCSI - GPP", 
          "IPI - 3 Master", "IPI - 3 Slave", "IPI - 3 Peer", 
          "CP IPI - 3 Master", "CP IPI - 3 Slave", 
          "CP IPI - 3 Peer", "SBCCS Channel", "SBCCS Control Unit", 
          "FC-SB-2 Channel", "FC-SB-2 Control Unit", 
          "Fibre Channel Services (FC-GS, FC-GS-2, FC-GS-3)", 
          "FC-SW", "FC - SNMP", "HIPPI - FP", "BBL Control", 
          "BBL FDDI Encapsulated LAN PDU", 
          "BBL 802.3 Encapsulated LAN PDU", "FC - VI", "FC - AV", 
          "Vendor Unique" }, 
       ModelCorrespondence { 
          "CIM_FibreChannelAdapter.FC4TypesSupported", 
          "CIM_FibreChannelAdapter.CurrentFC4VendorTypes" }]
   uint16 CurrentFC4Types[];

      [Deprecated { "CIM_FCPort.ActiveFC4Types" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: When the CurrentFC4Types array "
          "contains the value 255 (\"Vendor Unique\"), then the "
          "property, CurrentFC4 VendorTypes, lists all the "
          "vendor-specific protocols running on the Adapter. These "
          "values are in the range 0xE0 to 0xFF." ), 
       MinValue ( 240 ), 
       MaxValue ( 255 ), 
       ModelCorrespondence { 
          "CIM_FibreChannelAdapter.FC4VendorUniqueTypes" }]
   uint16 CurrentFC4VendorTypes[];

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: A list of the Capabilities of "
          "the Fibre Channel Adapter. For example, the capability "
          "that the Adapter utilizes the Directory Server, or that "
          "it generates State Change Notifications can be indicated "
          "using the values 2 and 12, respectively." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11", "12", "13", "14", "15" }, 
       Values { "Unknown", "Other", "Utilizes the Directory Server", 
          "Utilizes the Time Server", 
          "Utilizes the Management Server", 
          "Utilizes the Alias Server", 
          "Utilizes the Security Key Distribution Server", 
          "Utilizes the Clock Synchronization Server", 
          "Utilizes the Multicast Server", 
          "Utilizes QoS Facilitator", "Utilizes Broadcast Services", 
          "Supports Fabric Login Server", 
          "Generates State Change Notifications", 
          "Registers for State Change Notifications", 
          "Responds to Read Connection Status", 
          "Supports Third Party Process Logout" }, 
       ArrayType ( "Indexed" )]
   uint16 Capabilities[];

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: An array of free-form strings "
          "that provide more detailed explanations for any of the "
          "Adapter features that are indicated in the Capabilities "
          "array. Note, each entry of this array is related to the "
          "entry in the Capabilities array that is located at the "
          "same index." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_FibreChannelAdapter.Capabilities" }]
   string CapabilityDescriptions[];

      [Deprecated { "CIM_FCPortStatistics.ErrorFrames" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: The number of times that a frame "
          "was received but no buffer was available." ), 
       Counter]
   uint64 ReceiveBufferErrors;

      [Deprecated { "CIM_FCPortStatistics.ErrorFrames" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: The number of times that a frame "
          "was received but no end-to-end credit was available." ), 
       Counter]
   uint64 ReceiveEndErrors;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: A \'long\' timeout value (in "
          "milliseconds) for determining when to reinstate a "
          "Recovery_Qualifier. The default value is 120 seconds "
          "(120000 milliseconds). The value is typically set to the "
          "ErrorDetectTimeout value + 2*(fabric delay time)." ), 
       Units ( "MilliSeconds" ), 
       PUnit ( "second * 10^-3" )]
   uint64 ResourceAllocationTimeout;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: A \'short\' timeout value (in "
          "milliseconds) for determining that an error has "
          "occurred. The default value is 10 seconds (10000 "
          "milliseconds)." ), 
       Units ( "MilliSeconds" ), 
       PUnit ( "second * 10^-3" )]
   uint64 ErrorDetectTimeout;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of Class 1 sequences sent "
          "since the last reset of the Device." ), 
       Counter]
   uint64 Class1SequencesSent;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of Class 2 sequences sent "
          "since the last reset of the Device." ), 
       Counter]
   uint64 Class2SequencesSent;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of Class 3 sequences sent "
          "since the last reset of the Device." ), 
       Counter]
   uint64 Class3SequencesSent;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of Class 4 sequences sent "
          "since the last reset of the Device." ), 
       Counter]
   uint64 Class4SequencesSent;

      [Deprecated { "CIM_FCPortStatistics.BytesReceived" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of octets received by the "
          "Adapter when running Class 2 service." ), 
       Counter]
   uint64 Class2OctetsReceived;

      [Deprecated { "CIM_FCPortStatistics.BytesTransmitted" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of octets that are "
          "transmitted by the Adapter when running Class 2 service." ), 
       Counter]
   uint64 Class2OctetsTransmitted;

      [Deprecated { "CIM_FCPortStatistics.PacketsReceived" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of frames that were "
          "received by the Adapter when running Class 2 service." ), 
       Counter]
   uint64 Class2FramesReceived;

      [Deprecated { "CIM_FCPortStatistics.PacketsTransmitted" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of frames that were "
          "transmitted by the Adapter when running Class 2 service." ), 
       Counter]
   uint64 Class2FramesTransmitted;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of frames that were "
          "discarded by the Adapter when running Class 2 service." ), 
       Counter]
   uint64 Class2DiscardFrames;

      [Deprecated { "CIM_FCPortStatistics.BytesReceived" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of octets that were "
          "received by the Adapter when running Class 3 service." ), 
       Counter]
   uint64 Class3OctetsReceived;

      [Deprecated { "CIM_FCPortStatistics.BytesTransmitted" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of octets that were "
          "transmitted by the Adapter when running Class 3 service." ), 
       Counter]
   uint64 Class3OctetsTransmitted;

      [Deprecated { "CIM_FCPortStatistics.PacketsReceived" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of frames that were "
          "received by the Adapter when running Class 3 service." ), 
       Counter]
   uint64 Class3FramesReceived;

      [Deprecated { "CIM_FCPortStatistics.PacketsTransmitted" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of frames that were "
          "transmitted by the Adapter when running Class 3 service." ), 
       Counter]
   uint64 Class3FramesTransmitted;

      [Deprecated { "No value" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of frames that were "
          "discarded by the Adapter when running Class 3 service." ), 
       Counter]
   uint64 Class3DiscardFrames;

      [Deprecated { "CIM_FCPortStatistics.ErrorFrames" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of parity errors that "
          "were detected somewhere in the data path." ), 
       Counter]
   uint64 ParityErrors;

      [Deprecated { "CIM_FCPortStatistics.ErrorFrames" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of Class 1 or 2 frames "
          "that are not ACKed within the time indicated by "
          "ErrorDetectTimeout." ), 
       Counter]
   uint64 FrameTimeouts;

      [Deprecated { "CIM_FCPortStatistics.BufferCreditNotProvided" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of times that the Device "
          "has been without a buffer credit for a time longer than "
          "ErrorDetectTimeout." ), 
       Counter]
   uint64 BufferCreditErrors;

      [Deprecated { "CIM_FCPortStatistics.BufferCreditNotReceived" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of times that the Device "
          "has been without an end credit for a time longer than "
          "ErrorDetectTimeout." ), 
       Counter]
   uint64 EndCreditErrors;

      [Deprecated { "CIM_FCPortStatistics.DelimiterErrors" }, 
       Description ( 
          "Note: The use of this method has been deprecated. \n"
          "Deprecated description: Number of frames that were "
          "received out of order." ), 
       Counter]
   uint64 OutOfOrderFramesReceived;


};
