// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_StorageError 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::StorageExtents" ), 
    Description ( 
       "StorageError defines blocks of media or memory space that are "
       "mapped \'out of use\' due to errors. The Key of the class is "
       "the StartingAddress of the bytes in error." )]
class CIM_StorageError : CIM_ManagedElement {

      [Key, Description ( "The scoping System\'s CreationClassName." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_StorageExtent.SystemCreationClassName" )]
   string SystemCreationClassName;

      [Key, Description ( "The scoping System\'s Name." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_StorageExtent.SystemName" )]
   string SystemName;

      [Key, Description ( 
          "The scoping StorageExtent\'s CreationClassName." ), 
       MaxLen ( 256 ), 
       Propagated ( "CIM_StorageExtent.CreationClassName" )]
   string DeviceCreationClassName;

      [Key, Description ( "The scoping StorageExtent\'s DeviceID." ), 
       MaxLen ( 64 ), 
       Propagated ( "CIM_StorageExtent.DeviceID" )]
   string DeviceID;

      [Key, Description ( 
          "The starting address of the bytes in error." )]
   uint64 StartingAddress;

      [Description ( "The ending address of the bytes in error." )]
   uint64 EndingAddress;


};
