// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RealizesTapePartition 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::StorageExtents" ), 
    Description ( 
       "TapePartitions are realized on PhysicalTape. This relationship "
       "is made explicit by the RealizesTapePartition association." )]
class CIM_RealizesTapePartition : CIM_RealizesExtent {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The PhysicalTape on which the Partition is realized." )]
   CIM_PhysicalTape REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The TapePartition that is located on the Media." )]
   CIM_TapePartition REF Dependent;


};
