// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_UserDevice 
// ==================================================================
   [Abstract, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::UserDevices" ), 
    Description ( 
       "UserDevices are LogicalDevices that allow a ComputerSystem\'s "
       "users to input, view or hear data. It is a superclass from "
       "which other classes, such as Keyboard or DesktopMonitor, "
       "descend." )]
class CIM_UserDevice : CIM_LogicalDevice {

      [Description ( 
          "An indication of whether the Device is locked, "
          "preventing user input or output." )]
   boolean IsLocked;


};
