// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00735.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PackageCooling
// ==================================================================
   [Association, Deprecated { "CIM_PackageDependency" }, 
    Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::CoolingAndPower" ), 
    Description ( 
       "Note: The use of this association has been deprecated. "
       "Instead, the more generic PackageDependency relationship "
       "should be used. \n"
       "Deprecated description: Often, a CoolingDevice is installed in "
       "a Package such as a Chassis or a Rack, not for a specific "
       "Device, but to assist in the cooling of the Package in "
       "general." )]
class CIM_PackageCooling : CIM_PackageDependency {

      [Deprecated { "CIM_PackageDependency.Antecedent" }, 
       Override ( "Antecedent" ), 
       Description ( 
          "Note: The use of this method is deprecated. \n"
          "Deprecated description: The CoolingDevice for the "
          "Package." )]
   CIM_CoolingDevice REF Antecedent;

      [Deprecated { "CIM_PackageDependency.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "Note: The use of this method is deprecated. \n"
          "Deprecated description: The PhysicalPackage whose "
          "environment is cooled." )]
   CIM_PhysicalPackage REF Dependent;


};
