// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DeviceIdentity 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::DeviceElements" ), 
    Description ( 
       "CIM_DeviceIdentity indicates that two LogicalDevices represent "
       "different aspects of the same underlying entity. This "
       "association refines the CIM_LogicalIdentity superclass by "
       "restricting it to the Device level and defining its use in "
       "well understood scenarios. One of these scenarios is to "
       "represent that a Device is both a \'bus\' entity and a "
       "\'functional\' entity. For example, a Device could be both a "
       "PCI Device (or a USB Device), as well as a CIM_Keyboard. The "
       "other scenario is where a Device plays multiple functional "
       "roles that can not be distinguished by their hardware "
       "realization alone. For example, a Fibre Channel adapter might "
       "have aspects of both a NetworkAdapter and a SCSIController." )]
class CIM_DeviceIdentity : CIM_LogicalIdentity {

      [Override ( "SystemElement" ), 
       Description ( 
          "SystemElement represents one aspect of the Device." )]
   CIM_LogicalDevice REF SystemElement;

      [Override ( "SameElement" ), 
       Description ( 
          "SameElement represents an alternate aspect of the System entity."
           )]
   CIM_LogicalDevice REF SameElement;


};
