// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ComputerSystemMemory 
// ==================================================================
   [Association, Deprecated { "CIM_SystemDevice" }, 
    Aggregation, Composition, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Device::Memory" ), 
    Description ( 
       "The use of this association has be deprecated in lieu of "
       "SystemDevice. Association indicating that memory is installed "
       "and required for the UnitaryComputerSystem to operate. Note "
       "that this relationship inherits from the SystemDevice "
       "association, and therefore, the Memory StorageExtent is weak "
       "to the aggregating UnitaryComputerSystem." )]
class CIM_ComputerSystemMemory : CIM_SystemDevice {

      [Deprecated { "CIM_SystemDevice.GroupComponent" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The UnitaryComputerSystem." )]
   CIM_UnitaryComputerSystem REF GroupComponent;

      [Deprecated { "CIM_SystemDevice.PartComponent" }, 
       Override ( "PartComponent" ), 
       Description ( 
          "The Memory StorageExtent which is part of the "
          "UnitaryComputerSystem." )]
   CIM_Memory REF PartComponent;


};
