// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_Resource 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( 
       "Each PRS_Resolution may have an associated cost of "
       "implementation. This cost may have several components such as "
       "time, material costs, labor cost, etc. To capture these costs, "
       "a PRS_Resouce is associated with a PRS_Resolution. For Service "
       "Incidents, one or more PRS_Resource objects may be associated "
       "with an Activity." )]
class PRS_Resource : PRS_ExchangeElement {

      [Description ( "A string describing the type of resource." )]
   string ResourceType;

      [Description ( "Number of units of resource used." )]
   uint16 Quantity;

      [Description ( "Unit of measure for this resource." )]
   string Units;


};
