// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  PRS_ResolutionResource 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "PRS::Support" ), 
    Description ( "Associates PRS_Resolution with PRS_Resource." )]
class PRS_ResolutionResource : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The PRS_Resource." )]
   PRS_Resource REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The PRS_Resolution." )]
   PRS_Resolution REF Dependent;


};
