// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Aggregation, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Database::Storage" ), 
    Description ( 
       "DatabaseFile captures the relationship between a database and "
       "the supporting files that make up the database as well as the "
       "purpose served by the files within the context of the "
       "database." )]
class CIM_DatabaseFile : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The single CommonDatabase instance that uses the "
          "referenced LogicalFile." )]
   CIM_CommonDatabase REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "One of any number of LogicalFile instances that are "
          "utilized by the referenced CommonDatabase." )]
   CIM_LogicalFile REF PartComponent;


};
