#!/bin/sh
CURDIR=`pwd`
OUTPUTDIR=$CURDIR/output/`./buildtool hostname`
LIBDIR=$OUTPUTDIR/lib
BINDIR=$OUTPUTDIR/bin
LOCALSTATEDIR=$OUTPUTDIR/var
INCLUDEDIR=$OUTPUTDIR/include
CMD="./configure --enable-wchar --enable-werror --prefix=$CURDIR --libdir=$LIBDIR --bindir=$BINDIR --localstatedir=$LOCALSTATEDIR --includedir=$INCLUDEDIR $*"
echo $CMD
$CMD
