sd edit cli\GNUmakefile
sd edit common\MI.h
sd edit http\httpclient.c
sd edit micxx\instance.h
sd edit midll\GNUmakefile
sd edit server\GNUmakefile
sd edit protocol\protocol.c
sd edit sock\addr.h
sd edit sock\addr.c
sd edit sock\sock.h
sd edit sock\sock.c
sd edit samples\Providers\Test_Indication\GNUmakefile
sd edit tests\http\GNUmakefile
sd edit tests\http\test_http*.cpp
sd edit tests\indication\GNUmakefile
sd edit tests\miapi\GNUmakefile
sd edit tests\protocol\GNUmakefile
sd edit tests\sock\GNUmakefile
sd edit tests\sock\test_selector.cpp
sd edit tests\wsman\utils.cpp
