// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_Export 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "An association between a LocalFileSystem and its Directories "
       "indicating that the specified Directories are available for "
       "mount. When exporting an entire FileSystem, the Directory "
       "should reference the topmost directory of the FileSystem." )]
class CIM_Export {

      [Key, Max ( 1 ), 
       Description ( "The LocalFileSystem." )]
   CIM_LocalFileSystem REF LocalFS;

      [Key, Description ( "The Directory exported for mount." )]
   CIM_Directory REF Directory;

      [Description ( "Name under which the Directory is exported." )]
   string ExportedDirectoryName;


};
