// Copyright (c) 2010 DMTF.  All rights reserved.
   [Version ( "2.27.0" ), 
    UMLPackagePath ( "CIM::System::BIOS" ), 
    Description ( 
       "The CIM_BIOSPassword object may be used to instantiate detail "
       "information about manageable BIOS-based passwords." )]
class CIM_BIOSPassword : CIM_BIOSAttribute {

      [Description ( 
          "This property specifies the minimum string length "
          "allowed when modifying this BIOS attribute. A value of "
          "NULL SHALL be defined as zero." ), 
       ModelCorrespondence { "CIM_BIOSPassword.MaxLength" }]
   uint64 MinLength;

      [Description ( 
          "This property specifies the maximum string length "
          "allowed when modifying this BIOS attribute. A value of "
          "NULL defines the maximum length is unknown. A value of 0 "
          "defines the maximum length as 18446744073709551615, the "
          "limitation of the property definition as uint64." ), 
       ModelCorrespondence { "CIM_BIOSPassword.MinLength" }]
   uint64 MaxLength;

      [Override ( "CurrentValue" ), 
       Description ( "CurrentValue shall return an empty array." )]
   string CurrentValue[];

      [Required, Override ( "PendingValue" ), 
       Description ( "PendingValue shall return an empty array." )]
   string PendingValue[];

      [Description ( 
          "PasswordEncoding specifies encoding tag used to denote "
          "the format the password string was createdor set with "
          "\"kbd\" denotes a string in hexadecimal format "
          "containing keyboard scan code input. An example of a "
          "password structured in this format would be "
          "\"321539191E1F1F11181320\", which is the representation "
          "of \"my password\" in US English keyboard scan codes. "
          "\"ascii\" denotes clear text that shall comply with the "
          "ASCII character set. Character encodings from \" \" "
          "(decimal 32) to \"~\" (decimal 126) are supported. An "
          "example would be \"my password\".\"pin\" denotes that "
          "only numeric input in ASCII text is allowed for the "
          "password instance. An example would be \"1234\"." ), 
       ValueMap { "2", "3", "4", "5", "..", "65536..4294967295" }, 
       Values { "ascii", "kbd", "pin", "Unicode", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ModelCorrespondence { 
          "CIM_BIOSServiceCapabilities.SupportedPasswordEncodings" }]
   uint32 PasswordEncoding;

      [Description ( 
          "This property returns TRUE if the current password "
          "instance is non-blank and FALSE otherwise. This property "
          "is provided because the Value property is always defined "
          "as NULL for password instances." )]
   boolean IsSet;


};
