// Copyright (c) 2008 DMTF.  All rights reserved.
   [Version ( "2.22.0" ), 
    UMLPackagePath ( "CIM::System::Diagnostics" ), 
    Description ( 
       "This class contains a snapshot of the settings that were used "
       "when the associated Diagnostic service was run." )]
class CIM_DiagnosticSettingDataRecord : CIM_DiagnosticRecord {

      [Description ( 
          "A string containing an encoding of the "
          "DiagnosticSettingData instance that was used when the "
          "diagnostic service was run." ), 
       EmbeddedInstance ( "CIM_DiagnosticSettingData" )]
   string Settings;


};
