// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ProcessOfJob 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "ProcessOfJob describes that the referenced Process is the "
       "result of the execution of the Job. A Job may cause multiple "
       "Processes to run, perhaps on different operating systems. This "
       "is allowed by the \'*\' cardinality of the Process reference. "
       "Note that a Process can result from only one Job - hence, the "
       "\'0..1\' cardinality on Job." )]
class CIM_ProcessOfJob : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "Execution of the Job results in the creation of the "
          "Process referenced as PartComponent. The Job aggregates "
          "the Process(es) that are created when it is executed." )]
   CIM_Job REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The Process that results from the execution of the Job." )]
   CIM_Process REF PartComponent;


};
