// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_OSProcess 
// ==================================================================
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "A link between the OperatingSystem and Process(es) running in "
       "the context of this OperatingSystem." )]
class CIM_OSProcess : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The OperatingSystem." )]
   CIM_OperatingSystem REF GroupComponent;

      [Override ( "PartComponent" ), 
       Weak, Description ( 
          "The Process running in the context of the OperatingSystem."
           )]
   CIM_Process REF PartComponent;


};
