// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostedClusterService 
// ==================================================================
   [Association, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::SystemElements" ), 
    Description ( 
       "HostedClusterService defines the hosting Cluster for a "
       "ClusteringService. Since this relationship is subclassed from "
       "HostedService, it inherits the scoping/naming scheme defined "
       "for Service - where a Service is weak to its hosting System. "
       "In this case, a ClusteringService must be weak to its hosting "
       "Cluster System." )]
class CIM_HostedClusterService : CIM_HostedService {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The Cluster." )]
   CIM_ComputerSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The ClusteringService that is hosted on the Cluster." )]
   CIM_ClusteringService REF Dependent;


};
