// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_UseOfLog 
// ==================================================================
   [Association, Version ( "2.9.0" ), 
    UMLPackagePath ( "CIM::System::Logs" ), 
    Description ( 
       "ManagedSystemElements may record their event, error or "
       "informational data within Logs. The use of a Log to hold a "
       "ManagedSystemElement\'s data is described by this association. "
       "The type of Element data captured by the Log can be specified "
       "using the RecordedData string property." )]
class CIM_UseOfLog : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Log." )]
   CIM_Log REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The ManagedSystemElement whose information is recorded in the Log."
           )]
   CIM_ManagedSystemElement REF Dependent;

      [Description ( 
          "A free-form string describing the use of the Log by the "
          "ManagedSystemElement." )]
   string RecordedData;


};
