// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_JobDestinationJobs 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "An association describing where a Job is submitted for "
       "processing, ie to which JobDestination." )]
class CIM_JobDestinationJobs : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The JobDestination, possibly a queue." )]
   CIM_JobDestination REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Job that is in the Job queue/Destination." )]
   CIM_Job REF Dependent;


};
