// Copyright (c) 2008 DMTF.  All rights reserved.
   [Abstract, Version ( "2.18.0" ), 
    UMLPackagePath ( "CIM::System::Logs" ), 
    Description ( 
       "Log represents any type of event, error or informational "
       "register or chronicle. The object describes the existence of "
       "the log and its characteristics. Log does not dictate the form "
       "of the data represented or how records/messages are stored in "
       "the log and/or accessed. Subclasses will define the "
       "appropriate methods and behavior." )]
class CIM_Log : CIM_EnabledLogicalElement {

      [Description ( 
          "Maximum number of records that can be captured in the "
          "Log. If undefined, a value of zero should be specified." )]
   uint64 MaxNumberOfRecords;

      [Description ( "Current number of records in the Log." ), 
       Gauge]
   uint64 CurrentNumberOfRecords;

      [Description ( 
          "OverwritePolicy is an integer enumeration that indicates "
          "whether the log, represented by the CIM_Log subclasses, "
          "can overwrite its entries.Unknown (0) indicates the "
          "log\'s overwrite policy is unknown. \n"
          "Wraps when Full (2) indicates that the log overwrites "
          "its entries with new entries when the log has reached "
          "its maximum capacity. \n"
          "Never Overwrites (7) indicates that the log never "
          "overwrites its entries by the new entries." ), 
       ValueMap { "0", "2", "7", "..", "32768..65535" }, 
       Values { "Unknown", "Wraps When Full", "Never Overwrites", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint16 OverwritePolicy = 0;

      [Description ( 
          "LogState is an integer enumeration that indicates the "
          "current state of a log represented by CIM_Log "
          "subclasses. LogState is to be used in conjunction with "
          "the EnabledState property to fully describe the current "
          "state of the log. The following text briefly summarizes "
          "the various log states: \n"
          "Unknown (0) indicates the state of the log is unknown. \n"
          "Normal (2) indicates that the log is or could be "
          "executing logging commands, will process any queued log "
          "entries, and will queue new logging requests. \n"
          "Erasing (3) indicates that the log is being erased. \n"
          "Not Applicable (4) indicates the log does not support "
          "representing a log state." ), 
       ValueMap { "0", "2", "3", "4", "..", "32768..65535" }, 
       Values { "Unknown", "Normal", "Erasing", "Not Applicable", 
          "DMTF Reserved", "Vendor Reserved" }, 
       ModelCorrespondence { "CIM_EnabledLogicalElement.EnabledState" }]
   uint16 LogState = 4;


      [Description ( 
          "Requests that the Log be cleared of all entries. \n"
          "The return value should be 0 if the request was "
          "successfully executed, 1 if the request is not "
          "supported, and some other value, as indicated by the "
          "ValueMap/Values qualifiers, if an error occurred." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6..0x0FFF", 
          "0x1000..0x7FFF", "0x8000.." }, 
       Values { "Completed with no error", "Not Supported", 
          "Unspecified Error", "Timeout", "Failed", 
          "Invalid Parameter", "DMTF_Reserved", "Method_Reserved", 
          "Vendor_Reserved" }]
   uint32 ClearLog(
);

};
