// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_FIFOPipeFile 
// ==================================================================
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "FIFOPipeFile is a special type of LogicalFile that represents "
       "an interprocess FIFO (sometimes referred to as a \"named "
       "pipe\"). Operating systems use this convention to manage "
       "interprocess communication through processes reading and "
       "writing the FIFO. The FIFO can be accessed by unrelated "
       "processes, in contrast to the more well-known command line "
       "redirection mechanism (e.g. UNIX\'s \'ps -eaf | grep foo\', "
       "also known as an \"unnamed pipe\"). An exemplary operating "
       "system implementation (using the FIFO concept) is the UNIX "
       "S_IFIFO file type." )]
class CIM_FIFOPipeFile : CIM_LogicalFile {


};
