// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostingCS 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::System::SystemElements" ), 
    Description ( 
       "A VirtualComputerSystem is hosted on another ComputerSystem. "
       "This association makes that relationship explicit." )]
class CIM_HostingCS : CIM_HostedDependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Description ( "The hosting ComputerSystem." )]
   CIM_ComputerSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The VirtualComputerSystem." )]
   CIM_VirtualComputerSystem REF Dependent;


};
