// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RunningOS 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::OperatingSystem" ), 
    Description ( 
       "RunningOS indicates the currently executing OperatingSystem. "
       "At most one OperatingSystem can execute at any time on a "
       "ComputerSystem. \'At most one\' is specified, since the "
       "Computer System may not be currently booted, or its "
       "OperatingSystem may be unknown." )]
class CIM_RunningOS : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The OperatingSystem currently running on the ComputerSystem."
           )]
   CIM_OperatingSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( "The ComputerSystem." )]
   CIM_ComputerSystem REF Dependent;


};
