// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "PolicyRoleCollectionInSystem is an association used to "
       "establish a relationship between a collection and an \'owning\' "
       "System such as an AdminDomain or ComputerSystem." )]
class CIM_PolicyRoleCollectionInSystem : CIM_HostedCollection {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The parent system responsible for the collection." )]
   CIM_System REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Collection." )]
   CIM_PolicyRoleCollection REF Dependent;


};
