// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Abstract, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "PolicySetInSystem is an abstract association class that "
       "represents a relationship between a System and a PolicySet "
       "used in the administrative scope of that system (e.g., "
       "AdminDomain, ComputerSystem). The Priority property is used to "
       "assign a relative priority to a PolicySet within the "
       "administrative scope in contexts where it is not a component "
       "of another PolicySet." )]
class CIM_PolicySetInSystem : CIM_PolicyInSystem {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The System in whose scope a PolicySet is defined." )]
   CIM_System REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "A PolicySet named within the scope of a System." )]
   CIM_PolicySet REF Dependent;

      [Description ( 
          "The Priority property is used to specify the relative "
          "priority of the referenced PolicySet when there are more "
          "than one PolicySet instances applied to a managed "
          "resource that are not PolicySetComponents and, "
          "therefore, have no other relative priority defined. The "
          "priority is a non-negative integer; a larger value "
          "indicates a higher priority." )]
   uint16 Priority;


};
