// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "A class describing a company\'s and/or administrator\'s "
       "credential requirements that should be authenticated in order "
       "to establish/trust a CIM_Identity. This class defines the "
       "specific type of physical credential that should be "
       "authenticated." )]
class CIM_PhysicalCredentialAuthentication : CIM_AuthenticationCondition {

      [Description ( 
          "Integer enumeration identifying the credential that "
          "should be authenticated." ), 
       ValueMap { "1", "2", "3", "4" }, 
       Values { "Other", "Magnetic Stripe Card", "Smart Card", 
          "Password Generator Card" }, 
       ModelCorrespondence { 
          "CIM_PhysicalCredentialAuthentication.OtherCredential" }]
   uint16 TypeOfCredential;

      [Description ( 
          "String specifying the credential when the "
          "TypeOfCredential property is set to 1, \"Other\"." ), 
       ModelCorrespondence { 
          "CIM_PhysicalCredentialAuthentication.TypeOfCredential" }]
   string OtherCredential;

      [Description ( 
          "String defining a character or binary sequence, which is "
          "built into the physical credential to identify it. If "
          "left blank, it is the responsibility of the security "
          "infrastructure to verify that a valid credential (of the "
          "specified type) has been used." )]
   string PhysicalIdentifier;


};
