// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Aggregation, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "A relationship that aggregates one or more lower-level "
       "ReusablePolicyContainer instances into a higher-level "
       "ReusablePolicyContainer." )]
class CIM_PolicyContainerInPolicyContainer : CIM_SystemComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "A ReusablePolicyContainer that aggregates other "
          "ReusablePolicyContainers." )]
   CIM_ReusablePolicyContainer REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "A ReusablePolicyContainer aggregated by another "
          "ReusablePolicyContainer." )]
   CIM_ReusablePolicyContainer REF PartComponent;


};
