// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_ReusablePolicy" }, 
    Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "The ReusablePolicy association is a more general relationship "
       "that incorporates both Conditions and Actions as well as any "
       "other policy subclass. \n"
       "\n"
       "This class represents the hosting of reusable PolicyConditions "
       "by a PolicyRepository. A reusable Policy Condition is always "
       "related to a single PolicyRepository, via this association. \n"
       "\n"
       "Note, that an instance of PolicyCondition can be either "
       "reusable or rule-specific. When the Condition is rule- "
       "specific, it shall not be related to any PolicyRepository via "
       "the PolicyConditionInPolicyRepository association." )]
class CIM_PolicyConditionInPolicyRepository : CIM_PolicyInSystem {

      [Deprecated { "CIM_ReusablePolicy.Antecedent" }, 
       Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "This property identifies a PolicyRepository hosting one "
          "or more PolicyConditions. A reusable PolicyCondition is "
          "always related to exactly one PolicyRepository via the "
          "PolicyConditionInPolicyRepository association. The "
          "[0..1] cardinality for this property covers the two "
          "types of PolicyConditions: 0 for a rule-specific "
          "PolicyCondition, 1 for a reusable one." )]
   CIM_PolicyRepository REF Antecedent;

      [Deprecated { "CIM_ReusablePolicy.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( 
          "This property holds the name of a PolicyCondition hosted "
          "in the PolicyRepository." )]
   CIM_PolicyCondition REF Dependent;


};
