// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "CompoundPolicyCondition is used to represent compound "
       "conditions formed by aggregating simpler policy conditions. "
       "Compound conditions are constructed by associating subordinate "
       "condition terms together using the "
       "PolicyConditionInPolicyCondition aggregation." )]
class CIM_CompoundPolicyCondition : CIM_PolicyCondition {

      [Description ( 
          "Indicates whether the list of CompoundPolicyConditions "
          "associated with this PolicyRule is in disjunctive normal "
          "form (DNF) or conjunctive normal form (CNF). The default "
          "value is 1 (\"DNF\")." ), 
       ValueMap { "1", "2" }, 
       Values { "DNF", "CNF" }]
   uint16 ConditionListType;


};
