// Copyright (c) 2009 DMTF.  All rights reserved.
   [Version ( "2.21.0" ), 
    UMLPackagePath ( "CIM::Physical::Package" ), 
    Description ( 
       "A Rack is a PhysicalFrame that represents an enclosure in "
       "which Chassis are placed. Typically a Rack is nothing more "
       "than the enclosure, and all the functioning componentry is "
       "packaged in the Chassis, loaded in the Rack." )]
class CIM_Rack : CIM_PhysicalFrame {

      [Override ( "Height" ), 
       Description ( 
          "The height of the PhysicalPackage in \'U\'s. A \'U\' is "
          "a standard unit of measure for the height of a Rack or "
          "rack-mountable component. It is equal to 1.75 inches or "
          "4.445 cm." ), 
       Units ( "Us" ), 
       PUnit ( "rack unit" )]
   real32 Height;

      [Description ( 
          "Enumeration indicating the type of Rack. Information "
          "such as \"Telco\" rack (value=2) or standard 19 inch "
          "rack (1) can be specified. The country for which the "
          "Rack is manufactured is defined in the the Country "
          "Designation property." ), 
       ValueMap { "0", "1", "2", "3", "4" }, 
       Values { "Unknown", "Standard 19 Inch", "Telco", 
          "Equipment Shelf", "Non-Standard" }, 
       ModelCorrespondence { "CIM_Rack.CountryDesignation" }]
   uint16 TypeOfRack;

      [Description ( 
          "Designation of the country for which the Rack is "
          "designed. Country code strings are as defined by ISO/IEC "
          "3166. The rack type is specified in the TypeOf Rack "
          "property." ), 
       ModelCorrespondence { "CIM_Rack.TypeOfRack" }]
   string CountryDesignation;


};
