// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Physical::Link" ), 
    Description ( 
       "The PhysicalLink class represents the cabling of "
       "PhysicalElements together. For example, serial or Ethernet "
       "cables would be subclasses (if additional properties or "
       "associations are defined) or instances of PhysicalLink. In "
       "many cases, the numerous physical cables within a "
       "PhysicalPackage or Network will not be modeled. However, where "
       "these cables or Links are critical components, or are tagged "
       "assets of the company, these objects can be instantiated using "
       "this class or one of its descendent classes." )]
class CIM_PhysicalLink : CIM_PhysicalElement {

      [Description ( 
          "The maximum length of the PhysicalLink in feet." ), 
       Units ( "Feet" ), 
       PUnit ( "foot" )]
   real64 MaxLength;

      [Description ( 
          "The current length of the PhysicalLink in feet. For some "
          "connections, especially wireless technologies, this "
          "property may not be applicable and should be left "
          "uninitialized." ), 
       Units ( "Feet" ), 
       PUnit ( "foot" )]
   real64 Length;

      [Description ( 
          "Boolean indicating whether the PhysicalLink is an actual "
          "cable (TRUE) or a wireless connection (FALSE)." )]
   boolean Wired;

      [Description ( 
          "The MediaType property defines the particular type of "
          "Media through which transmission signals pass. Common "
          "network media include twisted-pair (value=11 or 12), "
          "coaxial (7, 8 or 9) and fiber-optic cable (10)." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11", "12", "13", "14", "15", "16", "17" }, 
       Values { "Unknown", "Other", "Cat1", "Cat2", "Cat3", "Cat4", 
          "Cat5", "50-ohm Coaxial", "75-ohm Coaxial", 
          "100-ohm Coaxial", "Fiber-optic", "UTP", "STP", 
          "Ribbon Cable", "Twinaxial", "Optical 9um", 
          "Optical 50um", "Optical 62.5um" }, 
       MappingStrings { 
          "MIF.DMTF|Fibre Channel Bus Port Extensions|001.4" }]
   uint16 MediaType;


};
