// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Physical::StoragePackage" ), 
    Description ( 
       "StorageMediaLocation is a PackageLocation where PhysicalMedia "
       "may be placed. This class is typically used in the context of "
       "a StorageLibrary. Examples of StorageMediaLocations are Media "
       "AccessDevices, InterLibraryPorts or \'slots\' in a Library\'s "
       "panel." )]
class CIM_StorageMediaLocation : CIM_PackageLocation {

      [Description ( 
          "The type of Location. For example, whether this is an "
          "individual Media \"Slot\" (value=2), a MediaAccessDevice "
          "(value=4) or a \"Magazine\" (value=3) is indicated in "
          "this property." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }, 
       Values { "Unknown", "Other", "Slot", "Magazine", 
          "MediaAccessDevice", "InterLibrary Port", 
          "Limited Access Port", "Door", "Shelf", "Vault" }]
   uint16 LocationType;

      [Description ( 
          "Certain StorageMediaLocations may only be able to accept "
          "a limited set of PhysicalMedia MediaTypes. This property "
          "defines an array containing the types of Media that are "
          "acceptable for placement in the Location. Additional "
          "information and description of the contained MediaTypes "
          "can be provided using the TypesDescription array. Also, "
          "size data (for example, DVD disc diameter) can be "
          "specified using the MediaSizesSupported array. \n"
          "\n"
          "Values defined here correspond to those in the "
          "CIM_Physical Media.MediaType property. This allows quick "
          "comparisons using value equivalence calculations. It is "
          "understood that there is no external physical difference "
          "between (for example) DVD- Video and DVD-RAM. But, "
          "equivalent values in both the Physical Media and "
          "StorageMediaLocation enumerations allows for one for one "
          "comparisons with no additional processing logic (i.e., "
          "the following is not required ... if \"DVD-Video\" then "
          "value=\"DVD\")." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11", "12", "13", "14", "15", "16", "17", "18", 
          "19", "20", "21", "22", "23", "24", "25", "26", "27", 
          "28", "29", "30", "31", "32", "33", "34", "35", "36", 
          "37", "38", "39", "40", "41", "42", "43", "44", "45", 
          "46", "47", "48", "49", "50", "51", "52", "53", "54", 
          "55", "56", "57", "58", "59", "60", "61", "62", "63", 
          "64", "65", "66" }, 
       Values { "Unknown", "Other", "Tape Cartridge", 
          "QIC Cartridge", "AIT Cartridge", "DTF Cartridge", 
          "DAT Cartridge", "8mm Tape Cartridge", 
          "19mm Tape Cartridge", "DLT Cartridge", 
          // 10               
          "Half-Inch Magnetic Tape Cartridge", 
          "Cartridge Disk", "JAZ Disk", "ZIP Disk", "SyQuest Disk", 
          "Winchester Removable Disk", "CD-ROM", "CD-ROM/XA", 
          "CD-I", "CD Recordable", 
          // 20                          
          "WORM", 
          "Magneto-Optical", "DVD", "DVD-RW+", "DVD-RAM", "DVD-ROM", 
          "DVD-Video", "Divx", "Floppy/Diskette", "Hard Disk", 
          // 30               
          "Memory Card", "Hard Copy", 
          "Clik Disk", "CD-RW", "CD-DA", "CD+", "DVD Recordable", 
          "DVD-RW", "DVD-Audio", "DVD-5", 
          // 40               
          "DVD-9", "DVD-10", 
          "DVD-18", "Magneto-Optical Rewriteable", 
          "Magneto-Optical Write Once", 
          "Magneto-Optical Rewriteable (LIMDOW)", 
          "Phase Change Write Once", "Phase Change Rewriteable", 
          "Phase Change Dual Rewriteable", "Ablative Write Once", 
          // 50               
          "Near Field Recording", 
          "MiniQic", "Travan", "8mm Metal Particle", 
          "8mm Advanced Metal Evaporate", "NCTP", "LTO Ultrium", 
          "LTO Accelis", "9 Track Tape", "18 Track Tape", 
          // 60               
          "36 Track Tape", 
          "Magstar 3590", "Magstar MP", "D2 Tape", 
          "Tape - DST Small", "Tape - DST Medium", "Tape - DST Large" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_PhysicalMedia.MediaType", 
          "CIM_StorageMediaLocation.MediaSizesSupported" }]
   uint16 MediaTypesSupported[];

      [Description ( 
          "The sizes (in inches) of the particular MediaTypes that "
          "may be placed in the Location. Note, each entry of this "
          "array is related to the entry in the MediaTypesSupported "
          "array that is located at the same index." ), 
       Units ( "Inches" ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_PhysicalMedia.MediaType", 
          "CIM_StorageMediaLocation.MediaSizesSupported", 
          "CIM_StorageMediaLocation.TypeDescriptions" }, 
       PUnit ( "inch" )]
   real32 MediaSizesSupported[];

      [Description ( 
          "A StorageMediaLocation may hold more than one "
          "PhysicalMedia - for example, a Magazine. This property "
          "indicates the Physical Media capacity of the Location." )]
   uint32 MediaCapacity;

      [Description ( 
          "This property provides additional detail related to the "
          "entries in the MediaTypesSupported array. This is "
          "especially critical when the MediaTypesSupported value "
          "is 1 (\"Other\"). Note, each entry of this array is "
          "related to the entry in MediaTypesSupported that is "
          "located at the same index." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_StorageMediaLocation.MediaTypesSupported" }]
   string TypeDescriptions[];


};
