// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Physical::Component" ), 
    Description ( 
       "The PhysicalComponent class represents any low-level or basic "
       "Component within a Package. A Component object either can not "
       "or does not need to be decomposed into its constituent parts. "
       "For example, an ASIC (or Chip) can not be further decomposed. "
       "A tape for data storage (PhysicalMedia) does not need to be "
       "decomposed. Any PhysicalElement that is not a Link, Connector, "
       "or Package is a descendent (or member) of this class. For "
       "example, the UART chipset on an internal modem Card would be a "
       "subclass (if additional properties or associations are "
       "defined) or an instance of PhysicalComponent." )]
class CIM_PhysicalComponent : CIM_PhysicalElement {

      [Description ( 
          "The RemovalCapabilites property is used to describe the "
          "conditions under which a PhysicalPackage can be removed. "
          "Since all PhysicalPackages are not removable, this "
          "property defaults to 2, \'Not Applicable\'." ), 
       ValueMap { "0", "2", "3", "4" }, 
       Values { "Unknown", "Not Applicable", "Removable when off", 
          "Removable when on or off" }]
   uint16 RemovalConditions = 2;

      [Deprecated { "CIM_PhysicalComponent.RemovalConditions" }, 
       Description ( 
          "The use of this property is being deprecated. Instead "
          "RemovalConditions should be used. The RemovalConditions "
          "property addresses whether a PhysicalComponent is "
          "removable with or without power being applied. \n"
          "\n"
          "A PhysicalComponent is Removable if it is designed to be "
          "taken in and out of the physical container in which it "
          "is normally found, without impairing the function of the "
          "overall packaging. A Component can still be Removable if "
          "power must be \'off\' in order to perform the removal. "
          "If power can be \'on\' and the Component removed, then "
          "the Element is both Removable and HotSwappable. For "
          "example, an upgradeable Processor chip is Removable." )]
   boolean Removable;

      [Deprecated { "No value" }, 
       Description ( 
          "The use of this property is being deprecated because it "
          "is redundant with the FRU class and its associations. A "
          "PhysicalComponent is Replaceable if it is possible to "
          "replace (FRU or upgrade) the Element with a physically "
          "different one. For example, some ComputerSystems allow "
          "the main Processor chip to be upgraded to one of a "
          "higher clock rating. In this case, the Processor is said "
          "to be Replaceable. All Removable Components are "
          "inherently Replaceable." )]
   boolean Replaceable;

      [Deprecated { "CIM_PhysicalComponent.RemovalConditions" }, 
       Description ( 
          "The use of this property is being deprecated. Instead "
          "RemovalConditions should be used. The RemovalConditions "
          "property addresses whether a PhysicalComponent is "
          "removable with or without power being applied. \n"
          "\n"
          "A PhysicalComponent is HotSwappable if it is possible to "
          "replace the Element with a physically different but "
          "equivalent one while the containing Package has power "
          "applied to it (ie, is \'on\'). For example, a fan "
          "Component may be designed to be HotSwappable. All "
          "HotSwappable Components are inherently Removable and "
          "Replaceable." )]
   boolean HotSwappable;


};
