// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_LinkHasConnector 
// ==================================================================
   [Association, Aggregation, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Physical::Link" ), 
    Description ( 
       "Cables and Links utilize PhysicalConnectors to actually "
       "\'connect\' PhysicalElements. This association explicitly "
       "defines this relationship of Connectors for PhysicalLinks." )]
class CIM_LinkHasConnector : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( "The PhysicalLink that has a Connector." )]
   CIM_PhysicalLink REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "The PhysicalConnector." )]
   CIM_PhysicalConnector REF PartComponent;


};
