// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Physical::Connector" ), 
    Description ( 
       "AdjacentSlots describes the layout of Slots on a HostingBoard "
       "or adapter Card. Information like the distance between the "
       "Slots and whether they are \'shared\' (if one is populated, "
       "then the other Slot can not be used), is conveyed as "
       "properties of the association." )]
class CIM_AdjacentSlots {

      [Key, Description ( "One of the adjacent Slots." )]
   CIM_Slot REF SlotA;

      [Key, Description ( "The \'other\' adjacent Slot." )]
   CIM_Slot REF SlotB;

      [Description ( 
          "The distance, in inches, between adjacent Slots." ), 
       Units ( "Inches" ), 
       PUnit ( "inch" )]
   real32 DistanceBetweenSlots;

      [Description ( 
          "Slots can be located in close proximity on Hosting "
          "Boards or other Cards, such that if one of these Slots "
          "is populated by an adapter Card, the other Slot must be "
          "left empty. This relationship is indicated by the "
          "SharedSlots boolean set to TRUE." )]
   boolean SharedSlots;


};
