TOP = ../..
include $(TOP)/config.mak

LIBRARY = nitsbase

SOURCES = Frame.cpp \
    Globals.cpp \
    nits_c.cpp \
    nitsdll.cpp \
    Run.cpp \
    Switch.cpp \
    LocalInjection.cpp \

DEFINES = UNICODE

INCLUDES = . $(TOP) $(TOP)/common

LIBRARIES = 

include $(TOP)/mak/rules.mak
