TOP = ..
include $(TOP)/config.mak

CXXSHLIBRARY = xmlcxx

SOURCES = xmlcxx.cpp

INCLUDES = $(TOP) $(TOP)/common

LIBRARIES = xml base

DEFINES = BUILDING_XMLCXX

include $(TOP)/mak/rules.mak
