// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "IdentificationOfManagedSystem is an association that links the "
       "SystemIdentification object to the CIM_System(s) that are "
       "being identified and represented in the Namespace." )]
class CIM_IdentificationOfManagedSystem : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The System which is identified." )]
   CIM_System REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( "The SystemIdentification information." )]
   CIM_SystemIdentification REF Dependent;


};
