// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_CommMechanismForObjectManagerAdapter" }, 
    Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "CommMechanismForAdapter is an association between an "
       "ObjectManager\'s communication mechanism and a ProtocolAdapter "
       "that supports that mechanism to translate requests and "
       "responses for the Object Manager." )]
class CIM_CommMechanismForAdapter : CIM_Dependency {

      [Deprecated { 
          "CIM_CommMechanismForObjectManagerAdapter.Antecedent" }, 
       Override ( "Antecedent" ), 
       Description ( 
          "The specific ProtocolAdapter whose communication "
          "mechanism with the CIM Object Manager is described." )]
   CIM_ProtocolAdapter REF Antecedent;

      [Deprecated { 
          "CIM_CommMechanismForObjectManagerAdapter.Dependent" }, 
       Override ( "Dependent" ), 
       Min ( 1 ), 
       Description ( 
          "The encoding/protocol/set of operations that may be used "
          "to communicate between the Object Manager and the "
          "referenced ProtocolAdapter." )]
   CIM_ObjectManagerCommunicationMechanism REF Dependent;


};
