TOP = ../..
include $(TOP)/config.mak

CXXPROGRAM = striplic

SOURCES = striplic.cpp 

INCLUDES = $(TOP) $(TOP)/common

MAKEDEPSRCDIR=1

SUPPRESS_CCTOOL=1

SUPPRESS_STDERRX=1

include $(TOP)/mak/rules.mak
