class OMI_Identify
{
    [Key] String InstanceID;
    String SystemName;
    String ProductName;
    String ProductVendor;
    Uint32 ProductVersionMajor;
    Uint32 ProductVersionMinor;
    Uint32 ProductVersionRevision;
    String ProductVersionString;
    String Platform;
    String OperatingSystem;
    String Architecture;
    String Compiler;
    String ConfigPrefix;
    String ConfigLibDir;
    String ConfigBinDir;
    String ConfigIncludeDir;
    String ConfigDataDir;
    String ConfigLocalStateDir;
    String ConfigSysConfDir;
    String ConfigProviderDir;
    String ConfigLogFile;
    String ConfigPIDFile;
    String ConfigRegisterDir;
    String ConfigSchemaDir;
    String ConfigNameSpaces[];
};
