// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AuthenticationService 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "CIM_AuthenticationService verifies users\' identities through "
       "some means. These services are decomposed into a subclass that "
       "provides credentials to users and a subclass that provides for "
       "the verification of the validity of a credential and, perhaps, "
       "the appropriateness of its use for access to target resources. "
       "The persistent state information used from one such "
       "verification to another is maintained in an instance of "
       "Identity class." )]
class CIM_AuthenticationService : CIM_SecurityService {


};
