// Copyright (c) 2012 DMTF.  All rights reserved.
   [Experimental, Version ( "2.32.0" ), 
    UMLPackagePath ( "CIM::Network" ), 
    Description ( 
       "This class describes the configuration of a network policy "
       "rule. Typically, this network policy service corresponds to an "
       "abstraction of the service within a domain (for example, an "
       "orchestration layer)." )]
class CIM_NetworkPolicyRuleSettingData : CIM_SettingData {


};
