// ===============================================================
//  MSFT_InterfaceCollection
// ===============================================================
	[Description ( "MSFT_InterfaceCollection description." ), 
	Association]
class MSFT_InterfaceCollection: CIM_Component 
{
	
	   [Override ( "GroupComponent" ), 
       Description ( "The parent System in the Association." )]
   CIM_EthernetPort REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The child element that is a component of a System." )]
   MSFT_SubInterface REF PartComponent;
};
