// ===============================================================
//  MSFT_NetworkACLService
// ===============================================================
	[Description ( "MSFT_NetworkACLService description." ), 
	Version ( "0.70" )]
class MSFT_NetworkACLService : CIM_NetworkPolicyService
{

       [Description ( 
          "Creates ande Names a new ACL" ),
       ValueMap { "0",  "4096", "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error", "Job Started", 
	             "Method Reserved", "Vendor Specific" }]
       uint32 CreateACL(
          
       [Description ( 
             "A string an containing an embedded "
             "instance of class\subclass MSFT_ACL a subclass of "
             "CIM_NetworkPolicyRule that is the top level name for an ordered set of rules "
              ),
       EmbeddedInstance ( "MSFT_ACL" ) ]
	   String AccessList,        
         
         [In ( false ), Out, Description ( 
             "If a the ACL creation is successfully, "
             "reference to an instance of class "
             "CIM_NetworkPolicyRule that represents the newly "
             "created ACL is returned." )]
         MSFT_ACL REF ResultingACL, 

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);


	  [Description ( 
          "Adds a rule an array of conditions and an action to an existing ACL" ),
       ValueMap { "0",  "4096", "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error", "Job Started", 
	             "Method Reserved", "Vendor Specific" }]
   uint32 AddRule(
        [Description ( 
             "Reference to the targeted ACL to add the Rule. This should be an instance of MSFT_ACL"
			 
              )]
        MSFT_ACL REF TargetACL, 


	   [Description ( 
             "A string an containing an embedded "
             "instance of class\subclass of "
             "CIM_NetworkPolicyRule"
			 "This rule has an associated array of conditions and actions  The way the conditions are"
			 "evaluated are contained in the rule"
              ),
          EmbeddedInstance ( "CIM_NetworkPolicyRule" ) ]
		  String NetworkPolicyRule, 
       
	   [Description ( 
             "The conditions for the rule. A string containing an array of embedded "
             "instance of class\subclass of "
             "CIM_NetworkPolicyCondition"
              ),
          EmbeddedInstance ( "CIM_NetworkPolicyCondition" ) ]
		  String NetworkPolicyCondition[], 

		   [Description ( 
             "The action to take if the condition evaluate true. A string containing an embedded array of instances"
             "of class\subclass of "
             "CIM_NetworkPolicyAction. "
              ),
          EmbeddedInstance ( "CIM_NetworkPolicyAction" ) ]
		  String NetworkPolicyAction[], 


		   [Description ( 
             "There can be many rules."
              "The sequence-number argument can be a whole number"
              "between 1 and 4294967295"             
              )
           ]
		  uint32 SequenceNumber, 


      [In ( false ), Out, Description ( 
             "If a the Rule creation is successfully, "
             "reference to an instance of class "
             "CIM_NetworkPolicyRule that represents the newly "
             "created ACL is returned." )]
      CIM_NetworkPolicyRule REF ResultingNetworkPolicyRule, 

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	   [Description ( 
          "Removes and ACL and all associated Rules\n"
          "The referenced ACL is removed from the system, including "
          "any rules associated with it. "
           ), 
       ValueMap { "0", "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Job Started", 
          "Method Reserved", "Vendor Specific" }]
       uint32 RemoveACL(
       [Description ( 
             "Reference to an instance of class "
             "MSFT_ACL representing the ACL "
             "to be removed from the system" )]
      MSFT_ACL REF RemovedACL, 
         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	  [Description ( 
          "Removes a network policy rule\n"
          "The referenced rule is removed from the  ACL "
		  "There is no modify Rule operation. To modify a rule a new rule must be added"
		  "and the rule to be modified removed."
           ), 
       ValueMap { "0", "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Job Started", 
          "Method Reserved", "Vendor Specific" }]
       uint32 RemoveRule(
         [Description ( 
             "Reference to an instance of class "
             "CIM_NetworkPolicyRule representing the rule "
             "to be removed from the system" )]
      CIM_NetworkPolicyRule REF RemovedRule, 
         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	  [Description ( 
          "Changes the sequence number of a  network policy rule\n"
       ), 
       ValueMap { "0", "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Job Started", 
          "Method Reserved", "Vendor Specific" }]
       uint32 ResequenceRule(
       [Description ( 
             "Reference to an instance of class "
             "CIM_NetworkPolicyRule representing the rule "
             "to be resequenced" )]
        CIM_NetworkPolicyRule REF TargetRule, 

	   [Description ( 
             "New sequence number"
              "The sequence-number argument can be a whole number"
              "between 1 and 4294967295"             
              )
       ]
	   uint32 SequenceNumber, 

       [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

	  [Description ( 
          "Attaches an ACL and all associated Rules to an interface\n"
          
           ), 
       ValueMap { "0", "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Job Started", 
          "Method Reserved", "Vendor Specific" }]
       uint32 AttachACL(
       
	   [Description ( 
             "Reference to an instance of class "
             "MSFT_ACL to be applied "
              )]
      MSFT_ACL REF AttachedACL, 
	  
	  [Description ( 
             "Reference to a managed element that the "
             "MSFT_ACL is to be applied "
              )]
        CIM_ManagedElement REF TargetInterface, 
       [Description ( 
          "Direction the ACL applies to"), 
       ValueMap { "2", "3"}, 
       Values { "In", "Out"}

	]
     uint16 Direction,
 
 
         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);


	 [Description ( 
          "Attaches an VACL and all associated Rules to an interface\n"
          
           ), 
       ValueMap { "0", "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Job Started", 
          "Method Reserved", "Vendor Specific" }]
       uint32 AttachVACL(
       
	   [Description ( 
             "Reference to an instance of class "
             "MSFT_ACL to be applied "
              )]
      MSFT_ACL REF AttachedVACL, 
	  
	  [Description ( 
             "Reference to a managed element that the "
             "MSFT_ACL is to be applied "
              )]
        CIM_NetworkVLAN REF TargetInterface, 
       

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

    [Description ( 
          "Detaches an ACL and all associated Rules from an interface\n"
          
           ), 
       ValueMap { "0", "4096", 
          "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error",
          "Job Started", 
          "Method Reserved", "Vendor Specific" }]
       uint32 DetachACL(
   
   [Description ( 
             "Reference to an instance of class "
             "MSFT_ACL to be detached "
              )]
      MSFT_ACL REF AttachedACL, 
	  
	  [Description ( 
             "Reference to a managed element from which the "
             "MSFT_ACL is to be detached "
              )]
        CIM_ManagedElement REF TargetInterface, 
 
     [Description ( 
          "Direction the ACL applies to"), 
       ValueMap { "2", "3"}, 
       Values { "In", "Out"}

	]
     uint16 Direction,
 

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);
	


	  [Description ( 
          "Adds a rule an array of conditions and an action to an existing ACL" ),
       ValueMap { "0",  "4096", "4097..32767", "32768..65535" }, 
       Values { "Completed with No Error", "Job Started", 
	             "Method Reserved", "Vendor Specific" }]
   uint32 AddRuleWithMatchedACL(
        [Description ( 
             "Reference to the targeted ACL to add the rule with the match. This should be an instance of MSFT_ACL"
			 
              )]
        MSFT_ACL REF TargetACL, 


	   [Description ( 
             "A string an containing an embedded "
             "instance of class\subclass of "
             "CIM_NetworkPolicyRule"
			 "This rule has an associated array of conditions and actions  The way the conditions are"
			 "evaluated are contained in the rule"
              ),
          EmbeddedInstance ( "CIM_NetworkPolicyRule" ) ]
		  String NetworkPolicyRule, 

		[Description ( 
             "Array of References to the ACLs that this rule will match.  "
			 
              )]
        MSFT_ACL REF MatchedACLs[], 
       
	  

		   [Description ( 
             "The action to take if the condition evaluate true. A string containing an embedded array of instances"
             "of class\subclass of "
             "CIM_NetworkPolicyAction. "
              ),
          EmbeddedInstance ( "CIM_NetworkPolicyAction" ) ]
		  String NetworkPolicyAction[], 


		   [Description ( 
             "There can be many rules."
              "The sequence-number argument can be a whole number"
              "between 1 and 4294967295"             
              )
           ]
		  uint32 SequenceNumber, 


      [In ( false ), Out, Description ( 
             "If a the Rule creation is successfully, "
             "reference to an instance of class "
             "CIM_NetworkPolicyRule that represents the newly "
             "created ACL is returned." )]
      CIM_NetworkPolicyRule REF ResultingNetworkPolicyRule, 

         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);
	  


};
