// ===============================================================
//  MSFT_SpanningTree
// ===============================================================
	[Description ( "MSFT_SpanningTree describes the spanning tree properties for an associated port." ), 
	Version ( "0.70" )]
class MSFT_SpanningTree : CIM_ProtocolEndpoint 
{


   [Description ( 
          "An enumeration indicating the spanningtree modes of the associated ports. "
         ), 
       ValueMap {   "2", "3", "4" }, 
       Values { "Edge", "Trunk", "Normal" } 
   ]
   uint16 PortType[];


};
