// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DirectorySpecificationFile 
// ==================================================================
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Application::CheckAction" ), 
    Description ( 
       "The CIM_DirectorySpecificationFile association identifies the "
       "directory that contains the file being checked in the CIM_ "
       "FileSpecification class." )]
class CIM_DirectorySpecificationFile {

      [Key, Max ( 1 ), 
       Description ( "The directory to be checked." )]
   CIM_DirectorySpecification REF DirectorySpecification;

      [Key, Description ( "The file to be checked." )]
   CIM_FileSpecification REF FileSpecification;


};
