// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeServer 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "The CIM_J2eeServer class represents the J2EE Server core of "
       "one instance of a J2EE platform product as described in the "
       "Java 2 Enterprise Edition Platform specification." )]
class CIM_J2eeServer : CIM_ApplicationSystem {

      [Override ( "Name" ), 
       Description ( 
          "The name of a J2EE Server. The name MUST be constructed "
          "using the form specified in JSR77.3.1.1.1 in order to "
          "avoid the need for manual key propagation." ), 
       MaxLen ( 256 ), 
       MappingStrings { "JSR77.JCP|JSR77.3.1.1.1 objectName|V1.0" }]
   string Name;

      [Description ( "The name of the server\'s vendor." ), 
       MappingStrings { "JSR77.JCP|JSR77.3.3.1.4 serverVendor|V1.0" }]
   string Vendor;

      [Description ( 
          "The J2EE implementation version of the J2EE server." ), 
       MappingStrings { "JSR77.JCP|JSR77.3.3.1.5 serverVersion|V1.0" }]
   string Version;


};
