// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeModule 
// ==================================================================
   [Abstract, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "The CIM_J2eeModule class is an abstract class from which all "
       "J2EE module type classes extend. These represent EAR, JAR, "
       "WAR, and RAR files that have been deployed." )]
class CIM_J2eeModule : CIM_J2eeDeployedObject {


};
