// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeResourceOnServer 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "CIM_J2eeResourceOnServer is an association that establishes "
       "the relationship between a J2EE server and its resources." )]
class CIM_J2eeResourceOnServer : CIM_ResourceOfSystem {

      [Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The Server exposing the resources." )]
   CIM_J2eeServer REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The resource that is a component of the server." )]
   CIM_J2eeResource REF PartComponent;


};
