// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ApplicationSystemSoftwareFeature 
// ==================================================================
   [Association, Aggregation, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Application::DeploymentModel" ), 
    Description ( 
       "The ApplicationSystemSoftwareFeature association identifies "
       "the Features that make up a particular ApplicationSystem. The "
       "SoftwareFeatures can be scoped by different Products." )]
class CIM_ApplicationSystemSoftwareFeature : CIM_SystemComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "The ApplicationSystem that aggregates the Features." )]
   CIM_ApplicationSystem REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "The Features in an ApplicationSystem." )]
   CIM_SoftwareFeature REF PartComponent;


};
