// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeServerInDomain 
// ==================================================================
   [Association, Aggregation, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "The CIM_J2eeServerInDomain association identifies the J2EE "
       "Server that are part of a J2EE Domain for management purposes." )]
class CIM_J2eeServerInDomain : CIM_SystemComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The J2ee Management Domain." )]
   CIM_J2eeDomain REF GroupComponent;

      [Override ( "PartComponent" ), 
       Min ( 1 ), 
       Description ( 
          "The J2ee Server that is a member of the domain." )]
   CIM_J2eeServer REF PartComponent;


};
