// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ApplicationSystemHierarchy 
// ==================================================================
   [Association, Aggregation, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::AppRuntime" ), 
    Description ( 
       "Application systems may have arbitrarily complex structures. "
       "It may be necessary to build application system hierarchies "
       "including the two-step hierarchy of distributed and local "
       "systems. ApplicationSystemHierarchy allows building "
       "containment trees (only one parent at a time). It should not "
       "be used to express use-relationships; use "
       "CIM_ApplicationSystemDependency instead." )]
class CIM_ApplicationSystemHierarchy : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( 
          "The parent ApplicationSystem in the association." )]
   CIM_ApplicationSystem REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The child ApplicationSystem in the association." )]
   CIM_ApplicationSystem REF PartComponent;


};
