// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeStatelessSessionBean 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "Identifies a deployed stateless session bean within an EJB module."
        )]
class CIM_J2eeStatelessSessionBean : CIM_J2eeSessionBean {


};
