// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeSessionBeanStats 
// ==================================================================
   [Abstract, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServerStats" ), 
    Description ( 
       "The J2eeSessionBeanStats class is a base class that defines "
       "the performance statistics that are provided by both stateful "
       "and stateless session beans." )]
class CIM_J2eeSessionBeanStats : CIM_J2eeEJBStats {

      [Description ( 
          "The number of bean instances in the method-ready state." ), 
       Counter, MappingStrings { 
          "JSR77.JCP|JSR77.6.14.1.1 getMethodReadyCount|V1.0" }]
   uint64 MethodReadyCount;

      [Description ( 
          "The lowest number of bean instances in the method-ready "
          "state since the beginning of the measurement." ), 
       MappingStrings { 
          "JSR77.JCP|JSR77.6.7.1.2 getLowWaterMark|V1.0" }]
   uint64 MethodReadyLowWaterMark;

      [Description ( 
          "The highest number of bean instances in the method-ready "
          "state since the beginning of the measurement." ), 
       MappingStrings { 
          "JSR77.JCP|JSR77.6.7.1.1 getHighWaterMark|V1.0" }]
   uint64 MethodReadyHighWaterMark;


};
