// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeApplicationModule 
// ==================================================================
   [Association, Aggregation, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "The CIM_J2eeApplicationModule association identifies a "
       "software module for a particular J2EE Application." )]
class CIM_J2eeApplicationModule : CIM_SystemComponent {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "The J2ee Application that is comprised of modules." )]
   CIM_J2eeApplication REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The Module that is part of a J2ee Application." )]
   CIM_J2eeModule REF PartComponent;


};
