// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_VideoBIOSFeatureVideoBIOSElements 
// ==================================================================
   [Association, Aggregation, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Application::BIOS" ), 
    Description ( 
       "A link between VideoBIOSFeature and its aggregated VideoBIOSElements."
        )]
class CIM_VideoBIOSFeatureVideoBIOSElements : CIM_SoftwareFeatureSoftwareElements {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( "The VideoBIOSFeature." )]
   CIM_VideoBIOSFeature REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The VideoBIOSElement that implements the capabilities "
          "described by VideoBIOSFeature." )]
   CIM_VideoBIOSElement REF PartComponent;


};
