// Copyright 1998-2008 Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.
// DMTF is a not-for-profit association of industry members dedicated
// to promoting enterprise and systems management and interoperability.
// DMTF specifications and documents may be reproduced by
// members and non-members, provided that correct attribution is given.
// As DMTF specifications may be revised from time to time,
// the particular version and release date should always be noted.
// 
// Implementation of certain elements of this standard or proposed
// standard may be subject to third party patent rights, including
// provisional patent rights (herein "patent rights"). DMTF makes
// no representations to users of the standard as to the existence
// of such rights, and is not responsible to recognize, disclose, or
// identify any or all such third party patent right, owners or
// claimants, nor for any incomplete or inaccurate identification or
// disclosure of such rights, owners or claimants. DMTF shall have no
// liability to any party, in any manner or circumstance, under any
// legal theory whatsoever, for failure to recognize, disclose, or
// identify any such third party patent rights, or for such party's
// reliance on the standard or incorporation thereof in its product,
// protocols or testing procedures. DMTF shall have no liability to
// any party implementing such standard, whether such implementation
// is foreseeable or not, nor to any patent owner or claimant, and shall
// have no liability or responsibility for costs or losses incurred if
// a standard is withdrawn or modified after publication, and shall be
// indemnified and held harmless by any party implementing the
// standard from any and all claims of infringement by a patent owner
// for such implementations.
// 
// For information about patents held by third-parties which have
// notified the DMTF that, in their opinion, such patent may relate to
// or impact implementations of DMTF standards, visit
// http://www.dmtf.org/about/policies/disclosures.php.
#pragma locale ("en_US")
#pragma include ("qualifiers.mof")
#pragma include ("qualifiers_optional.mof")
#pragma include ("Core/CIM_ManagedElement.mof")
#pragma include ("Core/CIM_ManagedSystemElement.mof")
#pragma include ("Core/CIM_MethodParameters.mof")
#pragma include ("Core/CIM_ParametersForMethod.mof")
#pragma include ("Core/CIM_ParameterValueSources.mof")
#pragma include ("Core/CIM_PhysicalElement.mof")
#pragma include ("Core/CIM_Product.mof")
#pragma include ("Core/CIM_ProductParentChild.mof")
#pragma include ("Core/CIM_ProductPhysicalElements.mof")
#pragma include ("Core/CIM_ProductProductDependency.mof")
#pragma include ("Core/CIM_SettingData.mof")
#pragma include ("Core/CIM_SettingsDefineState.mof")
#pragma include ("Core/CIM_StatisticalData.mof")
#pragma include ("Core/CIM_StatisticalInformation.mof")
#pragma include ("Core/CIM_StatisticalSetting.mof")
#pragma include ("Core/CIM_Statistics.mof")
#pragma include ("Core/CIM_SupportAccess.mof")
#pragma include ("Core/CIM_Synchronized.mof")
#pragma include ("Core/CIM_SystemConfiguration.mof")
#pragma include ("Core/CIM_SystemStatisticalInformation.mof")
#pragma include ("Core/CIM_View.mof")
#pragma include ("Core/CIM_VirtualSystemSettingData.mof")
#pragma include ("Database/CIM_CommonDatabaseSettingData.mof")
#pragma include ("Database/CIM_CommonDatabaseStatistics.mof")
#pragma include ("Database/CIM_DatabaseResourceStatistics.mof")
#pragma include ("Database/CIM_DatabaseServiceStatistics.mof")
#pragma include ("Device/CIM_BlockStatisticsManifest.mof")
#pragma include ("Device/CIM_BlockStorageStatisticalData.mof")
#pragma include ("Device/CIM_DeviceErrorCounts.mof")
#pragma include ("Device/CIM_DeviceErrorData.mof")
#pragma include ("Device/CIM_FCPortRateStatistics.mof")
#pragma include ("Device/CIM_FCSwitchSettings.mof")
#pragma include ("Device/CIM_LabelReaderStatData.mof")
#pragma include ("Device/CIM_LogicalPortSettings.mof")
#pragma include ("Device/CIM_MediaAccessStatData.mof")
#pragma include ("Device/CIM_NetworkPortStatistics.mof")
#pragma include ("Device/CIM_PickerStatData.mof")
#pragma include ("Device/CIM_SCSIMultipathSettings.mof")
#pragma include ("Device/CIM_StorageError.mof")
#pragma include ("Device/CIM_StorageSetting.mof")
#pragma include ("Device/CIM_StorageSettingWithHints.mof")
#pragma include ("Device/CIM_StorageSynchronized.mof")
#pragma include ("Device/CIM_TokenRingPortStatistics.mof")
#pragma include ("Device/CIM_VideoHeadResolution.mof")
#pragma include ("Event/CIM_Indication.mof")
#pragma include ("Event/CIM_IndicationFilter.mof")
#pragma include ("Event/CIM_IndicationServiceSettingData.mof")
#pragma include ("Event/CIM_InstIndication.mof")
#pragma include ("Event/CIM_InstMethodCall.mof")
#pragma include ("Event/CIM_InstModification.mof")
#pragma include ("Event/CIM_InstRead.mof")
#pragma include ("Event/CIM_ListenerDestination.mof")
#pragma include ("Event/CIM_ListenerDestinationCIMXML.mof")
#pragma include ("Event/CIM_ListenerDestinationWSManagement.mof")
#pragma include ("Event/CIM_ProcessIndication.mof")
#pragma include ("Event/CIM_SNMPTrapIndication.mof")
#pragma include ("Interop/CIM_CIMOMStatisticalData.mof")
#pragma include ("Interop/CIM_Error.mof")
#pragma include ("Interop/CIM_Namespace.mof")
#pragma include ("Interop/CIM_RegisteredProfile.mof")
#pragma include ("Interop/CIM_RegisteredSubProfile.mof")
#pragma include ("Interop/CIM_SystemIdentification.mof")
#pragma include ("Interop/CIM_SystemInNamespace.mof")
#pragma include ("Metrics/CIM_BaseMetricDefinition.mof")
#pragma include ("Metrics/CIM_BaseMetricValue.mof")
#pragma include ("Metrics/CIM_MetricDefinition.mof")
#pragma include ("Metrics/CIM_TraceLevelType.mof")
#pragma include ("Metrics/CIM_UnitOfWork.mof")
#pragma include ("Network/CIM_BGPEndpointStatistics.mof")
#pragma include ("Network/CIM_CLPSettingData.mof")
#pragma include ("Network/CIM_ConnectivityMembershipSettingData.mof")
#pragma include ("Network/CIM_IEEE8021xSettings.mof")
#pragma include ("Network/CIM_IPAssignmentSettingData.mof")
#pragma include ("Network/CIM_IPVersionSettingData.mof")
#pragma include ("Network/CIM_iSCSIConnectionSettings.mof")
#pragma include ("Network/CIM_iSCSILoginStatistics.mof")
#pragma include ("Network/CIM_iSCSISessionFailures.mof")
#pragma include ("Network/CIM_iSCSISessionSettings.mof")
#pragma include ("Network/CIM_NextHopRoute.mof")
#pragma include ("Network/CIM_SAEndpointConnectionStatistics.mof")
#pragma include ("Network/CIM_SAEndpointRefreshSettings.mof")
#pragma include ("Network/CIM_SchedulingElement.mof")
#pragma include ("Network/CIM_SSHSettingData.mof")
#pragma include ("Network/CIM_StaticIPAssignmentSettingData.mof")
#pragma include ("Network/CIM_TelnetSettingData.mof")
#pragma include ("Network/CIM_VLANEndpointSettingData.mof")
#pragma include ("Network/CIM_WiFiEndpointSettings.mof")
#pragma include ("Network/CIM_WiFiNetworkDetectionSettings.mof")
#pragma include ("Network/CIM_WRRSchedulingElement.mof")
#pragma include ("Physical/CIM_MediaPhysicalStatData.mof")
#pragma include ("Physical/CIM_PhysicalCapacity.mof")
#pragma include ("Physical/CIM_PhysicalComponent.mof")
#pragma include ("Physical/CIM_PhysicalConnector.mof")
#pragma include ("Physical/CIM_PhysicalLink.mof")
#pragma include ("Physical/CIM_PhysicalMedia.mof")
#pragma include ("Physical/CIM_PhysicalPackage.mof")
#pragma include ("Physical/CIM_PhysicalTape.mof")
#pragma include ("Physical/CIM_Slot.mof")
#pragma include ("Policy/CIM_Policy.mof")
#pragma include ("Policy/CIM_PolicyAction.mof")
#pragma include ("Policy/CIM_PolicyCondition.mof")
#pragma include ("Policy/CIM_PolicySet.mof")
#pragma include ("Policy/CIM_PolicySetAppliesToElement.mof")
#pragma include ("Policy/CIM_PolicyTimePeriodCondition.mof")
#pragma include ("Policy/CIM_QueryCondition.mof")
#pragma include ("Policy/CIM_RejectConnectionAction.mof")
#pragma include ("Policy/CIM_VendorPolicyAction.mof")
#pragma include ("Policy/CIM_VendorPolicyCondition.mof")
#pragma include ("Support/PRS_ExchangeElement.mof")
#pragma include ("Support/PRS_ExpressionElement.mof")
#pragma include ("Support/PRS_Feature.mof")
#pragma include ("Support/PRS_Location.mof")
#pragma include ("Support/PRS_Product.mof")
#pragma include ("Support/PRS_Resource.mof")
#pragma include ("Support/PRS_Revision.mof")
#pragma include ("Support/PRS_ServiceIncident.mof")
#pragma include ("Support/PRS_Solution.mof")
#pragma include ("Support/PRS_SolutionElement.mof")
#pragma include ("Support/PRS_Statement.mof")
#pragma include ("Support/PRS_Transaction.mof")
#pragma include ("System/CIM_BIOSAttribute.mof")
#pragma include ("System/CIM_BIOSEnumeration.mof")
#pragma include ("System/CIM_BIOSInteger.mof")
#pragma include ("System/CIM_BIOSPassword.mof")
#pragma include ("System/CIM_BIOSString.mof")
#pragma include ("System/CIM_BootSettingData.mof")
#pragma include ("System/CIM_BootSourceSetting.mof")
#pragma include ("System/CIM_DiagnosticResult.mof")
#pragma include ("System/CIM_DiagnosticResultForMSE.mof")
#pragma include ("System/CIM_DiagnosticResultInPackage.mof")
#pragma include ("System/CIM_DiagnosticSettingData.mof")
#pragma include ("System/CIM_JobSettingData.mof")
#pragma include ("System/CIM_MethodResult.mof")
#pragma include ("System/CIM_RecordForLog.mof")
#pragma include ("System/CIM_UnixProcessStatisticalInformation.mof")
#pragma include ("User/CIM_AccountSettingData.mof")
#pragma include ("User/CIM_AssociatedPrivilege.mof")
#pragma include ("User/CIM_Credential.mof")
#pragma include ("User/CIM_CredentialContext.mof")
#pragma include ("User/CIM_Identity.mof")
#pragma include ("User/CIM_IdentityContext.mof")
#pragma include ("User/CIM_IPNetworkIdentity.mof")
#pragma include ("User/CIM_KerberosCredential.mof")
#pragma include ("User/CIM_KerberosTicket.mof")
#pragma include ("User/CIM_NamedCredential.mof")
#pragma include ("User/CIM_NamedSharedIKESecret.mof")
#pragma include ("User/CIM_OpaqueManagementDataOwner.mof")
#pragma include ("User/CIM_OrganizationalEntity.mof")
#pragma include ("User/CIM_OrgStructure.mof")
#pragma include ("User/CIM_OrgUnit.mof")
#pragma include ("User/CIM_OtherGroupInformation.mof")
#pragma include ("User/CIM_OtherOrganizationInformation.mof")
#pragma include ("User/CIM_OtherOrgUnitInformation.mof")
#pragma include ("User/CIM_OtherPersonInformation.mof")
#pragma include ("User/CIM_OtherRoleInformation.mof")
#pragma include ("User/CIM_Privilege.mof")
#pragma include ("User/CIM_SecuritySensitivity.mof")
#pragma include ("User/CIM_SharedCredential.mof")
#pragma include ("User/CIM_SharedSecret.mof")
#pragma include ("User/CIM_SignedCredential.mof")
#pragma include ("User/CIM_StorageClientSettingData.mof")
#pragma include ("User/CIM_StorageHardwareID.mof")
#pragma include ("User/CIM_UnsignedCredential.mof")
#pragma include ("User/CIM_UnsignedPublicKey.mof")
#pragma include ("User/CIM_UserEntity.mof")
#pragma include ("User/CIM_UsersAccess.mof")
#pragma include ("User/CIM_X509Infrastructure.mof")
#pragma include ("Application/CIM_J2eeNotification.mof")
#pragma include ("Application/CIM_J2eeStatistic.mof")
#pragma include ("Application/CIM_J2eeURLStats.mof")
#pragma include ("Application/CIM_StatisticalRuntimeOverview.mof")
#pragma include ("Core/CIM_Capabilities.mof")
#pragma include ("Core/CIM_Collection.mof")
#pragma include ("Core/CIM_CollectionOfMSEs.mof")
#pragma include ("Core/CIM_CompatibleProduct.mof")
#pragma include ("Core/CIM_Component.mof")
#pragma include ("Core/CIM_ConcreteCollection.mof")
#pragma include ("Core/CIM_ConcreteComponent.mof")
#pragma include ("Core/CIM_Configuration.mof")
#pragma include ("Core/CIM_ConfigurationComponent.mof")
#pragma include ("Core/CIM_Dependency.mof")
#pragma include ("Core/CIM_DependencyContext.mof")
#pragma include ("Core/CIM_DeviceStatisticalInformation.mof")
#pragma include ("Core/CIM_ElementCapabilities.mof")
#pragma include ("Core/CIM_ElementConfiguration.mof")
#pragma include ("Core/CIM_ElementSettingData.mof")
#pragma include ("Core/CIM_ElementStatisticalData.mof")
#pragma include ("Core/CIM_EnabledLogicalElementCapabilities.mof")
#pragma include ("Core/CIM_FRU.mof")
#pragma include ("Core/CIM_FRUIncludesProduct.mof")
#pragma include ("Core/CIM_FRUPhysicalElements.mof")
#pragma include ("Core/CIM_HostedDependency.mof")
#pragma include ("Core/CIM_LaunchInContextCapabilities.mof")
#pragma include ("Core/CIM_LocalizationCapabilities.mof")
#pragma include ("Core/CIM_Location.mof")
#pragma include ("Core/CIM_LogicalElement.mof")
#pragma include ("Core/CIM_LogicalIdentity.mof")
#pragma include ("Core/CIM_MemberOfCollection.mof")
#pragma include ("Core/CIM_OpaqueManagementDataCapabilities.mof")
#pragma include ("Core/CIM_OrderedComponent.mof")
#pragma include ("Core/CIM_OrderedDependency.mof")
#pragma include ("Core/CIM_OrderedMemberOfCollection.mof")
#pragma include ("Core/CIM_OwningCollectionElement.mof")
#pragma include ("Core/CIM_PhysicalStatisticalInformation.mof")
#pragma include ("Core/CIM_PhysicalStatistics.mof")
#pragma include ("Core/CIM_PowerManagementCapabilities.mof")
#pragma include ("Core/CIM_PowerUtilizationManagementCapabilities.mof")
#pragma include ("Core/CIM_ProductComponent.mof")
#pragma include ("Core/CIM_ProductElementComponent.mof")
#pragma include ("Core/CIM_ProductFRU.mof")
#pragma include ("Core/CIM_ProductPhysicalComponent.mof")
#pragma include ("Core/CIM_ProductSupport.mof")
#pragma include ("Core/CIM_Profile.mof")
#pragma include ("Core/CIM_RedundancyGroup.mof")
#pragma include ("Core/CIM_RelatedStatisticalData.mof")
#pragma include ("Core/CIM_RelatedStatistics.mof")
#pragma include ("Core/CIM_ReplaceableProductFRU.mof")
#pragma include ("Core/CIM_ResourceAllocationSettingData.mof")
#pragma include ("Core/CIM_ResourcePool.mof")
#pragma include ("Core/CIM_ResourcePoolConfigurationCapabilities.mof")
#pragma include ("Core/CIM_SAPStatisticalInformation.mof")
#pragma include ("Core/CIM_ScopedSettingData.mof")
#pragma include ("Core/CIM_ServiceStatisticalInformation.mof")
#pragma include ("Core/CIM_Setting.mof")
#pragma include ("Core/CIM_SettingAssociatedToCapabilities.mof")
#pragma include ("Core/CIM_SettingContext.mof")
#pragma include ("Core/CIM_SettingsDefineCapabilities.mof")
#pragma include ("Core/CIM_SoftwareIdentity.mof")
#pragma include ("Core/CIM_SoftwareInstallationServiceCapabilities.mof")
#pragma include ("Core/CIM_Spared.mof")
#pragma include ("Core/CIM_SpareGroup.mof")
#pragma include ("Core/CIM_StorageAllocationSettingData.mof")
#pragma include ("Core/CIM_StorageRedundancyGroup.mof")
#pragma include ("Core/CIM_SystemSetting.mof")
#pragma include ("Core/CIM_SystemSettingContext.mof")
#pragma include ("Core/CIM_SystemSpecificCollection.mof")
#pragma include ("Core/CIM_VirtualEthernetSwitchSettingData.mof")
#pragma include ("Core/CIM_VirtualSystemManagementCapabilities.mof")
#pragma include ("Core/CIM_VirtualSystemSnapshotCapabilities.mof")
#pragma include ("Core/CIM_VirtualSystemSnapshotServiceCapabilities.mof")
#pragma include ("Database/CIM_CommonDatabaseCapabilities.mof")
#pragma include ("Database/CIM_DatabaseParameter.mof")
#pragma include ("Database/CIM_DatabaseSegmentSettingData.mof")
#pragma include ("Database/CIM_SNMPDatabaseParameter.mof")
#pragma include ("Device/CIM_AlarmDeviceCapabilities.mof")
#pragma include ("Device/CIM_BlockStatisticsManifestCollection.mof")
#pragma include ("Device/CIM_DeviceSharingCapabilities.mof")
#pragma include ("Device/CIM_DiskGroup.mof")
#pragma include ("Device/CIM_EthernetPortStatistics.mof")
#pragma include ("Device/CIM_FCAdapterEventCounters.mof")
#pragma include ("Device/CIM_FCPortStatistics.mof")
#pragma include ("Device/CIM_FCSwitchCapabilities.mof")
#pragma include ("Device/CIM_FibrePortEventCounters.mof")
#pragma include ("Device/CIM_IndicatorLEDCapabilities.mof")
#pragma include ("Device/CIM_LabelReaderStatInfo.mof")
#pragma include ("Device/CIM_LogicalPortCapabilities.mof")
#pragma include ("Device/CIM_LogicalPortGroup.mof")
#pragma include ("Device/CIM_MediaAccessStatInfo.mof")
#pragma include ("Device/CIM_MemoryError.mof")
#pragma include ("Device/CIM_MonitorResolution.mof")
#pragma include ("Device/CIM_NetworkPortCapabilities.mof")
#pragma include ("Device/CIM_PCIPortGroup.mof")
#pragma include ("Device/CIM_PickerStatInfo.mof")
#pragma include ("Device/CIM_PowerAllocationSettingData.mof")
#pragma include ("Device/CIM_PrinterElement.mof")
#pragma include ("Device/CIM_PrintInputTray.mof")
#pragma include ("Device/CIM_PrintInterpreter.mof")
#pragma include ("Device/CIM_PrintMarker.mof")
#pragma include ("Device/CIM_PrintSupply.mof")
#pragma include ("Device/CIM_ProcessorCapabilities.mof")
#pragma include ("Device/CIM_ProtocolControllerMaskingCapabilities.mof")
#pragma include ("Device/CIM_SCSIMultipathConfigurationCapabilities.mof")
#pragma include ("Device/CIM_SCSITargetPortGroup.mof")
#pragma include ("Device/CIM_StatisticsCapabilities.mof")
#pragma include ("Device/CIM_StorageCapabilities.mof")
#pragma include ("Device/CIM_StorageConfigurationCapabilities.mof")
#pragma include ("Device/CIM_StorageReplicationCapabilities.mof")
#pragma include ("Device/CIM_StorageSettingsAssociatedToCapabilities.mof")
#pragma include ("Device/CIM_StorageSettingsGeneratedFromCapabilities.mof")
#pragma include ("Device/CIM_VideoControllerResolution.mof")
#pragma include ("Device/CIM_WiFiPortCapabilities.mof")
#pragma include ("Device/CIM_ZoneCapabilities.mof")
#pragma include ("Device/CIM_ZoneMembershipSettingData.mof")
#pragma include ("Event/CIM_AbstractIndicationSubscription.mof")
#pragma include ("Event/CIM_AlertIndication.mof")
#pragma include ("Event/CIM_AlertInstIndication.mof")
#pragma include ("Event/CIM_ClassIndication.mof")
#pragma include ("Event/CIM_ClassModification.mof")
#pragma include ("Event/CIM_FilterCollection.mof")
#pragma include ("Event/CIM_FilterCollectionSubscription.mof")
#pragma include ("Event/CIM_IndicationHandler.mof")
#pragma include ("Event/CIM_IndicationHandlerCIMXML.mof")
#pragma include ("Event/CIM_IndicationServiceCapabilities.mof")
#pragma include ("Event/CIM_IndicationSubscription.mof")
#pragma include ("Event/CIM_InstCreation.mof")
#pragma include ("Event/CIM_InstDeletion.mof")
#pragma include ("Event/CIM_ThresholdIndication.mof")
#pragma include ("Interop/CIM_ElementConformsToProfile.mof")
#pragma include ("Interop/CIM_QueryCapabilities.mof")
#pragma include ("Interop/CIM_ReferencedProfile.mof")
#pragma include ("Interop/CIM_SubProfileRequiresProfile.mof")
#pragma include ("IPsecPolicy/CIM_SAAction.mof")
#pragma include ("IPsecPolicy/CIM_SANegotiationAction.mof")
#pragma include ("IPsecPolicy/CIM_SAProposal.mof")
#pragma include ("IPsecPolicy/CIM_SAStaticAction.mof")
#pragma include ("Metrics/CIM_AggregationMetricDefinition.mof")
#pragma include ("Metrics/CIM_AggregationMetricValue.mof")
#pragma include ("Metrics/CIM_LogicalElementPerformsUoW.mof")
#pragma include ("Metrics/CIM_MetricDefForME.mof")
#pragma include ("Metrics/CIM_MetricForME.mof")
#pragma include ("Metrics/CIM_MetricInstance.mof")
#pragma include ("Metrics/CIM_MetricServiceCapabilities.mof")
#pragma include ("Metrics/CIM_SubUoW.mof")
#pragma include ("Metrics/CIM_UnitOfWorkDefinition.mof")
#pragma include ("Metrics/CIM_UoWDefTraceLevelType.mof")
#pragma include ("Metrics/CIM_UoWMetric.mof")
#pragma include ("Metrics/CIM_UoWMetricDefinition.mof")
#pragma include ("Network/CIM_AdministrativeDistance.mof")
#pragma include ("Network/CIM_AllocationSchedulingElement.mof")
#pragma include ("Network/CIM_BGPAttributes.mof")
#pragma include ("Network/CIM_BGPCluster.mof")
#pragma include ("Network/CIM_BGPPathAttributes.mof")
#pragma include ("Network/CIM_BGPPeerGroup.mof")
#pragma include ("Network/CIM_BGPRouteMap.mof")
#pragma include ("Network/CIM_BGPStatistics.mof")
#pragma include ("Network/CIM_BufferPool.mof")
#pragma include ("Network/CIM_CollectedBufferPool.mof")
#pragma include ("Network/CIM_ConnectivityCollection.mof")
#pragma include ("Network/CIM_DHCPCapabilities.mof")
#pragma include ("Network/CIM_DHCPSettingData.mof")
#pragma include ("Network/CIM_DNSGeneralSettingData.mof")
#pragma include ("Network/CIM_DNSSettingData.mof")
#pragma include ("Network/CIM_DynamicForwardingEntry.mof")
#pragma include ("Network/CIM_ExtendedStaticIPAssignmentSettingData.mof")
#pragma include ("Network/CIM_FilterEntryBase.mof")
#pragma include ("Network/CIM_FilterList.mof")
#pragma include ("Network/CIM_FilterListsInBGPRouteMap.mof")
#pragma include ("Network/CIM_Hdr8021Filter.mof")
#pragma include ("Network/CIM_IEEE8021xCapabilities.mof")
#pragma include ("Network/CIM_IPAddressRange.mof")
#pragma include ("Network/CIM_IPConnectivitySubnet.mof")
#pragma include ("Network/CIM_IPHeadersFilter.mof")
#pragma include ("Network/CIM_IPSOFilterEntry.mof")
#pragma include ("Network/CIM_IPXConnectivityNetwork.mof")
#pragma include ("Network/CIM_iSCSICapabilities.mof")
#pragma include ("Network/CIM_LANConnectivitySegment.mof")
#pragma include ("Network/CIM_LogicalNetwork.mof")
#pragma include ("Network/CIM_NamedAddressCollection.mof")
#pragma include ("Network/CIM_NetworkVLAN.mof")
#pragma include ("Network/CIM_NextHopIPRoute.mof")
#pragma include ("Network/CIM_NextHopRouting.mof")
#pragma include ("Network/CIM_OSPFAreaConfiguration.mof")
#pragma include ("Network/CIM_OSPFLink.mof")
#pragma include ("Network/CIM_OSPFServiceCapabilities.mof")
#pragma include ("Network/CIM_PeerIDPayloadFilterEntry.mof")
#pragma include ("Network/CIM_PreambleFilter.mof")
#pragma include ("Network/CIM_PrioritySchedulingElement.mof")
#pragma include ("Network/CIM_ProtocolServiceCapabilities.mof")
#pragma include ("Network/CIM_RangeOfIPAddresses.mof")
#pragma include ("Network/CIM_RangesOfConfiguration.mof")
#pragma include ("Network/CIM_RedirectionServiceCapabilities.mof")
#pragma include ("Network/CIM_RoutingPolicy.mof")
#pragma include ("Network/CIM_SATransform.mof")
#pragma include ("Network/CIM_SpanningTreeStatistics.mof")
#pragma include ("Network/CIM_SSHCapabilities.mof")
#pragma include ("Network/CIM_StaticForwardingEntry.mof")
#pragma include ("Network/CIM_SwitchPortSourceRoutingStatistics.mof")
#pragma include ("Network/CIM_SwitchPortSpanningTreeStatistics.mof")
#pragma include ("Network/CIM_SwitchPortStatistics.mof")
#pragma include ("Network/CIM_SwitchPortTransparentBridgingStatistics.mof")
#pragma include ("Network/CIM_TelnetCapabilities.mof")
#pragma include ("Network/CIM_TransparentBridgingStatistics.mof")
#pragma include ("Network/CIM_USBRedirectionCapabilities.mof")
#pragma include ("Network/CIM_VLANEndpointCapabilities.mof")
#pragma include ("Network/CIM_WiFiEndpointCapabilities.mof")
#pragma include ("Network/CIM_X509CredentialFilterEntry.mof")
#pragma include ("Physical/CIM_AdjacentSlots.mof")
#pragma include ("Physical/CIM_Card.mof")
#pragma include ("Physical/CIM_Chip.mof")
#pragma include ("Physical/CIM_ConfigurationCapacity.mof")
#pragma include ("Physical/CIM_ConnectedTo.mof")
#pragma include ("Physical/CIM_Container.mof")
#pragma include ("Physical/CIM_ElementCapacity.mof")
#pragma include ("Physical/CIM_ElementInConnector.mof")
#pragma include ("Physical/CIM_ElementsLinked.mof")
#pragma include ("Physical/CIM_LinkHasConnector.mof")
#pragma include ("Physical/CIM_MediaPhysicalStatInfo.mof")
#pragma include ("Physical/CIM_MemoryCapacity.mof")
#pragma include ("Physical/CIM_PackagedComponent.mof")
#pragma include ("Physical/CIM_PackageInConnector.mof")
#pragma include ("Physical/CIM_PackageInSlot.mof")
#pragma include ("Physical/CIM_PackageLocation.mof")
#pragma include ("Physical/CIM_PhysicalAssetCapabilities.mof")
#pragma include ("Physical/CIM_PhysicalFrame.mof")
#pragma include ("Physical/CIM_PhysicalMemory.mof")
#pragma include ("Physical/CIM_Rack.mof")
#pragma include ("Physical/CIM_ReplacementSet.mof")
#pragma include ("Physical/CIM_SlotInSlot.mof")
#pragma include ("Physical/CIM_StorageMediaLocation.mof")
#pragma include ("Physical/CIM_SystemBusCard.mof")
#pragma include ("Policy/CIM_AuthenticationCondition.mof")
#pragma include ("Policy/CIM_BiometricAuthentication.mof")
#pragma include ("Policy/CIM_CompoundPolicyAction.mof")
#pragma include ("Policy/CIM_CompoundPolicyCondition.mof")
#pragma include ("Policy/CIM_DocumentAuthentication.mof")
#pragma include ("Policy/CIM_KerberosAuthentication.mof")
#pragma include ("Policy/CIM_MethodAction.mof")
#pragma include ("Policy/CIM_NetworkingIDAuthentication.mof")
#pragma include ("Policy/CIM_NetworkPacketAction.mof")
#pragma include ("Policy/CIM_PacketFilterCondition.mof")
#pragma include ("Policy/CIM_PhysicalCredentialAuthentication.mof")
#pragma include ("Policy/CIM_PolicyComponent.mof")
#pragma include ("Policy/CIM_PolicyConditionStructure.mof")
#pragma include ("Policy/CIM_PolicyGroup.mof")
#pragma include ("Policy/CIM_PolicyGroupInPolicyGroup.mof")
#pragma include ("Policy/CIM_PolicyRoleCollection.mof")
#pragma include ("Policy/CIM_PolicyRule.mof")
#pragma include ("Policy/CIM_PolicyRuleInPolicyGroup.mof")
#pragma include ("Policy/CIM_PolicyRuleValidityPeriod.mof")
#pragma include ("Policy/CIM_PolicySetComponent.mof")
#pragma include ("Policy/CIM_PolicySetInRoleCollection.mof")
#pragma include ("Policy/CIM_PolicySetValidityPeriod.mof")
#pragma include ("Policy/CIM_PublicPrivateKeyAuthentication.mof")
#pragma include ("Policy/CIM_SharedSecretAuthentication.mof")
#pragma include ("Support/PRS_Activity.mof")
#pragma include ("Support/PRS_ActivityResource.mof")
#pragma include ("Support/PRS_ActivityTransaction.mof")
#pragma include ("Support/PRS_Address.mof")
#pragma include ("Support/PRS_AddressLocation.mof")
#pragma include ("Support/PRS_Administrative.mof")
#pragma include ("Support/PRS_AdministrativeRevision.mof")
#pragma include ("Support/PRS_Agreement.mof")
#pragma include ("Support/PRS_Attachment.mof")
#pragma include ("Support/PRS_Category.mof")
#pragma include ("Support/PRS_CategoryParentChild.mof")
#pragma include ("Support/PRS_Contact.mof")
#pragma include ("Support/PRS_ContactItem.mof")
#pragma include ("Support/PRS_ContactItemAddress.mof")
#pragma include ("Support/PRS_Expression.mof")
#pragma include ("Support/PRS_ExpressionLink.mof")
#pragma include ("Support/PRS_FeatureResource.mof")
#pragma include ("Support/PRS_Organization.mof")
#pragma include ("Support/PRS_Person.mof")
#pragma include ("Support/PRS_Problem.mof")
#pragma include ("Support/PRS_ProductAsset.mof")
#pragma include ("Support/PRS_ProductComponent.mof")
#pragma include ("Support/PRS_ProductParentChild.mof")
#pragma include ("Support/PRS_Reference.mof")
#pragma include ("Support/PRS_Resolution.mof")
#pragma include ("Support/PRS_ResolutionResource.mof")
#pragma include ("Support/PRS_RevisionContact.mof")
#pragma include ("Support/PRS_ServiceActivity.mof")
#pragma include ("Support/PRS_ServiceAgreement.mof")
#pragma include ("Support/PRS_ServiceProblem.mof")
#pragma include ("Support/PRS_ServiceProvider.mof")
#pragma include ("Support/PRS_ServiceRequester.mof")
#pragma include ("Support/PRS_ServiceResolutionSolution.mof")
#pragma include ("Support/PRS_SolutionCategory.mof")
#pragma include ("Support/PRS_SolutionExpression.mof")
#pragma include ("Support/PRS_SolutionHasElement.mof")
#pragma include ("Support/PRS_SolutionProblem.mof")
#pragma include ("Support/PRS_SolutionReference.mof")
#pragma include ("Support/PRS_SolutionResolution.mof")
#pragma include ("Support/PRS_StatementFeature.mof")
#pragma include ("System/CIM_BIOSServiceCapabilities.mof")
#pragma include ("System/CIM_BootServiceCapabilities.mof")
#pragma include ("System/CIM_ComputerSystemNodeCapabilities.mof")
#pragma include ("System/CIM_DiagnosticRecord.mof")
#pragma include ("System/CIM_DiagnosticServiceCapabilities.mof")
#pragma include ("System/CIM_DiagnosticServiceRecord.mof")
#pragma include ("System/CIM_DiagnosticSetting.mof")
#pragma include ("System/CIM_DiagnosticSettingDataRecord.mof")
#pragma include ("System/CIM_DiagnosticSettingRecord.mof")
#pragma include ("System/CIM_FileSystemCapabilities.mof")
#pragma include ("System/CIM_FileSystemSettingData.mof")
#pragma include ("System/CIM_LogEntry.mof")
#pragma include ("System/CIM_LogicalFile.mof")
#pragma include ("System/CIM_LogRecord.mof")
#pragma include ("System/CIM_OperatingSystemCapabilities.mof")
#pragma include ("System/CIM_PlatformWatchdogServiceCapabilities.mof")
#pragma include ("System/CIM_RecordAppliesToElement.mof")
#pragma include ("System/CIM_RecordLogCapabilities.mof")
#pragma include ("System/CIM_SymbolicLink.mof")
#pragma include ("System/CIM_TimeZone.mof")
#pragma include ("System/CIM_UnixFile.mof")
#pragma include ("System/CIM_VirtualSystemSettingDataComponent.mof")
#pragma include ("User/CIM_AccessControlInformation.mof")
#pragma include ("User/CIM_AccountManagementCapabilities.mof")
#pragma include ("User/CIM_AssignedIdentity.mof")
#pragma include ("User/CIM_AuthenticationRequirement.mof")
#pragma include ("User/CIM_AuthenticationTarget.mof")
#pragma include ("User/CIM_AuthorizationSubject.mof")
#pragma include ("User/CIM_AuthorizationTarget.mof")
#pragma include ("User/CIM_AuthorizedPrivilege.mof")
#pragma include ("User/CIM_AuthorizedSubject.mof")
#pragma include ("User/CIM_AuthorizedTarget.mof")
#pragma include ("User/CIM_CollectionInOrganization.mof")
#pragma include ("User/CIM_CredentialManagementCapabilities.mof")
#pragma include ("User/CIM_CredentialStore.mof")
#pragma include ("User/CIM_ElementAsUser.mof")
#pragma include ("User/CIM_ElementSecuritySensitivity.mof")
#pragma include ("User/CIM_GatewayPathID.mof")
#pragma include ("User/CIM_Group.mof")
#pragma include ("User/CIM_Keystore.mof")
#pragma include ("User/CIM_MemberPrincipal.mof")
#pragma include ("User/CIM_MoreGroupInfo.mof")
#pragma include ("User/CIM_MoreOrgUnitInfo.mof")
#pragma include ("User/CIM_Organization.mof")
#pragma include ("User/CIM_PrivilegeManagementCapabilities.mof")
// #pragma include ("User/CIM_PublicKeyCertificate.mof")
#pragma include ("User/CIM_Role.mof")
#pragma include ("User/CIM_RoleBasedManagementCapabilities.mof")
#pragma include ("User/CIM_RoleLimitedToTarget.mof")
#pragma include ("User/CIM_UserContact.mof")
#pragma include ("User/CIM_UsersCredential.mof")
#pragma include ("User/CIM_X509Certificate.mof")
#pragma include ("User/CIM_X509CRL.mof")
#pragma include ("Application/CIM_InstalledProduct.mof")
#pragma include ("Application/CIM_InstalledProductImage.mof")
#pragma include ("Application/CIM_J2eeConnectionStats.mof")
#pragma include ("Application/CIM_J2eeEJBStats.mof")
#pragma include ("Application/CIM_J2eeEntityBeanStats.mof")
#pragma include ("Application/CIM_J2eeJavaMailStats.mof")
#pragma include ("Application/CIM_J2eeJCAStats.mof")
#pragma include ("Application/CIM_J2eeJDBCStats.mof")
#pragma include ("Application/CIM_J2eeJMSConnectionStats.mof")
#pragma include ("Application/CIM_J2eeJMSEndpointStats.mof")
#pragma include ("Application/CIM_J2eeJMSProducerStats.mof")
#pragma include ("Application/CIM_J2eeJMSSessionStats.mof")
#pragma include ("Application/CIM_J2eeJMSStats.mof")
#pragma include ("Application/CIM_J2eeJTAStats.mof")
#pragma include ("Application/CIM_J2eeJVMStats.mof")
#pragma include ("Application/CIM_J2eeManagedObjectCapabilities.mof")
#pragma include ("Application/CIM_J2eeMessageDrivenBeanStats.mof")
#pragma include ("Application/CIM_J2eeServletStats.mof")
#pragma include ("Application/CIM_J2eeSessionBeanStats.mof")
#pragma include ("Application/CIM_J2eeStatefulSessionBeanStats.mof")
#pragma include ("Application/CIM_J2eeStatelessSessionBeanStats.mof")
#pragma include ("Application/CIM_SoftwareElement.mof")
#pragma include ("Application/CIM_SoftwareElementComponent.mof")
#pragma include ("Application/CIM_SoftwareFeature.mof")
#pragma include ("Application/CIM_SoftwareFeatureComponent.mof")
#pragma include ("Application/CIM_SoftwareFeatureSoftwareElements.mof")
#pragma include ("Application/CIM_VideoBIOSElement.mof")
#pragma include ("Application/CIM_VideoBIOSFeature.mof")
#pragma include ("Application/CIM_VideoBIOSFeatureVideoBIOSElements.mof")
#pragma include ("Core/CIM_ActsAsSpare.mof")
#pragma include ("Core/CIM_AllocationCapabilities.mof")
#pragma include ("Core/CIM_CollectedCollections.mof")
#pragma include ("Core/CIM_CollectedMSEs.mof")
#pragma include ("Core/CIM_CollectionConfiguration.mof")
#pragma include ("Core/CIM_CollectionSetting.mof")
#pragma include ("Core/CIM_ConcreteDependency.mof")
#pragma include ("Core/CIM_ConcreteIdentity.mof")
#pragma include ("Core/CIM_ContainedLocation.mof")
#pragma include ("Core/CIM_ElementAllocatedFromPool.mof")
#pragma include ("Core/CIM_ElementLocation.mof")
#pragma include ("Core/CIM_ElementProfile.mof")
#pragma include ("Core/CIM_ElementSetting.mof")
#pragma include ("Core/CIM_ElementSoftwareIdentity.mof")
#pragma include ("Core/CIM_EthernetPortAllocationSettingData.mof")
#pragma include ("Core/CIM_ExtraCapacityGroup.mof")
#pragma include ("Core/CIM_Job.mof")
#pragma include ("Core/CIM_PhysicalElementLocation.mof")
#pragma include ("Core/CIM_ProductSoftwareComponent.mof")
#pragma include ("Core/CIM_RedundancyComponent.mof")
#pragma include ("Core/CIM_RedundancySet.mof")
#pragma include ("Core/CIM_ResourceAllocationFromPool.mof")
#pragma include ("Core/CIM_ScopedSetting.mof")
#pragma include ("Core/CIM_StatisticsCollection.mof")
#pragma include ("Core/CIM_StorageRedundancySet.mof")
#pragma include ("Device/CIM_AssociatedBlockStatisticsManifestCollection.mof")
#pragma include ("Device/CIM_BlockStatisticsCapabilities.mof")
#pragma include ("Device/CIM_FCPortCapabilities.mof")
#pragma include ("Device/CIM_GroupInDiskGroup.mof")
#pragma include ("Device/CIM_PrintJob.mof")
#pragma include ("Device/CIM_Zone.mof")
#pragma include ("Device/CIM_ZoneSet.mof")
#pragma include ("Event/CIM_ClassCreation.mof")
#pragma include ("Event/CIM_ClassDeletion.mof")
#pragma include ("Event/CIM_FormattedIndicationSubscription.mof")
#pragma include ("IPsecPolicy/CIM_ContainedProposal.mof")
#pragma include ("IPsecPolicy/CIM_IKEAction.mof")
#pragma include ("IPsecPolicy/CIM_IKEProposal.mof")
#pragma include ("IPsecPolicy/CIM_IPsecAction.mof")
#pragma include ("IPsecPolicy/CIM_IPsecProposal.mof")
#pragma include ("IPsecPolicy/CIM_IPsecTransportAction.mof")
#pragma include ("IPsecPolicy/CIM_IPsecTunnelAction.mof")
#pragma include ("IPsecPolicy/CIM_PreconfiguredSAAction.mof")
#pragma include ("IPsecPolicy/CIM_PreconfiguredTransportAction.mof")
#pragma include ("IPsecPolicy/CIM_PreconfiguredTunnelAction.mof")
#pragma include ("IPsecPolicy/CIM_SARule.mof")
#pragma include ("IPsecPolicy/CIM_TransformOfPreconfiguredAction.mof")
#pragma include ("Metrics/CIM_LogicalElementUnitOfWorkDef.mof")
#pragma include ("Metrics/CIM_StartedUoW.mof")
#pragma include ("Metrics/CIM_SubUoWDef.mof")
#pragma include ("Network/CIM_AHTransform.mof")
#pragma include ("Network/CIM_BGPPeerUsesRouteMap.mof")
#pragma include ("Network/CIM_BGPRouteMapsInRoutingPolicy.mof")
#pragma include ("Network/CIM_BoundedPrioritySchedulingElement.mof")
#pragma include ("Network/CIM_CLPCapabilities.mof")
#pragma include ("Network/CIM_EntriesInFilterList.mof")
#pragma include ("Network/CIM_ESPTransform.mof")
#pragma include ("Network/CIM_FilteredBGPAttributes.mof")
#pragma include ("Network/CIM_FilterEntry.mof")
#pragma include ("Network/CIM_IPCOMPTransform.mof")
#pragma include ("Network/CIM_IPRoute.mof")
#pragma include ("Network/CIM_IPSubnet.mof")
#pragma include ("Network/CIM_IPXNetwork.mof")
#pragma include ("Network/CIM_LANSegment.mof")
#pragma include ("Network/CIM_ListsInRoutingPolicy.mof")
#pragma include ("Network/CIM_MediaRedirectionCapabilities.mof")
#pragma include ("Physical/CIM_CardInSlot.mof")
#pragma include ("Physical/CIM_CardOnCard.mof")
#pragma include ("Physical/CIM_Chassis.mof")
#pragma include ("Physical/CIM_ChassisInRack.mof")
#pragma include ("Physical/CIM_ConnectorOnPackage.mof")
#pragma include ("Physical/CIM_Docked.mof")
#pragma include ("Physical/CIM_HomeForMedia.mof")
#pragma include ("Physical/CIM_Magazine.mof")
#pragma include ("Physical/CIM_MemoryOnCard.mof")
#pragma include ("Physical/CIM_MemoryWithMedia.mof")
#pragma include ("Physical/CIM_PackageInChassis.mof")
#pragma include ("Physical/CIM_ParticipatesInSet.mof")
#pragma include ("Physical/CIM_PhysicalMediaInLocation.mof")
#pragma include ("Policy/CIM_AccountAuthentication.mof")
#pragma include ("Policy/CIM_AuthenticationRule.mof")
#pragma include ("Policy/CIM_ElementInPolicyRoleCollection.mof")
#pragma include ("Policy/CIM_FilterOfPacketCondition.mof")
#pragma include ("Policy/CIM_PolicyActionStructure.mof")
#pragma include ("Policy/CIM_PolicyConditionInPolicyCondition.mof")
#pragma include ("Policy/CIM_PolicyConditionInPolicyRule.mof")
#pragma include ("Support/PRS_ActivityContact.mof")
#pragma include ("Support/PRS_AdminAssociation.mof")
#pragma include ("Support/PRS_AdministrativeContact.mof")
#pragma include ("Support/PRS_Attached.mof")
#pragma include ("Support/PRS_Categorization.mof")
#pragma include ("Support/PRS_ContactContactItem.mof")
#pragma include ("Support/PRS_ContactOrganization.mof")
#pragma include ("Support/PRS_ContactPerson.mof")
#pragma include ("System/CIM_AffectedJobElement.mof")
#pragma include ("System/CIM_CorrespondingSettingDataRecord.mof")
#pragma include ("System/CIM_CorrespondingSettingsRecord.mof")
#pragma include ("System/CIM_DataFile.mof")
#pragma include ("System/CIM_DeviceFile.mof")
#pragma include ("System/CIM_DiagnosticCompletionRecord.mof")
#pragma include ("System/CIM_Directory.mof")
#pragma include ("System/CIM_DirectoryContainsFile.mof")
#pragma include ("System/CIM_FIFOPipeFile.mof")
#pragma include ("System/CIM_FileIdentity.mof")
#pragma include ("System/CIM_OwningJobElement.mof")
#pragma include ("System/CIM_UnixDeviceFile.mof")
#pragma include ("System/CIM_UnixDirectory.mof")
#pragma include ("User/CIM_CertificateManagementCapabilities.mof")
#pragma include ("User/CIM_MoreOrganizationInfo.mof")
#pragma include ("User/CIM_MoreRoleInfo.mof")
#pragma include ("User/CIM_Person.mof")
// #pragma include ("User/CIM_PublicPrivateKeyPair.mof")
#pragma include ("Application/CIM_AGPSoftwareFeature.mof")
#pragma include ("Application/CIM_BIOSElement.mof")
#pragma include ("Application/CIM_BIOSFeature.mof")
#pragma include ("Application/CIM_BIOSFeatureBIOSElements.mof")
#pragma include ("Application/CIM_CollectedSoftwareElements.mof")
#pragma include ("Application/CIM_CollectedSoftwareFeatures.mof")
#pragma include ("Application/CIM_FRUIncludesSoftwareFeature.mof")
#pragma include ("Application/CIM_J2eeConnectionPoolStats.mof")
#pragma include ("Application/CIM_J2eeJCAConnectionPools.mof")
#pragma include ("Application/CIM_J2eeJCANonpooledConnections.mof")
#pragma include ("Application/CIM_J2eeJDBCConnectionPools.mof")
#pragma include ("Application/CIM_J2eeJDBCNonpooledConnections.mof")
#pragma include ("Application/CIM_J2eeJMSConnectionSessions.mof")
#pragma include ("Application/CIM_J2eeJMSConsumerStats.mof")
#pragma include ("Application/CIM_J2eeJMSSessionConsumers.mof")
#pragma include ("Application/CIM_J2eeJMSSessionProducers.mof")
#pragma include ("Application/CIM_J2eeJMSStatConnections.mof")
#pragma include ("Application/CIM_ProductSoftwareFeatures.mof")
#pragma include ("Core/CIM_ConcreteJob.mof")
#pragma include ("Core/CIM_DefaultSetting.mof")
#pragma include ("Core/CIM_EnabledLogicalElement.mof")
#pragma include ("Core/CIM_IsSpare.mof")
#pragma include ("Core/CIM_LogicalDevice.mof")
#pragma include ("Core/CIM_Realizes.mof")
#pragma include ("Core/CIM_Service.mof")
#pragma include ("Core/CIM_ServiceAccessPoint.mof")
#pragma include ("Core/CIM_ServiceAccessURI.mof")
#pragma include ("Core/CIM_ServiceAffectsElement.mof")
#pragma include ("Core/CIM_ServiceAffectsElementWithQuota.mof")
#pragma include ("Core/CIM_ServiceAvailableToElement.mof")
#pragma include ("Core/CIM_ServiceComponent.mof")
#pragma include ("Core/CIM_ServiceSAPDependency.mof")
#pragma include ("Core/CIM_ServiceStatistics.mof")
#pragma include ("Core/CIM_SoftwareInstallationService.mof")
#pragma include ("Core/CIM_StorageExtent.mof")
#pragma include ("Core/CIM_System.mof")
#pragma include ("Core/CIM_SystemComponent.mof")
#pragma include ("Core/CIM_SystemDevice.mof")
#pragma include ("Core/CIM_SystemPackaging.mof")
#pragma include ("Core/CIM_SystemStatistics.mof")
#pragma include ("Core/CIM_TimeService.mof")
#pragma include ("Database/CIM_CommonDatabase.mof")
#pragma include ("Database/CIM_DatabaseAdministrator.mof")
#pragma include ("Database/CIM_DatabaseControlFile.mof")
#pragma include ("Database/CIM_DatabaseFile.mof")
#pragma include ("Database/CIM_DatabaseSegment.mof")
#pragma include ("Database/CIM_DatabaseService.mof")
#pragma include ("Database/CIM_ServiceAvailableToDatabase.mof")
#pragma include ("Device/CIM_AggregatePExtent.mof")
#pragma include ("Device/CIM_AggregatePSExtent.mof")
#pragma include ("Device/CIM_AlarmDevice.mof")
#pragma include ("Device/CIM_AssociatedAlarm.mof")
#pragma include ("Device/CIM_Battery.mof")
#pragma include ("Device/CIM_CompositeExtent.mof")
#pragma include ("Device/CIM_ConfigurationReportingService.mof")
#pragma include ("Device/CIM_Controller.mof")
#pragma include ("Device/CIM_CoolingDevice.mof")
#pragma include ("Device/CIM_DeviceConnection.mof")
#pragma include ("Device/CIM_DeviceIdentity.mof")
#pragma include ("Device/CIM_DeviceSoftware.mof")
#pragma include ("Device/CIM_DisplayController.mof")
#pragma include ("Device/CIM_Door.mof")
#pragma include ("Device/CIM_DoorAccessToDevice.mof")
#pragma include ("Device/CIM_DoorAccessToPhysicalElement.mof")
#pragma include ("Device/CIM_ErrorCountersForDevice.mof")
#pragma include ("Device/CIM_ESCONController.mof")
#pragma include ("Device/CIM_ExtentInDiskGroup.mof")
#pragma include ("Device/CIM_Fan.mof")
#pragma include ("Device/CIM_FibreProtocolService.mof")
#pragma include ("Device/CIM_HardwareThread.mof")
#pragma include ("Device/CIM_HeatPipe.mof")
#pragma include ("Device/CIM_IBSubnetManager.mof")
#pragma include ("Device/CIM_IDEController.mof")
#pragma include ("Device/CIM_IndicatorLED.mof")
#pragma include ("Device/CIM_InfraredController.mof")
#pragma include ("Device/CIM_LabelReader.mof")
#pragma include ("Device/CIM_LogicalDisk.mof")
#pragma include ("Device/CIM_LogicalModule.mof")
#pragma include ("Device/CIM_LogicalPort.mof")
#pragma include ("Device/CIM_ManagementController.mof")
#pragma include ("Device/CIM_MediaAccessDevice.mof")
#pragma include ("Device/CIM_MediaPartition.mof")
#pragma include ("Device/CIM_MediaPresent.mof")
#pragma include ("Device/CIM_MediaTransferDevice.mof")
#pragma include ("Device/CIM_Memory.mof")
#pragma include ("Device/CIM_Modem.mof")
#pragma include ("Device/CIM_NetworkAdapter.mof")
#pragma include ("Device/CIM_NetworkAdapterRedundancyComponent.mof")
#pragma include ("Device/CIM_NetworkPort.mof")
#pragma include ("Device/CIM_NetworkVirtualAdapter.mof")
#pragma include ("Device/CIM_NonVolatileStorage.mof")
#pragma include ("Device/CIM_PackageDependency.mof")
#pragma include ("Device/CIM_ParallelController.mof")
#pragma include ("Device/CIM_PassThroughModule.mof")
#pragma include ("Device/CIM_PCIController.mof")
#pragma include ("Device/CIM_PCIDevice.mof")
#pragma include ("Device/CIM_PCIeSwitch.mof")
#pragma include ("Device/CIM_PCIPort.mof")
#pragma include ("Device/CIM_PCMCIAController.mof")
#pragma include ("Device/CIM_PhysicalExtent.mof")
#pragma include ("Device/CIM_PickerElement.mof")
#pragma include ("Device/CIM_PortActiveConnection.mof")
#pragma include ("Device/CIM_PortController.mof")
#pragma include ("Device/CIM_PortOnDevice.mof")
#pragma include ("Device/CIM_PowerSource.mof")
#pragma include ("Device/CIM_PowerSupply.mof")
#pragma include ("Device/CIM_Printer.mof")
#pragma include ("Device/CIM_PrinterServicingJob.mof")
#pragma include ("Device/CIM_PrintJobFile.mof")
#pragma include ("Device/CIM_PrintSAP.mof")
#pragma include ("Device/CIM_PrintService.mof")
#pragma include ("Device/CIM_Processor.mof")
#pragma include ("Device/CIM_ProcessorCore.mof")
#pragma include ("Device/CIM_ProtectedSpaceExtent.mof")
#pragma include ("Device/CIM_ProtocolController.mof")
#pragma include ("Device/CIM_ProtocolControllerForDevice.mof")
#pragma include ("Device/CIM_ProtocolControllerForPort.mof")
#pragma include ("Device/CIM_ProtocolControllerForUnit.mof")
#pragma include ("Device/CIM_RealizesExtent.mof")
#pragma include ("Device/CIM_RealizesPExtent.mof")
#pragma include ("Device/CIM_Refrigeration.mof")
#pragma include ("Device/CIM_Scanner.mof")
#pragma include ("Device/CIM_SCSIController.mof")
#pragma include ("Device/CIM_SCSIProtocolController.mof")
#pragma include ("Device/CIM_Sensor.mof")
#pragma include ("Device/CIM_SerialController.mof")
#pragma include ("Device/CIM_SharedDeviceManagementService.mof")
#pragma include ("Device/CIM_SharingDependency.mof")
#pragma include ("Device/CIM_Snapshot.mof")
#pragma include ("Device/CIM_SnapshotOfExtent.mof")
#pragma include ("Device/CIM_SSAController.mof")
#pragma include ("Device/CIM_StatisticsService.mof")
#pragma include ("Device/CIM_StorageDefect.mof")
#pragma include ("Device/CIM_StorageLibrary.mof")
#pragma include ("Device/CIM_StoragePool.mof")
#pragma include ("Device/CIM_StorageVolume.mof")
#pragma include ("Device/CIM_SuppliesPower.mof")
#pragma include ("Device/CIM_TapeDrive.mof")
#pragma include ("Device/CIM_TapePartition.mof")
#pragma include ("Device/CIM_TokenRingAdapter.mof")
#pragma include ("Device/CIM_TokenRingPort.mof")
#pragma include ("Device/CIM_UninterruptiblePowerSupply.mof")
#pragma include ("Device/CIM_USBController.mof")
#pragma include ("Device/CIM_USBDevice.mof")
#pragma include ("Device/CIM_USBHub.mof")
#pragma include ("Device/CIM_USBPort.mof")
#pragma include ("Device/CIM_USBPortOnHub.mof")
#pragma include ("Device/CIM_UserDevice.mof")
#pragma include ("Device/CIM_VideoController.mof")
#pragma include ("Device/CIM_VideoHead.mof")
#pragma include ("Device/CIM_VideoSetting.mof")
#pragma include ("Device/CIM_VolatileStorage.mof")
#pragma include ("Device/CIM_VolumeSet.mof")
#pragma include ("Device/CIM_Watchdog.mof")
#pragma include ("Device/CIM_WiFiPort.mof")
#pragma include ("Device/CIM_WiFiRadio.mof")
#pragma include ("Device/CIM_WORMDrive.mof")
#pragma include ("Device/CIM_ZoneService.mof")
#pragma include ("Event/CIM_IndicationService.mof")
#pragma include ("Interop/CIM_IdentificationOfManagedSystem.mof")
#pragma include ("Interop/CIM_ObjectManagerCommunicationMechanism.mof")
#pragma include ("Interop/CIM_WBEMService.mof")
#pragma include ("IPsecPolicy/CIM_ContainedTransform.mof")
#pragma include ("IPsecPolicy/CIM_IKERule.mof")
#pragma include ("IPsecPolicy/CIM_IPsecPolicyForSystem.mof")
#pragma include ("IPsecPolicy/CIM_IPsecRule.mof")
#pragma include ("IPsecPolicy/CIM_PacketConditionInSARule.mof")
#pragma include ("Metrics/CIM_MetricService.mof")
#pragma include ("Network/CIM_BGPIPRoute.mof")
#pragma include ("Network/CIM_ConditioningService.mof")
#pragma include ("Network/CIM_DropperService.mof")
#pragma include ("Network/CIM_DropThresholdCalculationService.mof")
#pragma include ("Network/CIM_HeadTailDropper.mof")
#pragma include ("Network/CIM_HostedRoute.mof")
#pragma include ("Network/CIM_IPNetworkConnection.mof")
#pragma include ("Network/CIM_KVMRedirectionSAP.mof")
#pragma include ("Network/CIM_MarkerService.mof")
#pragma include ("Network/CIM_MediaRedirectionSAP.mof")
#pragma include ("Network/CIM_MeterService.mof")
#pragma include ("Network/CIM_NetworkPipe.mof")
#pragma include ("Network/CIM_NetworkPipeComposition.mof")
#pragma include ("Network/CIM_NetworkService.mof")
#pragma include ("Network/CIM_NextService.mof")
#pragma include ("Network/CIM_NextServiceAfterMeter.mof")
#pragma include ("Network/CIM_PacketSchedulingService.mof")
#pragma include ("Network/CIM_PreambleMarkerService.mof")
#pragma include ("Network/CIM_Priority8021QMarkerService.mof")
#pragma include ("Network/CIM_QoSService.mof")
#pragma include ("Network/CIM_QoSSubService.mof")
#pragma include ("Network/CIM_QueuingService.mof")
#pragma include ("Network/CIM_REDDropperService.mof")
#pragma include ("Network/CIM_RedirectionService.mof")
#pragma include ("Network/CIM_RouteCalculationService.mof")
#pragma include ("Network/CIM_SchedulingServiceToSchedule.mof")
#pragma include ("Network/CIM_SNMPCommunityString.mof")
#pragma include ("Network/CIM_SNMPService.mof")
#pragma include ("Network/CIM_TextRedirectionSAP.mof")
#pragma include ("Network/CIM_TextRedirectionService.mof")
#pragma include ("Network/CIM_TokenBucketMeterService.mof")
#pragma include ("Network/CIM_ToSMarkerService.mof")
#pragma include ("Network/CIM_USBRedirectionSAP.mof")
#pragma include ("Network/CIM_VLAN.mof")
#pragma include ("Network/CIM_VLANService.mof")
#pragma include ("Network/CIM_WeightedREDDropperService.mof")
#pragma include ("Policy/CIM_PolicyActionInPolicyAction.mof")
#pragma include ("Policy/CIM_PolicyActionInPolicyRule.mof")
#pragma include ("Policy/CIM_PolicyInSystem.mof")
#pragma include ("Policy/CIM_PolicySetInSystem.mof")
#pragma include ("Support/PRS_SISService.mof")
#pragma include ("System/CIM_AssociatedJobMethodResult.mof")
#pragma include ("System/CIM_BIOSService.mof")
#pragma include ("System/CIM_BootConfigSetting.mof")
#pragma include ("System/CIM_BootSAP.mof")
#pragma include ("System/CIM_ClusteringSAP.mof")
#pragma include ("System/CIM_ComputerSystem.mof")
#pragma include ("System/CIM_ComputerSystemPackage.mof")
#pragma include ("System/CIM_DeviceAccessedByFile.mof")
#pragma include ("System/CIM_DiagnosticService.mof")
#pragma include ("System/CIM_DiagnosticTest.mof")
#pragma include ("System/CIM_DiagnosticTestInPackage.mof")
#pragma include ("System/CIM_FileSystem.mof")
#pragma include ("System/CIM_HelpService.mof")
#pragma include ("System/CIM_HelpServiceAvailableToFile.mof")
#pragma include ("System/CIM_HostedFileSystem.mof")
#pragma include ("System/CIM_JobDestination.mof")
#pragma include ("System/CIM_JobDestinationJobs.mof")
#pragma include ("System/CIM_JobQueue.mof")
#pragma include ("System/CIM_LocalFileSystem.mof")
#pragma include ("System/CIM_Log.mof")
#pragma include ("System/CIM_LogManagesRecord.mof")
#pragma include ("System/CIM_MessageLog.mof")
#pragma include ("System/CIM_Mount.mof")
#pragma include ("System/CIM_OOBAlertService.mof")
#pragma include ("System/CIM_OperatingSystem.mof")
#pragma include ("System/CIM_PlatformWatchdogService.mof")
#pragma include ("System/CIM_Process.mof")
#pragma include ("System/CIM_ProcessExecutable.mof")
#pragma include ("System/CIM_ProcessOfJob.mof")
#pragma include ("System/CIM_RecordInLog.mof")
#pragma include ("System/CIM_RecordLog.mof")
#pragma include ("System/CIM_RemoteFileSystem.mof")
#pragma include ("System/CIM_ResidesOnExtent.mof")
#pragma include ("System/CIM_RunningOS.mof")
#pragma include ("System/CIM_ServiceProcess.mof")
#pragma include ("System/CIM_SystemResource.mof")
#pragma include ("System/CIM_Thread.mof")
#pragma include ("System/CIM_UnitaryComputerSystem.mof")
#pragma include ("System/CIM_UnixLocalFileSystem.mof")
#pragma include ("System/CIM_UnixProcess.mof")
#pragma include ("System/CIM_UnixProcessStatistics.mof")
#pragma include ("System/CIM_UnixThread.mof")
#pragma include ("System/CIM_UseOfLog.mof")
#pragma include ("System/CIM_UseOfMessageLog.mof")
#pragma include ("System/CIM_VirtualComputerSystem.mof")
#pragma include ("System/CIM_WakeUpService.mof")
#pragma include ("User/CIM_Account.mof")
#pragma include ("User/CIM_AccountIdentity.mof")
#pragma include ("User/CIM_AccountMapsToAccount.mof")
#pragma include ("User/CIM_AccountOnSystem.mof")
#pragma include ("User/CIM_CollectionInSystem.mof")
#pragma include ("User/CIM_CredentialManagementSAP.mof")
#pragma include ("User/CIM_HostedACI.mof")
#pragma include ("User/CIM_HostedAuthenticationRequirement.mof")
#pragma include ("User/CIM_MorePersonInfo.mof")
#pragma include ("User/CIM_SecurityService.mof")
#pragma include ("User/CIM_SecurityServiceUsesAccount.mof")
#pragma include ("User/CIM_SystemAdministrator.mof")
#pragma include ("User/CIM_SystemAdministratorGroup.mof")
#pragma include ("User/CIM_SystemAdministratorRole.mof")
#pragma include ("User/CIM_UsersAccount.mof")
#pragma include ("Application/CIM_Action.mof")
#pragma include ("Application/CIM_ActionSequence.mof")
#pragma include ("Application/CIM_ApplicationSystem.mof")
#pragma include ("Application/CIM_ApplicationSystemDependency.mof")
#pragma include ("Application/CIM_ApplicationSystemDirectory.mof")
#pragma include ("Application/CIM_ApplicationSystemHierarchy.mof")
#pragma include ("Application/CIM_ApplicationSystemSoftwareFeature.mof")
#pragma include ("Application/CIM_AssociatedAppSystemOverviewStatistics.mof")
#pragma include ("Application/CIM_Check.mof")
#pragma include ("Application/CIM_DiagnosticTestSoftware.mof")
#pragma include ("Application/CIM_DirectoryAction.mof")
#pragma include ("Application/CIM_DirectorySpecification.mof")
#pragma include ("Application/CIM_DiskSpaceCheck.mof")
#pragma include ("Application/CIM_ExecuteProgram.mof")
#pragma include ("Application/CIM_FileAction.mof")
#pragma include ("Application/CIM_FileSpecification.mof")
#pragma include ("Application/CIM_FromDirectoryAction.mof")
#pragma include ("Application/CIM_FromDirectorySpecification.mof")
#pragma include ("Application/CIM_InstalledSoftwareElement.mof")
#pragma include ("Application/CIM_J2eeApplication.mof")
#pragma include ("Application/CIM_J2eeDeployedObject.mof")
#pragma include ("Application/CIM_J2eeEJB.mof")
#pragma include ("Application/CIM_J2eeEntityBean.mof")
#pragma include ("Application/CIM_J2eeJCAConnectionFactory.mof")
#pragma include ("Application/CIM_J2eeJCAManagedConnectionFactory.mof")
#pragma include ("Application/CIM_J2eeJDBCDataSource.mof")
#pragma include ("Application/CIM_J2eeJDBCDriver.mof")
#pragma include ("Application/CIM_J2eeJVM.mof")
#pragma include ("Application/CIM_J2eeManagedObject.mof")
#pragma include ("Application/CIM_J2eeMessageDrivenBean.mof")
#pragma include ("Application/CIM_J2eeModule.mof")
#pragma include ("Application/CIM_J2eeModuleUsesJVM.mof")
#pragma include ("Application/CIM_J2eeResource.mof")
#pragma include ("Application/CIM_J2eeResourceAdapter.mof")
#pragma include ("Application/CIM_J2eeResourceAdapterModule.mof")
#pragma include ("Application/CIM_J2eeRMI_IIOPResource.mof")
#pragma include ("Application/CIM_J2eeServer.mof")
#pragma include ("Application/CIM_J2eeServerUsesJVM.mof")
#pragma include ("Application/CIM_J2eeServlet.mof")
#pragma include ("Application/CIM_J2eeSessionBean.mof")
#pragma include ("Application/CIM_J2eeStatefulSessionBean.mof")
#pragma include ("Application/CIM_J2eeStatelessSessionBean.mof")
#pragma include ("Application/CIM_J2eeURLResource.mof")
#pragma include ("Application/CIM_J2eeWebModule.mof")
#pragma include ("Application/CIM_MemoryCheck.mof")
#pragma include ("Application/CIM_ModifySettingAction.mof")
#pragma include ("Application/CIM_OperatingSystemSoftwareFeature.mof")
#pragma include ("Application/CIM_OSVersionCheck.mof")
#pragma include ("Application/CIM_RebootAction.mof")
#pragma include ("Application/CIM_RemoveDirectoryAction.mof")
#pragma include ("Application/CIM_RemoveFileAction.mof")
#pragma include ("Application/CIM_SettingCheck.mof")
#pragma include ("Application/CIM_SoftwareElementActions.mof")
#pragma include ("Application/CIM_SoftwareElementChecks.mof")
#pragma include ("Application/CIM_SoftwareElementSAPImplementation.mof")
#pragma include ("Application/CIM_SoftwareElementServiceImplementation.mof")
#pragma include ("Application/CIM_SoftwareElementVersionCheck.mof")
#pragma include ("Application/CIM_SoftwareFeatureSAPImplementation.mof")
#pragma include ("Application/CIM_SoftwareFeatureServiceImplementation.mof")
#pragma include ("Application/CIM_SwapSpaceCheck.mof")
#pragma include ("Application/CIM_SystemBIOS.mof")
#pragma include ("Application/CIM_VersionCompatibilityCheck.mof")
#pragma include ("Core/CIM_AdminDomain.mof")
#pragma include ("Core/CIM_BasedOn.mof")
#pragma include ("Core/CIM_ConfigurationForSystem.mof")
#pragma include ("Core/CIM_ContainedDomain.mof")
#pragma include ("Core/CIM_DeviceSAPImplementation.mof")
#pragma include ("Core/CIM_DeviceServiceImplementation.mof")
#pragma include ("Core/CIM_DeviceStatistics.mof")
#pragma include ("Core/CIM_ExtentRedundancyComponent.mof")
#pragma include ("Core/CIM_HostedAccessPoint.mof")
#pragma include ("Core/CIM_HostedCollection.mof")
#pragma include ("Core/CIM_HostedResourcePool.mof")
#pragma include ("Core/CIM_HostedService.mof")
#pragma include ("Core/CIM_InstalledSoftwareIdentity.mof")
#pragma include ("Core/CIM_LastAppliedSnapshot.mof")
#pragma include ("Core/CIM_OpaqueManagementData.mof")
#pragma include ("Core/CIM_OpaqueManagementDataService.mof")
#pragma include ("Core/CIM_PowerManagementService.mof")
#pragma include ("Core/CIM_PowerUtilizationManagementService.mof")
#pragma include ("Core/CIM_ProductServiceComponent.mof")
#pragma include ("Core/CIM_ProtocolEndpoint.mof")
#pragma include ("Core/CIM_ProvidesServiceToElement.mof")
#pragma include ("Core/CIM_RemoteServiceAccessPoint.mof")
#pragma include ("Core/CIM_ResourcePoolConfigurationService.mof")
#pragma include ("Core/CIM_SAPAvailableForElement.mof")
#pragma include ("Core/CIM_SAPSAPDependency.mof")
#pragma include ("Core/CIM_SAPStatistics.mof")
#pragma include ("Core/CIM_ServiceAccessBySAP.mof")
#pragma include ("Core/CIM_ServiceServiceDependency.mof")
#pragma include ("Core/CIM_SettingForSystem.mof")
#pragma include ("Core/CIM_SnapshotOfVirtualSystem.mof")
#pragma include ("Core/CIM_VirtualSystemManagementService.mof")
#pragma include ("Core/CIM_VirtualSystemSnapshotService.mof")
#pragma include ("Database/CIM_DatabaseStorageArea.mof")
#pragma include ("Database/CIM_DatabaseSystem.mof")
#pragma include ("Device/CIM_AdapterActiveConnection.mof")
#pragma include ("Device/CIM_AggregatePSExtentBasedOnAggregatePExtent.mof")
#pragma include ("Device/CIM_AggregatePSExtentBasedOnPExtent.mof")
#pragma include ("Device/CIM_AggregateRedundancyComponent.mof")
#pragma include ("Device/CIM_AGPVideoController.mof")
#pragma include ("Device/CIM_AllocatedFromStoragePool.mof")
#pragma include ("Device/CIM_AssociatedBattery.mof")
#pragma include ("Device/CIM_AssociatedComponentExtent.mof")
#pragma include ("Device/CIM_AssociatedCooling.mof")
#pragma include ("Device/CIM_AssociatedIndicatorLED.mof")
#pragma include ("Device/CIM_AssociatedLabelReader.mof")
#pragma include ("Device/CIM_AssociatedMemory.mof")
#pragma include ("Device/CIM_AssociatedProcessorMemory.mof")
#pragma include ("Device/CIM_AssociatedProtocolController.mof")
#pragma include ("Device/CIM_AssociatedRemainingExtent.mof")
#pragma include ("Device/CIM_AssociatedSensor.mof")
#pragma include ("Device/CIM_BinarySensor.mof")
#pragma include ("Device/CIM_BIOSLoadedInNV.mof")
#pragma include ("Device/CIM_BlockStatisticsService.mof")
#pragma include ("Device/CIM_CacheMemory.mof")
#pragma include ("Device/CIM_CallBasedModem.mof")
#pragma include ("Device/CIM_CDROMDrive.mof")
#pragma include ("Device/CIM_ChangerDevice.mof")
#pragma include ("Device/CIM_CompositeExtentBasedOn.mof")
#pragma include ("Device/CIM_ComputerSystemMemory.mof")
#pragma include ("Device/CIM_ComputerSystemProcessor.mof")
#pragma include ("Device/CIM_ConnectionBasedModem.mof")
#pragma include ("Device/CIM_ControlledBy.mof")
#pragma include ("Device/CIM_ControllerConfigurationService.mof")
#pragma include ("Device/CIM_DeviceServicesLocation.mof")
#pragma include ("Device/CIM_DiscreteSensor.mof")
#pragma include ("Device/CIM_DiskDrive.mof")
#pragma include ("Device/CIM_DisketteDrive.mof")
#pragma include ("Device/CIM_DiskPartition.mof")
#pragma include ("Device/CIM_DiskPartitionBasedOnVolume.mof")
#pragma include ("Device/CIM_Display.mof")
#pragma include ("Device/CIM_DriveInDiskGroup.mof")
#pragma include ("Device/CIM_DSLModem.mof")
#pragma include ("Device/CIM_DVDDrive.mof")
#pragma include ("Device/CIM_EthernetAdapter.mof")
#pragma include ("Device/CIM_EthernetPort.mof")
#pragma include ("Device/CIM_FCPort.mof")
#pragma include ("Device/CIM_FibreChannelAdapter.mof")
#pragma include ("Device/CIM_FibrePort.mof")
#pragma include ("Device/CIM_FibrePortActiveLogin.mof")
#pragma include ("Device/CIM_FibrePortOnFCAdapter.mof")
#pragma include ("Device/CIM_FlatPanel.mof")
#pragma include ("Device/CIM_HDSLModem.mof")
#pragma include ("Device/CIM_HostedStoragePool.mof")
#pragma include ("Device/CIM_InterLibraryPort.mof")
#pragma include ("Device/CIM_ISDNModem.mof")
#pragma include ("Device/CIM_Keyboard.mof")
#pragma include ("Device/CIM_LibraryExchange.mof")
#pragma include ("Device/CIM_LibraryPackage.mof")
#pragma include ("Device/CIM_LimitedAccessPort.mof")
#pragma include ("Device/CIM_LogicalDiskBasedOnExtent.mof")
#pragma include ("Device/CIM_LogicalDiskBasedOnPartition.mof")
#pragma include ("Device/CIM_LogicalDiskBasedOnVolume.mof")
#pragma include ("Device/CIM_LogicalDiskBasedOnVolumeSet.mof")
#pragma include ("Device/CIM_MagnetoOpticalDrive.mof")
#pragma include ("Device/CIM_ModulePort.mof")
#pragma include ("Device/CIM_MultiStateSensor.mof")
#pragma include ("Device/CIM_NumericSensor.mof")
#pragma include ("Device/CIM_OOBAlertServiceOnModem.mof")
#pragma include ("Device/CIM_OOBAlertServiceOnNetworkAdapter.mof")
#pragma include ("Device/CIM_OOBAlertServiceOnNetworkPort.mof")
#pragma include ("Device/CIM_PackageAlarm.mof")
#pragma include ("Device/CIM_PackageCooling.mof")
#pragma include ("Device/CIM_PCIBridge.mof")
#pragma include ("Device/CIM_PCVideoController.mof")
#pragma include ("Device/CIM_PExtentRedundancyComponent.mof")
#pragma include ("Device/CIM_PickerForChanger.mof")
#pragma include ("Device/CIM_PickerLabelReader.mof")
#pragma include ("Device/CIM_PointingDevice.mof")
#pragma include ("Device/CIM_PortImplementsEndpoint.mof")
#pragma include ("Device/CIM_POTSModem.mof")
#pragma include ("Device/CIM_PrintQueue.mof")
#pragma include ("Device/CIM_ProtectedExtentBasedOn.mof")
#pragma include ("Device/CIM_ProtocolControllerAccessesUnit.mof")
#pragma include ("Device/CIM_PSExtentBasedOnPExtent.mof")
#pragma include ("Device/CIM_QueueForPrintService.mof")
#pragma include ("Device/CIM_QueueForwardsToPrintSAP.mof")
#pragma include ("Device/CIM_RealizedOnSide.mof")
#pragma include ("Device/CIM_RealizesAggregatePExtent.mof")
#pragma include ("Device/CIM_RealizesDiskPartition.mof")
#pragma include ("Device/CIM_RealizesTapePartition.mof")
#pragma include ("Device/CIM_SCSIInterface.mof")
#pragma include ("Device/CIM_SDSLModem.mof")
#pragma include ("Device/CIM_SerialInterface.mof")
#pragma include ("Device/CIM_StorageConfigurationService.mof")
#pragma include ("Device/CIM_Tachometer.mof")
#pragma include ("Device/CIM_TapePartitionOnSurface.mof")
#pragma include ("Device/CIM_TemperatureSensor.mof")
#pragma include ("Device/CIM_Unimodem.mof")
#pragma include ("Device/CIM_USBConnection.mof")
#pragma include ("Device/CIM_USBControllerHasHub.mof")
#pragma include ("Device/CIM_VDSLModem.mof")
#pragma include ("Device/CIM_VoltageSensor.mof")
#pragma include ("Device/CIM_VolumeSetBasedOnPSExtent.mof")
#pragma include ("Device/CIM_WakeUpServiceOnModem.mof")
#pragma include ("Device/CIM_WakeUpServiceOnNetworkAdapter.mof")
#pragma include ("Device/CIM_WakeUpServiceOnNetworkPort.mof")
#pragma include ("Interop/CIM_CIMXMLCommunicationMechanism.mof")
#pragma include ("Interop/CIM_ObjectManager.mof")
#pragma include ("Interop/CIM_ObjectManagerAdapter.mof")
#pragma include ("Interop/CIM_ProtocolAdapter.mof")
#pragma include ("IPsecPolicy/CIM_PeerGatewayForPreconfiguredTunnel.mof")
#pragma include ("IPsecPolicy/CIM_PeerGatewayForTunnel.mof")
#pragma include ("Network/CIM_AssociatedNextHop.mof")
#pragma include ("Network/CIM_AutonomousSystem.mof")
#pragma include ("Network/CIM_AverageRateMeterService.mof")
#pragma include ("Network/CIM_BGPAttributesForRoute.mof")
#pragma include ("Network/CIM_BGPClustersInAS.mof")
#pragma include ("Network/CIM_BGPProtocolEndpoint.mof")
#pragma include ("Network/CIM_BGPService.mof")
#pragma include ("Network/CIM_BGPServiceAttributes.mof")
#pragma include ("Network/CIM_BGPServiceStatistics.mof")
#pragma include ("Network/CIM_CalculatedRoutes.mof")
#pragma include ("Network/CIM_CalculatesAmong.mof")
#pragma include ("Network/CIM_CalculationBasedOnQueue.mof")
#pragma include ("Network/CIM_CalculationServiceForDropper.mof")
#pragma include ("Network/CIM_ClassifierService.mof")
#pragma include ("Network/CIM_CLPProtocolEndpoint.mof")
#pragma include ("Network/CIM_ConditioningServiceOnEndpoint.mof")
#pragma include ("Network/CIM_Confederation.mof")
#pragma include ("Network/CIM_DHCPProtocolEndpoint.mof")
#pragma include ("Network/CIM_DiffServService.mof")
#pragma include ("Network/CIM_DNSProtocolEndpoint.mof")
#pragma include ("Network/CIM_DSCPMarkerService.mof")
#pragma include ("Network/CIM_EFService.mof")
#pragma include ("Network/CIM_EGPRouteCalcDependency.mof")
#pragma include ("Network/CIM_EgressConditioningServiceOnEndpoint.mof")
#pragma include ("Network/CIM_ElementInSchedulingService.mof")
#pragma include ("Network/CIM_EndpointForIPNetworkConnection.mof")
#pragma include ("Network/CIM_EndpointIdentity.mof")
#pragma include ("Network/CIM_EndpointOfNetworkPipe.mof")
#pragma include ("Network/CIM_EWMAMeterService.mof")
#pragma include ("Network/CIM_FilterEntryInSystem.mof")
#pragma include ("Network/CIM_FilterListInSystem.mof")
#pragma include ("Network/CIM_FlowService.mof")
#pragma include ("Network/CIM_ForwardingService.mof")
#pragma include ("Network/CIM_ForwardsAmong.mof")
#pragma include ("Network/CIM_Hdr8021PService.mof")
#pragma include ("Network/CIM_HeadTailDropQueueBinding.mof")
#pragma include ("Network/CIM_HostedAdminDistance.mof")
#pragma include ("Network/CIM_HostedBGPAttributes.mof")
#pragma include ("Network/CIM_HostedBGPPeerGroup.mof")
#pragma include ("Network/CIM_HostedBGPRouteMap.mof")
#pragma include ("Network/CIM_HostedFilterEntryBase.mof")
#pragma include ("Network/CIM_HostedFilterList.mof")
#pragma include ("Network/CIM_HostedForwardingServices.mof")
#pragma include ("Network/CIM_HostedRoutingPolicy.mof")
#pragma include ("Network/CIM_HostedRoutingServices.mof")
#pragma include ("Network/CIM_InBGPPeerGroup.mof")
#pragma include ("Network/CIM_IngressConditioningServiceOnEndpoint.mof")
#pragma include ("Network/CIM_InLogicalNetwork.mof")
#pragma include ("Network/CIM_IPProtocolEndpoint.mof")
#pragma include ("Network/CIM_IPXProtocolEndpoint.mof")
#pragma include ("Network/CIM_iSCSIConnection.mof")
#pragma include ("Network/CIM_iSCSISession.mof")
#pragma include ("Network/CIM_LANEndpoint.mof")
#pragma include ("Network/CIM_LogicalNetworkService.mof")
#pragma include ("Network/CIM_Network.mof")
#pragma include ("Network/CIM_NetworkPortConfigurationService.mof")
#pragma include ("Network/CIM_NetworkServicesInAdminDomain.mof")
#pragma include ("Network/CIM_NetworksInAdminDomain.mof")
#pragma include ("Network/CIM_NextScheduler.mof")
#pragma include ("Network/CIM_NonWorkConservingSchedulingService.mof")
#pragma include ("Network/CIM_OSPFProtocolEndpointBase.mof")
#pragma include ("Network/CIM_OSPFService.mof")
#pragma include ("Network/CIM_OSPFServiceConfiguration.mof")
#pragma include ("Network/CIM_OSPFVirtualInterface.mof")
#pragma include ("Network/CIM_PrecedenceService.mof")
#pragma include ("Network/CIM_QoSConditioningSubService.mof")
#pragma include ("Network/CIM_QueueAllocation.mof")
#pragma include ("Network/CIM_QueueHierarchy.mof")
#pragma include ("Network/CIM_QueueToSchedule.mof")
#pragma include ("Network/CIM_ReflectorClientService.mof")
#pragma include ("Network/CIM_ReflectorNonClientService.mof")
#pragma include ("Network/CIM_ReflectorService.mof")
#pragma include ("Network/CIM_RemoteAccessAvailableToElement.mof")
#pragma include ("Network/CIM_RouteForwardedByService.mof")
#pragma include ("Network/CIM_RoutersInAS.mof")
#pragma include ("Network/CIM_RoutersInBGPCluster.mof")
#pragma include ("Network/CIM_RoutesBGP.mof")
#pragma include ("Network/CIM_RouteUsesEndpoint.mof")
#pragma include ("Network/CIM_RoutingProtocolDomain.mof")
#pragma include ("Network/CIM_RoutingProtocolDomainInAS.mof")
#pragma include ("Network/CIM_SchedulerUsed.mof")
#pragma include ("Network/CIM_SCSIProtocolEndpoint.mof")
#pragma include ("Network/CIM_SecurityAssociationEndpoint.mof")
#pragma include ("Network/CIM_SourceRoutingService.mof")
#pragma include ("Network/CIM_SpanningTreeService.mof")
#pragma include ("Network/CIM_Specific802dot1QVLANService.mof")
#pragma include ("Network/CIM_SSHProtocolEndpoint.mof")
#pragma include ("Network/CIM_SwitchPort.mof")
#pragma include ("Network/CIM_SwitchPortDynamicForwarding.mof")
#pragma include ("Network/CIM_SwitchPortPair.mof")
#pragma include ("Network/CIM_SwitchPortSourceRouting.mof")
#pragma include ("Network/CIM_SwitchPortSpanningTree.mof")
#pragma include ("Network/CIM_SwitchPortStaticForwarding.mof")
#pragma include ("Network/CIM_SwitchService.mof")
#pragma include ("Network/CIM_SwitchServiceSourceRouting.mof")
#pragma include ("Network/CIM_SwitchServiceSpanningTree.mof")
#pragma include ("Network/CIM_SwitchServiceVLAN.mof")
#pragma include ("Network/CIM_TCPProtocolEndpoint.mof")
#pragma include ("Network/CIM_TelnetProtocolEndpoint.mof")
#pragma include ("Network/CIM_TransparentBridgingService.mof")
#pragma include ("Network/CIM_TransparentBridgingStaticForwarding.mof")
#pragma include ("Network/CIM_TrapSourceForSNMPService.mof")
#pragma include ("Network/CIM_UDPProtocolEndpoint.mof")
#pragma include ("Network/CIM_USBRedirectionService.mof")
#pragma include ("Network/CIM_VLANEndpoint.mof")
#pragma include ("Network/CIM_VLANFor.mof")
#pragma include ("Policy/CIM_PolicyGroupInSystem.mof")
#pragma include ("Policy/CIM_PolicyRepository.mof")
#pragma include ("Policy/CIM_PolicyRepositoryInPolicyRepository.mof")
#pragma include ("Policy/CIM_PolicyRoleCollectionInSystem.mof")
#pragma include ("Policy/CIM_PolicyRuleInSystem.mof")
#pragma include ("Policy/CIM_ReusablePolicyContainer.mof")
#pragma include ("System/CIM_AllocatedResource.mof")
#pragma include ("System/CIM_AvailableDiagnosticService.mof")
#pragma include ("System/CIM_BootOSFromFS.mof")
#pragma include ("System/CIM_BootService.mof")
#pragma include ("System/CIM_BootServiceAccessBySAP.mof")
#pragma include ("System/CIM_Cluster.mof")
#pragma include ("System/CIM_ClusteringService.mof")
#pragma include ("System/CIM_ClusterServiceAccessBySAP.mof")
#pragma include ("System/CIM_ComponentCS.mof")
#pragma include ("System/CIM_DiagnosticLog.mof")
#pragma include ("System/CIM_DiagnosticResultForTest.mof")
#pragma include ("System/CIM_DiagnosticSettingForTest.mof")
#pragma include ("System/CIM_DiagnosticsLog.mof")
#pragma include ("System/CIM_DiagnosticTestForMSE.mof")
#pragma include ("System/CIM_DMA.mof")
#pragma include ("System/CIM_Export.mof")
#pragma include ("System/CIM_FileStorage.mof")
#pragma include ("System/CIM_HostedBootSAP.mof")
#pragma include ("System/CIM_HostedBootService.mof")
#pragma include ("System/CIM_HostedClusterSAP.mof")
#pragma include ("System/CIM_HostedClusterService.mof")
#pragma include ("System/CIM_HostedJobDestination.mof")
#pragma include ("System/CIM_HostingCS.mof")
#pragma include ("System/CIM_InstalledOS.mof")
#pragma include ("System/CIM_IRQ.mof")
#pragma include ("System/CIM_LogInDataFile.mof")
#pragma include ("System/CIM_LogInDeviceFile.mof")
#pragma include ("System/CIM_LogInStorage.mof")
#pragma include ("System/CIM_MemoryMappedIO.mof")
#pragma include ("System/CIM_MemoryResource.mof")
#pragma include ("System/CIM_NFS.mof")
#pragma include ("System/CIM_OperationLog.mof")
#pragma include ("System/CIM_OSProcess.mof")
#pragma include ("System/CIM_ParticipatingCS.mof")
#pragma include ("System/CIM_PortResource.mof")
#pragma include ("System/CIM_ProcessThread.mof")
#pragma include ("System/CIM_ResourceOfSystem.mof")
#pragma include ("System/CIM_SystemPartition.mof")
#pragma include ("User/CIM_AccountManagementService.mof")
#pragma include ("User/CIM_AuthenticationService.mof")
#pragma include ("User/CIM_AuthorizationService.mof")
#pragma include ("User/CIM_AuthorizedUse.mof")
#pragma include ("User/CIM_CredentialManagementService.mof")
#pragma include ("User/CIM_IdentityManagementService.mof")
#pragma include ("User/CIM_KerberosKeyDistributionCenter.mof")
#pragma include ("User/CIM_KeyBasedCredentialManagementService.mof")
#pragma include ("User/CIM_LocalCredentialManagementService.mof")
#pragma include ("User/CIM_ManagedCredential.mof")
#pragma include ("User/CIM_ManagesAccount.mof")
#pragma include ("User/CIM_Notary.mof")
#pragma include ("User/CIM_NotaryVerifiesBiometric.mof")
#pragma include ("User/CIM_PrivilegeManagementService.mof")
#pragma include ("User/CIM_PublicKeyManagementService.mof")
#pragma include ("User/CIM_RequireCredentialsFrom.mof")
#pragma include ("User/CIM_RoleBasedAuthorizationService.mof")
#pragma include ("User/CIM_SecurityServiceForSystem.mof")
#pragma include ("User/CIM_ServiceUsesSecurityService.mof")
#pragma include ("User/CIM_SharedSecretService.mof")
#pragma include ("User/CIM_StorageHardwareIDManagementService.mof")
#pragma include ("User/CIM_TrustHierarchy.mof")
#pragma include ("User/CIM_VerificationService.mof")
#pragma include ("Application/CIM_ArchitectureCheck.mof")
#pragma include ("Application/CIM_CopyFileAction.mof")
#pragma include ("Application/CIM_CreateDirectoryAction.mof")
#pragma include ("Application/CIM_DirectorySpecificationFile.mof")
#pragma include ("Application/CIM_J2eeAppClientModule.mof")
#pragma include ("Application/CIM_J2eeApplicationHostedOnServer.mof")
#pragma include ("Application/CIM_J2eeApplicationModule.mof")
#pragma include ("Application/CIM_J2eeDomain.mof")
#pragma include ("Application/CIM_J2eeEJBModule.mof")
#pragma include ("Application/CIM_J2eeJavaMailResource.mof")
#pragma include ("Application/CIM_J2eeJCAConnectionFactoryManagedConnectionFactory.mof")
#pragma include ("Application/CIM_J2eeJCAResource.mof")
#pragma include ("Application/CIM_J2eeJDBCDataSourceDriver.mof")
#pragma include ("Application/CIM_J2eeJDBCResource.mof")
#pragma include ("Application/CIM_J2eeJDBCResourceUsesDataSource.mof")
#pragma include ("Application/CIM_J2eeJMSResource.mof")
#pragma include ("Application/CIM_J2eeJNDIResource.mof")
#pragma include ("Application/CIM_J2eeJTAResource.mof")
#pragma include ("Application/CIM_J2eeResourceAdapterInModule.mof")
#pragma include ("Application/CIM_J2eeResourceOnServer.mof")
#pragma include ("Application/CIM_J2eeServerInDomain.mof")
#pragma include ("Application/CIM_J2eeServletInModule.mof")
#pragma include ("Application/CIM_ToDirectoryAction.mof")
#pragma include ("Application/CIM_ToDirectorySpecification.mof")
#pragma include ("Core/CIM_ActiveConnection.mof")
#pragma include ("Core/CIM_AssociatedPowerManagementService.mof")
#pragma include ("Core/CIM_BindsTo.mof")
#pragma include ("Core/CIM_LaunchInContextSAP.mof")
#pragma include ("Core/CIM_LaunchInContextService.mof")
#pragma include ("Core/CIM_ProtocolService.mof")
#pragma include ("Core/CIM_ProvidesEndpoint.mof")
#pragma include ("Core/CIM_RemotePort.mof")
#pragma include ("Database/CIM_AssociatedDatabaseSystem.mof")
#pragma include ("Database/CIM_DatabaseStorage.mof")
#pragma include ("Device/CIM_AccessLabelReader.mof")
#pragma include ("Device/CIM_ADSLModem.mof")
#pragma include ("Device/CIM_AssociatedCacheMemory.mof")
#pragma include ("Device/CIM_AssociatedSupplyVoltageSensor.mof")
#pragma include ("Device/CIM_CableModem.mof")
#pragma include ("Device/CIM_CollectionOfSensors.mof")
#pragma include ("Device/CIM_CurrentSensor.mof")
#pragma include ("Device/CIM_DesktopMonitor.mof")
#pragma include ("Device/CIM_MonitorSetting.mof")
#pragma include ("Device/CIM_OwningPrintQueue.mof")
#pragma include ("Device/CIM_PackageTempSensor.mof")
#pragma include ("Device/CIM_PrinterServicingQueue.mof")
#pragma include ("Device/CIM_SCSIInitiatorTargetLogicalUnitPath.mof")
#pragma include ("Device/CIM_SCSIPathConfigurationService.mof")
#pragma include ("Device/CIM_WiFiEndpoint.mof")
#pragma include ("Device/CIM_WiFiPortConfigurationService.mof")
#pragma include ("Interop/CIM_CommMechanismForAdapter.mof")
#pragma include ("Interop/CIM_CommMechanismForManager.mof")
#pragma include ("Interop/CIM_CommMechanismForObjectManagerAdapter.mof")
#pragma include ("Interop/CIM_NamespaceInManager.mof")
#pragma include ("IPsecPolicy/CIM_IPsecPolicyForEndpoint.mof")
#pragma include ("IPsecPolicy/CIM_RuleThatGeneratedSA.mof")
#pragma include ("Network/CIM_AFService.mof")
#pragma include ("Network/CIM_ASBGPEndpoints.mof")
#pragma include ("Network/CIM_BGPAdminDistance.mof")
#pragma include ("Network/CIM_BGPPeerGroupService.mof")
#pragma include ("Network/CIM_BGPRoutingPolicy.mof")
#pragma include ("Network/CIM_BindsToLANEndpoint.mof")
#pragma include ("Network/CIM_ClassifierElement.mof")
#pragma include ("Network/CIM_ClassifierElementInClassifierService.mof")
#pragma include ("Network/CIM_ClassifierElementUsesFilterList.mof")
#pragma include ("Network/CIM_ClassifierFilterSet.mof")
#pragma include ("Network/CIM_EndpointInLink.mof")
#pragma include ("Network/CIM_FailNextScheduler.mof")
#pragma include ("Network/CIM_FilterOfSecurityAssociation.mof")
#pragma include ("Network/CIM_ForwardedRoutes.mof")
#pragma include ("Network/CIM_HostedNetworkPipe.mof")
#pragma include ("Network/CIM_IKESAEndpoint.mof")
#pragma include ("Network/CIM_InboundVLAN.mof")
#pragma include ("Network/CIM_InSegment.mof")
#pragma include ("Network/CIM_IPConfigurationService.mof")
#pragma include ("Network/CIM_IPsecSAEndpoint.mof")
#pragma include ("Network/CIM_iSCSIProtocolEndpoint.mof")
#pragma include ("Network/CIM_NextServiceAfterClassifierElement.mof")
#pragma include ("Network/CIM_OSPFArea.mof")
#pragma include ("Network/CIM_OSPFProtocolEndpoint.mof")
#pragma include ("Network/CIM_OutboundVLAN.mof")
#pragma include ("Network/CIM_PeerOfSAEndpoint.mof")
#pragma include ("Network/CIM_Phase1SAUsedForPhase2.mof")
#pragma include ("Network/CIM_RelatedSpanningTree.mof")
#pragma include ("Network/CIM_RelatedTransparentBridgingService.mof")
#pragma include ("Network/CIM_SNMPTrapTarget.mof")
#pragma include ("Network/CIM_Switchable.mof")
#pragma include ("Network/CIM_SwitchesAmong.mof")
#pragma include ("Network/CIM_SwitchServiceTransparentBridging.mof")
#pragma include ("Network/CIM_TransformOfSecurityAssociation.mof")
#pragma include ("Network/CIM_TransparentBridgingDynamicForwarding.mof")
#pragma include ("Policy/CIM_AcceptCredentialFrom.mof")
#pragma include ("Policy/CIM_PolicyActionInPolicyRepository.mof")
#pragma include ("Policy/CIM_PolicyConditionInPolicyRepository.mof")
#pragma include ("Policy/CIM_PolicyContainerInPolicyContainer.mof")
#pragma include ("Policy/CIM_ReusablePolicy.mof")
#pragma include ("System/CIM_AllocatedDMA.mof")
#pragma include ("System/CIM_ComputerSystemResource.mof")
#pragma include ("User/CIM_AuthenticateForUse.mof")
#pragma include ("User/CIM_CertificateAuthority.mof")
#pragma include ("User/CIM_CertificateManagementService.mof")
#pragma include ("User/CIM_IKESecretIsNamed.mof")
#pragma include ("User/CIM_KDCIssuesKerberosTicket.mof")
#pragma include ("User/CIM_LocallyManagedPublicKey.mof")
#pragma include ("User/CIM_ManagesAccountOnSystem.mof")
#pragma include ("User/CIM_SharedSecretIsShared.mof")
#pragma include ("Application/CIM_J2eeConnectionFactoryAvailableToJCAResource.mof")
#pragma include ("Application/CIM_J2eeEJBInModule.mof")
#pragma include ("Device/CIM_AssociatedSupplyCurrentSensor.mof")
#pragma include ("Network/CIM_AFRelatedServices.mof")
#pragma include ("Network/CIM_AreaOfConfiguration.mof")
#pragma include ("Network/CIM_EndpointInArea.mof")
#pragma include ("System/CIM_ComputerSystemDMA.mof")
#pragma include ("System/CIM_ComputerSystemIRQ.mof")
#pragma include ("System/CIM_ComputerSystemMappedIO.mof")
//#pragma include ("User/CIM_CAHasPublicCertificate.mof")
//#pragma include ("User/CIM_CASignsPublicKeyCertificate.mof")
