TOP = ../..
include $(TOP)/config.mak

LIBRARY = indimgr

SOURCES = \
	cimbase.c \
	filter.c \
	filtercol.c \
	listener.c \
	mgr.c \
	mgrstrand.c \
	subscrip.c \
	classlist.c \
	host.c \

INCLUDES = $(TOP) $(TOP)/common $(TOP)/nits/base 

DEFINES = MI_CONST= HOOK_BUILD

include $(TOP)/mak/rules.mak
