// Copyright (c) 2008 DMTF.  All rights reserved.
   [Version ( "2.19.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "This class identifies JCA managed connection factories." )]
class CIM_J2eeJCAManagedConnectionFactory : CIM_EnabledLogicalElement {

      [Key, Override ( "InstanceID" ), 
       Description ( 
          "InstanceID identifies a unique instance of a J2ee "
          "JCAManagedConnectionFactory. In order to ensure "
          "uniqueness, the value of InstanceID MUST be constructed "
          "using the form specified in JSR77.3.1.1.1 in order to "
          "avoid the need for manual key propagation." ), 
       ModelCorrespondence { 
          "CIM_J2eeJCAManagedConnectionFactory.Name" }]
   string InstanceID;

      [Override ( "Name" ), 
       Description ( 
          "The name of a J2EE JCAManagedConnectionFactory. The name "
          "MUST be constructed using the form specified in "
          "JSR77.3.1.1.1 in order to avoid the need for manual key "
          "propagation." ), 
       MaxLen ( 256 ), 
       MappingStrings { "JSR77.JCP|JSR77.3.1.1.1 objectName|V1.0" }, 
       ModelCorrespondence { 
          "CIM_J2eeJCAManagedConnectionFactory.InstanceID" }]
   string Name;


};
