// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeStatefulSessionBeanStats 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServerStats" ), 
    Description ( 
       "The J2eeStatefulSessionBeanStats class defines the performance "
       "statistics that are provided by a stateful session bean." )]
class CIM_J2eeStatefulSessionBeanStats : CIM_J2eeSessionBeanStats {

      [Description ( 
          "The number of bean instances in a passive state." ), 
       Counter, MappingStrings { 
          "JSR77.JCP|JSR77.6.15.1.1 getPassiveCount|V1.0" }]
   uint64 PassiveCount;

      [Description ( 
          "The lowest number of bean instances in the passive state "
          "since the beginning of the measurement." ), 
       MappingStrings { 
          "JSR77.JCP|JSR77.6.7.1.2 getLowWaterMark|V1.0" }]
   uint64 PassiveLowWaterMark;

      [Description ( 
          "The highest number of bean instances in the passive "
          "state since the beginning of the measurement." ), 
       MappingStrings { 
          "JSR77.JCP|JSR77.6.7.1.1 getHighWaterMark|V1.0" }]
   uint64 PassiveHighWaterMark;


};
