// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_FileAction 
// ==================================================================
   [Abstract, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Application::CheckAction" ), 
    Description ( 
       "FileAction locates files that already exist on the CIM_ "
       "ComputerSystem that defines the Action\'s environment. These "
       "files are removed or moved/copied to a new location." )]
class CIM_FileAction : CIM_Action {


};
