// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeMessageDrivenBeanStats 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServerStats" ), 
    Description ( 
       "The J2eeMessageDrivenBeanStats class defines the performance "
       "statistics that are provided by message driven beans." )]
class CIM_J2eeMessageDrivenBeanStats : CIM_J2eeEJBStats {

      [Description ( "The number of messages received." ), 
       Counter, MappingStrings { 
          "JSR77.JCP|JSR77.6.13.1.1 getMessageCount|V1.0" }]
   uint64 MessageCount;


};
