// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeJMSConnectionStats 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServerStats" ), 
    Description ( 
       "The CIM_J2eeJMSConnectionStats class defines the performance "
       "statistics that are provided by a JMS connection." )]
class CIM_J2eeJMSConnectionStats : CIM_J2eeStatistic {

      [Description ( 
          "The transactional state of the JMS connection. A value "
          "of true indicates that the JMS connection is "
          "transactional." ), 
       MappingStrings { 
          "JSR77.JCP|JSR77.6.25.1.2 isTransactional|V1.0" }]
   boolean IsTransactional;


};
