// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.8.2" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServerStats" ), 
    Description ( 
       "The CIM_J2eeJVMStats class defines the performance statistics "
       "that are provided by a Java VM." )]
class CIM_J2eeJVMStats : CIM_J2eeStatistic {

      [Description ( "The heap size of the JVM." ), 
       Units ( "Bytes" ), 
       Gauge, MappingStrings { 
          "JSR77.JCP|JSR77.6.31.1.1 getHeapSize|V1.0" }, 
       PUnit ( "byte" )]
   uint64 HeapSize;

      [Description ( "The upper limit for the heap size of the JVM." ), 
       Units ( "Bytes" ), 
       MappingStrings { "JSR77.JCP|JSR77.6.8.1.1 getUpperBound|V1.0" }, 
       PUnit ( "byte" )]
   uint64 HeapSizeUpperBound;

      [Description ( "The lower limit for the heap size of the JVM." ), 
       Units ( "Bytes" ), 
       MappingStrings { "JSR77.JCP|JSR77.6.8.1.2 getLowerBound|V1.0" }, 
       PUnit ( "byte" )]
   uint64 HeapSizeLowerBound;

      [Description ( 
          "The smallest size of the JVM heap since the beginning of "
          "the measurement." ), 
       Units ( "Bytes" ), 
       MappingStrings { 
          "JSR77.JCP|JSR77.6.7.1.2 getLowWaterMark|V1.0" }, 
       PUnit ( "byte" )]
   uint64 HeapSizeLowWaterMark;

      [Description ( 
          "The largest size of the JVM heap since the beginning of "
          "the measurement." ), 
       Units ( "Bytes" ), 
       MappingStrings { 
          "JSR77.JCP|JSR77.6.7.1.1 getHighWaterMark|V1.0" }, 
       PUnit ( "byte" )]
   uint64 HeapSizeHighWaterMark;

      [Description ( 
          "The amount of time the JVM has been running. The time is "
          "represented as a datetime interval." ), 
       MappingStrings { "JSR77.JCP|JSR77.6.31.1.2 getUpTime|V1.0" }]
   datetime UpTime;


};
