// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeJCAConnectionPools 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServerStats" ), 
    Description ( 
       "CIM_J2eeJCAConnectionPools provides the list of statistics "
       "about the connections pools that are associated with the "
       "referencing JCA resource statistics." )]
class CIM_J2eeJCAConnectionPools : CIM_RelatedStatisticalData {

      [Override ( "Stats" ), 
       Description ( "The JCA resource statistic." )]
   CIM_J2eeJCAStats REF Stats;

      [Override ( "RelatedStats" ), 
       Description ( "The related JCA connection pool statistics." )]
   CIM_J2eeConnectionPoolStats REF RelatedStats;


};
