// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeApplicationHostedOnServer 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "The CIM_J2eeApplicationHostedOnServer association identifies a "
       "hosting J2ee Server for a particular J2EE Application." )]
class CIM_J2eeApplicationHostedOnServer : CIM_HostedDependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The hosting J2ee Server." )]
   CIM_J2eeServer REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The hosted J2ee Application." )]
   CIM_J2eeApplication REF Dependent;


};
