// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeJDBCResourceUsesDataSource 
// ==================================================================
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "CIM_J2eeJDBCResourceUsesDataSource is an association that "
       "identifies the JDBC data sources that are available to a "
       "CIM_J2eeJDBCResource." )]
class CIM_J2eeJDBCResourceUsesDataSource : CIM_HostedDependency {

      [Override ( "Dependent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The JDBC Resource that requires a Data Source." )]
   CIM_J2eeJDBCResource REF Dependent;

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Description ( 
          "The Data Source that is being used by a JDBC Resource." )]
   CIM_J2eeJDBCDataSource REF Antecedent;


};
