// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_CollectedSoftwareFeatures 
// ==================================================================
   [Association, Aggregation, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Application::InstalledProduct" ), 
    Description ( 
       "CollectedSoftwareFeatures defines the SoftwareFeatures that "
       "are collected by InstalledProduct (ie, the installed image of "
       "a Product)." )]
class CIM_CollectedSoftwareFeatures : CIM_MemberOfCollection {

      [Aggregate, Override ( "Collection" ), 
       Description ( 
          "The collection representing the installed image of a Product."
           )]
   CIM_InstalledProduct REF Collection;

      [Override ( "Member" ), 
       Description ( 
          "The SoftwareFeature that is a member of the "
          "InstalledProduct collection." )]
   CIM_SoftwareFeature REF Member;


};
