// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_J2eeJMSResource 
// ==================================================================
   [Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( "CIM_J2eeJMSResource identifies a JMS resource." )]
class CIM_J2eeJMSResource : CIM_J2eeResource {


};
