TOP = ..
include $(TOP)/config.mak

LIBRARY = mofparsererror

SOURCES = errors.c errorswrap.c omiutils.c

INCLUDES = $(TOP) $(TOP)/common

DEFINES =  MI_CONST=

# LIBRARIES = base

include $(TOP)/mak/rules.mak

